/* ---------------------------------------------------- */
/*  Generated by Enterprise Architect Version 12.1 		*/
/*  Created On : 26-Oct-2021 12:47:55 				*/
/*  DBMS       : PostgreSQL 						*/
/* ---------------------------------------------------- */

CREATE SCHEMA geoserver
    AUTHORIZATION ikn;

GRANT ALL ON SCHEMA geoserver TO ikn;

GRANT USAGE ON SCHEMA geoserver TO ikn_readonly;

/* Drop Views */

DROP VIEW IF EXISTS bron_specificatie_wfs CASCADE
;

DROP VIEW IF EXISTS ikn_upload CASCADE
;

DROP VIEW IF EXISTS ikn_upload_files CASCADE
;

/* Drop Tables */

DROP TABLE IF EXISTS geoserver.attentiezones_nnn CASCADE
;

DROP TABLE IF EXISTS geoserver.beleid_totaal_historie CASCADE
;

DROP TABLE IF EXISTS geoserver.beleid_totaal_huidig CASCADE
;

DROP TABLE IF EXISTS geoserver.beschermd_leefgebied CASCADE
;

DROP TABLE IF EXISTS geoserver.beschermde_natuurmonumenten CASCADE
;

DROP TABLE IF EXISTS geoserver.bescherming_houtopstanden CASCADE
;

DROP TABLE IF EXISTS geoserver.bijzonder_provinciaal_landschap CASCADE
;

DROP TABLE IF EXISTS geoserver.bos_natuur_buiten_nnn CASCADE
;

DROP TABLE IF EXISTS geoserver.bosreservaten CASCADE
;

DROP TABLE IF EXISTS geoserver.cultuur_historische_waardenkaart CASCADE
;

DROP TABLE IF EXISTS geoserver.distel_verordening CASCADE
;

DROP TABLE IF EXISTS geoserver.drone_vlieg_gebieden CASCADE
;

DROP TABLE IF EXISTS geoserver.duisternis_gebieden CASCADE
;

DROP TABLE IF EXISTS geoserver.ecologiche_verbindingszone CASCADE
;

DROP TABLE IF EXISTS geoserver.erosie_verordening CASCADE
;

DROP TABLE IF EXISTS geoserver.faunabeheereenheid_of_wildbeheereenheid CASCADE
;

DROP TABLE IF EXISTS geoserver.ganzen_foerageergebied CASCADE
;

DROP TABLE IF EXISTS geoserver.grondwater_bescherming CASCADE
;

DROP TABLE IF EXISTS geoserver.leefgebied_akkervogels CASCADE
;

DROP TABLE IF EXISTS geoserver.leefgebied_weidevogels CASCADE
;

DROP TABLE IF EXISTS geoserver.militaire_terreinen CASCADE
;

DROP TABLE IF EXISTS geoserver.nationaal_landschap CASCADE
;

DROP TABLE IF EXISTS geoserver.nationale_parken CASCADE
;

DROP TABLE IF EXISTS geoserver.natte_natuurparels CASCADE
;

DROP TABLE IF EXISTS geoserver.natura_2000_beheerplannen CASCADE
;

DROP TABLE IF EXISTS geoserver.natura_2000_bufferzone CASCADE
;

DROP TABLE IF EXISTS geoserver.natuur_netwerk_nederland CASCADE
;

DROP TABLE IF EXISTS geoserver.natuur_netwerk_rijkswateren CASCADE
;

DROP TABLE IF EXISTS geoserver.natuur_netwerk_rijkswateren_watervlakken CASCADE
;

DROP TABLE IF EXISTS geoserver.overgangszone_nnn CASCADE
;

DROP TABLE IF EXISTS geoserver.stilte_gebieden CASCADE
;

DROP TABLE IF EXISTS geoserver.waardevolle_open_gebieden CASCADE
;

DROP TABLE IF EXISTS geoserver.waterbergings_gebied CASCADE
;

DROP TABLE IF EXISTS geoserver.werelderfgoed CASCADE
;

DROP TABLE IF EXISTS geoserver.wet_ammoniak_en_veehouderij_gebieden CASCADE
;

DROP TABLE IF EXISTS geoserver.wezenlijke_waarden_kenmerken_nnn CASCADE
;

DROP TABLE IF EXISTS geoserver.zoekgebied_robuuste_verbindingszones CASCADE
;

/* Create Tables */

CREATE TABLE geoserver.attentiezones_nnn
(
	identificatie varchar(100) NOT NULL,
	begin_geldigheid date NOT NULL,
	eind_geldigheid date NULL,
	beleid_type_code varchar(20) NOT NULL,
	beleid_type_desc varchar(100) NOT NULL,
	beleid_naam_code varchar(20) NOT NULL,
	beleid_naam_desc varchar(100) NOT NULL,
	beleid_naam_bronhouder varchar(100) NOT NULL,
	beleid_bron_naam varchar(100) NOT NULL,
	beleid_bron_datum timestamp NOT NULL,
	beleid_bron_url varchar(255) NOT NULL,
	bronhouder_code varchar(20) NOT NULL,
	bronhouder_desc varchar(100) NOT NULL,
	geom geometry(polygon) NOT NULL
)
;

CREATE TABLE geoserver.beleid_totaal_historie
(
	identificatie varchar(100) NOT NULL,
	begin_geldigheid date NOT NULL,
	eind_geldigheid date NULL,
	beleid_type_code varchar(20) NOT NULL,
	beleid_type_desc varchar(100) NOT NULL,
	beleid_naam_code varchar(20) NOT NULL,
	beleid_naam_desc varchar(100) NOT NULL,
	beleid_naam_bronhouder varchar(100) NOT NULL,
	beleid_bron_naam varchar(100) NOT NULL,
	beleid_bron_datum timestamp NOT NULL,
	beleid_bron_url varchar(255) NOT NULL,
	bronhouder_code varchar(20) NOT NULL,
	bronhouder_desc varchar(100) NOT NULL,
	classificatie1_code varchar(20) NULL,
	classificatie1_desc varchar(100) NULL,
	classificatie2_code varchar(20) NULL,
	classificatie2_desc varchar(100) NULL,
	classificatie3_code varchar(20) NULL,
	classificatie3_desc varchar(100) NULL,
	geom geometry(polygon) NOT NULL
)
;

CREATE TABLE geoserver.beleid_totaal_huidig
(
	identificatie varchar(100) NOT NULL,
	begin_geldigheid date NOT NULL,
	eind_geldigheid date NULL,
	beleid_type_code varchar(20) NOT NULL,
	beleid_type_desc varchar(100) NOT NULL,
	beleid_naam_code varchar(20) NOT NULL,
	beleid_naam_desc varchar(100) NOT NULL,
	beleid_naam_bronhouder varchar(100) NOT NULL,
	beleid_bron_naam varchar(100) NOT NULL,
	beleid_bron_datum timestamp NOT NULL,
	beleid_bron_url varchar(255) NOT NULL,
	bronhouder_code varchar(20) NOT NULL,
	bronhouder_desc varchar(100) NOT NULL,
	classificatie1_code varchar(20) NULL,
	classificatie1_desc varchar(100) NULL,
	classificatie2_code varchar(20) NULL,
	classificatie2_desc varchar(100) NULL,
	classificatie3_code varchar(20) NULL,
	classificatie3_desc varchar(100) NULL,
	geom geometry(polygon) NOT NULL
)
;

CREATE TABLE geoserver.beschermd_leefgebied
(
	identificatie varchar(100) NOT NULL,
	begin_geldigheid date NOT NULL,
	eind_geldigheid date NULL,
	beleid_type_code varchar(20) NOT NULL,
	beleid_type_desc varchar(100) NOT NULL,
	beleid_naam_code varchar(20) NOT NULL,
	beleid_naam_desc varchar(100) NOT NULL,
	beleid_naam_bronhouder varchar(100) NOT NULL,
	beleid_bron_naam varchar(100) NOT NULL,
	beleid_bron_datum timestamp NOT NULL,
	beleid_bron_url varchar(255) NOT NULL,
	bronhouder_code varchar(20) NOT NULL,
	bronhouder_desc varchar(100) NOT NULL,
	geom geometry(polygon) NOT NULL
)
;

CREATE TABLE geoserver.beschermde_natuurmonumenten
(
	identificatie varchar(100) NOT NULL,
	begin_geldigheid date NOT NULL,
	eind_geldigheid date NULL,
	beleid_type_code varchar(20) NOT NULL,
	beleid_type_desc varchar(100) NOT NULL,
	beleid_naam_code varchar(20) NOT NULL,
	beleid_naam_desc varchar(100) NOT NULL,
	beleid_naam_bronhouder varchar(100) NOT NULL,
	beleid_bron_naam varchar(100) NOT NULL,
	beleid_bron_datum timestamp NOT NULL,
	beleid_bron_url varchar(255) NOT NULL,
	bronhouder_code varchar(20) NOT NULL,
	bronhouder_desc varchar(100) NOT NULL,
	geom geometry(polygon) NOT NULL
)
;

CREATE TABLE geoserver.bescherming_houtopstanden
(
	identificatie varchar(100) NOT NULL,
	begin_geldigheid date NOT NULL,
	eind_geldigheid date NULL,
	beleid_type_code varchar(20) NOT NULL,
	beleid_type_desc varchar(100) NOT NULL,
	beleid_naam_code varchar(20) NOT NULL,
	beleid_naam_desc varchar(100) NOT NULL,
	beleid_naam_bronhouder varchar(100) NOT NULL,
	beleid_bron_naam varchar(100) NOT NULL,
	beleid_bron_datum timestamp NOT NULL,
	beleid_bron_url varchar(255) NOT NULL,
	bronhouder_code varchar(20) NOT NULL,
	bronhouder_desc varchar(100) NOT NULL,
	geom geometry(polygon) NOT NULL
)
;

CREATE TABLE geoserver.bijzonder_provinciaal_landschap
(
	identificatie varchar(100) NOT NULL,
	begin_geldigheid date NOT NULL,
	eind_geldigheid date NULL,
	beleid_type_code varchar(20) NOT NULL,
	beleid_type_desc varchar(100) NOT NULL,
	beleid_naam_code varchar(20) NOT NULL,
	beleid_naam_desc varchar(100) NOT NULL,
	beleid_naam_bronhouder varchar(100) NOT NULL,
	beleid_bron_naam varchar(100) NOT NULL,
	beleid_bron_datum timestamp NOT NULL,
	beleid_bron_url varchar(255) NOT NULL,
	bronhouder_code varchar(20) NOT NULL,
	bronhouder_desc varchar(100) NOT NULL,
	geom geometry(polygon) NOT NULL
)
;

CREATE TABLE geoserver.bos_natuur_buiten_nnn
(
	identificatie varchar(100) NOT NULL,
	begin_geldigheid date NOT NULL,
	eind_geldigheid date NULL,
	beleid_type_code varchar(20) NOT NULL,
	beleid_type_desc varchar(100) NOT NULL,
	beleid_naam_code varchar(20) NOT NULL,
	beleid_naam_desc varchar(100) NOT NULL,
	beleid_naam_bronhouder varchar(100) NOT NULL,
	beleid_bron_naam varchar(100) NOT NULL,
	beleid_bron_datum timestamp NOT NULL,
	beleid_bron_url varchar(255) NOT NULL,
	bronhouder_code varchar(20) NOT NULL,
	bronhouder_desc varchar(100) NOT NULL,
	geom geometry(polygon) NOT NULL
)
;

CREATE TABLE geoserver.bosreservaten
(
	identificatie varchar(100) NOT NULL,
	begin_geldigheid date NOT NULL,
	eind_geldigheid date NULL,
	beleid_type_code varchar(20) NOT NULL,
	beleid_type_desc varchar(100) NOT NULL,
	beleid_naam_code varchar(20) NOT NULL,
	beleid_naam_desc varchar(100) NOT NULL,
	beleid_naam_bronhouder varchar(100) NOT NULL,
	beleid_bron_naam varchar(100) NOT NULL,
	beleid_bron_datum timestamp NOT NULL,
	beleid_bron_url varchar(255) NOT NULL,
	bronhouder_code varchar(20) NOT NULL,
	bronhouder_desc varchar(100) NOT NULL,
	geom geometry(polygon) NOT NULL
)
;

CREATE TABLE geoserver.cultuur_historische_waardenkaart
(
	identificatie varchar(100) NOT NULL,
	begin_geldigheid date NOT NULL,
	eind_geldigheid date NULL,
	beleid_type_code varchar(20) NOT NULL,
	beleid_type_desc varchar(100) NOT NULL,
	beleid_naam_code varchar(20) NOT NULL,
	beleid_naam_desc varchar(100) NOT NULL,
	beleid_naam_bronhouder varchar(100) NOT NULL,
	beleid_bron_naam varchar(100) NOT NULL,
	beleid_bron_datum timestamp NOT NULL,
	beleid_bron_url varchar(255) NOT NULL,
	bronhouder_code varchar(20) NOT NULL,
	bronhouder_desc varchar(100) NOT NULL,
	geom geometry(polygon) NOT NULL
)
;

CREATE TABLE geoserver.distel_verordening
(
	identificatie varchar(100) NOT NULL,
	begin_geldigheid date NOT NULL,
	eind_geldigheid date NULL,
	beleid_type_code varchar(20) NOT NULL,
	beleid_type_desc varchar(100) NOT NULL,
	beleid_naam_code varchar(20) NOT NULL,
	beleid_naam_desc varchar(100) NOT NULL,
	beleid_naam_bronhouder varchar(100) NOT NULL,
	beleid_bron_naam varchar(100) NOT NULL,
	beleid_bron_datum timestamp NOT NULL,
	beleid_bron_url varchar(255) NOT NULL,
	bronhouder_code varchar(20) NOT NULL,
	bronhouder_desc varchar(100) NOT NULL,
	geom geometry(polygon) NOT NULL
)
;

CREATE TABLE geoserver.drone_vlieg_gebieden
(
	identificatie varchar(100) NOT NULL,
	begin_geldigheid date NOT NULL,
	eind_geldigheid date NULL,
	beleid_type_code varchar(20) NOT NULL,
	beleid_type_desc varchar(100) NOT NULL,
	beleid_naam_code varchar(20) NOT NULL,
	beleid_naam_desc varchar(100) NOT NULL,
	beleid_naam_bronhouder varchar(100) NOT NULL,
	beleid_bron_naam varchar(100) NOT NULL,
	beleid_bron_datum timestamp NOT NULL,
	beleid_bron_url varchar(255) NOT NULL,
	bronhouder_code varchar(20) NOT NULL,
	bronhouder_desc varchar(100) NOT NULL,
	geom geometry(polygon) NOT NULL
)
;

CREATE TABLE geoserver.duisternis_gebieden
(
	identificatie varchar(100) NOT NULL,
	begin_geldigheid date NOT NULL,
	eind_geldigheid date NULL,
	beleid_type_code varchar(20) NOT NULL,
	beleid_type_desc varchar(100) NOT NULL,
	beleid_naam_code varchar(20) NOT NULL,
	beleid_naam_desc varchar(100) NOT NULL,
	beleid_naam_bronhouder varchar(100) NOT NULL,
	beleid_bron_naam varchar(100) NOT NULL,
	beleid_bron_datum timestamp NOT NULL,
	beleid_bron_url varchar(255) NOT NULL,
	bronhouder_code varchar(20) NOT NULL,
	bronhouder_desc varchar(100) NOT NULL,
	geom geometry(polygon) NOT NULL
)
;

CREATE TABLE geoserver.ecologiche_verbindingszone
(
	identificatie varchar(100) NOT NULL,
	begin_geldigheid date NOT NULL,
	eind_geldigheid date NULL,
	beleid_type_code varchar(20) NOT NULL,
	beleid_type_desc varchar(100) NOT NULL,
	beleid_naam_code varchar(20) NOT NULL,
	beleid_naam_desc varchar(100) NOT NULL,
	beleid_naam_bronhouder varchar(100) NOT NULL,
	beleid_bron_naam varchar(100) NOT NULL,
	beleid_bron_datum timestamp NOT NULL,
	beleid_bron_url varchar(255) NOT NULL,
	bronhouder_code varchar(20) NOT NULL,
	bronhouder_desc varchar(100) NOT NULL,
	geom geometry(polygon) NOT NULL
)
;

CREATE TABLE geoserver.erosie_verordening
(
	identificatie varchar(100) NOT NULL,
	begin_geldigheid date NOT NULL,
	eind_geldigheid date NULL,
	beleid_type_code varchar(20) NOT NULL,
	beleid_type_desc varchar(100) NOT NULL,
	beleid_naam_code varchar(20) NOT NULL,
	beleid_naam_desc varchar(100) NOT NULL,
	beleid_naam_bronhouder varchar(100) NOT NULL,
	beleid_bron_naam varchar(100) NOT NULL,
	beleid_bron_datum timestamp NOT NULL,
	beleid_bron_url varchar(255) NOT NULL,
	bronhouder_code varchar(20) NOT NULL,
	bronhouder_desc varchar(100) NOT NULL,
	geom geometry(polygon) NOT NULL
)
;

CREATE TABLE geoserver.faunabeheereenheid_of_wildbeheereenheid
(
	identificatie varchar(100) NOT NULL,
	begin_geldigheid date NOT NULL,
	eind_geldigheid date NULL,
	beleid_type_code varchar(20) NOT NULL,
	beleid_type_desc varchar(100) NOT NULL,
	beleid_naam_code varchar(20) NOT NULL,
	beleid_naam_desc varchar(100) NOT NULL,
	beleid_naam_bronhouder varchar(100) NOT NULL,
	beleid_bron_naam varchar(100) NOT NULL,
	beleid_bron_datum timestamp NOT NULL,
	beleid_bron_url varchar(255) NOT NULL,
	bronhouder_code varchar(20) NOT NULL,
	bronhouder_desc varchar(100) NOT NULL,
	geom geometry(polygon) NOT NULL
)
;

CREATE TABLE geoserver.ganzen_foerageergebied
(
	identificatie varchar(100) NOT NULL,
	begin_geldigheid date NOT NULL,
	eind_geldigheid date NULL,
	beleid_type_code varchar(20) NOT NULL,
	beleid_type_desc varchar(100) NOT NULL,
	beleid_naam_code varchar(20) NOT NULL,
	beleid_naam_desc varchar(100) NOT NULL,
	beleid_naam_bronhouder varchar(100) NOT NULL,
	beleid_bron_naam varchar(100) NOT NULL,
	beleid_bron_datum timestamp NOT NULL,
	beleid_bron_url varchar(255) NOT NULL,
	bronhouder_code varchar(20) NOT NULL,
	bronhouder_desc varchar(100) NOT NULL,
	geom geometry(polygon) NOT NULL
)
;

CREATE TABLE geoserver.grondwater_bescherming
(
	identificatie varchar(100) NOT NULL,
	begin_geldigheid date NOT NULL,
	eind_geldigheid date NULL,
	beleid_type_code varchar(20) NOT NULL,
	beleid_type_desc varchar(100) NOT NULL,
	beleid_naam_code varchar(20) NOT NULL,
	beleid_naam_desc varchar(100) NOT NULL,
	beleid_naam_bronhouder varchar(100) NOT NULL,
	beleid_bron_naam varchar(100) NOT NULL,
	beleid_bron_datum timestamp NOT NULL,
	beleid_bron_url varchar(255) NOT NULL,
	bronhouder_code varchar(20) NOT NULL,
	bronhouder_desc varchar(100) NOT NULL,
	geom geometry(polygon) NOT NULL
)
;

CREATE TABLE geoserver.leefgebied_akkervogels
(
	identificatie varchar(100) NOT NULL,
	begin_geldigheid date NOT NULL,
	eind_geldigheid date NULL,
	beleid_type_code varchar(20) NOT NULL,
	beleid_type_desc varchar(100) NOT NULL,
	beleid_naam_code varchar(20) NOT NULL,
	beleid_naam_desc varchar(100) NOT NULL,
	beleid_naam_bronhouder varchar(100) NOT NULL,
	beleid_bron_naam varchar(100) NOT NULL,
	beleid_bron_datum timestamp NOT NULL,
	beleid_bron_url varchar(255) NOT NULL,
	bronhouder_code varchar(20) NOT NULL,
	bronhouder_desc varchar(100) NOT NULL,
	geom geometry(polygon) NOT NULL
)
;

CREATE TABLE geoserver.leefgebied_weidevogels
(
	identificatie varchar(100) NOT NULL,
	begin_geldigheid date NOT NULL,
	eind_geldigheid date NULL,
	beleid_type_code varchar(20) NOT NULL,
	beleid_type_desc varchar(100) NOT NULL,
	beleid_naam_code varchar(20) NOT NULL,
	beleid_naam_desc varchar(100) NOT NULL,
	beleid_naam_bronhouder varchar(100) NOT NULL,
	beleid_bron_naam varchar(100) NOT NULL,
	beleid_bron_datum timestamp NOT NULL,
	beleid_bron_url varchar(255) NOT NULL,
	bronhouder_code varchar(20) NOT NULL,
	bronhouder_desc varchar(100) NOT NULL,
	geom geometry(polygon) NOT NULL
)
;

CREATE TABLE geoserver.militaire_terreinen
(
	identificatie varchar(100) NOT NULL,
	begin_geldigheid date NOT NULL,
	eind_geldigheid date NULL,
	beleid_type_code varchar(20) NOT NULL,
	beleid_type_desc varchar(100) NOT NULL,
	beleid_naam_code varchar(20) NOT NULL,
	beleid_naam_desc varchar(100) NOT NULL,
	beleid_naam_bronhouder varchar(100) NOT NULL,
	beleid_bron_naam varchar(100) NOT NULL,
	beleid_bron_datum timestamp NOT NULL,
	beleid_bron_url varchar(255) NOT NULL,
	bronhouder_code varchar(20) NOT NULL,
	bronhouder_desc varchar(100) NOT NULL,
	geom geometry(polygon) NOT NULL
)
;

CREATE TABLE geoserver.nationaal_landschap
(
	identificatie varchar(100) NOT NULL,
	begin_geldigheid date NOT NULL,
	eind_geldigheid date NULL,
	beleid_type_code varchar(20) NOT NULL,
	beleid_type_desc varchar(100) NOT NULL,
	beleid_naam_code varchar(20) NOT NULL,
	beleid_naam_desc varchar(100) NOT NULL,
	beleid_naam_bronhouder varchar(100) NOT NULL,
	beleid_bron_naam varchar(100) NOT NULL,
	beleid_bron_datum timestamp NOT NULL,
	beleid_bron_url varchar(255) NOT NULL,
	bronhouder_code varchar(20) NOT NULL,
	bronhouder_desc varchar(100) NOT NULL,
	geom geometry(polygon) NOT NULL
)
;

CREATE TABLE geoserver.nationale_parken
(
	identificatie varchar(100) NOT NULL,
	begin_geldigheid date NOT NULL,
	eind_geldigheid date NULL,
	beleid_type_code varchar(20) NOT NULL,
	beleid_type_desc varchar(100) NOT NULL,
	beleid_naam_code varchar(20) NOT NULL,
	beleid_naam_desc varchar(100) NOT NULL,
	beleid_naam_bronhouder varchar(100) NOT NULL,
	beleid_bron_naam varchar(100) NOT NULL,
	beleid_bron_datum timestamp NOT NULL,
	beleid_bron_url varchar(255) NOT NULL,
	bronhouder_code varchar(20) NOT NULL,
	bronhouder_desc varchar(100) NOT NULL,
	geom geometry(polygon) NOT NULL
)
;

CREATE TABLE geoserver.natte_natuurparels
(
	identificatie varchar(100) NOT NULL,
	begin_geldigheid date NOT NULL,
	eind_geldigheid date NULL,
	beleid_type_code varchar(20) NOT NULL,
	beleid_type_desc varchar(100) NOT NULL,
	beleid_naam_code varchar(20) NOT NULL,
	beleid_naam_desc varchar(100) NOT NULL,
	beleid_naam_bronhouder varchar(100) NOT NULL,
	beleid_bron_naam varchar(100) NOT NULL,
	beleid_bron_datum timestamp NOT NULL,
	beleid_bron_url varchar(255) NOT NULL,
	bronhouder_code varchar(20) NOT NULL,
	bronhouder_desc varchar(100) NOT NULL,
	geom geometry(polygon) NOT NULL
)
;

CREATE TABLE geoserver.natura_2000_beheerplannen
(
	identificatie varchar(100) NOT NULL,
	begin_geldigheid date NOT NULL,
	eind_geldigheid date NULL,
	beleid_type_code varchar(20) NOT NULL,
	beleid_type_desc varchar(100) NOT NULL,
	beleid_naam_code varchar(20) NOT NULL,
	beleid_naam_desc varchar(100) NOT NULL,
	beleid_naam_bronhouder varchar(100) NOT NULL,
	beleid_bron_naam varchar(100) NOT NULL,
	beleid_bron_datum timestamp NOT NULL,
	beleid_bron_url varchar(255) NOT NULL,
	bronhouder_code varchar(20) NOT NULL,
	bronhouder_desc varchar(100) NOT NULL,
	richtlijn_code varchar(20) NOT NULL,
	richtlijn_desc varchar(100) NOT NULL,
	geom geometry(polygon) NOT NULL
)
;

CREATE TABLE geoserver.natura_2000_bufferzone
(
	identificatie varchar(100) NOT NULL,
	begin_geldigheid date NOT NULL,
	eind_geldigheid date NULL,
	beleid_type_code varchar(20) NOT NULL,
	beleid_type_desc varchar(100) NOT NULL,
	beleid_naam_code varchar(20) NOT NULL,
	beleid_naam_desc varchar(100) NOT NULL,
	beleid_naam_bronhouder varchar(100) NOT NULL,
	beleid_bron_naam varchar(100) NOT NULL,
	beleid_bron_datum timestamp NOT NULL,
	beleid_bron_url varchar(255) NOT NULL,
	bronhouder_code varchar(20) NOT NULL,
	bronhouder_desc varchar(100) NOT NULL,
	geom geometry(polygon) NOT NULL
)
;

CREATE TABLE geoserver.natuur_netwerk_nederland
(
	identificatie varchar(100) NOT NULL,
	begin_geldigheid date NOT NULL,
	eind_geldigheid date NULL,
	beleid_type_code varchar(20) NOT NULL,
	beleid_type_desc varchar(100) NOT NULL,
	beleid_naam_code varchar(20) NOT NULL,
	beleid_naam_desc varchar(100) NOT NULL,
	beleid_naam_bronhouder varchar(100) NOT NULL,
	beleid_bron_naam varchar(100) NOT NULL,
	beleid_bron_datum timestamp NOT NULL,
	beleid_bron_url varchar(255) NOT NULL,
	bronhouder_code varchar(20) NOT NULL,
	bronhouder_desc varchar(100) NOT NULL,
	geom geometry(polygon) NOT NULL
)
;

CREATE TABLE geoserver.natuur_netwerk_rijkswateren
(
	identificatie varchar(100) NOT NULL,
	begin_geldigheid date NOT NULL,
	eind_geldigheid date NULL,
	beleid_type_code varchar(20) NOT NULL,
	beleid_type_desc varchar(100) NOT NULL,
	beleid_naam_code varchar(20) NOT NULL,
	beleid_naam_desc varchar(100) NOT NULL,
	beleid_naam_bronhouder varchar(100) NOT NULL,
	beleid_bron_naam varchar(100) NOT NULL,
	beleid_bron_datum timestamp NOT NULL,
	beleid_bron_url varchar(255) NOT NULL,
	bronhouder_code varchar(20) NOT NULL,
	bronhouder_desc varchar(100) NOT NULL,
	geom geometry(polygon) NOT NULL
)
;

CREATE TABLE geoserver.natuur_netwerk_rijkswateren_watervlakken
(
	identificatie varchar(100) NOT NULL,
	begin_geldigheid date NOT NULL,
	eind_geldigheid date NULL,
	beleid_type_code varchar(20) NOT NULL,
	beleid_type_desc varchar(100) NOT NULL,
	beleid_naam_code varchar(20) NOT NULL,
	beleid_naam_desc varchar(100) NOT NULL,
	beleid_naam_bronhouder varchar(100) NOT NULL,
	beleid_bron_naam varchar(100) NOT NULL,
	beleid_bron_datum timestamp NOT NULL,
	beleid_bron_url varchar(255) NOT NULL,
	bronhouder_code varchar(20) NOT NULL,
	bronhouder_desc varchar(100) NOT NULL,
	geom geometry(polygon) NOT NULL
)
;

CREATE TABLE geoserver.overgangszone_nnn
(
	identificatie varchar(100) NOT NULL,
	begin_geldigheid date NOT NULL,
	eind_geldigheid date NULL,
	beleid_type_code varchar(20) NOT NULL,
	beleid_type_desc varchar(100) NOT NULL,
	beleid_naam_code varchar(20) NOT NULL,
	beleid_naam_desc varchar(100) NOT NULL,
	beleid_naam_bronhouder varchar(100) NOT NULL,
	beleid_bron_naam varchar(100) NOT NULL,
	beleid_bron_datum timestamp NOT NULL,
	beleid_bron_url varchar(255) NOT NULL,
	bronhouder_code varchar(20) NOT NULL,
	bronhouder_desc varchar(100) NOT NULL,
	geom geometry(polygon) NOT NULL
)
;

CREATE TABLE geoserver.stilte_gebieden
(
	identificatie varchar(100) NOT NULL,
	begin_geldigheid date NOT NULL,
	eind_geldigheid date NULL,
	beleid_type_code varchar(20) NOT NULL,
	beleid_type_desc varchar(100) NOT NULL,
	beleid_naam_code varchar(20) NOT NULL,
	beleid_naam_desc varchar(100) NOT NULL,
	beleid_naam_bronhouder varchar(100) NOT NULL,
	beleid_bron_naam varchar(100) NOT NULL,
	beleid_bron_datum timestamp NOT NULL,
	beleid_bron_url varchar(255) NOT NULL,
	bronhouder_code varchar(20) NOT NULL,
	bronhouder_desc varchar(100) NOT NULL,
	geom geometry(polygon) NOT NULL
)
;

CREATE TABLE geoserver.waardevolle_open_gebieden
(
	identificatie varchar(100) NOT NULL,
	begin_geldigheid date NOT NULL,
	eind_geldigheid date NULL,
	beleid_type_code varchar(20) NOT NULL,
	beleid_type_desc varchar(100) NOT NULL,
	beleid_naam_code varchar(20) NOT NULL,
	beleid_naam_desc varchar(100) NOT NULL,
	beleid_naam_bronhouder varchar(100) NOT NULL,
	beleid_bron_naam varchar(100) NOT NULL,
	beleid_bron_datum timestamp NOT NULL,
	beleid_bron_url varchar(255) NOT NULL,
	bronhouder_code varchar(20) NOT NULL,
	bronhouder_desc varchar(100) NOT NULL,
	geom geometry(polygon) NOT NULL
)
;

CREATE TABLE geoserver.waterbergings_gebied
(
	identificatie varchar(100) NOT NULL,
	begin_geldigheid date NOT NULL,
	eind_geldigheid date NULL,
	beleid_type_code varchar(20) NOT NULL,
	beleid_type_desc varchar(100) NOT NULL,
	beleid_naam_code varchar(20) NOT NULL,
	beleid_naam_desc varchar(100) NOT NULL,
	beleid_naam_bronhouder varchar(100) NOT NULL,
	beleid_bron_naam varchar(100) NOT NULL,
	beleid_bron_datum timestamp NOT NULL,
	beleid_bron_url varchar(255) NOT NULL,
	bronhouder_code varchar(20) NOT NULL,
	bronhouder_desc varchar(100) NOT NULL,
	geom geometry(polygon) NOT NULL
)
;

CREATE TABLE geoserver.werelderfgoed
(
	identificatie varchar(100) NOT NULL,
	begin_geldigheid date NOT NULL,
	eind_geldigheid date NULL,
	beleid_type_code varchar(20) NOT NULL,
	beleid_type_desc varchar(100) NOT NULL,
	beleid_naam_code varchar(20) NOT NULL,
	beleid_naam_desc varchar(100) NOT NULL,
	beleid_naam_bronhouder varchar(100) NOT NULL,
	beleid_bron_naam varchar(100) NOT NULL,
	beleid_bron_datum timestamp NOT NULL,
	beleid_bron_url varchar(255) NOT NULL,
	bronhouder_code varchar(20) NOT NULL,
	bronhouder_desc varchar(100) NOT NULL,
	geom geometry(polygon) NOT NULL
)
;

CREATE TABLE geoserver.wet_ammoniak_en_veehouderij_gebieden
(
	identificatie varchar(100) NOT NULL,
	begin_geldigheid date NOT NULL,
	eind_geldigheid date NULL,
	beleid_type_code varchar(20) NOT NULL,
	beleid_type_desc varchar(100) NOT NULL,
	beleid_naam_code varchar(20) NOT NULL,
	beleid_naam_desc varchar(100) NOT NULL,
	beleid_naam_bronhouder varchar(100) NOT NULL,
	beleid_bron_naam varchar(100) NOT NULL,
	beleid_bron_datum timestamp NOT NULL,
	beleid_bron_url varchar(255) NOT NULL,
	bronhouder_code varchar(20) NOT NULL,
	bronhouder_desc varchar(100) NOT NULL,
	geom geometry(polygon) NOT NULL
)
;

CREATE TABLE geoserver.wezenlijke_waarden_kenmerken_nnn
(
	identificatie varchar(100) NOT NULL,
	begin_geldigheid date NOT NULL,
	eind_geldigheid date NULL,
	beleid_type_code varchar(20) NOT NULL,
	beleid_type_desc varchar(100) NOT NULL,
	beleid_naam_code varchar(20) NOT NULL,
	beleid_naam_desc varchar(100) NOT NULL,
	beleid_naam_bronhouder varchar(100) NOT NULL,
	beleid_bron_naam varchar(100) NOT NULL,
	beleid_bron_datum timestamp NOT NULL,
	beleid_bron_url varchar(255) NOT NULL,
	bronhouder_code varchar(20) NOT NULL,
	bronhouder_desc varchar(100) NOT NULL,
	geom geometry(polygon) NOT NULL
)
;

CREATE TABLE geoserver.zoekgebied_robuuste_verbindingszones
(
	identificatie varchar(100) NOT NULL,
	begin_geldigheid date NOT NULL,
	eind_geldigheid date NULL,
	beleid_type_code varchar(20) NOT NULL,
	beleid_type_desc varchar(100) NOT NULL,
	beleid_naam_code varchar(20) NOT NULL,
	beleid_naam_desc varchar(100) NOT NULL,
	beleid_naam_bronhouder varchar(100) NOT NULL,
	beleid_bron_naam varchar(100) NOT NULL,
	beleid_bron_datum timestamp NOT NULL,
	beleid_bron_url varchar(255) NOT NULL,
	bronhouder_code varchar(20) NOT NULL,
	bronhouder_desc varchar(100) NOT NULL,
	geom geometry(polygon) NOT NULL
)
;

/* Create Primary Keys, Indexes, Uniques, Checks */

ALTER TABLE geoserver.attentiezones_nnn ADD CONSTRAINT PK_attentiezones_nnn
	PRIMARY KEY (identificatie,begin_geldigheid,bronhouder_code)
;

ALTER TABLE geoserver.beleid_totaal_historie ADD CONSTRAINT PK_beleid_totaal_historie
	PRIMARY KEY (identificatie,begin_geldigheid,bronhouder_code,beleid_type_code)
;

ALTER TABLE geoserver.beleid_totaal_huidig ADD CONSTRAINT PK_beleid_totaal_huidig
	PRIMARY KEY (identificatie,begin_geldigheid,bronhouder_code,beleid_type_code)
;

ALTER TABLE geoserver.beschermd_leefgebied ADD CONSTRAINT PK_beschermd_leefgebied
	PRIMARY KEY (identificatie,begin_geldigheid,bronhouder_code)
;

ALTER TABLE geoserver.beschermde_natuurmonumenten ADD CONSTRAINT PK_beschermde_natuurmonumenten
	PRIMARY KEY (identificatie,begin_geldigheid,bronhouder_code)
;

ALTER TABLE geoserver.bescherming_houtopstanden ADD CONSTRAINT PK_bescherming_houtopstanden
	PRIMARY KEY (identificatie,begin_geldigheid,bronhouder_code)
;

ALTER TABLE geoserver.bijzonder_provinciaal_landschap ADD CONSTRAINT PK_bijzonder_provinciaal_landschap
	PRIMARY KEY (identificatie,begin_geldigheid,bronhouder_code)
;

ALTER TABLE geoserver.bos_natuur_buiten_nnn ADD CONSTRAINT PK_bos_natuur_buiten_nnn
	PRIMARY KEY (identificatie,begin_geldigheid,bronhouder_code)
;

ALTER TABLE geoserver.bosreservaten ADD CONSTRAINT PK_bosreservaten
	PRIMARY KEY (identificatie,begin_geldigheid,bronhouder_code)
;

ALTER TABLE geoserver.cultuur_historische_waardenkaart ADD CONSTRAINT PK_cultuur_historische_waardenkaart
	PRIMARY KEY (identificatie,begin_geldigheid,bronhouder_code)
;

ALTER TABLE geoserver.distel_verordening ADD CONSTRAINT PK_distel_verordening
	PRIMARY KEY (identificatie,begin_geldigheid,bronhouder_code)
;

ALTER TABLE geoserver.drone_vlieg_gebieden ADD CONSTRAINT PK_drone_vlieg_gebieden
	PRIMARY KEY (identificatie,begin_geldigheid,bronhouder_code)
;

ALTER TABLE geoserver.duisternis_gebieden ADD CONSTRAINT PK_duisternis_gebieden
	PRIMARY KEY (identificatie,begin_geldigheid,bronhouder_code)
;

ALTER TABLE geoserver.ecologiche_verbindingszone ADD CONSTRAINT PK_ecologiche_verbindingszone
	PRIMARY KEY (identificatie,begin_geldigheid,bronhouder_code)
;

ALTER TABLE geoserver.erosie_verordening ADD CONSTRAINT PK_erosie_verordening
	PRIMARY KEY (identificatie,begin_geldigheid,bronhouder_code)
;

ALTER TABLE geoserver.faunabeheereenheid_of_wildbeheereenheid ADD CONSTRAINT PK_faunabeheereenheid_of_wildbeheereenheid
	PRIMARY KEY (identificatie,begin_geldigheid,bronhouder_code)
;

ALTER TABLE geoserver.ganzen_foerageergebied ADD CONSTRAINT PK_ganzen_foerageergebied
	PRIMARY KEY (identificatie,begin_geldigheid,bronhouder_code)
;

ALTER TABLE geoserver.grondwater_bescherming ADD CONSTRAINT PK_grondwater_bescherming
	PRIMARY KEY (identificatie,begin_geldigheid,bronhouder_code)
;

ALTER TABLE geoserver.leefgebied_akkervogels ADD CONSTRAINT PK_leefgebied_akkervogels
	PRIMARY KEY (identificatie,begin_geldigheid,bronhouder_code)
;

ALTER TABLE geoserver.leefgebied_weidevogels ADD CONSTRAINT PK_leefgebied_weidevogels
	PRIMARY KEY (identificatie,begin_geldigheid,bronhouder_code)
;

ALTER TABLE geoserver.militaire_terreinen ADD CONSTRAINT PK_militaire_terreinen
	PRIMARY KEY (identificatie,begin_geldigheid,bronhouder_code)
;

ALTER TABLE geoserver.nationaal_landschap ADD CONSTRAINT PK_nationaal_landschap
	PRIMARY KEY (identificatie,begin_geldigheid,bronhouder_code)
;

ALTER TABLE geoserver.nationale_parken ADD CONSTRAINT PK_nationale_parken
	PRIMARY KEY (identificatie,begin_geldigheid,bronhouder_code)
;

ALTER TABLE geoserver.natte_natuurparels ADD CONSTRAINT PK_natte_natuurparels
	PRIMARY KEY (identificatie,begin_geldigheid,bronhouder_code)
;

ALTER TABLE geoserver.natura_2000_beheerplannen ADD CONSTRAINT PK_natura_2000_beheerplannen
	PRIMARY KEY (identificatie,begin_geldigheid,bronhouder_code)
;

ALTER TABLE geoserver.natura_2000_bufferzone ADD CONSTRAINT PK_natura_2000_bufferzone
	PRIMARY KEY (identificatie,begin_geldigheid,bronhouder_code)
;

ALTER TABLE geoserver.natuur_netwerk_nederland ADD CONSTRAINT PK_natuur_netwerk_nederland
	PRIMARY KEY (identificatie,begin_geldigheid,bronhouder_code)
;

ALTER TABLE geoserver.natuur_netwerk_rijkswateren ADD CONSTRAINT PK_natuur_netwerk_rijkswateren
	PRIMARY KEY (identificatie,begin_geldigheid,bronhouder_code)
;

ALTER TABLE geoserver.natuur_netwerk_rijkswateren_watervlakken ADD CONSTRAINT PK_natuur_netwerk_rijkswateren_watervlakken
	PRIMARY KEY (identificatie,begin_geldigheid,bronhouder_code)
;

ALTER TABLE geoserver.overgangszone_nnn ADD CONSTRAINT PK_overgangszone_nnn
	PRIMARY KEY (identificatie,begin_geldigheid,bronhouder_code)
;

ALTER TABLE geoserver.stilte_gebieden ADD CONSTRAINT PK_stilte_gebieden
	PRIMARY KEY (identificatie,begin_geldigheid,bronhouder_code)
;

ALTER TABLE geoserver.waardevolle_open_gebieden ADD CONSTRAINT PK_waardevolle_open_gebieden
	PRIMARY KEY (identificatie,begin_geldigheid,bronhouder_code)
;

ALTER TABLE geoserver.waterbergings_gebied ADD CONSTRAINT PK_waterbergings_gebied
	PRIMARY KEY (identificatie,begin_geldigheid,bronhouder_code)
;

ALTER TABLE geoserver.werelderfgoed ADD CONSTRAINT PK_werelderfgoed
	PRIMARY KEY (identificatie,begin_geldigheid,bronhouder_code)
;

ALTER TABLE geoserver.wet_ammoniak_en_veehouderij_gebieden ADD CONSTRAINT PK_wet_ammoniak_en_veehouderij_gebieden
	PRIMARY KEY (identificatie,begin_geldigheid,bronhouder_code)
;

ALTER TABLE geoserver.wezenlijke_waarden_kenmerken_nnn ADD CONSTRAINT PK_wezenlijke_waarden_kenmerken_nnn
	PRIMARY KEY (identificatie,begin_geldigheid,bronhouder_code)
;

ALTER TABLE geoserver.zoekgebied_robuuste_verbindingszones ADD CONSTRAINT PK_zoekgebied_robuuste_verbindingszones
	PRIMARY KEY (identificatie,begin_geldigheid,bronhouder_code)
;


ALTER TABLE geoserver.natura_2000_beheerplannen
    OWNER to ikn;

GRANT ALL ON TABLE geoserver.natura_2000_beheerplannen TO ikn;

GRANT SELECT ON TABLE geoserver.natura_2000_beheerplannen TO ikn_readonly;

ALTER TABLE geoserver.natuur_netwerk_rijkswateren_watervlakken
  OWNER TO ikn;
GRANT SELECT ON TABLE geoserver.natuur_netwerk_rijkswateren_watervlakken TO ikn_readonly
; 

ALTER TABLE geoserver.natuur_netwerk_rijkswateren
  OWNER TO ikn;
GRANT SELECT ON TABLE geoserver.natuur_netwerk_rijkswateren TO ikn_readonly
; 

ALTER TABLE geoserver.natuur_netwerk_nederland
  OWNER TO ikn;
GRANT SELECT ON TABLE geoserver.natuur_netwerk_nederland TO ikn_readonly
; 

/* Ownership */

ALTER TABLE geoserver.attentiezones_nnn 
  OWNER TO ikn;

ALTER TABLE geoserver.beleid_totaal_historie 
  OWNER TO ikn;

ALTER TABLE geoserver.beleid_totaal_huidig 
  OWNER TO ikn;

ALTER TABLE geoserver.beschermd_leefgebied 
  OWNER TO ikn;

ALTER TABLE geoserver.beschermde_natuurmonumenten 
  OWNER TO ikn;

ALTER TABLE geoserver.bescherming_houtopstanden 
  OWNER TO ikn;

ALTER TABLE geoserver.bijzonder_provinciaal_landschap 
  OWNER TO ikn;

ALTER TABLE geoserver.bos_natuur_buiten_nnn 
  OWNER TO ikn;

ALTER TABLE geoserver.bosreservaten 
  OWNER TO ikn;

ALTER TABLE geoserver.cultuur_historische_waardenkaart 
  OWNER TO ikn;

ALTER TABLE geoserver.distel_verordening 
  OWNER TO ikn;

ALTER TABLE geoserver.drone_vlieg_gebieden 
  OWNER TO ikn;

ALTER TABLE geoserver.duisternis_gebieden 
  OWNER TO ikn;

ALTER TABLE geoserver.ecologiche_verbindingszone 
  OWNER TO ikn;

ALTER TABLE geoserver.erosie_verordening 
  OWNER TO ikn;

ALTER TABLE geoserver.faunabeheereenheid_of_wildbeheereenheid 
  OWNER TO ikn;

ALTER TABLE geoserver.ganzen_foerageergebied 
  OWNER TO ikn;

ALTER TABLE geoserver.grondwater_bescherming 
  OWNER TO ikn;

ALTER TABLE geoserver.leefgebied_akkervogels 
  OWNER TO ikn;

ALTER TABLE geoserver.leefgebied_weidevogels 
  OWNER TO ikn;

ALTER TABLE geoserver.militaire_terreinen 
  OWNER TO ikn;

ALTER TABLE geoserver.nationaal_landschap 
  OWNER TO ikn;

ALTER TABLE geoserver.nationale_parken 
  OWNER TO ikn;

ALTER TABLE geoserver.natte_natuurparels 
  OWNER TO ikn;

ALTER TABLE geoserver.natura_2000_bufferzone 
  OWNER TO ikn;

ALTER TABLE geoserver.overgangszone_nnn 
  OWNER TO ikn;

ALTER TABLE geoserver.stilte_gebieden 
  OWNER TO ikn;

ALTER TABLE geoserver.waardevolle_open_gebieden 
  OWNER TO ikn;

ALTER TABLE geoserver.waterbergings_gebied 
  OWNER TO ikn;

ALTER TABLE geoserver.werelderfgoed 
  OWNER TO ikn;

ALTER TABLE geoserver.wet_ammoniak_en_veehouderij_gebieden 
  OWNER TO ikn;

ALTER TABLE geoserver.wezenlijke_waarden_kenmerken_nnn 
  OWNER TO ikn;

ALTER TABLE geoserver.zoekgebied_robuuste_verbindingszones 
  OWNER TO ikn;

/* Grant */

GRANT SELECT ON TABLE geoserver.attentiezones_nnn TO ikn_readonly
;

GRANT SELECT ON TABLE geoserver.beleid_totaal_historie TO ikn_readonly
;

GRANT SELECT ON TABLE geoserver.beleid_totaal_huidig TO ikn_readonly
;

GRANT SELECT ON TABLE geoserver.beschermd_leefgebied TO ikn_readonly
;

GRANT SELECT ON TABLE geoserver.beschermde_natuurmonumenten TO ikn_readonly
;

GRANT SELECT ON TABLE geoserver.bescherming_houtopstanden TO ikn_readonly
;

GRANT SELECT ON TABLE geoserver.bijzonder_provinciaal_landschap TO ikn_readonly
;

GRANT SELECT ON TABLE geoserver.bos_natuur_buiten_nnn TO ikn_readonly
;

GRANT SELECT ON TABLE geoserver.bosreservaten TO ikn_readonly
;

GRANT SELECT ON TABLE geoserver.cultuur_historische_waardenkaart TO ikn_readonly
;

GRANT SELECT ON TABLE geoserver.distel_verordening TO ikn_readonly
;

GRANT SELECT ON TABLE geoserver.drone_vlieg_gebieden TO ikn_readonly
;

GRANT SELECT ON TABLE geoserver.duisternis_gebieden TO ikn_readonly
;

GRANT SELECT ON TABLE geoserver.ecologiche_verbindingszone TO ikn_readonly
;

GRANT SELECT ON TABLE geoserver.erosie_verordening TO ikn_readonly
;

GRANT SELECT ON TABLE geoserver.faunabeheereenheid_of_wildbeheereenheid TO ikn_readonly
;

GRANT SELECT ON TABLE geoserver.ganzen_foerageergebied TO ikn_readonly
;

GRANT SELECT ON TABLE geoserver.grondwater_bescherming TO ikn_readonly
;

GRANT SELECT ON TABLE geoserver.leefgebied_akkervogels TO ikn_readonly
;

GRANT SELECT ON TABLE geoserver.leefgebied_weidevogels TO ikn_readonly
;

GRANT SELECT ON TABLE geoserver.militaire_terreinen TO ikn_readonly
;

GRANT SELECT ON TABLE geoserver.nationaal_landschap TO ikn_readonly
;

GRANT SELECT ON TABLE geoserver.nationale_parken TO ikn_readonly
;

GRANT SELECT ON TABLE geoserver.natte_natuurparels TO ikn_readonly
;

GRANT SELECT ON TABLE geoserver.natura_2000_bufferzone TO ikn_readonly
;

GRANT SELECT ON TABLE geoserver.overgangszone_nnn TO ikn_readonly
;

GRANT SELECT ON TABLE geoserver.stilte_gebieden TO ikn_readonly
;

GRANT SELECT ON TABLE geoserver.waardevolle_open_gebieden TO ikn_readonly
;

GRANT SELECT ON TABLE geoserver.waterbergings_gebied TO ikn_readonly
;

GRANT SELECT ON TABLE geoserver.werelderfgoed TO ikn_readonly
;

GRANT SELECT ON TABLE geoserver.wet_ammoniak_en_veehouderij_gebieden TO ikn_readonly
;

GRANT SELECT ON TABLE geoserver.wezenlijke_waarden_kenmerken_nnn TO ikn_readonly
;

GRANT SELECT ON TABLE geoserver.zoekgebied_robuuste_verbindingszones TO ikn_readonly
;

/* Create Views */

-- View: geoserver.bron_specificatie_wfs

-- DROP VIEW geoserver.bron_specificatie_wfs;

CREATE OR REPLACE VIEW geoserver.bron_specificatie_wfs AS
SELECT beleid_naam_id,
       (SELECT code FROM masterdata.dmn_beleid_naam WHERE id = beleid_naam_id) AS beleid_naam_code,
	   (SELECT description FROM masterdata.dmn_beleid_naam WHERE id = beleid_naam_id) AS beleid_naam_desc,
	   bronhouder_id,
       (SELECT code FROM masterdata.dmn_bronhouder WHERE id = bronhouder_id) AS bronhouder_code,
	   (SELECT description FROM masterdata.dmn_bronhouder WHERE id = bronhouder_id) AS bronhouder_desc,
	   metadata_url,
	   wfs_end_point,
	   feature_type,
	   laatste_revisie,
	   NULL::geometry AS geom	   
  FROM masterdata.bron_specificatie_wfs;
ALTER TABLE geoserver.bron_specificatie_wfs
    OWNER TO ikn;

GRANT ALL ON TABLE geoserver.bron_specificatie_wfs TO ikn;
GRANT SELECT ON TABLE geoserver.bron_specificatie_wfs TO ikn_readonly;
;

-- View: geoserver.ikn_upload

-- DROP VIEW geoserver.ikn_upload;

CREATE OR REPLACE VIEW geoserver.ikn_upload AS
 SELECT ikn_upload.id,
    ikn_upload.informatie_kaart_aanlevering_id,
    ( SELECT dmn_bronhouder.code
           FROM masterdata.dmn_bronhouder
          WHERE dmn_bronhouder.id = ikn_upload.bronhouder_id) AS bronhouder_code,
    ( SELECT dmn_bronhouder.description
           FROM masterdata.dmn_bronhouder
          WHERE dmn_bronhouder.id = ikn_upload.bronhouder_id) AS bronhouder_desc,
    ( SELECT dmn_beleid_naam.code
           FROM masterdata.dmn_beleid_naam
          WHERE dmn_beleid_naam.id = ikn_upload.beleid_naam_id) AS beleid_naam_code,
    ( SELECT dmn_beleid_naam.description
           FROM masterdata.dmn_beleid_naam
          WHERE dmn_beleid_naam.id = ikn_upload.beleid_naam_id) AS beleid_naam_desc,
    ( SELECT dmn_bron_type.code
           FROM masterdata.dmn_bron_type
          WHERE dmn_bron_type.id = ikn_upload.bron_type_id) AS bron_type_code,
    ( SELECT dmn_bron_type.description
           FROM masterdata.dmn_bron_type
          WHERE dmn_bron_type.id = ikn_upload.bron_type_id) AS bron_type_desc,
    ikn_upload.upload_date,
    ikn_upload.user_id,
    ikn_upload.status,
	NULL::geometry AS geom
   FROM geoweb.ikn_upload;

ALTER TABLE geoserver.ikn_upload
    OWNER TO ikn;

GRANT ALL ON TABLE geoserver.ikn_upload TO ikn;
GRANT SELECT ON TABLE geoserver.ikn_upload TO ikn_readonly;

;

-- View: geoserver.ikn_upload_files

-- DROP VIEW geoserver.ikn_upload_files;

CREATE OR REPLACE VIEW geoserver.ikn_upload_files AS
 SELECT ikn_upload.id,
    ikn_upload.informatie_kaart_aanlevering_id,
    ( SELECT dmn_bronhouder.code
           FROM masterdata.dmn_bronhouder
          WHERE dmn_bronhouder.id = ikn_upload.bronhouder_id) AS bronhouder_code,
    ( SELECT dmn_bronhouder.description
           FROM masterdata.dmn_bronhouder
          WHERE dmn_bronhouder.id = ikn_upload.bronhouder_id) AS bronhouder_desc,
    ( SELECT dmn_beleid_naam.code
           FROM masterdata.dmn_beleid_naam
          WHERE dmn_beleid_naam.id = ikn_upload.beleid_naam_id) AS beleid_naam_code,
    ( SELECT dmn_beleid_naam.description
           FROM masterdata.dmn_beleid_naam
          WHERE dmn_beleid_naam.id = ikn_upload.beleid_naam_id) AS beleid_naam_desc,
    ( SELECT dmn_bron_type.code
           FROM masterdata.dmn_bron_type
          WHERE dmn_bron_type.id = ikn_upload.bron_type_id) AS bron_type_code,
    ( SELECT dmn_bron_type.description
           FROM masterdata.dmn_bron_type
          WHERE dmn_bron_type.id = ikn_upload.bron_type_id) AS bron_type_desc,
    ikn_upload.upload_date,
    ikn_upload.user_id,
    ikn_upload_files.file_name,
    ikn_upload_files.file_type,
    ((((( SELECT parameters.value
           FROM masterdata.parameters
          WHERE parameters.name::text = 'GeoWebIKNGetFileURL'::text))::text) || ikn_upload.id) || '/'::text) || ikn_upload_files.file_name::text AS file_url,
	NULL::geometry AS geom
   FROM geoweb.ikn_upload
     JOIN geoweb.ikn_upload_files ON ikn_upload.id = ikn_upload_files.ikn_upload_id;

ALTER TABLE geoserver.ikn_upload_files
    OWNER TO ikn;

GRANT ALL ON TABLE geoserver.ikn_upload_files TO ikn;
GRANT SELECT ON TABLE geoserver.ikn_upload_files TO ikn_readonly;

;
