/* ---------------------------------------------------- */
/*  Generated by Enterprise Architect Version 12.1 		*/
/*  Created On : 23-Feb-2022 12:36:23 				*/
/*  DBMS       : PostgreSQL 						*/
/* ---------------------------------------------------- */

/* Create Primary Keys, Indexes, Uniques, Checks */

ALTER TABLE masterdata.provinces DROP CONSTRAINT PK_provinces
;

ALTER TABLE masterdata.provinces ADD CONSTRAINT PK_provinces
	PRIMARY KEY (code,program)
;

ALTER TABLE masterdata.provinces ADD CONSTRAINT UN_provincies_program_role UNIQUE (program,drupal_role)
;