/* ---------------------------------------------------- */
/*  Generated by Enterprise Architect Version 12.1 		*/
/*  Created On : 27-Feb-2022 00:08:48 				*/
/*  DBMS       : PostgreSQL 						*/
/* ---------------------------------------------------- */

/* Create Tables */

CREATE TABLE masterdata.features_overlap
(
	feature1 varchar(100) NOT NULL,
	feature2 varchar(100) NOT NULL,
	must_overlap_or_may_not_overlap boolean NOT NULL    -- when true layers must overlap when false layers may not overlap
)
;

/* Create Primary Keys, Indexes, Uniques, Checks */

ALTER TABLE masterdata.features_overlap ADD CONSTRAINT PK_features_overlap
	PRIMARY KEY (feature1,feature2)
;

/* Create Table Comments, Sequences for Autonumber Columns */

COMMENT ON COLUMN masterdata.features_overlap.must_overlap_or_may_not_overlap
	IS 'when true layers must overlap when false layers may not overlap'
;

ALTER TABLE masterdata.features_overlap
    OWNER to anlb;

GRANT ALL ON TABLE masterdata.features_overlap TO anlb;

GRANT SELECT ON TABLE masterdata.features_overlap TO anlb_sqlpad;

GRANT SELECT ON TABLE masterdata.features_overlap TO snl_readonly;