/* ---------------------------------------------------- */
/*  Generated by Enterprise Architect Version 12.1 		*/
/*  Created On : 16-dec-2019 10:59:36 				*/
/*  DBMS       : PostgreSQL 						*/
/* ---------------------------------------------------- */

CREATE SCHEMA masterdata
  AUTHORIZATION anlb;

GRANT USAGE ON SCHEMA masterdata TO anlb_sqlpad;  

/* Create Sequences */

CREATE SEQUENCE masterdata.masterdata_seq
    INCREMENT 1
    START 1
    MINVALUE 1
    MAXVALUE 9223372036854775807
    CACHE 1;

ALTER SEQUENCE masterdata.masterdata_seq
    OWNER TO anlb
;

/* Create Tables */

CREATE TABLE masterdata.dmn_ambitiegebied_type
(
	id bigint NOT NULL   DEFAULT NEXTVAL(('masterdata.masterdata_seq'::text)::regclass),
	code char(20) NOT NULL,
	description char(100),
	active boolean NOT NULL
)
;

CREATE TABLE masterdata.dmn_beheer_functie
(
	id bigint NOT NULL   DEFAULT NEXTVAL(('masterdata.masterdata_seq'::text)::regclass),
	code char(20) NOT NULL,
	description char(100),
	active boolean NOT NULL
)
;

CREATE TABLE masterdata.dmn_beheer_pakket
(
	id bigint NOT NULL   DEFAULT NEXTVAL(('masterdata.masterdata_seq'::text)::regclass),
	code char(20) NOT NULL,
	description char(100),
	active boolean NOT NULL
)
;

CREATE TABLE masterdata.dmn_beheer_pakket_landschap
(
	id bigint NOT NULL   DEFAULT NEXTVAL(('masterdata.masterdata_seq'::text)::regclass),
	code char(20) NOT NULL,
	description char(100),
	active boolean NOT NULL
)
;

CREATE TABLE masterdata.dmn_beheer_type
(
	id bigint NOT NULL   DEFAULT NEXTVAL(('masterdata.masterdata_seq'::text)::regclass),
	code char(20) NOT NULL,
	description char(100),
	active boolean NOT NULL
)
;

CREATE TABLE masterdata.dmn_beheer_type_agrarisch
(
	id bigint NOT NULL   DEFAULT NEXTVAL(('masterdata.masterdata_seq'::text)::regclass),
	code char(20) NOT NULL,
	description char(100),
	active boolean NOT NULL
)
;

CREATE TABLE masterdata.dmn_beheer_type_grootschaligenatuur
(
	id bigint NOT NULL   DEFAULT NEXTVAL(('masterdata.masterdata_seq'::text)::regclass),
	code char(20) NOT NULL,
	description char(100),
	active boolean NOT NULL
)
;

CREATE TABLE masterdata.dmn_beheer_type_landschap
(
	id bigint NOT NULL   DEFAULT NEXTVAL(('masterdata.masterdata_seq'::text)::regclass),
	code char(20) NOT NULL,
	description char(100),
	active boolean NOT NULL
)
;

CREATE TABLE masterdata.dmn_beheer_type_natuur
(
	id bigint NOT NULL   DEFAULT NEXTVAL(('masterdata.masterdata_seq'::text)::regclass),
	code char(20) NOT NULL,
	description char(100),
	active boolean NOT NULL
)
;

CREATE TABLE masterdata.dmn_beheer_type_natuur_ambitie
(
	id bigint NOT NULL   DEFAULT NEXTVAL(('masterdata.masterdata_seq'::text)::regclass),
	code char(20) NOT NULL,
	description char(100),
	active boolean NOT NULL
)
;

CREATE TABLE masterdata.dmn_beheer_type_omtevormennatuur_ambitie
(
	id bigint NOT NULL   DEFAULT NEXTVAL(('masterdata.masterdata_seq'::text)::regclass),
	code char(20) NOT NULL,
	description char(100),
	active boolean NOT NULL
)
;

CREATE TABLE masterdata.dmn_beheer_type_water
(
	id bigint NOT NULL   DEFAULT NEXTVAL(('masterdata.masterdata_seq'::text)::regclass),
	code char(20) NOT NULL,
	description char(100),
	active boolean NOT NULL
)
;

CREATE TABLE masterdata.dmn_beheergebied_type
(
	id bigint NOT NULL   DEFAULT NEXTVAL(('masterdata.masterdata_seq'::text)::regclass),
	code char(20) NOT NULL,
	description char(100),
	active boolean NOT NULL
)
;

CREATE TABLE masterdata.dmn_bijzonder_gebied_code
(
	id bigint NOT NULL   DEFAULT NEXTVAL(('masterdata.masterdata_seq'::text)::regclass),
	code char(20) NOT NULL,
	description char(100),
	active boolean NOT NULL
)
;

CREATE TABLE masterdata.dmn_natuur_type
(
	id bigint NOT NULL   DEFAULT NEXTVAL(('masterdata.masterdata_seq'::text)::regclass),
	code char(20) NOT NULL,
	description char(100),
	active boolean NOT NULL
)
;

CREATE TABLE masterdata.dmn_natuur_type_agrarisch
(
	id bigint NOT NULL   DEFAULT NEXTVAL(('masterdata.masterdata_seq'::text)::regclass),
	code char(20) NOT NULL,
	description char(100),
	active boolean NOT NULL
)
;

CREATE TABLE masterdata.dmn_natuur_type_water
(
	id bigint NOT NULL   DEFAULT NEXTVAL(('masterdata.masterdata_seq'::text)::regclass),
	code char(20) NOT NULL,
	description char(100),
	active boolean NOT NULL
)
;

CREATE TABLE masterdata.dmn_openstellings_bijdrage_type
(
	id bigint NOT NULL   DEFAULT NEXTVAL(('masterdata.masterdata_seq'::text)::regclass),
	code char(20) NOT NULL,
	description char(100),
	active boolean NOT NULL
)
;

CREATE TABLE masterdata.dmn_provincie_code
(
	id bigint NOT NULL   DEFAULT NEXTVAL(('masterdata.masterdata_seq'::text)::regclass),
	code char(20) NOT NULL,
	description char(100),
	active boolean NOT NULL
)
;

CREATE TABLE masterdata.dmn_status_ehs
(
	id bigint NOT NULL   DEFAULT NEXTVAL(('masterdata.masterdata_seq'::text)::regclass),
	code char(20) NOT NULL,
	description char(100),
	active boolean NOT NULL
)
;

CREATE TABLE masterdata.dmn_status_plan
(
	id bigint NOT NULL   DEFAULT NEXTVAL(('masterdata.masterdata_seq'::text)::regclass),
	code char(20) NOT NULL,
	description char(100),
	active boolean NOT NULL
)
;

CREATE TABLE masterdata.domain_feature
(
	domain char(100) NOT NULL,
	feature char(100) NOT NULL,
	attribute char(100) NOT NULL
)
;

CREATE TABLE masterdata.feature_layer
(
	feature char(100) NOT NULL,
	layer char(100) NOT NULL,
	geo_validation boolean NOT NULL,
	self_overlap_validation boolean NOT NULL,
	multipart_validation boolean NOT NULL
)
;

CREATE TABLE masterdata.lnk_table_ambitiegebied_type
(
	ambitiegebied_type_id bigint NOT NULL,
	beheer_type_id bigint NOT NULL
)
;

CREATE TABLE masterdata.lnk_table_beheer_functies
(
	natuur_type_id bigint NOT NULL,
	beheer_functie_id bigint NOT NULL,
	active boolean NOT NULL
)
;

CREATE TABLE masterdata.lnk_table_beheer_typen
(
	natuur_type_id bigint NOT NULL,
	beheer_type_id bigint NOT NULL,
	active boolean NOT NULL
)
;

CREATE TABLE masterdata.lnk_table_beheergebied_type
(
	beheergebied_type_id bigint NOT NULL,
	beheer_type_id bigint NOT NULL
)
;

CREATE TABLE masterdata.lnk_table_beheerpakket
(
	beheer_type_id bigint NOT NULL,
	beheer_pakket_id bigint NOT NULL,
	active boolean NOT NULL
)
;

CREATE TABLE masterdata.mandatory_attributes
(
	feature char(100) NOT NULL,
	attribute char(100) NOT NULL
)
;

CREATE TABLE masterdata.parameters
(
	name varchar(50) NOT NULL,
	value varchar(1024) NOT NULL
)
;

CREATE TABLE masterdata.provinces
(
	code char(2) NOT NULL,
	drupal_role char(50) NOT NULL,
	name char(50) NOT NULL
)
;

CREATE TABLE masterdata.specific_attribute_types
(
	feature varchar(100) NOT NULL,
	attribute varchar(100) NOT NULL,
	type varchar(20) NOT NULL,
	length bigint
)
;

CREATE TABLE masterdata.translations
(
	nl varchar(255) NOT NULL,
	en varchar(255) NOT NULL
)
;

/* Create Primary Keys, Indexes, Uniques, Checks */

ALTER TABLE masterdata.dmn_ambitiegebied_type ADD CONSTRAINT PK_dmn_ambitiegebied_type
	PRIMARY KEY (id)
;

ALTER TABLE masterdata.dmn_ambitiegebied_type ADD CONSTRAINT un_code_ambitiegebied_type UNIQUE (code)
;

ALTER TABLE masterdata.dmn_beheer_functie ADD CONSTRAINT PK_dmn_beheer_functie
	PRIMARY KEY (id)
;

ALTER TABLE masterdata.dmn_beheer_functie ADD CONSTRAINT un_code_beheer_functie UNIQUE (code)
;

ALTER TABLE masterdata.dmn_beheer_pakket ADD CONSTRAINT PK_dmn_beheer_pakket
	PRIMARY KEY (id)
;

ALTER TABLE masterdata.dmn_beheer_pakket ADD CONSTRAINT un_code_beheer_pakket UNIQUE (code)
;

ALTER TABLE masterdata.dmn_beheer_pakket_landschap ADD CONSTRAINT PK_dmn_beheer_pakket_landschap
	PRIMARY KEY (id)
;

ALTER TABLE masterdata.dmn_beheer_pakket_landschap ADD CONSTRAINT un_code_beheer_pakket_landschap UNIQUE (code)
;

ALTER TABLE masterdata.dmn_beheer_type ADD CONSTRAINT PK_dmn_beheer_type
	PRIMARY KEY (id)
;

ALTER TABLE masterdata.dmn_beheer_type ADD CONSTRAINT un_code_beheer_type UNIQUE (code)
;

ALTER TABLE masterdata.dmn_beheer_type_agrarisch ADD CONSTRAINT PK_dmn_beheer_type_agrarisch
	PRIMARY KEY (id)
;

ALTER TABLE masterdata.dmn_beheer_type_agrarisch ADD CONSTRAINT un_code_beheer_type_agrarisch UNIQUE (code)
;

ALTER TABLE masterdata.dmn_beheer_type_grootschaligenatuur ADD CONSTRAINT PK_dmn_gebied_type_grootschalige_natuur
	PRIMARY KEY (id)
;

ALTER TABLE masterdata.dmn_beheer_type_grootschaligenatuur ADD CONSTRAINT un_code_gebied_type_grootschalige_natuur UNIQUE (code)
;

ALTER TABLE masterdata.dmn_beheer_type_landschap ADD CONSTRAINT PK_dmn_beheer_type_landschap
	PRIMARY KEY (id)
;

ALTER TABLE masterdata.dmn_beheer_type_landschap ADD CONSTRAINT un_code_beheer_type_landschap UNIQUE (code)
;

ALTER TABLE masterdata.dmn_beheer_type_natuur ADD CONSTRAINT PK_dmn_gebied_type_natuur
	PRIMARY KEY (id)
;

ALTER TABLE masterdata.dmn_beheer_type_natuur ADD CONSTRAINT un_code_gebied_type_natuur UNIQUE (code)
;

ALTER TABLE masterdata.dmn_beheer_type_natuur_ambitie ADD CONSTRAINT PK_dmn_beheer_type_natuur_ambitie
	PRIMARY KEY (id)
;

ALTER TABLE masterdata.dmn_beheer_type_natuur_ambitie ADD CONSTRAINT un_code_beheer_type_natuur_ambitie UNIQUE (code)
;

ALTER TABLE masterdata.dmn_beheer_type_omtevormennatuur_ambitie ADD CONSTRAINT PK_dmn_beheer_type_omtevormennatuur_ambitie
	PRIMARY KEY (id)
;

ALTER TABLE masterdata.dmn_beheer_type_omtevormennatuur_ambitie ADD CONSTRAINT un_code_beheer_type_omtevormennatuur_ambitie UNIQUE (code)
;

ALTER TABLE masterdata.dmn_beheer_type_water ADD CONSTRAINT PK_dmn_beheer_type_water
	PRIMARY KEY (id)
;

ALTER TABLE masterdata.dmn_beheer_type_water ADD CONSTRAINT un_code_beheer_type_water UNIQUE (code)
;

ALTER TABLE masterdata.dmn_beheergebied_type ADD CONSTRAINT PK_dmn_gebiedgebied_type
	PRIMARY KEY (id)
;

ALTER TABLE masterdata.dmn_beheergebied_type ADD CONSTRAINT un_code_beheergebied_type UNIQUE (code)
;

ALTER TABLE masterdata.dmn_bijzonder_gebied_code ADD CONSTRAINT PK_dmn_bijzonder_gebied_code
	PRIMARY KEY (id)
;

ALTER TABLE masterdata.dmn_bijzonder_gebied_code ADD CONSTRAINT un_code_bijzonder_gebied_code UNIQUE (code)
;

ALTER TABLE masterdata.dmn_natuur_type ADD CONSTRAINT PK_dmn_natuur_type_water
	PRIMARY KEY (id)
;

ALTER TABLE masterdata.dmn_natuur_type ADD CONSTRAINT un_code_natuur_type_water UNIQUE (code)
;

ALTER TABLE masterdata.dmn_natuur_type_agrarisch ADD CONSTRAINT PK_dmn_natuur_type_agrarisch
	PRIMARY KEY (id)
;

ALTER TABLE masterdata.dmn_natuur_type_agrarisch ADD CONSTRAINT un_code_natuur_type_agrarisch UNIQUE (code)
;

ALTER TABLE masterdata.dmn_natuur_type_water ADD CONSTRAINT PK_dmn_gebied_type
	PRIMARY KEY (id)
;

ALTER TABLE masterdata.dmn_natuur_type_water ADD CONSTRAINT un_code_gebied_type UNIQUE (code)
;

ALTER TABLE masterdata.dmn_openstellings_bijdrage_type ADD CONSTRAINT PK_dmn_openstellings_bijdrage_type
	PRIMARY KEY (id)
;

ALTER TABLE masterdata.dmn_openstellings_bijdrage_type ADD CONSTRAINT un_code_openstellings_bijdrage_type UNIQUE (code)
;

ALTER TABLE masterdata.dmn_provincie_code ADD CONSTRAINT PK_dmn_provincie_code
	PRIMARY KEY (id)
;

ALTER TABLE masterdata.dmn_provincie_code ADD CONSTRAINT un_code_provincie_code UNIQUE (code)
;

ALTER TABLE masterdata.dmn_status_ehs ADD CONSTRAINT PK_dmn_status_ehs
	PRIMARY KEY (id)
;

ALTER TABLE masterdata.dmn_status_ehs ADD CONSTRAINT un_code_status_ehs UNIQUE (code)
;

ALTER TABLE masterdata.dmn_status_plan ADD CONSTRAINT PK_dmn_status_plan
	PRIMARY KEY (id)
;

ALTER TABLE masterdata.dmn_status_plan ADD CONSTRAINT un_code_status_plan UNIQUE (code)
;

ALTER TABLE masterdata.feature_layer ADD CONSTRAINT PK_feature_layer
	PRIMARY KEY (feature,layer)
;

ALTER TABLE masterdata.lnk_table_ambitiegebied_type ADD CONSTRAINT PK_lnk_table_ambitiegebied_type
	PRIMARY KEY (ambitiegebied_type_id,beheer_type_id)
;

CREATE INDEX IXFK_dmn_ambitiegebied_type_01 ON masterdata.lnk_table_ambitiegebied_type (ambitiegebied_type_id ASC)
;

CREATE INDEX IXFK_dmn_beheer_type_04 ON masterdata.lnk_table_ambitiegebied_type (beheer_type_id ASC)
;

ALTER TABLE masterdata.lnk_table_beheer_functies ADD CONSTRAINT PK_lnk_table_beheer_functies
	PRIMARY KEY (natuur_type_id,beheer_functie_id)
;

CREATE INDEX IXFK_dmn_natuur_type ON masterdata.lnk_table_beheer_functies (natuur_type_id ASC)
;

ALTER TABLE masterdata.lnk_table_beheer_typen ADD CONSTRAINT PK_lnk_table_beheer_typen
	PRIMARY KEY (natuur_type_id,beheer_type_id)
;

CREATE INDEX IXFK_dmn_beheer_type_02 ON masterdata.lnk_table_beheer_typen (beheer_type_id ASC)
;

CREATE INDEX IXFK_dmn_natuur_type_01 ON masterdata.lnk_table_beheer_typen (natuur_type_id ASC)
;

ALTER TABLE masterdata.lnk_table_beheergebied_type ADD CONSTRAINT PK_lnk_table_beheergebied_type
	PRIMARY KEY (beheergebied_type_id,beheer_type_id)
;

CREATE INDEX IXFK_dmn_beheer_type_03 ON masterdata.lnk_table_beheergebied_type (beheer_type_id ASC)
;

CREATE INDEX IXFK_dmn_beheergebied_type_01 ON masterdata.lnk_table_beheergebied_type (beheergebied_type_id ASC)
;

ALTER TABLE masterdata.lnk_table_beheerpakket ADD CONSTRAINT PK_lnk_table_beheerpakket
	PRIMARY KEY (beheer_type_id,beheer_pakket_id)
;

CREATE INDEX IXFK_dmn_beheer_pakket ON masterdata.lnk_table_beheerpakket (beheer_pakket_id ASC)
;

CREATE INDEX IXFK_dmn_beheer_type_01 ON masterdata.lnk_table_beheerpakket (beheer_type_id ASC)
;

ALTER TABLE masterdata.mandatory_attributes ADD CONSTRAINT PK_mandatory_attributes
	PRIMARY KEY (feature,attribute)
;

ALTER TABLE masterdata.parameters ADD CONSTRAINT PK_parameters
	PRIMARY KEY (name)
;

ALTER TABLE masterdata.provinces ADD CONSTRAINT PK_provinces
	PRIMARY KEY (code)
;

ALTER TABLE masterdata.specific_attribute_types ADD CONSTRAINT PK_specific_attribute_types
	PRIMARY KEY (feature,attribute)
;

ALTER TABLE masterdata.translations ADD CONSTRAINT PK_translations
	PRIMARY KEY (nl)
;

/* Create Foreign Key Constraints */

ALTER TABLE masterdata.lnk_table_ambitiegebied_type ADD CONSTRAINT FK_dmn_ambitiegebied_type_01
	FOREIGN KEY (ambitiegebied_type_id) REFERENCES masterdata.dmn_ambitiegebied_type (id) ON DELETE No Action ON UPDATE No Action
;

ALTER TABLE masterdata.lnk_table_ambitiegebied_type ADD CONSTRAINT FK_dmn_beheer_type_04
	FOREIGN KEY (beheer_type_id) REFERENCES masterdata.dmn_beheer_type (id) ON DELETE No Action ON UPDATE No Action
;

ALTER TABLE masterdata.lnk_table_beheer_functies ADD CONSTRAINT FK_dmn_beheer_functie
	FOREIGN KEY (beheer_functie_id) REFERENCES masterdata.dmn_beheer_functie (id) ON DELETE No Action ON UPDATE No Action
;

ALTER TABLE masterdata.lnk_table_beheer_functies ADD CONSTRAINT FK_dmn_natuur_type_02
	FOREIGN KEY (natuur_type_id) REFERENCES masterdata.dmn_natuur_type (id) ON DELETE No Action ON UPDATE No Action
;

ALTER TABLE masterdata.lnk_table_beheer_typen ADD CONSTRAINT FK_dmn_beheer_type_02
	FOREIGN KEY (beheer_type_id) REFERENCES masterdata.dmn_beheer_type (id) ON DELETE No Action ON UPDATE No Action
;

ALTER TABLE masterdata.lnk_table_beheer_typen ADD CONSTRAINT FK_dmn_natuur_type_01
	FOREIGN KEY (natuur_type_id) REFERENCES masterdata.dmn_natuur_type (id) ON DELETE No Action ON UPDATE No Action
;

ALTER TABLE masterdata.lnk_table_beheergebied_type ADD CONSTRAINT FK_dmn_beheer_type_03
	FOREIGN KEY (beheer_type_id) REFERENCES masterdata.dmn_beheer_type (id) ON DELETE No Action ON UPDATE No Action
;

ALTER TABLE masterdata.lnk_table_beheergebied_type ADD CONSTRAINT FK_dmn_beheergebied_type_01
	FOREIGN KEY (beheergebied_type_id) REFERENCES masterdata.dmn_beheergebied_type (id) ON DELETE No Action ON UPDATE No Action
;

ALTER TABLE masterdata.lnk_table_beheerpakket ADD CONSTRAINT FK_dmn_beheer_pakket
	FOREIGN KEY (beheer_pakket_id) REFERENCES masterdata.dmn_beheer_pakket (id) ON DELETE No Action ON UPDATE No Action
;

ALTER TABLE masterdata.lnk_table_beheerpakket ADD CONSTRAINT FK_dmn_beheer_type_01
	FOREIGN KEY (beheer_type_id) REFERENCES masterdata.dmn_beheer_type (id) ON DELETE No Action ON UPDATE No Action
;

/* Create Views */

-- View: masterdata.all_domains

-- DROP VIEW masterdata.all_domains;

CREATE OR REPLACE VIEW masterdata.all_domains AS 
        (        (        (        (        (        (        (        (        (        (        (        (        (        (        (        (        (        (        (         SELECT dmn_ambitiegebied_type.id, 
                                                                                                                                                                    dmn_ambitiegebied_type.code, 
                                                                                                                                                                    dmn_ambitiegebied_type.description, 
                                                                                                                                                                    dmn_ambitiegebied_type.active, 
                                                                                                                                                                    'dmn_ambitiegebied_type'::text AS dmn
                                                                                                                                                                   FROM masterdata.dmn_ambitiegebied_type
                                                                                                                                                        UNION 
                                                                                                                                                                 SELECT dmn_beheer_pakket_landschap.id, 
                                                                                                                                                                    dmn_beheer_pakket_landschap.code, 
                                                                                                                                                                    dmn_beheer_pakket_landschap.description, 
                                                                                                                                                                    dmn_beheer_pakket_landschap.active, 
                                                                                                                                                                    'dmn_beheer_pakket_landschap'::text AS dmn
                                                                                                                                                                   FROM masterdata.dmn_beheer_pakket_landschap)
                                                                                                                                                UNION 
                                                                                                                                                         SELECT dmn_beheer_type_agrarisch.id, 
                                                                                                                                                            dmn_beheer_type_agrarisch.code, 
                                                                                                                                                            dmn_beheer_type_agrarisch.description, 
                                                                                                                                                            dmn_beheer_type_agrarisch.active, 
                                                                                                                                                            'dmn_beheer_type_agrarisch'::text AS dmn
                                                                                                                                                           FROM masterdata.dmn_beheer_type_agrarisch)
                                                                                                                                        UNION 
                                                                                                                                                 SELECT dmn_beheer_type_grootschaligenatuur.id, 
                                                                                                                                                    dmn_beheer_type_grootschaligenatuur.code, 
                                                                                                                                                    dmn_beheer_type_grootschaligenatuur.description, 
                                                                                                                                                    dmn_beheer_type_grootschaligenatuur.active, 
                                                                                                                                                    'dmn_beheer_type_grootschaligenatuur'::text AS dmn
                                                                                                                                                   FROM masterdata.dmn_beheer_type_grootschaligenatuur)
                                                                                                                                UNION 
                                                                                                                                         SELECT dmn_beheer_type_landschap.id, 
                                                                                                                                            dmn_beheer_type_landschap.code, 
                                                                                                                                            dmn_beheer_type_landschap.description, 
                                                                                                                                            dmn_beheer_type_landschap.active, 
                                                                                                                                            'dmn_beheer_type_landschap'::text AS dmn
                                                                                                                                           FROM masterdata.dmn_beheer_type_landschap)
                                                                                                                        UNION 
                                                                                                                                 SELECT dmn_beheer_type_natuur.id, 
                                                                                                                                    dmn_beheer_type_natuur.code, 
                                                                                                                                    dmn_beheer_type_natuur.description, 
                                                                                                                                    dmn_beheer_type_natuur.active, 
                                                                                                                                    'dmn_beheer_type_natuur'::text AS dmn
                                                                                                                                   FROM masterdata.dmn_beheer_type_natuur)
                                                                                                                UNION 
                                                                                                                         SELECT dmn_beheer_type_natuur_ambitie.id, 
                                                                                                                            dmn_beheer_type_natuur_ambitie.code, 
                                                                                                                            dmn_beheer_type_natuur_ambitie.description, 
                                                                                                                            dmn_beheer_type_natuur_ambitie.active, 
                                                                                                                            'dmn_beheer_type_natuur_ambitie'::text AS dmn
                                                                                                                           FROM masterdata.dmn_beheer_type_natuur_ambitie)
                                                                                                        UNION 
                                                                                                                 SELECT dmn_beheer_type_omtevormennatuur_ambitie.id, 
                                                                                                                    dmn_beheer_type_omtevormennatuur_ambitie.code, 
                                                                                                                    dmn_beheer_type_omtevormennatuur_ambitie.description, 
                                                                                                                    dmn_beheer_type_omtevormennatuur_ambitie.active, 
                                                                                                                    'dmn_beheer_type_omtevormennatuur_ambitie'::text AS dmn
                                                                                                                   FROM masterdata.dmn_beheer_type_omtevormennatuur_ambitie)
                                                                                                UNION 
                                                                                                         SELECT dmn_beheer_type_water.id, 
                                                                                                            dmn_beheer_type_water.code, 
                                                                                                            dmn_beheer_type_water.description, 
                                                                                                            dmn_beheer_type_water.active, 
                                                                                                            'dmn_beheer_type_water'::text AS dmn
                                                                                                           FROM masterdata.dmn_beheer_type_water)
                                                                                        UNION 
                                                                                                 SELECT dmn_beheergebied_type.id, 
                                                                                                    dmn_beheergebied_type.code, 
                                                                                                    dmn_beheergebied_type.description, 
                                                                                                    dmn_beheergebied_type.active, 
                                                                                                    'dmn_beheergebied_type'::text AS dmn
                                                                                                   FROM masterdata.dmn_beheergebied_type)
                                                                                UNION 
                                                                                         SELECT dmn_bijzonder_gebied_code.id, 
                                                                                            dmn_bijzonder_gebied_code.code, 
                                                                                            dmn_bijzonder_gebied_code.description, 
                                                                                            dmn_bijzonder_gebied_code.active, 
                                                                                            'dmn_bijzonder_gebied_code'::text AS dmn
                                                                                           FROM masterdata.dmn_bijzonder_gebied_code)
                                                                        UNION 
                                                                                 SELECT dmn_natuur_type_agrarisch.id, 
                                                                                    dmn_natuur_type_agrarisch.code, 
                                                                                    dmn_natuur_type_agrarisch.description, 
                                                                                    dmn_natuur_type_agrarisch.active, 
                                                                                    'dmn_natuur_type_agrarisch'::text AS dmn
                                                                                   FROM masterdata.dmn_natuur_type_agrarisch)
                                                                UNION 
                                                                         SELECT dmn_natuur_type_water.id, 
                                                                            dmn_natuur_type_water.code, 
                                                                            dmn_natuur_type_water.description, 
                                                                            dmn_natuur_type_water.active, 
                                                                            'dmn_natuur_type_water'::text AS dmn
                                                                           FROM masterdata.dmn_natuur_type_water)
                                                        UNION 
                                                                 SELECT dmn_openstellings_bijdrage_type.id, 
                                                                    dmn_openstellings_bijdrage_type.code, 
                                                                    dmn_openstellings_bijdrage_type.description, 
                                                                    dmn_openstellings_bijdrage_type.active, 
                                                                    'dmn_openstellings_bijdrage_type'::text AS dmn
                                                                   FROM masterdata.dmn_openstellings_bijdrage_type)
                                                UNION 
                                                         SELECT dmn_provincie_code.id, 
                                                            dmn_provincie_code.code, 
                                                            dmn_provincie_code.description, 
                                                            dmn_provincie_code.active, 
                                                            'dmn_provincie_code'::text AS dmn
                                                           FROM masterdata.dmn_provincie_code)
                                        UNION 
                                                 SELECT dmn_status_ehs.id, 
                                                    dmn_status_ehs.code, 
                                                    dmn_status_ehs.description, 
                                                    dmn_status_ehs.active, 
                                                    'dmn_status_ehs'::text AS dmn
                                                   FROM masterdata.dmn_status_ehs)
                                UNION 
                                         SELECT dmn_status_plan.id, 
                                            dmn_status_plan.code, 
                                            dmn_status_plan.description, 
                                            dmn_status_plan.active, 
                                            'dmn_status_plan'::text AS dmn
                                           FROM masterdata.dmn_status_plan)
                        UNION 
                                 SELECT dmn_beheer_functie.id, 
                                    dmn_beheer_functie.code, 
                                    dmn_beheer_functie.description, 
                                    dmn_beheer_functie.active, 
                                    'dmn_beheer_functie'::text AS dmn
                                   FROM masterdata.dmn_beheer_functie)
                UNION 
                         SELECT dmn_natuur_type.id, dmn_natuur_type.code, 
                            dmn_natuur_type.description, dmn_natuur_type.active, 
                            'dmn_natuur_type'::text AS dmn
                           FROM masterdata.dmn_natuur_type)
        UNION 
                 SELECT dmn_beheer_pakket.id, dmn_beheer_pakket.code, 
                    dmn_beheer_pakket.description, dmn_beheer_pakket.active, 
                    'dmn_beheer_pakket'::text AS dmn
                   FROM masterdata.dmn_beheer_pakket)
UNION 
         SELECT dmn_beheer_type.id, dmn_beheer_type.code, 
            dmn_beheer_type.description, dmn_beheer_type.active, 
            'dmn_beheer_type'::text AS dmn
           FROM masterdata.dmn_beheer_type;

ALTER TABLE masterdata.all_domains
  OWNER TO anlb;


-- View: masterdata.all_domain_features

-- DROP VIEW masterdata.all_domain_features;

CREATE OR REPLACE VIEW masterdata.all_domain_features AS 
 SELECT all_domains.id, all_domains.code, all_domains.description, 
    all_domains.active, all_domains.dmn, domain_feature.domain, 
    domain_feature.feature, domain_feature.attribute
   FROM masterdata.all_domains
   JOIN masterdata.domain_feature ON all_domains.dmn = domain_feature.domain::text
  WHERE all_domains.active = true;

ALTER TABLE masterdata.all_domain_features
  OWNER TO anlb;


GRANT SELECT ON ALL TABLES IN SCHEMA masterdata TO anlb_sqlpad;