/* ---------------------------------------------------- */
/*  Generated by Enterprise Architect Version 12.1 		*/
/*  Created On : 28-Jan-2022 10:03:49 				*/
/*  DBMS       : PostgreSQL 						*/
/* ---------------------------------------------------- */

/* Create Tables */

CREATE TABLE masterdata.dmn_deelgebied
(
	id bigint NOT NULL   DEFAULT NEXTVAL(('masterdata.masterdata_seq'::text)::regclass),
	code char(20) NOT NULL,
	description char(100) NULL,
	valid_from timestamp NOT NULL,
	valid_to timestamp NULL
)
;

CREATE TABLE masterdata.dmn_natuur_type_klimaat
(
	id bigint NOT NULL   DEFAULT NEXTVAL(('masterdata.masterdata_seq'::text)::regclass),
	code char(20) NOT NULL,
	description char(100) NULL,
	valid_from timestamp NOT NULL,
	valid_to timestamp NULL
)
;

CREATE TABLE masterdata.dmn_status_zoek_gebied_klimaat
(
	id bigint NOT NULL   DEFAULT NEXTVAL(('masterdata.masterdata_seq'::text)::regclass),
	code char(20) NOT NULL,
	description char(100) NULL,
	valid_from timestamp NOT NULL,
	valid_to timestamp NULL
)
;

CREATE TABLE masterdata.lnk_table_provincie_deelgebied
(
	provincie_id bigint NOT NULL,
	deelgebied_id bigint NOT NULL,
	valid_from timestamp NOT NULL,
	valid_to timestamp NULL
)
;

/* Create Primary Keys, Indexes, Uniques, Checks */

ALTER TABLE masterdata.dmn_deelgebied ADD CONSTRAINT PK_dmn_deelgebied
	PRIMARY KEY (id)
;

ALTER TABLE masterdata.dmn_deelgebied ADD CONSTRAINT un_code_deelgebied UNIQUE (code)
;

ALTER TABLE masterdata.dmn_natuur_type_klimaat ADD CONSTRAINT PK_dmn_natuur_type_klimaat
	PRIMARY KEY (id)
;

ALTER TABLE masterdata.dmn_natuur_type_klimaat ADD CONSTRAINT un_code_natuur_type_klimaat UNIQUE (code)
;

ALTER TABLE masterdata.dmn_status_zoek_gebied_klimaat ADD CONSTRAINT PK_dmn_status_zoek_gebied_klimaat
	PRIMARY KEY (id)
;

ALTER TABLE masterdata.dmn_status_zoek_gebied_klimaat ADD CONSTRAINT un_code_status_zoek_gebied_klimaat UNIQUE (code)
;

ALTER TABLE masterdata.lnk_table_provincie_deelgebied ADD CONSTRAINT PK_lnk_table_provincie_deelgebied
	PRIMARY KEY (provincie_id,deelgebied_id)
;

CREATE INDEX IXFK_lnk_table_provincie_deelgebied_dmn_deelgebied ON masterdata.lnk_table_provincie_deelgebied (deelgebied_id ASC)
;

CREATE INDEX IXFK_lnk_table_provincie_deelgebied_dmn_provincie_code ON masterdata.lnk_table_provincie_deelgebied (provincie_id ASC)
;

/* Create Foreign Key Constraints */

ALTER TABLE masterdata.lnk_table_provincie_deelgebied ADD CONSTRAINT FK_lnk_table_provincie_deelgebied_dmn_deelgebied
	FOREIGN KEY (deelgebied_id) REFERENCES masterdata.dmn_deelgebied (id) ON DELETE No Action ON UPDATE No Action
;

ALTER TABLE masterdata.lnk_table_provincie_deelgebied ADD CONSTRAINT FK_lnk_table_provincie_deelgebied_dmn_provincie_code
	FOREIGN KEY (provincie_id) REFERENCES masterdata.dmn_provincie_code (id) ON DELETE No Action ON UPDATE No Action
;

GRANT SELECT ON ALL TABLES IN SCHEMA masterdata TO anlb_sqlpad;

GRANT SELECT ON ALL TABLES IN SCHEMA masterdata TO snl_readonly;
