/* ---------------------------------------------------- */
/*  Generated by Enterprise Architect Version 12.1 		*/
/*  Created On : 07-Feb-2022 14:47:10 				*/
/*  DBMS       : PostgreSQL 						*/
/* ---------------------------------------------------- */

/* Create Tables */

CREATE TABLE masterdata.lnk_table_provincie_type_regeling
(
	provincie_id bigint NOT NULL,
	type_regeling_id bigint NOT NULL,
	valid_from timestamp NOT NULL,
	valid_to timestamp NULL
)
;

/* Create Primary Keys, Indexes, Uniques, Checks */

ALTER TABLE masterdata.lnk_table_provincie_type_regeling ADD CONSTRAINT PK_lnk_table_provincie_type_regeling
	PRIMARY KEY (provincie_id,type_regeling_id)
;

CREATE INDEX IXFK_lnk_table_provincie_type_regeling_dmn_provincie_code ON masterdata.lnk_table_provincie_type_regeling (provincie_id ASC)
;

CREATE INDEX IXFK_lnk_table_provincie_type_regeling_dmn_type_regeling ON masterdata.lnk_table_provincie_type_regeling (type_regeling_id ASC)
;

/* Create Foreign Key Constraints */

ALTER TABLE masterdata.lnk_table_provincie_type_regeling ADD CONSTRAINT FK_lnk_table_provincie_type_regeling_dmn_provincie_code
	FOREIGN KEY (provincie_id) REFERENCES masterdata.dmn_provincie_code (id) ON DELETE No Action ON UPDATE No Action
;

ALTER TABLE masterdata.lnk_table_provincie_type_regeling ADD CONSTRAINT FK_lnk_table_provincie_type_regeling_dmn_type_regeling
	FOREIGN KEY (type_regeling_id) REFERENCES masterdata.dmn_type_regeling (id) ON DELETE No Action ON UPDATE No Action
;

GRANT SELECT ON ALL TABLES IN SCHEMA masterdata TO anlb_sqlpad;

GRANT SELECT ON ALL TABLES IN SCHEMA masterdata TO snl_readonly;