/* ---------------------------------------------------- */
/*  Generated by Enterprise Architect Version 12.1 		*/
/*  Created On : 26-Oct-2021 12:28:02 				*/
/*  DBMS       : PostgreSQL 						*/
/* ---------------------------------------------------- */

/* Drop Tables */

DROP TABLE IF EXISTS masterdata.dmn_bronhouder CASCADE
;

DROP TABLE IF EXISTS masterdata.dmn_habitat_kwaliteit CASCADE
;

DROP TABLE IF EXISTS masterdata.dmn_habitat_kwaliteit_t0 CASCADE
;

DROP TABLE IF EXISTS masterdata.dmn_habitat_kwaliteit_tx CASCADE
;

DROP TABLE IF EXISTS masterdata.dmn_habitat_package_type CASCADE
;

DROP TABLE IF EXISTS masterdata.dmn_habitat_package_versie CASCADE
;

DROP TABLE IF EXISTS masterdata.dmn_habitat_type CASCADE
;

DROP TABLE IF EXISTS masterdata.dmn_habitat_type_t0 CASCADE
;

DROP TABLE IF EXISTS masterdata.dmn_habitat_type_tx CASCADE
;

DROP TABLE IF EXISTS masterdata.dmn_methodiek_document_versie CASCADE
;

DROP TABLE IF EXISTS masterdata.dmn_natura_2000_bijdrage CASCADE
;

DROP TABLE IF EXISTS masterdata.dmn_natura_2000_karterings_type CASCADE
;

DROP TABLE IF EXISTS masterdata.dmn_natura_2000_type CASCADE
;

DROP TABLE IF EXISTS masterdata.dmn_package_kwaliteit CASCADE
;

/* Create Tables */

CREATE TABLE masterdata.dmn_bronhouder
(
	id bigint NOT NULL   DEFAULT NEXTVAL(('masterdata.masterdata_seq'::text)::regclass),
	code char(20) NOT NULL,
	description char(100) NULL,
	valid_from timestamp NOT NULL,
	valid_to timestamp NULL
)
;

CREATE TABLE masterdata.dmn_habitat_kwaliteit
(
	id bigint NOT NULL   DEFAULT NEXTVAL(('masterdata.masterdata_seq'::text)::regclass),
	code char(20) NOT NULL,
	description char(100) NULL,
	valid_from timestamp NOT NULL,
	valid_to timestamp NULL
)
;

CREATE TABLE masterdata.dmn_habitat_kwaliteit_t0
(
	id bigint NOT NULL   DEFAULT NEXTVAL(('masterdata.masterdata_seq'::text)::regclass),
	code char(20) NOT NULL,
	description char(100) NULL,
	valid_from timestamp NOT NULL,
	valid_to timestamp NULL
)
;

CREATE TABLE masterdata.dmn_habitat_kwaliteit_tx
(
	id bigint NOT NULL   DEFAULT NEXTVAL(('masterdata.masterdata_seq'::text)::regclass),
	code char(20) NOT NULL,
	description char(100) NULL,
	valid_from timestamp NOT NULL,
	valid_to timestamp NULL
)
;

CREATE TABLE masterdata.dmn_habitat_package_type
(
	id bigint NOT NULL   DEFAULT NEXTVAL(('masterdata.masterdata_seq'::text)::regclass),
	code char(20) NOT NULL,
	description char(100) NULL,
	valid_from timestamp NOT NULL,
	valid_to timestamp NULL
)
;

CREATE TABLE masterdata.dmn_habitat_package_versie
(
	id bigint NOT NULL   DEFAULT NEXTVAL(('masterdata.masterdata_seq'::text)::regclass),
	code char(20) NOT NULL,
	description char(100) NULL,
	valid_from timestamp NOT NULL,
	valid_to timestamp NULL
)
;

CREATE TABLE masterdata.dmn_habitat_type
(
	id bigint NOT NULL   DEFAULT NEXTVAL(('masterdata.masterdata_seq'::text)::regclass),
	code char(20) NOT NULL,
	description char(100) NULL,
	valid_from timestamp NOT NULL,
	valid_to timestamp NULL
)
;

CREATE TABLE masterdata.dmn_habitat_type_t0
(
	id bigint NOT NULL   DEFAULT NEXTVAL(('masterdata.masterdata_seq'::text)::regclass),
	code char(20) NOT NULL,
	description char(100) NULL,
	valid_from timestamp NOT NULL,
	valid_to timestamp NULL
)
;

CREATE TABLE masterdata.dmn_habitat_type_tx
(
	id bigint NOT NULL   DEFAULT NEXTVAL(('masterdata.masterdata_seq'::text)::regclass),
	code char(20) NOT NULL,
	description char(100) NULL,
	valid_from timestamp NOT NULL,
	valid_to timestamp NULL
)
;

CREATE TABLE masterdata.dmn_methodiek_document_versie
(
	id bigint NOT NULL   DEFAULT NEXTVAL(('masterdata.masterdata_seq'::text)::regclass),
	code char(20) NOT NULL,
	description char(100) NULL,
	valid_from timestamp NOT NULL,
	valid_to timestamp NULL
)
;

CREATE TABLE masterdata.dmn_natura_2000_bijdrage
(
	id bigint NOT NULL   DEFAULT NEXTVAL(('masterdata.masterdata_seq'::text)::regclass),
	code char(20) NOT NULL,
	description char(100) NULL,
	valid_from timestamp NOT NULL,
	valid_to timestamp NULL
)
;

CREATE TABLE masterdata.dmn_natura_2000_karterings_type
(
	id bigint NOT NULL   DEFAULT NEXTVAL(('masterdata.masterdata_seq'::text)::regclass),
	code char(20) NOT NULL,
	description char(100) NULL,
	valid_from timestamp NOT NULL,
	valid_to timestamp NULL
)
;

CREATE TABLE masterdata.dmn_natura_2000_type
(
	id bigint NOT NULL   DEFAULT NEXTVAL(('masterdata.masterdata_seq'::text)::regclass),
	code char(20) NOT NULL,
	description char(100) NULL,
	valid_from timestamp NOT NULL,
	valid_to timestamp NULL
)
;

CREATE TABLE masterdata.dmn_package_kwaliteit
(
	id bigint NOT NULL   DEFAULT NEXTVAL(('masterdata.masterdata_seq'::text)::regclass),
	code char(20) NOT NULL,
	description char(100) NULL,
	valid_from timestamp NOT NULL,
	valid_to timestamp NULL
)
;

/* Create Primary Keys, Indexes, Uniques, Checks */

ALTER TABLE masterdata.dmn_bronhouder ADD CONSTRAINT PK_dmn_bronhouder
	PRIMARY KEY (id)
;

ALTER TABLE masterdata.dmn_bronhouder ADD CONSTRAINT UN_code_bronhouder UNIQUE (code)
;

ALTER TABLE masterdata.dmn_habitat_kwaliteit ADD CONSTRAINT PK_dmn_habitat_kwaliteit
	PRIMARY KEY (id)
;

ALTER TABLE masterdata.dmn_habitat_kwaliteit ADD CONSTRAINT UN_code_habitat_kwaliteit UNIQUE (code)
;

ALTER TABLE masterdata.dmn_habitat_kwaliteit_t0 ADD CONSTRAINT PK_dmn_habitat_kwaliteit_to
	PRIMARY KEY (id)
;

ALTER TABLE masterdata.dmn_habitat_kwaliteit_t0 ADD CONSTRAINT UN_code_habitat_kwaliteit_to UNIQUE (code)
;

ALTER TABLE masterdata.dmn_habitat_kwaliteit_tx ADD CONSTRAINT PK_dmn_habitat_kwaliteit_tx
	PRIMARY KEY (id)
;

ALTER TABLE masterdata.dmn_habitat_kwaliteit_tx ADD CONSTRAINT UN_code_habitat_kwaliteit_tx UNIQUE (code)
;

ALTER TABLE masterdata.dmn_habitat_package_type ADD CONSTRAINT PK_dmn_habitat_package_type
	PRIMARY KEY (id)
;

ALTER TABLE masterdata.dmn_habitat_package_type ADD CONSTRAINT UN_code_habitat_package_type UNIQUE (code)
;

ALTER TABLE masterdata.dmn_habitat_package_versie ADD CONSTRAINT PK_dmn_habitat_package_versie
	PRIMARY KEY (id)
;

ALTER TABLE masterdata.dmn_habitat_package_versie ADD CONSTRAINT UN_code_habitat_package_versie UNIQUE (code)
;

ALTER TABLE masterdata.dmn_habitat_type ADD CONSTRAINT PK_dmn_habitat_type
	PRIMARY KEY (id)
;

ALTER TABLE masterdata.dmn_habitat_type ADD CONSTRAINT UN_code_habitat_type UNIQUE (code)
;

ALTER TABLE masterdata.dmn_habitat_type_t0 ADD CONSTRAINT PK_dmn_habitat_type_to
	PRIMARY KEY (id)
;

ALTER TABLE masterdata.dmn_habitat_type_t0 ADD CONSTRAINT UN_code_habitat_type_to UNIQUE (code)
;

ALTER TABLE masterdata.dmn_habitat_type_tx ADD CONSTRAINT PK_dmn_habitat_type_tx
	PRIMARY KEY (id)
;

ALTER TABLE masterdata.dmn_habitat_type_tx ADD CONSTRAINT UN_code_habitat_type_tx UNIQUE (code)
;

ALTER TABLE masterdata.dmn_methodiek_document_versie ADD CONSTRAINT PK_dmn_methodiek_document_versie
	PRIMARY KEY (id)
;

ALTER TABLE masterdata.dmn_methodiek_document_versie ADD CONSTRAINT UN_code_methodiek_docuement_versie UNIQUE (code)
;

ALTER TABLE masterdata.dmn_natura_2000_bijdrage ADD CONSTRAINT PK_dmn_natura_2000_bijdrage
	PRIMARY KEY (id)
;

ALTER TABLE masterdata.dmn_natura_2000_bijdrage ADD CONSTRAINT UN_code_natura_2000_bijdrage UNIQUE (code)
;

ALTER TABLE masterdata.dmn_natura_2000_karterings_type ADD CONSTRAINT PK_dmn_natura_2000_karterings_type
	PRIMARY KEY (id)
;

ALTER TABLE masterdata.dmn_natura_2000_karterings_type ADD CONSTRAINT UN_code_natura_2000_katerings_type UNIQUE (code)
;

ALTER TABLE masterdata.dmn_natura_2000_type ADD CONSTRAINT PK_dmn_natura_2000_type
	PRIMARY KEY (id)
;

ALTER TABLE masterdata.dmn_natura_2000_type ADD CONSTRAINT UN_code_natura_2000_type UNIQUE (code)
;

ALTER TABLE masterdata.dmn_package_kwaliteit ADD CONSTRAINT PK_dmn_package_kwaliteit
	PRIMARY KEY (id)
;

ALTER TABLE masterdata.dmn_package_kwaliteit ADD CONSTRAINT UN_code_package_kwaliteit UNIQUE (code)
;

/* Create Table Comments, Sequences for Autonumber Columns */

COMMENT ON TABLE masterdata.dmn_bronhouder
	IS 'List of Organizations that claim responsibility for a set of Natura 2000 Areas.  Code should equal the name of the role in LDAP. Roles can be found in ou=groups,dc=cvd,dc=gboApps,dc=gbo,dc=nl'
;

COMMENT ON TABLE masterdata.dmn_habitat_kwaliteit
	IS 'G = Goed M = Matig NB = Onbekend'
;

COMMENT ON TABLE masterdata.dmn_habitat_kwaliteit_t0
	IS 'G = Goed M = Matig NB = Onbekend'
;

COMMENT ON TABLE masterdata.dmn_habitat_kwaliteit_tx
	IS 'G = Goed M = Matig'
;

COMMENT ON TABLE masterdata.dmn_habitat_package_type
	IS 'H = Habitat L = Leefgebied'
;

COMMENT ON TABLE masterdata.dmn_habitat_package_versie
	IS 'Waardes  T0	Situatie rond aanwijzings besluit T1	12 jaar na aanwijzing T2	24 jaar na aanwijzing'
;

COMMENT ON TABLE masterdata.dmn_natura_2000_bijdrage
	IS 'Betekenis van het gebied, naar oppervlakte van het habitattype: oppervlakte in het onderhavige gebied uitgedrukt als percentage van de landelijke oppervlakte:   	-     A4: >75%; 	-     A3: 50-75%; 	-     A2: 30-50%; 	-     A1: 15-30%; 	-     B2: 6-15%; 	-     B1: 2-6%; 	-     C: <2%'
;

COMMENT ON TABLE masterdata.dmn_natura_2000_karterings_type
	IS 'L =  Leefgebiedtype, vegetatietypen gedeeltelijk kwalificerend H = Habitattype conform habitatrichtlijn ZGH = Zoekgebied voor een habitattype conform habitatrichtlijn ZGL =  Zoekgebied voor leefgebiedtype, vegetatietypen gedeeltelijk kwalificerend Lg = Leefgebied voor soorten ZGLg = Zoekgebied voor een leefgebied voor soorten'
;

COMMENT ON TABLE masterdata.dmn_natura_2000_type
	IS 'HR = Habitat Richtlijn VR = Vogel Richtlijn VR+HR = Vogel en Habitat Richtlijn HR Groeve = Habitat Groeve'
;

COMMENT ON TABLE masterdata.dmn_package_kwaliteit
	IS 'G = Goed,  N = Niet beoordeeld  O = Onvoldoende'
;


-- View: masterdata.all_domains

--DROP VIEW masterdata.all_domains;

CREATE OR REPLACE VIEW masterdata.all_domains AS
    SELECT
        id,
        code,
        description,
		valid_from,
		valid_to,
        'dmn_ambitiegebied_type' AS dmn
    FROM
        masterdata.dmn_ambitiegebied_type
    UNION
    SELECT
        id,
        code,
        description,
		valid_from,
		valid_to,
        'dmn_beheer_pakket_landschap' AS dmn
    FROM
        masterdata.dmn_beheer_pakket_landschap
    UNION
    SELECT
        id,
        code,
        description,
		valid_from,
		valid_to,
        'dmn_beheer_type_agrarisch' AS dmn
    FROM
        masterdata.dmn_beheer_type_agrarisch
    UNION
    SELECT
        id,
        code,
        description,
		valid_from,
		valid_to,
        'dmn_beheer_type_grootschaligenatuur' AS dmn
    FROM
        masterdata.dmn_beheer_type_grootschaligenatuur
    UNION
    SELECT
        id,
        code,
        description,
		valid_from,
		valid_to,
        'dmn_beheer_type_landschap' AS dmn
    FROM
        masterdata.dmn_beheer_type_landschap
    UNION
    SELECT
        id,
        code,
        description,
		valid_from,
		valid_to,
        'dmn_beheer_type_natuur' AS dmn
    FROM
        masterdata.dmn_beheer_type_natuur
    UNION
    SELECT
        id,
        code,
        description,
		valid_from,
		valid_to,
        'dmn_beheer_type_natuur_ambitie' AS dmn
    FROM
        masterdata.dmn_beheer_type_natuur_ambitie
    UNION
    SELECT
        id,
        code,
        description,
		valid_from,
		valid_to,
        'dmn_beheer_type_omtevormennatuur_ambitie' AS dmn
    FROM
        masterdata.dmn_beheer_type_omtevormennatuur_ambitie
    UNION
    SELECT
        id,
        code,
        description,
		valid_from,
		valid_to,
        'dmn_beheer_type_water' AS dmn
    FROM
        masterdata.dmn_beheer_type_water
    UNION
    SELECT
        id,
        code,
        description,
		valid_from,
		valid_to,
        'dmn_beheergebied_type' AS dmn
    FROM
        masterdata.dmn_beheergebied_type
    UNION
    SELECT
        id,
        code,
        description,
		valid_from,
		valid_to,
        'dmn_bijzonder_gebied_code' AS dmn
    FROM
        masterdata.dmn_bijzonder_gebied_code
    UNION
    SELECT
        id,
        code,
        description,
		valid_from,
		valid_to,
        'dmn_natuur_type_agrarisch' AS dmn
    FROM
        masterdata.dmn_natuur_type_agrarisch
    UNION
    SELECT
        id,
        code,
        description,
		valid_from,
		valid_to,
        'dmn_natuur_type_water' AS dmn
    FROM
        masterdata.dmn_natuur_type_water
    UNION
    SELECT
        id,
        code,
        description,
		valid_from,
		valid_to,
        'dmn_openstellings_bijdrage_type' AS dmn
    FROM
        masterdata.dmn_openstellings_bijdrage_type
    UNION
    SELECT
        id,
        code,
        description,
		valid_from,
		valid_to,
        'dmn_provincie_code' AS dmn
    FROM
        masterdata.dmn_provincie_code
    UNION
    SELECT
        id,
        code,
        description,
		valid_from,
		valid_to,
        'dmn_status_ehs' AS dmn
    FROM
        masterdata.dmn_status_ehs
    UNION
    SELECT
        id,
        code,
        description,
		valid_from,
		valid_to,
        'dmn_status_plan' AS dmn
    FROM
        masterdata.dmn_status_plan
	UNION
	SELECT
        id,
        code,
        description,
		valid_from,
		valid_to,
        'dmn_status_beheer_gebied' AS dmn
    FROM
        masterdata.dmn_status_beheer_gebied
	UNION
	SELECT
        id,
        code,
        description,
		valid_from,
		valid_to,
        'dmn_status_beheer_gebied_ambitie' AS dmn
    FROM
        masterdata.dmn_status_beheer_gebied_ambitie
	UNION
	SELECT
        id,
        code,
        description,
		valid_from,
		valid_to,
        'dmn_status_bijzonder_gebied' AS dmn
    FROM
        masterdata.dmn_status_bijzonder_gebied
	UNION
	SELECT
        id,
        code,
        description,
		valid_from,
		valid_to,
        'dmn_status_deel_gebied' AS dmn
    FROM
        masterdata.dmn_status_deel_gebied
	UNION
	SELECT
        id,
        code,
        description,
		valid_from,
		valid_to,
        'dmn_status_zoek_gebied_agrarisch' AS dmn
    FROM
        masterdata.dmn_status_zoek_gebied_agrarisch
	UNION
	SELECT
        id,
        code,
        description,
		valid_from,
		valid_to,
        'dmn_status_zoek_gebied_landschap' AS dmn
    FROM
        masterdata.dmn_status_zoek_gebied_landschap
	UNION
	SELECT
        id,
        code,
        description,
		valid_from,
		valid_to,
        'dmn_status_zoek_gebied_water' AS dmn
    FROM
        masterdata.dmn_status_zoek_gebied_water		
    UNION
    SELECT
        id,
        code,
        description,
		valid_from,
		valid_to,
        'dmn_beheer_functie' AS dmn
    FROM
        masterdata.dmn_beheer_functie
    UNION
    SELECT
        id,
        code,
        description,
		valid_from,
		valid_to,
        'dmn_natuur_type' AS dmn
    FROM
        masterdata.dmn_natuur_type
    UNION
    SELECT
        id,
        code,
        description,
		valid_from,
		valid_to,
        'dmn_beheer_pakket' AS dmn
    FROM
        masterdata.dmn_beheer_pakket
    UNION
    SELECT
        id,
        code,
        description,
		valid_from,
		valid_to,
        'dmn_beheer_type' AS dmn
    FROM
        masterdata.dmn_beheer_type
    UNION
    SELECT
        id,
        code,
        description,
		valid_from,
		valid_to,
        'dmn_status_natuur' AS dmn
    FROM
        masterdata.dmn_status_natuur
    UNION
    SELECT
        id,
        code,
        description,
		valid_from,
		valid_to,
        'dmn_type_beheerder_en_eigenaar' AS dmn
    FROM
        masterdata.dmn_type_beheerder_en_eigenaar
    UNION
    SELECT
        id,
        code,
        description,
		valid_from,
		valid_to,
        'dmn_status_aanvraag_subsidie' AS dmn
    FROM
        masterdata.dmn_status_aanvraag_subsidie
    UNION
    SELECT
        id,
        code,
        description,
		valid_from,
		valid_to,
        'dmn_type_regeling' AS dmn
    FROM
        masterdata.dmn_type_regeling
    UNION
    SELECT
        id,
        code,
        description,
		valid_from,
		valid_to,
        'dmn_type_regeling_snl' AS dmn
    FROM
        masterdata.dmn_type_regeling_snl
    UNION
    SELECT
        id,
        code,
        description,
		valid_from,
		valid_to,
        'dmn_type_regeling_niet_snl' AS dmn
    FROM
        masterdata.dmn_type_regeling_niet_snl
	UNION
    SELECT
        id,
        code,
        description,
		valid_from,
		valid_to,
        'dmn_beheer_type_beschikking_niet_snl' AS dmn
    FROM
        masterdata.dmn_beheer_type_beschikking_niet_snl
	UNION
    SELECT
        id,
        code,
        description,
		valid_from,
		valid_to,
        'dmn_bronhouder' AS dmn
    FROM
        masterdata.dmn_bronhouder
	UNION
    SELECT
        id,
        code,
        description,
		valid_from,
		valid_to,
        'dmn_natura_2000_karterings_type' AS dmn
    FROM
        masterdata.dmn_natura_2000_karterings_type
	UNION
    SELECT
        id,
        code,
        description,
		valid_from,
		valid_to,
        'dmn_habitat_kwaliteit' AS dmn
    FROM
        masterdata.dmn_habitat_kwaliteit
	UNION
    SELECT
        id,
        code,
        description,
		valid_from,
		valid_to,
        'dmn_habitat_kwaliteit_t0' AS dmn
    FROM
        masterdata.dmn_habitat_kwaliteit_t0
	UNION
    SELECT
        id,
        code,
        description,
		valid_from,
		valid_to,
        'dmn_habitat_package_type' AS dmn
    FROM
        masterdata.dmn_habitat_package_type
	UNION
    SELECT
        id,
        code,
        description,
		valid_from,
		valid_to,
        'dmn_habitat_package_versie' AS dmn
    FROM
        masterdata.dmn_habitat_package_versie
	UNION
    SELECT
        id,
        code,
        description,
		valid_from,
		valid_to,
        'dmn_habitat_type' AS dmn
    FROM
        masterdata.dmn_habitat_type
	UNION
    SELECT
        id,
        code,
        description,
		valid_from,
		valid_to,
        'dmn_habitat_type_t0' AS dmn
    FROM
        masterdata.dmn_habitat_type_t0
	UNION
    SELECT
        id,
        code,
        description,
		valid_from,
		valid_to,
        'dmn_methodiek_document_versie' AS dmn
    FROM
        masterdata.dmn_methodiek_document_versie
	UNION
    SELECT
        id,
        code,
        description,
		valid_from,
		valid_to,
        'dmn_natura_2000_bijdrage' AS dmn
    FROM
        masterdata.dmn_natura_2000_bijdrage
	UNION
    SELECT
        id,
        code,
        description,
		valid_from,
		valid_to,
        'dmn_natura_2000_type' AS dmn
    FROM
        masterdata.dmn_natura_2000_type
	UNION
    SELECT
        id,
        code,
        description,
		valid_from,
		valid_to,
        'dmn_package_kwaliteit' AS dmn
    FROM
        masterdata.dmn_package_kwaliteit		
	UNION
    SELECT
        id,
        code,
        description,
		valid_from,
		valid_to,
        'dmn_habitat_type_tx' AS dmn
    FROM
        masterdata.dmn_habitat_type_tx		
	UNION
    SELECT
        id,
        code,
        description,
		valid_from,
		valid_to,
        'dmn_habitat_kwaliteit_tx' AS dmn
    FROM
        masterdata.dmn_habitat_kwaliteit_tx		
		;

ALTER TABLE masterdata.all_domains
  OWNER TO anlb;
GRANT SELECT ON TABLE masterdata.all_domains TO anlb_sqlpad;  
;
GRANT SELECT ON TABLE masterdata.all_domains TO snl_readonly;
