/* ---------------------------------------------------- */
/*  Generated by Enterprise Architect Version 12.1 		*/
/*  Created On : 30-Apr-2020 09:58:57 				*/
/*  DBMS       : PostgreSQL 						*/
/* ---------------------------------------------------- */

/* Drop Views */

DROP VIEW IF EXISTS all_domains CASCADE
;

DROP VIEW IF EXISTS all_domain_features CASCADE
;

/* Drop Tables */

DROP TABLE IF EXISTS masterdata.dmn_beheer_type_beschikking_niet_snl CASCADE
;

DROP TABLE IF EXISTS masterdata.dmn_status_aanvraag_subsidie CASCADE
;

DROP TABLE IF EXISTS masterdata.dmn_type_regeling CASCADE
;

DROP TABLE IF EXISTS masterdata.dmn_type_regeling_niet_snl CASCADE
;

DROP TABLE IF EXISTS masterdata.dmn_type_regeling_snl CASCADE
;

DROP TABLE IF EXISTS masterdata.lnk_table_beheer_type_regeling CASCADE
;

/* Create Tables */

CREATE TABLE masterdata.dmn_beheer_type_beschikking_niet_snl
(
	id bigint NOT NULL   DEFAULT NEXTVAL(('masterdata.masterdata_seq'::text)::regclass),
	code char(20) NOT NULL,
	description char(100) NULL,
	valid_from timestamp NOT NULL,
	valid_to timestamp NULL
)
;

CREATE TABLE masterdata.dmn_status_aanvraag_subsidie
(
	id bigint NOT NULL   DEFAULT NEXTVAL(('masterdata.masterdata_seq'::text)::regclass),
	code char(20) NOT NULL,
	description char(100) NULL,
	valid_from timestamp NOT NULL,
	valid_to timestamp NULL
)
;

CREATE TABLE masterdata.dmn_type_regeling
(
	id bigint NOT NULL   DEFAULT NEXTVAL(('masterdata.masterdata_seq'::text)::regclass),
	code char(20) NOT NULL,
	description char(100) NULL,
	valid_from timestamp NOT NULL,
	valid_to timestamp NULL
)
;

CREATE TABLE masterdata.dmn_type_regeling_niet_snl
(
	id bigint NOT NULL   DEFAULT NEXTVAL(('masterdata.masterdata_seq'::text)::regclass),
	code char(20) NOT NULL,
	description char(100) NULL,
	valid_from timestamp NOT NULL,
	valid_to timestamp NULL
)
;

CREATE TABLE masterdata.dmn_type_regeling_snl
(
	id bigint NOT NULL   DEFAULT NEXTVAL(('masterdata.masterdata_seq'::text)::regclass),
	code char(20) NOT NULL,
	description char(100) NULL,
	valid_from timestamp NOT NULL,
	valid_to timestamp NULL
)
;

CREATE TABLE masterdata.lnk_table_beheer_type_regeling
(
	type_regeling_id bigint NOT NULL,
	beheer_type_id bigint NOT NULL,
	valid_from timestamp NOT NULL,
	valid_to timestamp NULL
)
;

/* Create Primary Keys, Indexes, Uniques, Checks */

ALTER TABLE masterdata.dmn_beheer_type_beschikking_niet_snl ADD CONSTRAINT PK_dmn_beheer_type_beschikking_niet_snl
	PRIMARY KEY (id)
;

ALTER TABLE masterdata.dmn_beheer_type_beschikking_niet_snl ADD CONSTRAINT un_code_beheer_type_beschikking_niet_snl UNIQUE (code)
;

ALTER TABLE masterdata.dmn_status_aanvraag_subsidie ADD CONSTRAINT PK_dmn_status_aanvraag_subsidie
	PRIMARY KEY (id)
;

ALTER TABLE masterdata.dmn_status_aanvraag_subsidie ADD CONSTRAINT un_code_status_aanvraag_subsidie UNIQUE (code)
;

ALTER TABLE masterdata.dmn_type_regeling ADD CONSTRAINT PK_dmn_type_regeling
	PRIMARY KEY (id)
;

ALTER TABLE masterdata.dmn_type_regeling ADD CONSTRAINT un_code_type_regeling UNIQUE (code)
;

ALTER TABLE masterdata.dmn_type_regeling_niet_snl ADD CONSTRAINT PK_dmn_beheer_type_pre_snl
	PRIMARY KEY (id)
;

ALTER TABLE masterdata.dmn_type_regeling_niet_snl ADD CONSTRAINT un_code_beheer_type_pre_snl UNIQUE (code)
;

ALTER TABLE masterdata.dmn_type_regeling_snl ADD CONSTRAINT PK_dmn_beheer_type_snl
	PRIMARY KEY (id)
;

ALTER TABLE masterdata.dmn_type_regeling_snl ADD CONSTRAINT un_code_beheer_type_snl UNIQUE (code)
;

ALTER TABLE masterdata.lnk_table_beheer_type_regeling ADD CONSTRAINT PK_lnk_table_beheer_type_regeling
	PRIMARY KEY (type_regeling_id,beheer_type_id)
;

CREATE INDEX IXFK_dmn_beheer_type_6 ON masterdata.lnk_table_beheer_type_regeling (beheer_type_id ASC)
;

CREATE INDEX IXFK_dmn_beheer_type_snl_1 ON masterdata.lnk_table_beheer_type_regeling (type_regeling_id ASC)
;

/* Create Foreign Key Constraints */

ALTER TABLE masterdata.lnk_table_beheer_type_regeling ADD CONSTRAINT FK_dmn_beheer_type_6
	FOREIGN KEY (beheer_type_id) REFERENCES masterdata.dmn_beheer_type (id) ON DELETE No Action ON UPDATE No Action
;

ALTER TABLE masterdata.lnk_table_beheer_type_regeling ADD CONSTRAINT FK_dmn_beheer_type_snl_1
	FOREIGN KEY (type_regeling_id) REFERENCES masterdata.dmn_type_regeling_snl (id) ON DELETE No Action ON UPDATE No Action
;

/* Create Views */

-- View: masterdata.all_domains

-- DROP VIEW masterdata.all_domains;

CREATE OR REPLACE VIEW masterdata.all_domains AS
    SELECT
        id,
        code,
        description,
		valid_from,
		valid_to,
        'dmn_ambitiegebied_type' AS dmn
    FROM
        masterdata.dmn_ambitiegebied_type
    UNION
    SELECT
        id,
        code,
        description,
		valid_from,
		valid_to,
        'dmn_beheer_pakket_landschap' AS dmn
    FROM
        masterdata.dmn_beheer_pakket_landschap
    UNION
    SELECT
        id,
        code,
        description,
		valid_from,
		valid_to,
        'dmn_beheer_type_agrarisch' AS dmn
    FROM
        masterdata.dmn_beheer_type_agrarisch
    UNION
    SELECT
        id,
        code,
        description,
		valid_from,
		valid_to,
        'dmn_beheer_type_grootschaligenatuur' AS dmn
    FROM
        masterdata.dmn_beheer_type_grootschaligenatuur
    UNION
    SELECT
        id,
        code,
        description,
		valid_from,
		valid_to,
        'dmn_beheer_type_landschap' AS dmn
    FROM
        masterdata.dmn_beheer_type_landschap
    UNION
    SELECT
        id,
        code,
        description,
		valid_from,
		valid_to,
        'dmn_beheer_type_natuur' AS dmn
    FROM
        masterdata.dmn_beheer_type_natuur
    UNION
    SELECT
        id,
        code,
        description,
		valid_from,
		valid_to,
        'dmn_beheer_type_natuur_ambitie' AS dmn
    FROM
        masterdata.dmn_beheer_type_natuur_ambitie
    UNION
    SELECT
        id,
        code,
        description,
		valid_from,
		valid_to,
        'dmn_beheer_type_omtevormennatuur_ambitie' AS dmn
    FROM
        masterdata.dmn_beheer_type_omtevormennatuur_ambitie
    UNION
    SELECT
        id,
        code,
        description,
		valid_from,
		valid_to,
        'dmn_beheer_type_water' AS dmn
    FROM
        masterdata.dmn_beheer_type_water
    UNION
    SELECT
        id,
        code,
        description,
		valid_from,
		valid_to,
        'dmn_beheergebied_type' AS dmn
    FROM
        masterdata.dmn_beheergebied_type
    UNION
    SELECT
        id,
        code,
        description,
		valid_from,
		valid_to,
        'dmn_bijzonder_gebied_code' AS dmn
    FROM
        masterdata.dmn_bijzonder_gebied_code
    UNION
    SELECT
        id,
        code,
        description,
		valid_from,
		valid_to,
        'dmn_natuur_type_agrarisch' AS dmn
    FROM
        masterdata.dmn_natuur_type_agrarisch
    UNION
    SELECT
        id,
        code,
        description,
		valid_from,
		valid_to,
        'dmn_natuur_type_water' AS dmn
    FROM
        masterdata.dmn_natuur_type_water
    UNION
    SELECT
        id,
        code,
        description,
		valid_from,
		valid_to,
        'dmn_openstellings_bijdrage_type' AS dmn
    FROM
        masterdata.dmn_openstellings_bijdrage_type
    UNION
    SELECT
        id,
        code,
        description,
		valid_from,
		valid_to,
        'dmn_provincie_code' AS dmn
    FROM
        masterdata.dmn_provincie_code
    UNION
    SELECT
        id,
        code,
        description,
		valid_from,
		valid_to,
        'dmn_status_ehs' AS dmn
    FROM
        masterdata.dmn_status_ehs
    UNION
    SELECT
        id,
        code,
        description,
		valid_from,
		valid_to,
        'dmn_status_plan' AS dmn
    FROM
        masterdata.dmn_status_plan
    UNION
    SELECT
        id,
        code,
        description,
		valid_from,
		valid_to,
        'dmn_beheer_functie' AS dmn
    FROM
        masterdata.dmn_beheer_functie
    UNION
    SELECT
        id,
        code,
        description,
		valid_from,
		valid_to,
        'dmn_natuur_type' AS dmn
    FROM
        masterdata.dmn_natuur_type
    UNION
    SELECT
        id,
        code,
        description,
		valid_from,
		valid_to,
        'dmn_beheer_pakket' AS dmn
    FROM
        masterdata.dmn_beheer_pakket
    UNION
    SELECT
        id,
        code,
        description,
		valid_from,
		valid_to,
        'dmn_beheer_type' AS dmn
    FROM
        masterdata.dmn_beheer_type
    UNION
    SELECT
        id,
        code,
        description,
		valid_from,
		valid_to,
        'dmn_status_natuur' AS dmn
    FROM
        masterdata.dmn_status_natuur
    UNION
    SELECT
        id,
        code,
        description,
		valid_from,
		valid_to,
        'dmn_status_verwerving' AS dmn
    FROM
        masterdata.dmn_status_verwerving
    UNION
    SELECT
        id,
        code,
        description,
		valid_from,
		valid_to,
        'dmn_type_beheerder_en_eigenaar' AS dmn
    FROM
        masterdata.dmn_type_beheerder_en_eigenaar
    UNION
    SELECT
        id,
        code,
        description,
		valid_from,
		valid_to,
        'dmn_status_aanvraag_subsidie' AS dmn
    FROM
        masterdata.dmn_status_aanvraag_subsidie
    UNION
    SELECT
        id,
        code,
        description,
		valid_from,
		valid_to,
        'dmn_type_regeling' AS dmn
    FROM
        masterdata.dmn_type_regeling
    UNION
    SELECT
        id,
        code,
        description,
		valid_from,
		valid_to,
        'dmn_type_regeling_snl' AS dmn
    FROM
        masterdata.dmn_type_regeling_snl
    UNION
    SELECT
        id,
        code,
        description,
		valid_from,
		valid_to,
        'dmn_type_regeling_niet_snl' AS dmn
    FROM
        masterdata.dmn_type_regeling_niet_snl
	UNION
    SELECT
        id,
        code,
        description,
		valid_from,
		valid_to,
        'dmn_beheer_type_beschikking_niet_snl' AS dmn
    FROM
        masterdata.dmn_beheer_type_beschikking_niet_snl;

ALTER TABLE masterdata.all_domains
  OWNER TO anlb;
GRANT SELECT ON TABLE masterdata.all_domains TO anlb_sqlpad;  
;

-- View: masterdata.all_domain_features

-- DROP VIEW masterdata.all_domain_features;

CREATE OR REPLACE VIEW masterdata.all_domain_features AS 
 SELECT all_domains.id,
    all_domains.code,
    all_domains.description,
    all_domains.valid_from,
    all_domains.valid_to,
    all_domains.dmn,
    domain_feature.domain,
    domain_feature.feature,
    domain_feature.attribute
   FROM masterdata.all_domains
     JOIN masterdata.domain_feature ON all_domains.dmn = domain_feature.domain;

ALTER TABLE masterdata.all_domain_features
  OWNER TO anlb;
GRANT SELECT ON TABLE masterdata.all_domain_features TO anlb_sqlpad;
;
