/* ---------------------------------------------------- */
/*  Generated by Enterprise Architect Version 12.1 		*/
/*  Created On : 22-Feb-2021 14:31:11 				*/
/*  DBMS       : PostgreSQL 						*/
/* ---------------------------------------------------- */


/* Create Tables */

CREATE TABLE masterdata.dmn_status_beheer_gebied
(
	id bigint NOT NULL   DEFAULT NEXTVAL(('masterdata.masterdata_seq'::text)::regclass),
	code char(20) NOT NULL,
	description char(100) NULL,
	valid_from timestamp NOT NULL,
	valid_to timestamp NULL
)
;

CREATE TABLE masterdata.dmn_status_beheer_gebied_ambitie
(
	id bigint NOT NULL   DEFAULT NEXTVAL(('masterdata.masterdata_seq'::text)::regclass),
	code char(20) NOT NULL,
	description char(100) NULL,
	valid_from timestamp NOT NULL,
	valid_to timestamp NULL
)
;

CREATE TABLE masterdata.dmn_status_bijzonder_gebied
(
	id bigint NOT NULL   DEFAULT NEXTVAL(('masterdata.masterdata_seq'::text)::regclass),
	code char(20) NOT NULL,
	description char(100) NULL,
	valid_from timestamp NOT NULL,
	valid_to timestamp NULL
)
;

CREATE TABLE masterdata.dmn_status_deel_gebied
(
	id bigint NOT NULL   DEFAULT NEXTVAL(('masterdata.masterdata_seq'::text)::regclass),
	code char(20) NOT NULL,
	description char(100) NULL,
	valid_from timestamp NOT NULL,
	valid_to timestamp NULL
)
;

CREATE TABLE masterdata.dmn_status_zoek_gebied_agrarisch
(
	id bigint NOT NULL   DEFAULT NEXTVAL(('masterdata.masterdata_seq'::text)::regclass),
	code char(20) NOT NULL,
	description char(100) NULL,
	valid_from timestamp NOT NULL,
	valid_to timestamp NULL
)
;

CREATE TABLE masterdata.dmn_status_zoek_gebied_landschap
(
	id bigint NOT NULL   DEFAULT NEXTVAL(('masterdata.masterdata_seq'::text)::regclass),
	code char(20) NOT NULL,
	description char(100) NULL,
	valid_from timestamp NOT NULL,
	valid_to timestamp NULL
)
;

CREATE TABLE masterdata.dmn_status_zoek_gebied_water
(
	id bigint NOT NULL   DEFAULT NEXTVAL(('masterdata.masterdata_seq'::text)::regclass),
	code char(20) NOT NULL,
	description char(100) NULL,
	valid_from timestamp NOT NULL,
	valid_to timestamp NULL
)
;

/* Create Primary Keys, Indexes, Uniques, Checks */

ALTER TABLE masterdata.dmn_status_beheer_gebied ADD CONSTRAINT PK_dmn_status_beheer_gebied
	PRIMARY KEY (id)
;

ALTER TABLE masterdata.dmn_status_beheer_gebied ADD CONSTRAINT un_code_status_beheer_gebied UNIQUE (code)
;

ALTER TABLE masterdata.dmn_status_beheer_gebied_ambitie ADD CONSTRAINT PK_dmn_status_beheer_gebied_ambitie
	PRIMARY KEY (id)
;

ALTER TABLE masterdata.dmn_status_beheer_gebied_ambitie ADD CONSTRAINT un_code_status_beheer_gebied_ambitie UNIQUE (code)
;

ALTER TABLE masterdata.dmn_status_bijzonder_gebied ADD CONSTRAINT PK_dmn_status_bijzonder_gebied
	PRIMARY KEY (id)
;

ALTER TABLE masterdata.dmn_status_bijzonder_gebied ADD CONSTRAINT un_code_status_bijzonder_gebied UNIQUE (code)
;

ALTER TABLE masterdata.dmn_status_deel_gebied ADD CONSTRAINT PK_dmn_status_deel_gebied
	PRIMARY KEY (id)
;

ALTER TABLE masterdata.dmn_status_deel_gebied ADD CONSTRAINT un_code_status_deel_gebied UNIQUE (code)
;

ALTER TABLE masterdata.dmn_status_zoek_gebied_agrarisch ADD CONSTRAINT PK_dmn_status_zoek_gebied_agrarisch
	PRIMARY KEY (id)
;

ALTER TABLE masterdata.dmn_status_zoek_gebied_agrarisch ADD CONSTRAINT un_code_status_zoek_gebied_agrarisch UNIQUE (code)
;

ALTER TABLE masterdata.dmn_status_zoek_gebied_landschap ADD CONSTRAINT PK_dmn_status_zoek_gebied_landschap
	PRIMARY KEY (id)
;

ALTER TABLE masterdata.dmn_status_zoek_gebied_landschap ADD CONSTRAINT un_code_status_zoek_gebied_landschap UNIQUE (code)
;

ALTER TABLE masterdata.dmn_status_zoek_gebied_water ADD CONSTRAINT PK_dmn_status_zoek_gebied_water
	PRIMARY KEY (id)
;

ALTER TABLE masterdata.dmn_status_zoek_gebied_water ADD CONSTRAINT un_code_status_zoek_gebied_water UNIQUE (code)
;

/* Create Foreign Key Constraints */

/* Create Table Comments, Sequences for Autonumber Columns */


/* Create Views */

-- View: masterdata.all_domains

--DROP VIEW masterdata.all_domains;

CREATE OR REPLACE VIEW masterdata.all_domains AS
    SELECT
        id,
        code,
        description,
		valid_from,
		valid_to,
        'dmn_ambitiegebied_type' AS dmn
    FROM
        masterdata.dmn_ambitiegebied_type
    UNION
    SELECT
        id,
        code,
        description,
		valid_from,
		valid_to,
        'dmn_beheer_pakket_landschap' AS dmn
    FROM
        masterdata.dmn_beheer_pakket_landschap
    UNION
    SELECT
        id,
        code,
        description,
		valid_from,
		valid_to,
        'dmn_beheer_type_agrarisch' AS dmn
    FROM
        masterdata.dmn_beheer_type_agrarisch
    UNION
    SELECT
        id,
        code,
        description,
		valid_from,
		valid_to,
        'dmn_beheer_type_grootschaligenatuur' AS dmn
    FROM
        masterdata.dmn_beheer_type_grootschaligenatuur
    UNION
    SELECT
        id,
        code,
        description,
		valid_from,
		valid_to,
        'dmn_beheer_type_landschap' AS dmn
    FROM
        masterdata.dmn_beheer_type_landschap
    UNION
    SELECT
        id,
        code,
        description,
		valid_from,
		valid_to,
        'dmn_beheer_type_natuur' AS dmn
    FROM
        masterdata.dmn_beheer_type_natuur
    UNION
    SELECT
        id,
        code,
        description,
		valid_from,
		valid_to,
        'dmn_beheer_type_natuur_ambitie' AS dmn
    FROM
        masterdata.dmn_beheer_type_natuur_ambitie
    UNION
    SELECT
        id,
        code,
        description,
		valid_from,
		valid_to,
        'dmn_beheer_type_omtevormennatuur_ambitie' AS dmn
    FROM
        masterdata.dmn_beheer_type_omtevormennatuur_ambitie
    UNION
    SELECT
        id,
        code,
        description,
		valid_from,
		valid_to,
        'dmn_beheer_type_water' AS dmn
    FROM
        masterdata.dmn_beheer_type_water
    UNION
    SELECT
        id,
        code,
        description,
		valid_from,
		valid_to,
        'dmn_beheergebied_type' AS dmn
    FROM
        masterdata.dmn_beheergebied_type
    UNION
    SELECT
        id,
        code,
        description,
		valid_from,
		valid_to,
        'dmn_bijzonder_gebied_code' AS dmn
    FROM
        masterdata.dmn_bijzonder_gebied_code
    UNION
    SELECT
        id,
        code,
        description,
		valid_from,
		valid_to,
        'dmn_natuur_type_agrarisch' AS dmn
    FROM
        masterdata.dmn_natuur_type_agrarisch
    UNION
    SELECT
        id,
        code,
        description,
		valid_from,
		valid_to,
        'dmn_natuur_type_water' AS dmn
    FROM
        masterdata.dmn_natuur_type_water
    UNION
    SELECT
        id,
        code,
        description,
		valid_from,
		valid_to,
        'dmn_openstellings_bijdrage_type' AS dmn
    FROM
        masterdata.dmn_openstellings_bijdrage_type
    UNION
    SELECT
        id,
        code,
        description,
		valid_from,
		valid_to,
        'dmn_provincie_code' AS dmn
    FROM
        masterdata.dmn_provincie_code
    UNION
    SELECT
        id,
        code,
        description,
		valid_from,
		valid_to,
        'dmn_status_ehs' AS dmn
    FROM
        masterdata.dmn_status_ehs
    UNION
    SELECT
        id,
        code,
        description,
		valid_from,
		valid_to,
        'dmn_status_plan' AS dmn
    FROM
        masterdata.dmn_status_plan
	UNION
	SELECT
        id,
        code,
        description,
		valid_from,
		valid_to,
        'dmn_status_beheer_gebied' AS dmn
    FROM
        masterdata.dmn_status_beheer_gebied
	UNION
	SELECT
        id,
        code,
        description,
		valid_from,
		valid_to,
        'dmn_status_beheer_gebied_ambitie' AS dmn
    FROM
        masterdata.dmn_status_beheer_gebied_ambitie
	UNION
	SELECT
        id,
        code,
        description,
		valid_from,
		valid_to,
        'dmn_status_bijzonder_gebied' AS dmn
    FROM
        masterdata.dmn_status_bijzonder_gebied
	UNION
	SELECT
        id,
        code,
        description,
		valid_from,
		valid_to,
        'dmn_status_deel_gebied' AS dmn
    FROM
        masterdata.dmn_status_deel_gebied
	UNION
	SELECT
        id,
        code,
        description,
		valid_from,
		valid_to,
        'dmn_status_zoek_gebied_agrarisch' AS dmn
    FROM
        masterdata.dmn_status_zoek_gebied_agrarisch
	UNION
	SELECT
        id,
        code,
        description,
		valid_from,
		valid_to,
        'dmn_status_zoek_gebied_landschap' AS dmn
    FROM
        masterdata.dmn_status_zoek_gebied_landschap
	UNION
	SELECT
        id,
        code,
        description,
		valid_from,
		valid_to,
        'dmn_status_zoek_gebied_water' AS dmn
    FROM
        masterdata.dmn_status_zoek_gebied_water		
    UNION
    SELECT
        id,
        code,
        description,
		valid_from,
		valid_to,
        'dmn_beheer_functie' AS dmn
    FROM
        masterdata.dmn_beheer_functie
    UNION
    SELECT
        id,
        code,
        description,
		valid_from,
		valid_to,
        'dmn_natuur_type' AS dmn
    FROM
        masterdata.dmn_natuur_type
    UNION
    SELECT
        id,
        code,
        description,
		valid_from,
		valid_to,
        'dmn_beheer_pakket' AS dmn
    FROM
        masterdata.dmn_beheer_pakket
    UNION
    SELECT
        id,
        code,
        description,
		valid_from,
		valid_to,
        'dmn_beheer_type' AS dmn
    FROM
        masterdata.dmn_beheer_type
    UNION
    SELECT
        id,
        code,
        description,
		valid_from,
		valid_to,
        'dmn_status_natuur' AS dmn
    FROM
        masterdata.dmn_status_natuur
    UNION
    SELECT
        id,
        code,
        description,
		valid_from,
		valid_to,
        'dmn_status_verwerving' AS dmn
    FROM
        masterdata.dmn_status_verwerving
    UNION
    SELECT
        id,
        code,
        description,
		valid_from,
		valid_to,
        'dmn_type_beheerder_en_eigenaar' AS dmn
    FROM
        masterdata.dmn_type_beheerder_en_eigenaar
    UNION
    SELECT
        id,
        code,
        description,
		valid_from,
		valid_to,
        'dmn_status_aanvraag_subsidie' AS dmn
    FROM
        masterdata.dmn_status_aanvraag_subsidie
    UNION
    SELECT
        id,
        code,
        description,
		valid_from,
		valid_to,
        'dmn_type_regeling' AS dmn
    FROM
        masterdata.dmn_type_regeling
    UNION
    SELECT
        id,
        code,
        description,
		valid_from,
		valid_to,
        'dmn_type_regeling_snl' AS dmn
    FROM
        masterdata.dmn_type_regeling_snl
    UNION
    SELECT
        id,
        code,
        description,
		valid_from,
		valid_to,
        'dmn_type_regeling_niet_snl' AS dmn
    FROM
        masterdata.dmn_type_regeling_niet_snl
	UNION
    SELECT
        id,
        code,
        description,
		valid_from,
		valid_to,
        'dmn_beheer_type_beschikking_niet_snl' AS dmn
    FROM
        masterdata.dmn_beheer_type_beschikking_niet_snl;

ALTER TABLE masterdata.all_domains
  OWNER TO anlb;
GRANT SELECT ON TABLE masterdata.all_domains TO anlb_sqlpad;  
;

