/* ---------------------------------------------------- */
/*  Generated by Enterprise Architect Version 12.1 		*/
/*  Created On : 15-Jan-2020 15:34:37 				*/
/*  DBMS       : PostgreSQL 						*/
/* ---------------------------------------------------- */

/* Drop Views */

DROP VIEW IF EXISTS masterdata.all_domain_features CASCADE
;

DROP VIEW IF EXISTS masterdata.all_domains CASCADE
;


/* Update Tables */

-- dmn_ambitiegebied_type
ALTER TABLE masterdata.dmn_ambitiegebied_type
ADD COLUMN valid_from timestamp without time zone NOT NULL DEFAULT NOW(),
ADD COLUMN valid_to timestamp without time zone,
DROP COLUMN active;

ALTER TABLE masterdata.dmn_ambitiegebied_type
ALTER COLUMN valid_from DROP DEFAULT;

-- dmn_beheer_functie
ALTER TABLE masterdata.dmn_beheer_functie
ADD COLUMN valid_from timestamp without time zone NOT NULL DEFAULT NOW(),
ADD COLUMN valid_to timestamp without time zone,
DROP COLUMN active;

ALTER TABLE masterdata.dmn_beheer_functie
ALTER COLUMN valid_from DROP DEFAULT;

-- dmn_beheer_pakket
ALTER TABLE masterdata.dmn_beheer_pakket
ADD COLUMN valid_from timestamp without time zone NOT NULL DEFAULT NOW(),
ADD COLUMN valid_to timestamp without time zone,
DROP COLUMN active;

ALTER TABLE masterdata.dmn_beheer_pakket
ALTER COLUMN valid_from DROP DEFAULT;

-- dmn_beheer_pakket_landschap
ALTER TABLE masterdata.dmn_beheer_pakket_landschap
ADD COLUMN valid_from timestamp without time zone NOT NULL DEFAULT NOW(),
ADD COLUMN valid_to timestamp without time zone,
DROP COLUMN active;

ALTER TABLE masterdata.dmn_beheer_pakket_landschap
ALTER COLUMN valid_from DROP DEFAULT;

-- dmn_beheer_type
ALTER TABLE masterdata.dmn_beheer_type
ADD COLUMN valid_from timestamp without time zone NOT NULL DEFAULT NOW(),
ADD COLUMN valid_to timestamp without time zone,
DROP COLUMN active;

ALTER TABLE masterdata.dmn_beheer_type
ALTER COLUMN valid_from DROP DEFAULT;

-- dmn_beheer_type_agrarisch
ALTER TABLE masterdata.dmn_beheer_type_agrarisch
ADD COLUMN valid_from timestamp without time zone NOT NULL DEFAULT NOW(),
ADD COLUMN valid_to timestamp without time zone,
DROP COLUMN active;

ALTER TABLE masterdata.dmn_beheer_type_agrarisch
ALTER COLUMN valid_from DROP DEFAULT;

-- dmn_beheer_type_grootschaligenatuur
ALTER TABLE masterdata.dmn_beheer_type_grootschaligenatuur
ADD COLUMN valid_from timestamp without time zone NOT NULL DEFAULT NOW(),
ADD COLUMN valid_to timestamp without time zone,
DROP COLUMN active;

ALTER TABLE masterdata.dmn_beheer_type_grootschaligenatuur
ALTER COLUMN valid_from DROP DEFAULT;

-- dmn_beheer_type_landschap
ALTER TABLE masterdata.dmn_beheer_type_landschap
ADD COLUMN valid_from timestamp without time zone NOT NULL DEFAULT NOW(),
ADD COLUMN valid_to timestamp without time zone,
DROP COLUMN active;

ALTER TABLE masterdata.dmn_beheer_type_landschap
ALTER COLUMN valid_from DROP DEFAULT;

-- dmn_beheer_type_natuur
ALTER TABLE masterdata.dmn_beheer_type_natuur
ADD COLUMN valid_from timestamp without time zone NOT NULL DEFAULT NOW(),
ADD COLUMN valid_to timestamp without time zone,
DROP COLUMN active;

ALTER TABLE masterdata.dmn_beheer_type_natuur
ALTER COLUMN valid_from DROP DEFAULT;

-- dmn_beheer_type_natuur_ambitie
ALTER TABLE masterdata.dmn_beheer_type_natuur_ambitie
ADD COLUMN valid_from timestamp without time zone NOT NULL DEFAULT NOW(),
ADD COLUMN valid_to timestamp without time zone,
DROP COLUMN active;

ALTER TABLE masterdata.dmn_beheer_type_natuur_ambitie
ALTER COLUMN valid_from DROP DEFAULT;

-- dmn_beheer_type_omtevormennatuur_ambitie
ALTER TABLE masterdata.dmn_beheer_type_omtevormennatuur_ambitie
ADD COLUMN valid_from timestamp without time zone NOT NULL DEFAULT NOW(),
ADD COLUMN valid_to timestamp without time zone,
DROP COLUMN active;

ALTER TABLE masterdata.dmn_beheer_type_omtevormennatuur_ambitie
ALTER COLUMN valid_from DROP DEFAULT;

-- dmn_beheer_type_water
ALTER TABLE masterdata.dmn_beheer_type_water
ADD COLUMN valid_from timestamp without time zone NOT NULL DEFAULT NOW(),
ADD COLUMN valid_to timestamp without time zone,
DROP COLUMN active;

ALTER TABLE masterdata.dmn_beheer_type_water
ALTER COLUMN valid_from DROP DEFAULT;

-- dmn_beheergebied_type
ALTER TABLE masterdata.dmn_beheergebied_type
ADD COLUMN valid_from timestamp without time zone NOT NULL DEFAULT NOW(),
ADD COLUMN valid_to timestamp without time zone,
DROP COLUMN active;

ALTER TABLE masterdata.dmn_beheergebied_type
ALTER COLUMN valid_from DROP DEFAULT;

-- dmn_bijzonder_gebied_code
ALTER TABLE masterdata.dmn_bijzonder_gebied_code
ADD COLUMN valid_from timestamp without time zone NOT NULL DEFAULT NOW(),
ADD COLUMN valid_to timestamp without time zone,
DROP COLUMN active;

ALTER TABLE masterdata.dmn_bijzonder_gebied_code
ALTER COLUMN valid_from DROP DEFAULT;

-- dmn_natuur_type
ALTER TABLE masterdata.dmn_natuur_type
ADD COLUMN valid_from timestamp without time zone NOT NULL DEFAULT NOW(),
ADD COLUMN valid_to timestamp without time zone,
DROP COLUMN active;

ALTER TABLE masterdata.dmn_natuur_type
ALTER COLUMN valid_from DROP DEFAULT;

-- dmn_natuur_type_agrarisch
ALTER TABLE masterdata.dmn_natuur_type_agrarisch
ADD COLUMN valid_from timestamp without time zone NOT NULL DEFAULT NOW(),
ADD COLUMN valid_to timestamp without time zone,
DROP COLUMN active;

ALTER TABLE masterdata.dmn_natuur_type_agrarisch
ALTER COLUMN valid_from DROP DEFAULT;

-- dmn_natuur_type_water
ALTER TABLE masterdata.dmn_natuur_type_water
ADD COLUMN valid_from timestamp without time zone NOT NULL DEFAULT NOW(),
ADD COLUMN valid_to timestamp without time zone,
DROP COLUMN active;

ALTER TABLE masterdata.dmn_natuur_type_water
ALTER COLUMN valid_from DROP DEFAULT;

-- dmn_openstellings_bijdrage_type
ALTER TABLE masterdata.dmn_openstellings_bijdrage_type
ADD COLUMN valid_from timestamp without time zone NOT NULL DEFAULT NOW(),
ADD COLUMN valid_to timestamp without time zone,
DROP COLUMN active;

ALTER TABLE masterdata.dmn_openstellings_bijdrage_type
ALTER COLUMN valid_from DROP DEFAULT;

-- dmn_provincie_code
ALTER TABLE masterdata.dmn_provincie_code
ADD COLUMN valid_from timestamp without time zone NOT NULL DEFAULT NOW(),
ADD COLUMN valid_to timestamp without time zone,
DROP COLUMN active;

ALTER TABLE masterdata.dmn_provincie_code
ALTER COLUMN valid_from DROP DEFAULT;

-- dmn_status_ehs
ALTER TABLE masterdata.dmn_status_ehs
ADD COLUMN valid_from timestamp without time zone NOT NULL DEFAULT NOW(),
ADD COLUMN valid_to timestamp without time zone,
DROP COLUMN active;

ALTER TABLE masterdata.dmn_status_ehs
ALTER COLUMN valid_from DROP DEFAULT;

-- dmn_status_plan
ALTER TABLE masterdata.dmn_status_plan
ADD COLUMN valid_from timestamp without time zone NOT NULL DEFAULT NOW(),
ADD COLUMN valid_to timestamp without time zone,
DROP COLUMN active;

ALTER TABLE masterdata.dmn_status_plan
ALTER COLUMN valid_from DROP DEFAULT;

-- lnk_table_beheer_functies
ALTER TABLE masterdata.lnk_table_beheer_functies
ADD COLUMN valid_from timestamp without time zone NOT NULL DEFAULT NOW(),
ADD COLUMN valid_to timestamp without time zone,
DROP COLUMN active;

ALTER TABLE masterdata.lnk_table_beheer_functies
ALTER COLUMN valid_from DROP DEFAULT;

-- lnk_table_beheer_typen
ALTER TABLE masterdata.lnk_table_beheer_typen
ADD COLUMN valid_from timestamp without time zone NOT NULL DEFAULT NOW(),
ADD COLUMN valid_to timestamp without time zone,
DROP COLUMN active;

ALTER TABLE masterdata.lnk_table_beheer_typen
ALTER COLUMN valid_from DROP DEFAULT;

-- lnk_table_beheerpakket
ALTER TABLE masterdata.lnk_table_beheerpakket
ADD COLUMN valid_from timestamp without time zone NOT NULL DEFAULT NOW(),
ADD COLUMN valid_to timestamp without time zone,
DROP COLUMN active;

ALTER TABLE masterdata.lnk_table_beheerpakket
ALTER COLUMN valid_from DROP DEFAULT;

-- feature_layer
ALTER TABLE masterdata.feature_layer
ADD COLUMN date_range_validation boolean NOT NULL DEFAULT true,
ADD COLUMN identificatie_validation boolean NOT NULL DEFAULT true
;

ALTER TABLE masterdata.feature_layer
ALTER COLUMN date_range_validation DROP DEFAULT,
ALTER COLUMN identificatie_validation DROP DEFAULT;

-- provinces
ALTER TABLE masterdata.provinces
ADD COLUMN program char(10) NOT NULL DEFAULT 'SNL'
;

ALTER TABLE masterdata.provinces
ALTER COLUMN program DROP DEFAULT
;

ALTER TABLE masterdata.provinces DROP CONSTRAINT PK_provinces
; 

ALTER TABLE masterdata.provinces ADD CONSTRAINT PK_provinces
	PRIMARY KEY (code,drupal_role)
; 

-- new domains for VRN

CREATE TABLE masterdata.dmn_status_natuur
(
	id bigint NOT NULL   DEFAULT NEXTVAL(('masterdata.masterdata_seq'::text)::regclass),
	code char(20) NOT NULL,
	description char(100) NULL,
	valid_from timestamp NOT NULL,
	valid_to timestamp NULL
)
;

CREATE TABLE masterdata.dmn_status_verwerving
(
	id bigint NOT NULL   DEFAULT NEXTVAL(('masterdata.masterdata_seq'::text)::regclass),
	code char(20) NOT NULL,
	description char(100) NULL,
	valid_from timestamp NOT NULL,
	valid_to timestamp NULL
)
;

CREATE TABLE masterdata.dmn_type_beheerder_en_eigenaar
(
	id bigint NOT NULL   DEFAULT NEXTVAL(('masterdata.masterdata_seq'::text)::regclass),
	code char(20) NOT NULL,
	description char(100) NOT NULL,
	valid_from timestamp NOT NULL,
	valid_to timestamp NULL
)
;

ALTER TABLE masterdata.dmn_status_natuur ADD CONSTRAINT PK_dmn_status_natuur
	PRIMARY KEY (id)
;

ALTER TABLE masterdata.dmn_status_natuur ADD CONSTRAINT un_code_status_natuur UNIQUE (code)
;

ALTER TABLE masterdata.dmn_status_verwerving ADD CONSTRAINT PK_dmn_status_verwerving
	PRIMARY KEY (id)
;

ALTER TABLE masterdata.dmn_status_verwerving ADD CONSTRAINT un_code_status_verwerving UNIQUE (code)
;

ALTER TABLE masterdata.dmn_type_beheerder_en_eigenaar ADD CONSTRAINT PK_dmn_type_beheerder_en_eigenaar
	PRIMARY KEY (id)
;

ALTER TABLE masterdata.dmn_type_beheerder_en_eigenaar ADD CONSTRAINT un_code_type_beheerder_en_eigenaar UNIQUE (code)
;

/* Create Views */

-- View: masterdata.all_domains

-- DROP VIEW masterdata.all_domains CASCADE;

CREATE OR REPLACE VIEW masterdata.all_domains AS
    SELECT
        id,
        code,
        description,
		valid_from,
		valid_to,
        'dmn_ambitiegebied_type' AS dmn
    FROM
        masterdata.dmn_ambitiegebied_type
    UNION
    SELECT
        id,
        code,
        description,
		valid_from,
		valid_to,
        'dmn_beheer_pakket_landschap' AS dmn
    FROM
        masterdata.dmn_beheer_pakket_landschap
    UNION
    SELECT
        id,
        code,
        description,
		valid_from,
		valid_to,
        'dmn_beheer_type_agrarisch' AS dmn
    FROM
        masterdata.dmn_beheer_type_agrarisch
    UNION
    SELECT
        id,
        code,
        description,
		valid_from,
		valid_to,
        'dmn_beheer_type_grootschaligenatuur' AS dmn
    FROM
        masterdata.dmn_beheer_type_grootschaligenatuur
    UNION
    SELECT
        id,
        code,
        description,
		valid_from,
		valid_to,
        'dmn_beheer_type_landschap' AS dmn
    FROM
        masterdata.dmn_beheer_type_landschap
    UNION
    SELECT
        id,
        code,
        description,
		valid_from,
		valid_to,
        'dmn_beheer_type_natuur' AS dmn
    FROM
        masterdata.dmn_beheer_type_natuur
    UNION
    SELECT
        id,
        code,
        description,
		valid_from,
		valid_to,
        'dmn_beheer_type_natuur_ambitie' AS dmn
    FROM
        masterdata.dmn_beheer_type_natuur_ambitie
    UNION
    SELECT
        id,
        code,
        description,
		valid_from,
		valid_to,
        'dmn_beheer_type_omtevormennatuur_ambitie' AS dmn
    FROM
        masterdata.dmn_beheer_type_omtevormennatuur_ambitie
    UNION
    SELECT
        id,
        code,
        description,
		valid_from,
		valid_to,
        'dmn_beheer_type_water' AS dmn
    FROM
        masterdata.dmn_beheer_type_water
    UNION
    SELECT
        id,
        code,
        description,
		valid_from,
		valid_to,
        'dmn_beheergebied_type' AS dmn
    FROM
        masterdata.dmn_beheergebied_type
    UNION
    SELECT
        id,
        code,
        description,
		valid_from,
		valid_to,
        'dmn_bijzonder_gebied_code' AS dmn
    FROM
        masterdata.dmn_bijzonder_gebied_code
    UNION
    SELECT
        id,
        code,
        description,
		valid_from,
		valid_to,
        'dmn_natuur_type_agrarisch' AS dmn
    FROM
        masterdata.dmn_natuur_type_agrarisch
    UNION
    SELECT
        id,
        code,
        description,
		valid_from,
		valid_to,
        'dmn_natuur_type_water' AS dmn
    FROM
        masterdata.dmn_natuur_type_water
    UNION
    SELECT
        id,
        code,
        description,
		valid_from,
		valid_to,
        'dmn_openstellings_bijdrage_type' AS dmn
    FROM
        masterdata.dmn_openstellings_bijdrage_type
    UNION
    SELECT
        id,
        code,
        description,
		valid_from,
		valid_to,
        'dmn_provincie_code' AS dmn
    FROM
        masterdata.dmn_provincie_code
    UNION
    SELECT
        id,
        code,
        description,
		valid_from,
		valid_to,
        'dmn_status_ehs' AS dmn
    FROM
        masterdata.dmn_status_ehs
    UNION
    SELECT
        id,
        code,
        description,
		valid_from,
		valid_to,
        'dmn_status_plan' AS dmn
    FROM
        masterdata.dmn_status_plan
    UNION
    SELECT
        id,
        code,
        description,
		valid_from,
		valid_to,
        'dmn_beheer_functie' AS dmn
    FROM
        masterdata.dmn_beheer_functie
    UNION
    SELECT
        id,
        code,
        description,
		valid_from,
		valid_to,
        'dmn_natuur_type' AS dmn
    FROM
        masterdata.dmn_natuur_type
    UNION
    SELECT
        id,
        code,
        description,
		valid_from,
		valid_to,
        'dmn_beheer_pakket' AS dmn
    FROM
        masterdata.dmn_beheer_pakket
    UNION
    SELECT
        id,
        code,
        description,
		valid_from,
		valid_to,
        'dmn_beheer_type' AS dmn
    FROM
        masterdata.dmn_beheer_type
    UNION
    SELECT
        id,
        code,
        description,
		valid_from,
		valid_to,
        'dmn_status_natuur' AS dmn
    FROM
        masterdata.dmn_status_natuur
    UNION
    SELECT
        id,
        code,
        description,
		valid_from,
		valid_to,
        'dmn_status_verwerving' AS dmn
    FROM
        masterdata.dmn_status_verwerving
    UNION
    SELECT
        id,
        code,
        description,
		valid_from,
		valid_to,
        'dmn_type_beheerder_en_eigenaar' AS dmn
    FROM
        masterdata.dmn_type_beheerder_en_eigenaar;

ALTER TABLE masterdata.all_domains
  OWNER TO anlb;

-- View: masterdata.all_domain_features

-- DROP VIEW masterdata.all_domain_features;

CREATE OR REPLACE VIEW masterdata.all_domain_features AS 
 SELECT all_domains.id, 
	    all_domains.code, 
		all_domains.description, 
		all_domains.valid_from,
		all_domains.valid_to,		
		all_domains.dmn, 
		domain_feature.domain, 
        domain_feature.feature, 
		domain_feature.attribute
   FROM masterdata.all_domains
   JOIN masterdata.domain_feature ON all_domains.dmn = domain_feature.domain::text;

ALTER TABLE masterdata.all_domain_features
  OWNER TO anlb;
GRANT SELECT ON ALL TABLES IN SCHEMA masterdata TO anlb_sqlpad;