/* ---------------------------------------------------- */
/*  Generated by Enterprise Architect Version 12.1 		*/
/*  Created On : 22-Dec-2023 16:33:43 				*/
/*  DBMS       : PostgreSQL 						*/
/* ---------------------------------------------------- */


/* Create Tables */
ALTER TABLE besi.besi_species_group ADD COLUMN IF NOT EXISTS animal_group_id bigint NULL;
ALTER TABLE besi.besi_species_group ADD COLUMN IF NOT EXISTS protected_nest_id bigint NULL;
ALTER TABLE besi.besi_species_group ADD COLUMN IF NOT EXISTS mammal_type_id bigint NULL;

ALTER TABLE besi.besi_taxa ADD COLUMN IF NOT EXISTS animal_group_id bigint NULL;
ALTER TABLE besi.besi_taxa ADD COLUMN IF NOT EXISTS protected_nest_id bigint NULL;
ALTER TABLE besi.besi_taxa ADD COLUMN IF NOT EXISTS mammal_type_id bigint NULL;



/* Create Primary Keys, Indexes, Uniques, Checks */



CREATE INDEX IF NOT EXISTS IXFK_besi_species_group_dmn_animal_group ON besi.besi_species_group (animal_group_id ASC);
CREATE INDEX IF NOT EXISTS IXFK_besi_species_group_dmn_mammal_type ON besi.besi_species_group (mammal_type_id ASC);
CREATE INDEX IF NOT EXISTS IXFK_besi_species_group_dmn_protected_nest ON besi.besi_species_group (protected_nest_id ASC);


CREATE INDEX IF NOT EXISTS IXFK_besi_taxa_dmn_animal_group ON besi.besi_taxa (animal_group_id ASC);
CREATE INDEX IF NOT EXISTS IXFK_besi_taxa_dmn_mammal_type ON besi.besi_taxa (mammal_type_id ASC);
CREATE INDEX IF NOT EXISTS IXFK_besi_taxa_dmn_protected_nest ON besi.besi_taxa (protected_nest_id ASC);


/* Create Foreign Key Constraints */

SELECT pg_temp.create_constraint_if_not_exists ('besi','besi_species_group','FK_besi_species_group_dmn_animal_group',
'ALTER TABLE besi.besi_species_group ADD CONSTRAINT FK_besi_species_group_dmn_animal_group
	FOREIGN KEY (animal_group_id) REFERENCES masterdata.dmn_animal_group (id) ON DELETE No Action ON UPDATE No Action
;');

SELECT pg_temp.create_constraint_if_not_exists ('besi','besi_species_group','FK_besi_species_group_dmn_mammal_type',
'ALTER TABLE besi.besi_species_group ADD CONSTRAINT FK_besi_species_group_dmn_mammal_type
	FOREIGN KEY (mammal_type_id) REFERENCES masterdata.dmn_mammal_type (id) ON DELETE No Action ON UPDATE No Action
;');

SELECT pg_temp.create_constraint_if_not_exists ('besi','besi_species_group','FK_besi_species_group_dmn_protected_nest',
'ALTER TABLE besi.besi_species_group ADD CONSTRAINT FK_besi_species_group_dmn_protected_nest
	FOREIGN KEY (protected_nest_id) REFERENCES masterdata.dmn_protected_nest (id) ON DELETE No Action ON UPDATE No Action
;');

SELECT pg_temp.create_constraint_if_not_exists ('besi','besi_taxa','FK_besi_taxa_dmn_animal_group',
'ALTER TABLE besi.besi_taxa ADD CONSTRAINT FK_besi_taxa_dmn_animal_group
	FOREIGN KEY (animal_group_id) REFERENCES masterdata.dmn_animal_group (id) ON DELETE No Action ON UPDATE No Action
;');

SELECT pg_temp.create_constraint_if_not_exists ('besi','besi_taxa','FK_besi_taxa_dmn_mammal_type',
'ALTER TABLE besi.besi_taxa ADD CONSTRAINT FK_besi_taxa_dmn_mammal_type
	FOREIGN KEY (mammal_type_id) REFERENCES masterdata.dmn_mammal_type (id) ON DELETE No Action ON UPDATE No Action
;');

SELECT pg_temp.create_constraint_if_not_exists ('besi','besi_taxa','FK_besi_taxa_dmn_protected_nest',
'ALTER TABLE besi.besi_taxa ADD CONSTRAINT FK_besi_taxa_dmn_protected_nest
	FOREIGN KEY (protected_nest_id) REFERENCES masterdata.dmn_protected_nest (id) ON DELETE No Action ON UPDATE No Action
;');


-- IMNA-12831
ALTER TABLE besi.besi_species_group ALTER COLUMN animal_group_id SET NOT NULL;
ALTER TABLE besi.besi_taxa ALTER COLUMN animal_group_id SET NOT NULL;