HTTP_PROXY=172.16.2.140:8080
JRE_HOME=C:\"Program Files"\Java\jdk1.8.0_341\bin\
SAXON_HOME=C:\apps\Saxon\
FME_SERVER_URL=https://etl-acceptatie.gbo-provincies.nl/
REPOSITORY_LOCATION=D:\GitLab-Deployments\IMNa\FME\workspaces
PROJECT_FILE=D:\GitLab-Deployments\IMNa\FME\projects
XSLT_FILE=D:\GitLab-Deployments\IMNa\FME\xslts
PROPERTIES_FILE=D:/GitLab-Deployments/IMNa/FME/properties
PARAMETER_FILE_IMNa_HAB_Publish=IMNa_HAB_Publish_Acc.xml
PARAMETER_FILE_IMNa_VEG_Submission=IMNa_VEG_Submission_Acc.xml
PARAMETER_FILE_IMNa_RNN_TaxaPerBeheertype_Submission=IMNa_RNN_TaxaPerBeheertype_Submission_Acc.xml
PARAMETER_FILE_IMNa_NDFF_Rodelijstsoort_Submission=IMNa_NDFF_Rodelijstsoort_Submission_Acc.xml
PARAMETER_FILE_IMNa_VEG_Publish=IMNa_VEG_Publish_Acc.xml
PARAMETER_FILE_IMNa_VEG_Unpublish=IMNa_VEG_Unpublish_Acc.xml
PARAMETER_FILE_IMNa_SYNB_Submission=IMNa_SYNB_Submission_Acc.xml
PARAMETER_FILE_IMNa_N2000_Submission=IMNa_N2000_Submission_Acc.xml
PARAMETER_FILE_IMNa_HAB_Download=IMNa_HAB_Download_Acc.xml
PARAMETER_FILE_IMNa_NDFF_Species_Submission=IMNa_NDFF_Species_Submission_Acc.xml
PARAMETER_FILE_IMNa_NBP_Validation=IMNa_NBP_Validation_Acc.xml
PARAMETER_FILE_IMNa_VRN_Validation=IMNa_VRN_Validation_Acc.xml
PARAMETER_FILE_IMNa_VRN_Submission=IMNa_VRN_Submission_Acc.xml
PARAMETER_FILE_IMNa_NBP_Submission=IMNa_NBP_Submission_Acc.xml
PARAMETER_FILE_IMNa_NBP_UpdateDatamart=IMNa_NBP_UpdateDatamart_Acc.xml
PARAMETER_FILE_IMNa_NBP_CreateRVOFile=IMNa_NBP_CreateRVOFile_Acc.xml
PARAMETER_FILE_IMNa_VRN_UpdateDatamart=IMNa_VRN_UpdateDatamart_Acc.xml
PARAMETER_FILE_IMNa_VRN_CreateRVOFile=IMNa_VRN_CreateRVOFile_Acc.xml
PARAMETER_FILE_IMNa_DSO_Workitems_Submission=IMNa_DSO_Workitems_Submission_Acc.xml
PARAMETER_FILE_IMNa_BES_Validation=IMNa_BES_Validation_Acc.xml
PARAMETER_FILE_IMNa_BES_Submission=IMNa_BES_Submission_Acc.xml
PARAMETER_FILE_IMNa_BES_CreateRVOFile=IMNa_BES_CreateRVOFile_Acc.xml
PARAMETER_FILE_IMNa_BESI_Export_Submission=IMNa_BESI_Export_Submission_Acc.xml
PARAMETER_FILE_IMNa_BESI_Import_Submission=IMNa_BESI_Import_Submission_Acc.xml
PARAMETER_FILE_IMNa_IKN_WFS_Submission=IMNa_IKN_WFS_Submission_Acc.xml
PARAMETER_FILE_IMNa_IKN_WFS_Validation=IMNa_IKN_WFS_Validation_Acc.xml
PARAMETER_FILE_IMNa_IKN_N2K_Submission=IMNa_IKN_N2K_Submission_Acc.xml
PARAMETER_FILE_IMNa_RNN_GPKG_Submission=IMNa_RNN_GPKG_Submission_Acc.xml
PARAMETER_FILE_IMNa_IKN_FGDB_Submission=IMNa_IKN_FGDB_Submission_Acc.xml
PARAMETER_FILE_IMNa_IKN_FGDB_Validation=IMNa_IKN_FGDB_Validation_Acc.xml
PARAMETER_FILE_IMNa_BESI_Regelink_Submission=IMNa_BESI_Regelink_Submission_Acc.xml
PARAMETER_FILE_IMNa_HAB_T0_Submission=IMNa_HAB_T0_Submission_Acc.xml
PARAMETER_FILE_IMNa_HAB_Tx_Submission=IMNa_HAB_Tx_Submission_Acc.xml
PARAMETER_FILE_IMNa_HAB_Complete=IMNa_HAB_Complete_Acc.xml
PARAMETER_FILE_IMNa_IKN_End_Koppelvlak=IMNa_IKN_End_Koppelvlak_Acc.xml
