/* ---------------------------------------------------- */
/*  Generated by Enterprise Architect Version 12.1 		*/
/*  Created On : 13-dec-2019 15:58:11 				*/
/*  DBMS       : PostgreSQL 						*/
/* ---------------------------------------------------- */

CREATE SCHEMA imna
  AUTHORIZATION anlb;   
  
GRANT USAGE ON SCHEMA imna TO anlb_sqlpad;
  
/* Create Sequences */

CREATE SEQUENCE imna.imna_seq
    INCREMENT 1
    START 1
    MINVALUE 1
    MAXVALUE 9223372036854775807
    CACHE 1;

ALTER SEQUENCE imna.imna_seq
    OWNER TO anlb
;

/* Create Tables */

CREATE TABLE imna.ambitie_grootschaligenatuur
(
	ambitie_gebied_id bigint NOT NULL,    -- ID linking to  the internal id of  the ambition area
	beheer_type_id bigint NOT NULL,    -- Domain Id linking to the specific maintenance type of the large nature ambition area
	subsidiabel boolean NOT NULL    -- Specifies if the area can be subsidized
)
;

CREATE TABLE imna.ambitie_indicatieve_verhouding_beheer_typen_gr
(
	ambitie_gebied_id bigint NOT NULL,    -- ID linking to the large nature ambition area
	beheer_type_id bigint NOT NULL,    -- Domain Id linking to the specific maintenance type of a nature ambition area
	percentage integer NOT NULL    -- the percentage of the ambition area this maintenance type is relevant for
)
;

CREATE TABLE imna.ambitie_indicatieve_verhouding_beheer_typen_vr
(
	ambitie_gebied_id bigint NOT NULL,    -- ID linking to the to transform nature ambition area
	beheer_type_id bigint NOT NULL,    -- Domain Id linking to the specific maintenance type of a nature ambition area
	percentage integer NOT NULL    -- the percentage of the ambition area this maintenance type is relevant for
)
;

CREATE TABLE imna.ambitie_landschap
(
	ambitie_gebied_id bigint NOT NULL,    -- ID linking to  the internal id of  the ambition area
	beheer_type_id bigint NOT NULL,    -- Domain Id linking to the specific maintenance type of the landscape ambition area
	subsidiabel boolean NOT NULL    -- Specifies if the area can be subsidized
)
;

CREATE TABLE imna.ambitie_natuur
(
	ambitie_gebied_id bigint NOT NULL,    -- ID linking to  the internal id of  the ambition area
	beheer_type_id bigint NOT NULL,    -- Domain Id linking to the specific maintenance type of the nature ambition area
	subsidiabel boolean NOT NULL    -- Specifies if the area can be subsidized
)
;

CREATE TABLE imna.ambitie_omtevormennatuur
(
	ambitie_gebied_id bigint NOT NULL,    -- ID linking to  the internal id of  the ambition area
	beheer_type_id bigint NOT NULL,    -- Domain Id linking to the specific maintenance type of the to transform ambition area
	subsidiabel boolean NOT NULL    -- Specifies if the area can be subsidized
)
;

CREATE TABLE imna.ambitie_toegestane_beheer_pakketten_landschap
(
	ambitie_gebied_id bigint NOT NULL,    -- ID linking to landscape ambition area
	beheer_type_id bigint NOT NULL,    -- Maintenance type inherited from  the landscape ambition area. Together with maintenance packages refers to the link table that specifies the allowed maintenance packages for the maintenance type
	beheer_pakket_id bigint NOT NULL    -- Maintenance package for the landscape ambition area. Together with maintenance type refers to the link table that specifies the allowed maintenance packages for the maintenance type.
)
;

CREATE TABLE imna.ambitie_water
(
	ambitie_gebied_id bigint NOT NULL,    -- ID linking to  the internal id of  the ambition area
	beheer_type_id bigint NOT NULL,    -- Domain Id linking to the specific maintenance type of the water ambition area
	subsidiabel boolean NOT NULL    -- Specifies if the area can be subsidized
)
;

CREATE TABLE imna.beheer_agrarisch
(
	beheer_gebied_id bigint NOT NULL,    -- ID linking to  the internal id of  the maintenance area
	beheer_type_id bigint NOT NULL,    -- Domain Id linking to the specific maintenance type of the landscape area
	subsidiabel boolean NOT NULL    -- Specifies if the area can be subsidized
)
;

CREATE TABLE imna.beheer_gebied
(
	id bigint NOT NULL   DEFAULT NEXTVAL(('imna_seq'::text)::regclass),    -- Internal ID of the maintenance area
	identificatie char(100) NOT NULL,    -- External ID of the maintenance area
	begin_geldigheid timestamp NOT NULL,    -- Start of the validity for this version of the maintenance area
	eind_geldigheid timestamp,    -- End of the validity for this version of the maintenance area
	begin_tijd timestamp,    -- Start of the validity for this version of the maintenance area identified by the idenficatie and provinceId
	eind_tijd timestamp,    -- End of the validity for this version of the maintenance area identified by the idenficatie and provinceId
	nbp_id bigint,    -- Id linking to the Nature Maintenance Plan used to submit this version of the Maintenance area
	status_id bigint NOT NULL,    -- Domain Id linking to the status of the maintenance area
	provincie_id bigint NOT NULL,    -- Domain id linking to the province who is responsible for the maintenance area
	gebied_type_id bigint NOT NULL,    -- Domain id linking to the main type of the maintenance area. This will denote what detail table is attached to this maintenance area.
	geom geometry NOT NULL    -- Geometry single polygon in EPSG:28992 of the maintenance area
)
;

CREATE TABLE imna.beheer_gebied_ambitie
(
	id bigint NOT NULL   DEFAULT NEXTVAL(('imna_seq'::text)::regclass),    -- Internal ID of the ambition area
	identificatie varchar(100) NOT NULL,    -- External ID of the ambition area
	begin_geldigheid timestamp NOT NULL,    -- Start of the validity for this version of the ambition area
	eind_geldigheid timestamp,    -- End of the validity for this version of the ambition area
	begin_tijd timestamp,    -- Start of the validity for this version of the ambition area identified by the idenficatie and provinceId
	eind_tijd timestamp,    -- End of the validity for this version of the ambition area identified by the idenficatie and provinceId
	nbp_id bigint NOT NULL,    -- Id linking to the Nature Maintenance Plan used to submit this version of the ambition area
	status_id bigint NOT NULL,    -- Domain Id linking to the status of the ambition area.
	provincie_id bigint NOT NULL,    -- Domain id linking to the province who is responsible for the ambition area
	gebied_type_id bigint NOT NULL,    -- Domain id linking to the main type of the ambition area. This will denote what detail table is attached to this ambition area.
	status_ehs_id bigint,    -- Domain Id linking to the EHS status of the ambition area. EHS (Ecologische hoofd structuur) stands for main ecological structure.
	geom geometry NOT NULL    -- Geometry single polygon in EPSG:28992 of the ambition area
)
;

CREATE TABLE imna.beheer_gebied_to_ambities
(
	beheer_gebied_id bigint NOT NULL,    -- ID linking to the maintenance area
	ambitie_gebied_id bigint NOT NULL    -- ID linking to the ambition area
)
;

CREATE TABLE imna.beheer_grootschaligenatuur
(
	beheer_gebied_id bigint NOT NULL,    -- ID linking to  the internal id of  the maintenance area
	beheer_type_id bigint NOT NULL,    -- Domain Id linking to the main specific maintenance type of the large nature area
	subsidiabel boolean NOT NULL,    -- Specifies if the area can be subsidized
	openstellings_bijdrage_type_id bigint    -- Domain Id linking to the type of allowance that can be received to have the area opened to the public
)
;

CREATE TABLE imna.beheer_indicatieve_verhouding_beheer_typen
(
	beheer_gebied_id bigint NOT NULL,    -- ID linking to the large nature area
	beheer_type_id bigint NOT NULL,    -- Domain Id linking to the specific maintenance type of a nature area
	percentage integer NOT NULL    -- the percentage of the maintenance area this maintenance type is relevant for.
)
;

CREATE TABLE imna.beheer_landschap
(
	beheer_gebied_id bigint NOT NULL,    -- ID linking to  the internal id of  the maintenance area
	beheer_type_id bigint NOT NULL,    -- Domain Id linking to the specific maintenance type of the landscape area
	subsidiabel boolean NOT NULL    -- Specifies if the area can be subsidized
)
;

CREATE TABLE imna.beheer_natuur
(
	beheer_gebied_id bigint NOT NULL,    -- ID linking to  the internal id of  the maintenance area
	beheer_type_id bigint NOT NULL,    -- Domain Id linking to the specific maintenance type of the nature area
	subsidiabel boolean NOT NULL,    -- Specifies if the area can be subsidized
	openstellings_bijdrage_type_id bigint    -- Domain Id linking to the type of allowance that can be received to have the area opened to the public
)
;

CREATE TABLE imna.beheer_niet_subsidiabele_beheer_pakketten_agrarisch
(
	beheer_gebied_id bigint NOT NULL,
	beheer_type_id bigint NOT NULL,    -- Maintenance type inherited from  the agricultural area. Together with maintenance packages refers to the link table that specifies the allowed maintenance packages for the maintenance type.
	beheer_pakket_id bigint NOT NULL    -- Maintenance package for the agricultural area. Together with maintenance type refers to the link table that specifies the allowed maintenance packages for the maintenance type.
)
;

CREATE TABLE imna.beheer_niet_subsidiabele_beheer_pakketten_landschap
(
	beheer_gebied_id bigint NOT NULL,    -- ID linking to landscape area
	beheer_type_id bigint NOT NULL,    -- Maintenance type inherited from  the landscape area. Together with maintenance packages refers to the link table that specifies the allowed maintenance packages for the maintenance type
	beheer_pakket_id bigint NOT NULL    -- Maintenance package for the landscape area. Together with maintenance type refers to the link table that specifies the allowed maintenance packages for the maintenance type.
)
;

CREATE TABLE imna.beheer_toegestane_beheer_pakketten_agrarisch
(
	beheer_gebied_id bigint NOT NULL,    -- ID linking to agricultural area
	beheer_type_id bigint NOT NULL,    -- Maintenance type inherited from  the agricultural area. Together with maintenance packages refers to the link table that specifies the allowed maintenance packages for the maintenance type.
	beheer_pakket_id bigint NOT NULL    -- Maintenance package for the agricultural area. Together with maintenance type refers to the link table that specifies the allowed maintenance packages for the maintenance type.
)
;

CREATE TABLE imna.beheer_toegestane_beheer_pakketten_landschap
(
	beheer_gebied_id bigint NOT NULL,    -- ID linking to landscape area
	beheer_type_id bigint NOT NULL,    -- Maintenance type inherited from  the landscape area. Together with maintenance packages refers to the link table that specifies the allowed maintenance packages for the maintenance type
	beheer_pakket_id bigint NOT NULL    -- Maintenance package for the landscape area. Together with maintenance type refers to the link table that specifies the allowed maintenance packages for the maintenance type.
)
;

CREATE TABLE imna.beheer_water
(
	beheer_gebied_id bigint NOT NULL,    -- ID linking to  the internal id of  the maintenance area
	beheer_type_id bigint NOT NULL,    -- Domain Id linking to the specific maintenance type of the water area
	subsidiabel boolean NOT NULL    -- Specifies if the area can be subsidized
)
;

CREATE TABLE imna.bijzonder_gebied
(
	id bigint NOT NULL   DEFAULT NEXTVAL(('imna_seq'::text)::regclass),    -- Internal ID of the special area
	identificatie char(100) NOT NULL,    -- External ID of the special area
	begin_geldigheid timestamp NOT NULL,    -- Start of the validity for this version of the special area
	eind_geldigheid timestamp,    -- End of the validity for this version of the special area
	begin_tijd timestamp,    -- Start of the validity for this version of the special area identified by the idenficatie and provinceId
	eind_tijd timestamp,    -- End of the validity for this version of the special area identified by the idenficatie and provinceId
	nbp_id bigint NOT NULL,    -- Id linking to the Nature Maintenance Plan use to submit this version of the special area
	status_id bigint NOT NULL,    -- Domain Id linking to the status of the special area.
	provincie_id bigint NOT NULL,    -- Domain id linking to the province who is responsible for the special area
	geom geometry NOT NULL,    -- Geometry single polygon in EPSG:28992 of the special area
	gebieds_code_id bigint NOT NULL,    -- Domain id linking to the code of the special area
	gebieds_naam char(100)    -- name of the special area
)
;

CREATE TABLE imna.deel_gebied
(
	id bigint NOT NULL   DEFAULT NEXTVAL(('imna_seq'::text)::regclass),    -- Internal ID of the sub area
	identificatie char(100) NOT NULL,    -- External ID of the sub area
	begin_geldigheid timestamp NOT NULL,    -- Start of the validity for this version of the sub area
	eind_geldigheid timestamp,    -- End of the validity for this version of the sub area
	begin_tijd timestamp,    -- Start of the validity for this version of the sub area identified by the idenficatie and provinceId
	eind_tijd timestamp,    -- End of the validity for this version of the sub area identified by the idenficatie and provinceId
	nbp_id bigint NOT NULL,    -- Id linking to the Nature Maintenance Plan use to submit this version of the sub area
	status_id bigint NOT NULL,    -- Domain Id linking to the status of the sub area
	provincie_id bigint NOT NULL,    -- Domain id linking to the province who is responsible for the sub area
	geom geometry NOT NULL,    -- Geometry single polygon in EPSG:28992 of the sub area
	gebieds_naam char(100) NOT NULL,    -- name of the sub area
	beschrijving text    -- description of the maintenance done for this area
)
;

CREATE TABLE imna.natuur_beheer_plan
(
	id bigint NOT NULL   DEFAULT NEXTVAL(('imna_seq'::text)::regclass),    -- Internal ID of the plan
	identificatie char(100) NOT NULL,    -- External ID of the plan
	begin_geldigheid timestamp NOT NULL,    -- Start of the validity for this version of the plan
	eind_geldigheid timestamp,    -- End of the validity for this version of the plan
	status_id bigint NOT NULL,    -- Domain Id linking to the status of the plan. 
	provincie_id bigint NOT NULL,    -- Domain id linking to the province who submitted the plan
	datum_vaststelling timestamp,    -- Date when the plan was specified by the province
	plan_naam char(256) NOT NULL,    -- Name of the plan
	plan_eigenaar_id bigint NOT NULL,    -- Domain Id linking to the owner of the plan.
	plan_verwijzing text,    -- Description of the area this plan applies to. Normally this is the province border
	subsidie_jaar integer NOT NULL,    -- Year the plan applies to.
	beheer_gebied_status_id bigint NOT NULL,    -- Domain Id linking to the status of maintenance area layer of the plan
	beheer_gebied_ambitie_status_id bigint NOT NULL,    -- Domain Id linking to the status of maintenance ambition area layer of the plan
	bijzonder_gebied_status_id bigint NOT NULL,    -- Domain Id linking to the status of special area layer of the plan
	deel_gebied_status_id bigint NOT NULL,    -- Domain Id linking to the status of subarea layer of the plan
	zoek_gebied_landschap_status_id bigint NOT NULL,    -- Domain Id linking to the status of landscape search area layer of the plan
	zoek_gebied_agrarisch_status_id bigint NOT NULL,    -- Domain Id linking to the status of agricultural search area layer of the plan
	zoek_gebied_water_status_id bigint NOT NULL,    -- Domain Id linking to the status of water search area layer of the plan
	document_link char(2000) NOT NULL    -- FileName of the main document that has the detailed description of the plan. Will be used in the viewers to facilitate linking to this document in Drupal
)
;

CREATE TABLE imna.zoek_gebied_agrarisch
(
	id bigint NOT NULL   DEFAULT NEXTVAL(('imna_seq'::text)::regclass),    -- Internal ID of the agricultural search area
	identificatie char(100) NOT NULL,    -- External ID of the agricultural search area
	begin_geldigheid timestamp NOT NULL,    -- Start of the validity for this version of the agricultural search area
	eind_geldigheid timestamp,    -- End of the validity for this version of the agricultural search area
	begin_tijd timestamp,    -- Start of the validity for this version of the agricultural search area identified by the idenficatie and provinceId
	eind_tijd timestamp,    -- End of the validity for this version of the agricultural search area identified by the idenficatie and provinceId
	nbp_id bigint NOT NULL,    -- Id linking to the Nature Maintenance Plan use to submit this version of the agricultural search area
	status_id bigint NOT NULL,    -- Domain Id linking to the status of the agricultural search area
	provincie_id bigint NOT NULL,    --  Domain id linking to the province who is responsible for the agricultural search area
	deel_gebied_naam char(100),
	geom geometry NOT NULL,    -- Geometry single polygon in EPSG:28992 of the agricultural search area
	agrarisch_natuur_type_id bigint NOT NULL,    -- Domain id linking to the agricultural nature type of the agricultural search area
	naam char(100)    -- name of the agricultural search area
)
;

CREATE TABLE imna.zoek_gebied_landschap
(
	id bigint NOT NULL   DEFAULT NEXTVAL(('imna_seq'::text)::regclass),    -- Internal ID of the landscape search area
	identificatie char(100) NOT NULL,    -- External ID of the landscape search area
	begin_geldigheid timestamp NOT NULL,    -- Start of the validity for this version of the landscape search area
	eind_geldigheid timestamp,    -- End of the validity for this version of the landscape search area
	begin_tijd timestamp,    -- Start of the validity for this version of the landscape search area identified by the idenficatie and provinceId
	eind_tijd timestamp,    -- End of the validity for this version of the landscape search area identified by the idenficatie and provinceId
	nbp_id bigint NOT NULL,    -- Id linking to the Nature Maintenance Plan use to submit this version of the landscape search area
	status_id bigint NOT NULL,    -- Domain Id linking to the status of the landscape search area
	provincie_id bigint NOT NULL,    -- Domain id linking to the province who is responsible for the landscape search area
	geom geometry NOT NULL,    -- Geometry single polygon in EPSG:28992 of the landscape search area
	naam char(100)    -- name of the landscape search area
)
;

CREATE TABLE imna.zoek_gebied_niet_subsidiabele_beheer_pakketten_landschap
(
	zoek_gebied_landschap_id bigint NOT NULL,    -- ID linking to the landscape search area
	beheer_pakket_id bigint NOT NULL    -- Domain Id linking to the specific maintenance package of a nature area
)
;

CREATE TABLE imna.zoek_gebied_toegestane_beheer_functies_agrarisch
(
	zoek_gebied_agrarisch_id bigint NOT NULL,    -- ID linking to the agricultural search area
	agrarisch_natuur_type_id bigint NOT NULL,    -- Nature type inherited from  the agricultural search area. Together with maintenance function refers to the link table that specifies the allowed maintenance functions for the nature type
	beheer_functie_id bigint NOT NULL    -- Maintenance function for the agricultural search area. Together with nature type refers to the link table that specifies the allowed maintenance function for the nature type .
)
;

CREATE TABLE imna.zoek_gebied_toegestane_beheer_functies_water
(
	zoek_gebied_water_id bigint NOT NULL,    -- ID linking to the water search area
	water_natuur_type_id bigint NOT NULL,    -- Nature type inherited from  the water search area. Together with maintenance function refers to the link table that specifies the allowed maintenance functions for the nature type
	beheer_functie_id bigint NOT NULL    -- Maintenance function for the water search area. Together with nature type refers to the link table that specifies the allowed maintenance function for the nature type .
)
;

CREATE TABLE imna.zoek_gebied_toegestane_beheer_typen_agrarisch
(
	zoek_gebied_agrarisch_id bigint NOT NULL,    -- ID linking to the agricultural search area
	agrarisch_natuur_type_id bigint NOT NULL,    -- Nature type inherited from  the agricultural search area. Together with maintenance type refers to the link table that specifies the allowed maintenance types for the nature type
	beheer_type_id bigint NOT NULL    -- Maintenance type for the agricultural search area. Together with nature type refers to the link table that specifies the allowed maintenance type for the nature type
)
;

CREATE TABLE imna.zoek_gebied_toegestane_beheer_typen_landschap
(
	zoek_gebied_landschap_id bigint NOT NULL,    -- ID linking to the landscape search area
	beheer_type_id bigint NOT NULL    -- Domain Id linking to the specific maintenance type of a landscape area
)
;

CREATE TABLE imna.zoek_gebied_toegestane_beheer_typen_water
(
	zoek_gebied_water_id bigint NOT NULL,    -- ID linking to the water search area
	water_natuur_type_id bigint NOT NULL,    -- Nature type inherited from  the water search area. Together with maintenance type refers to the link table that specifies the allowed maintenance types for the nature type
	beheer_type_id bigint NOT NULL
)
;

CREATE TABLE imna.zoek_gebied_water
(
	id bigint NOT NULL   DEFAULT NEXTVAL(('imna_seq'::text)::regclass),    -- Internal ID of the water search area
	identificatie char(100) NOT NULL,    -- External ID of the water search area
	begin_geldigheid timestamp NOT NULL,    -- Start of the validity for this version of the water search area
	eind_geldigheid timestamp,    -- End of the validity for this version of the water search area
	begin_tijd timestamp,    -- Start of the validity for this version of the water search area identified by the idenficatie and provinceId
	eind_tijd timestamp,    -- End of the validity for this version of the water search area identified by the idenficatie and provinceId
	nbp_id bigint NOT NULL,    -- Id linking to the Nature Maintenance Plan use to submit this version of the water search area
	status_id bigint NOT NULL,    -- Domain Id linking to the status of the water search area
	provincie_id bigint NOT NULL,    -- Domain id linking to the province who is responsible for the water search area
	deel_gebied_naam char(100),
	geom geometry NOT NULL,    -- Geometry single polygon in EPSG:28992 of the water search area
	water_natuur_type_id bigint NOT NULL,    -- Domain id linking to the water nature type of the water search area
	naam char(100)    -- name of the water search area
)
;

/* Create Primary Keys, Indexes, Uniques, Checks */

ALTER TABLE imna.ambitie_grootschaligenatuur ADD CONSTRAINT PK_ambitie_grootschaligenatuur
	PRIMARY KEY (ambitie_gebied_id)
;

CREATE INDEX IXFK_beheer_gebied_ambitie1 ON imna.ambitie_grootschaligenatuur (ambitie_gebied_id ASC)
;

CREATE INDEX IXFK_dmn_beheer_type_grootschaligenatuur1 ON imna.ambitie_grootschaligenatuur (beheer_type_id ASC)
;

ALTER TABLE imna.ambitie_indicatieve_verhouding_beheer_typen_gr ADD CONSTRAINT PK_ambitie_indicatieve_verhouding_beheer_typen
	PRIMARY KEY (ambitie_gebied_id,beheer_type_id)
;

CREATE INDEX IXFK_ambitie_grootschaligenatuur1 ON imna.ambitie_indicatieve_verhouding_beheer_typen_gr (ambitie_gebied_id ASC)
;

CREATE INDEX IXFK_dmn_beheer_type_natuur_ambitie2 ON imna.ambitie_indicatieve_verhouding_beheer_typen_gr (beheer_type_id ASC)
;

ALTER TABLE imna.ambitie_indicatieve_verhouding_beheer_typen_vr ADD CONSTRAINT PK_ambitie_indicatieve_verhouding_beheer_typen_vr
	PRIMARY KEY (ambitie_gebied_id,beheer_type_id)
;

CREATE INDEX IXFK_ambitie_omtevormennatuur1 ON imna.ambitie_indicatieve_verhouding_beheer_typen_vr (ambitie_gebied_id ASC)
;

CREATE INDEX IXFK_dmn_beheer_type_natuur_ambitie3 ON imna.ambitie_indicatieve_verhouding_beheer_typen_vr (beheer_type_id ASC)
;

ALTER TABLE imna.ambitie_landschap ADD CONSTRAINT PK_ambitie_landschap
	PRIMARY KEY (ambitie_gebied_id)
;

ALTER TABLE imna.ambitie_landschap ADD CONSTRAINT UN_ambitie_landschap UNIQUE (ambitie_gebied_id,beheer_type_id)
;

CREATE INDEX IXFK_beheer_gebied_ambitie2 ON imna.ambitie_landschap (ambitie_gebied_id ASC)
;

CREATE INDEX IXFK_dmn_beheer_type_landschap1 ON imna.ambitie_landschap (beheer_type_id ASC)
;

ALTER TABLE imna.ambitie_natuur ADD CONSTRAINT PK_ambitie_natuur
	PRIMARY KEY (ambitie_gebied_id)
;

CREATE INDEX IXFK_beheer_gebied_ambitie3 ON imna.ambitie_natuur (ambitie_gebied_id ASC)
;

CREATE INDEX IXFK_dmn_beheer_type_natuur_ambitie1 ON imna.ambitie_natuur (beheer_type_id ASC)
;

ALTER TABLE imna.ambitie_omtevormennatuur ADD CONSTRAINT PK_ambitie_omtevormennatuur
	PRIMARY KEY (ambitie_gebied_id)
;

CREATE INDEX IXFK_beheer_gebied_ambitie4 ON imna.ambitie_omtevormennatuur (ambitie_gebied_id ASC)
;

CREATE INDEX IXFK_dmn_beheer_type_omtevormennatuur_ambitie1 ON imna.ambitie_omtevormennatuur (beheer_type_id ASC)
;

ALTER TABLE imna.ambitie_toegestane_beheer_pakketten_landschap ADD CONSTRAINT PK_ambitie_toegestane_beheer_pakketten_landschap
	PRIMARY KEY (ambitie_gebied_id,beheer_type_id,beheer_pakket_id)
;

CREATE INDEX IXFK_ambitie_landschap1 ON imna.ambitie_toegestane_beheer_pakketten_landschap (ambitie_gebied_id ASC,beheer_type_id ASC)
;

CREATE INDEX IXFK_lnk_table_beheerpakket3 ON imna.ambitie_toegestane_beheer_pakketten_landschap (beheer_type_id ASC,beheer_pakket_id ASC)
;

ALTER TABLE imna.ambitie_water ADD CONSTRAINT PK_ambitie_water
	PRIMARY KEY (ambitie_gebied_id)
;

CREATE INDEX IXFK_beheer_gebied_ambitie5 ON imna.ambitie_water (ambitie_gebied_id ASC)
;

CREATE INDEX IXFK_dmn_beheer_type_water1 ON imna.ambitie_water (beheer_type_id ASC)
;

ALTER TABLE imna.beheer_agrarisch ADD CONSTRAINT PK_beheer_agrarisch
	PRIMARY KEY (beheer_gebied_id)
;

ALTER TABLE imna.beheer_agrarisch ADD CONSTRAINT un_agrarisch UNIQUE (beheer_gebied_id,beheer_type_id)
;

CREATE INDEX IXFK_beheer_gebied1 ON imna.beheer_agrarisch (beheer_gebied_id ASC)
;

CREATE INDEX IXFK_dmn_beheer_type_agrarisch1 ON imna.beheer_agrarisch (beheer_type_id ASC)
;

ALTER TABLE imna.beheer_gebied ADD CONSTRAINT PK_beheergebied
	PRIMARY KEY (id)
;

ALTER TABLE imna.beheer_gebied ADD CONSTRAINT UN_gebied_identificatie UNIQUE (identificatie,begin_geldigheid,provincie_id)
;

CREATE INDEX IXFK_dmn_beheergebied_type1 ON imna.beheer_gebied (gebied_type_id ASC)
;

CREATE INDEX IXFK_dmn_provincie_code1 ON imna.beheer_gebied (provincie_id ASC)
;

CREATE INDEX IXFK_dmn_status_plan1 ON imna.beheer_gebied (status_id ASC)
;

CREATE INDEX IXFK_natuur_beheer_plan1 ON imna.beheer_gebied (nbp_id ASC)
;

ALTER TABLE imna.beheer_gebied_ambitie ADD CONSTRAINT PK_beheer_gebied_ambitie
	PRIMARY KEY (id)
;

ALTER TABLE imna.beheer_gebied_ambitie ADD CONSTRAINT UN_ambitie_identificatie UNIQUE (identificatie,begin_geldigheid,provincie_id)
;

CREATE INDEX IXFK_dmn_ambitiegebied_type1 ON imna.beheer_gebied_ambitie (gebied_type_id ASC)
;

CREATE INDEX IXFK_dmn_provincie_code2 ON imna.beheer_gebied_ambitie (provincie_id ASC)
;

CREATE INDEX IXFK_dmn_status_ehs1 ON imna.beheer_gebied_ambitie (status_ehs_id ASC)
;

CREATE INDEX IXFK_dmn_status_plan2 ON imna.beheer_gebied_ambitie (status_id ASC)
;

CREATE INDEX IXFK_natuur_beheer_plan2 ON imna.beheer_gebied_ambitie (nbp_id ASC)
;

ALTER TABLE imna.beheer_gebied_to_ambities ADD CONSTRAINT PK_beheer_gebied_to_ambities
	PRIMARY KEY (beheer_gebied_id,ambitie_gebied_id)
;

CREATE INDEX IXFK_beheer_gebied_ambitie6 ON imna.beheer_gebied_to_ambities (ambitie_gebied_id ASC)
;

CREATE INDEX IXFK_beheer_gebied2 ON imna.beheer_gebied_to_ambities (beheer_gebied_id ASC)
;

ALTER TABLE imna.beheer_grootschaligenatuur ADD CONSTRAINT PK_beheer_grootschalige_natuur
	PRIMARY KEY (beheer_gebied_id)
;

CREATE INDEX IXFK_dmn_beheer_type_grootschaligenatuur2 ON imna.beheer_grootschaligenatuur (beheer_type_id ASC)
;

CREATE INDEX IXFK_dmn_openstellings_bijdrage_type1 ON imna.beheer_grootschaligenatuur (openstellings_bijdrage_type_id ASC)
;

CREATE INDEX IXFK_natuur_beheer_gebied1 ON imna.beheer_grootschaligenatuur (beheer_gebied_id ASC)
;

ALTER TABLE imna.beheer_indicatieve_verhouding_beheer_typen ADD CONSTRAINT PK_beheer_indicatieve_verhouding_beheer_typen
	PRIMARY KEY (beheer_type_id,beheer_gebied_id)
;

CREATE INDEX IXFK_beheer_grootschaligenatuur1 ON imna.beheer_indicatieve_verhouding_beheer_typen (beheer_gebied_id ASC)
;

CREATE INDEX IXFK_dmn_beheer_type_natuur1 ON imna.beheer_indicatieve_verhouding_beheer_typen (beheer_type_id ASC)
;

ALTER TABLE imna.beheer_landschap ADD CONSTRAINT PK_beheer_landschap
	PRIMARY KEY (beheer_gebied_id)
;

ALTER TABLE imna.beheer_landschap ADD CONSTRAINT UN_landschap UNIQUE (beheer_gebied_id,beheer_type_id)
;

CREATE INDEX IXFK_beheer_gebied3 ON imna.beheer_landschap (beheer_gebied_id ASC)
;

CREATE INDEX IXFK_dmn_beheer_type_landschap2 ON imna.beheer_landschap (beheer_type_id ASC)
;

ALTER TABLE imna.beheer_natuur ADD CONSTRAINT PK_beheer_natuur
	PRIMARY KEY (beheer_gebied_id)
;

CREATE INDEX IXFK_beheer_gebied5 ON imna.beheer_natuur (beheer_gebied_id ASC)
;

CREATE INDEX IXFK_dmn_beheer_type_natuur2 ON imna.beheer_natuur (beheer_type_id ASC)
;

CREATE INDEX IXFK_dmn_openstellings_bijdrage_type2 ON imna.beheer_natuur (openstellings_bijdrage_type_id ASC)
;

ALTER TABLE imna.beheer_niet_subsidiabele_beheer_pakketten_agrarisch ADD CONSTRAINT PK_beheer_niet_subsidiabele_beheer_pakketten_agrarisch
	PRIMARY KEY (beheer_pakket_id,beheer_type_id,beheer_gebied_id)
;

CREATE INDEX IXFK_beheer_agrarisch1 ON imna.beheer_niet_subsidiabele_beheer_pakketten_agrarisch (beheer_gebied_id ASC,beheer_type_id ASC)
;

CREATE INDEX IXFK_lnk_table_beheerpakket4 ON imna.beheer_niet_subsidiabele_beheer_pakketten_agrarisch (beheer_type_id ASC,beheer_pakket_id ASC)
;

ALTER TABLE imna.beheer_niet_subsidiabele_beheer_pakketten_landschap ADD CONSTRAINT PK_beheer_niet_subsidiabele_beheer_pakketten_landschap
	PRIMARY KEY (beheer_type_id,beheer_gebied_id,beheer_pakket_id)
;

CREATE INDEX IXFK_beheer_landschap1 ON imna.beheer_niet_subsidiabele_beheer_pakketten_landschap (beheer_gebied_id ASC,beheer_type_id ASC)
;

CREATE INDEX IXFK_lnk_table_beheerpakket5 ON imna.beheer_niet_subsidiabele_beheer_pakketten_landschap (beheer_type_id ASC,beheer_pakket_id ASC)
;

ALTER TABLE imna.beheer_toegestane_beheer_pakketten_agrarisch ADD CONSTRAINT PK_beheer_toegestane_beheer_paktten_agrarisch
	PRIMARY KEY (beheer_type_id,beheer_pakket_id,beheer_gebied_id)
;

CREATE INDEX IXFK_beheer_agrarisch2 ON imna.beheer_toegestane_beheer_pakketten_agrarisch (beheer_gebied_id ASC,beheer_type_id ASC)
;

CREATE INDEX IXFK_lnk_table_beheerpakket6 ON imna.beheer_toegestane_beheer_pakketten_agrarisch (beheer_type_id ASC,beheer_pakket_id ASC)
;

ALTER TABLE imna.beheer_toegestane_beheer_pakketten_landschap ADD CONSTRAINT PK_beheer_toegestane_beheer_pakketten_landschap
	PRIMARY KEY (beheer_type_id,beheer_gebied_id,beheer_pakket_id)
;

CREATE INDEX IXFK_beheer_landschap2 ON imna.beheer_toegestane_beheer_pakketten_landschap (beheer_gebied_id ASC,beheer_type_id ASC)
;

CREATE INDEX IXFK_lnk_table_beheerpakket7 ON imna.beheer_toegestane_beheer_pakketten_landschap (beheer_type_id ASC,beheer_pakket_id ASC)
;

ALTER TABLE imna.beheer_water ADD CONSTRAINT PK_beheer_water
	PRIMARY KEY (beheer_gebied_id)
;

CREATE INDEX IXFK_beheer_gebied4 ON imna.beheer_water (beheer_gebied_id ASC)
;

CREATE INDEX IXFK_dmn_beheer_type_water2 ON imna.beheer_water (beheer_type_id ASC)
;

ALTER TABLE imna.bijzonder_gebied ADD CONSTRAINT PK_bijzonder_gebied
	PRIMARY KEY (id)
;

ALTER TABLE imna.bijzonder_gebied ADD CONSTRAINT UN_bijzonder_identificatie UNIQUE (identificatie,begin_geldigheid,provincie_id)
;

CREATE INDEX IXFK_dmn_bijzonder_gebied_code1 ON imna.bijzonder_gebied (gebieds_code_id ASC)
;

CREATE INDEX IXFK_dmn_provincie_code3 ON imna.bijzonder_gebied (provincie_id ASC)
;

CREATE INDEX IXFK_dmn_status_plan3 ON imna.bijzonder_gebied (status_id ASC)
;

CREATE INDEX IXFK_natuur_beheer_plan3 ON imna.bijzonder_gebied (nbp_id ASC)
;

ALTER TABLE imna.deel_gebied ADD CONSTRAINT PK_deel_gebied
	PRIMARY KEY (id)
;

ALTER TABLE imna.deel_gebied ADD CONSTRAINT UN_deel_identificatie UNIQUE (identificatie,begin_geldigheid,provincie_id)
;

CREATE INDEX IXFK_dmn_provincie_code4 ON imna.deel_gebied (provincie_id ASC)
;

CREATE INDEX IXFK_dmn_status_plan4 ON imna.deel_gebied (status_id ASC)
;

CREATE INDEX IXFK_natuur_beheer_plan4 ON imna.deel_gebied (nbp_id ASC)
;

ALTER TABLE imna.natuur_beheer_plan ADD CONSTRAINT PK_natuur_beheer_plan
	PRIMARY KEY (id)
;

ALTER TABLE imna.natuur_beheer_plan ADD CONSTRAINT UN_identifcatie UNIQUE (identificatie,begin_geldigheid,provincie_id)
;

CREATE INDEX IXFK_dmn_provincie_code_eigenaar1 ON imna.natuur_beheer_plan (plan_eigenaar_id ASC)
;

CREATE INDEX IXFK_dmn_provincie_code_prov1 ON imna.natuur_beheer_plan (provincie_id ASC)
;

CREATE INDEX IXFK_dmn_status_plan_ambitie1 ON imna.natuur_beheer_plan (beheer_gebied_ambitie_status_id ASC)
;

CREATE INDEX IXFK_dmn_status_plan_beheer_gebied1 ON imna.natuur_beheer_plan (beheer_gebied_status_id ASC)
;

CREATE INDEX IXFK_dmn_status_plan_bijzonder1 ON imna.natuur_beheer_plan (bijzonder_gebied_status_id ASC)
;

CREATE INDEX IXFK_dmn_status_plan_deel1 ON imna.natuur_beheer_plan (deel_gebied_status_id ASC)
;

CREATE INDEX IXFK_dmn_status_plan_plan1 ON imna.natuur_beheer_plan (status_id ASC)
;

CREATE INDEX IXFK_dmn_status_plan_z_agr1 ON imna.natuur_beheer_plan (zoek_gebied_agrarisch_status_id ASC)
;

CREATE INDEX IXFK_dmn_status_plan_z_land1 ON imna.natuur_beheer_plan (zoek_gebied_landschap_status_id ASC)
;

CREATE INDEX IXFK_dmn_status_plan_z_water1 ON imna.natuur_beheer_plan (zoek_gebied_water_status_id ASC)
;

ALTER TABLE imna.zoek_gebied_agrarisch ADD CONSTRAINT PK_zoek_gebied_agrarisch
	PRIMARY KEY (id)
;

ALTER TABLE imna.zoek_gebied_agrarisch ADD CONSTRAINT UN_zk_gbd_agr_identificatie UNIQUE (identificatie,begin_geldigheid,provincie_id)
;

ALTER TABLE imna.zoek_gebied_agrarisch ADD CONSTRAINT UN_zk_gbd_agr_natuurtype UNIQUE (id,agrarisch_natuur_type_id)
;

CREATE INDEX IXFK_dmn_natuur_type_agrarisch1 ON imna.zoek_gebied_agrarisch (agrarisch_natuur_type_id ASC)
;

CREATE INDEX IXFK_dmn_provincie_code5 ON imna.zoek_gebied_agrarisch (provincie_id ASC)
;

CREATE INDEX IXFK_dmn_status_plan5 ON imna.zoek_gebied_agrarisch (status_id ASC)
;

CREATE INDEX IXFK_natuur_beheer_plan5 ON imna.zoek_gebied_agrarisch (nbp_id ASC)
;

ALTER TABLE imna.zoek_gebied_landschap ADD CONSTRAINT PK_zoek_gebied_landschap
	PRIMARY KEY (id)
;

ALTER TABLE imna.zoek_gebied_landschap ADD CONSTRAINT UN_zk_gbd_lnd_identificatie UNIQUE (identificatie,begin_geldigheid,provincie_id)
;

CREATE INDEX IXFK_dmn_provincie_code6 ON imna.zoek_gebied_landschap (provincie_id ASC)
;

CREATE INDEX IXFK_dmn_status_plan6 ON imna.zoek_gebied_landschap (status_id ASC)
;

CREATE INDEX IXFK_natuur_beheer_plan6 ON imna.zoek_gebied_landschap (nbp_id ASC)
;

ALTER TABLE imna.zoek_gebied_niet_subsidiabele_beheer_pakketten_landschap ADD CONSTRAINT PK_zoek_gebied_niet_subsidiabele_beheer_pakketten_landschap
	PRIMARY KEY (zoek_gebied_landschap_id,beheer_pakket_id)
;

CREATE INDEX IXFK_beheer_pakket_landschap1 ON imna.zoek_gebied_niet_subsidiabele_beheer_pakketten_landschap (beheer_pakket_id ASC)
;

CREATE INDEX IXFK_zoek_gebied_landschap1 ON imna.zoek_gebied_niet_subsidiabele_beheer_pakketten_landschap (zoek_gebied_landschap_id ASC)
;

ALTER TABLE imna.zoek_gebied_toegestane_beheer_functies_agrarisch ADD CONSTRAINT PK_zoek_gebied_toegestane_beheer_functies_agrarisch
	PRIMARY KEY (zoek_gebied_agrarisch_id,agrarisch_natuur_type_id,beheer_functie_id)
;

CREATE INDEX IXFK_lnk_table_beheer_functies1 ON imna.zoek_gebied_toegestane_beheer_functies_agrarisch (agrarisch_natuur_type_id ASC,beheer_functie_id ASC)
;

CREATE INDEX IXFK_zoek_gebied_agrarisch2 ON imna.zoek_gebied_toegestane_beheer_functies_agrarisch (zoek_gebied_agrarisch_id ASC,agrarisch_natuur_type_id ASC)
;

ALTER TABLE imna.zoek_gebied_toegestane_beheer_functies_water ADD CONSTRAINT PK_zoek_gebied_toegestane_beheer_functies_water
	PRIMARY KEY (zoek_gebied_water_id,water_natuur_type_id,beheer_functie_id)
;

CREATE INDEX IXFK_lnk_table_beheer_functies2 ON imna.zoek_gebied_toegestane_beheer_functies_water (water_natuur_type_id ASC,beheer_functie_id ASC)
;

CREATE INDEX IXFK_zoek_gebied_water2 ON imna.zoek_gebied_toegestane_beheer_functies_water (zoek_gebied_water_id ASC,water_natuur_type_id ASC)
;

ALTER TABLE imna.zoek_gebied_toegestane_beheer_typen_agrarisch ADD CONSTRAINT PK_zoek_gebied_toegestane_beheer_typen_agrarisch
	PRIMARY KEY (zoek_gebied_agrarisch_id,agrarisch_natuur_type_id,beheer_type_id)
;

CREATE INDEX IXFK_lnk_table_beheer_typen1 ON imna.zoek_gebied_toegestane_beheer_typen_agrarisch (agrarisch_natuur_type_id ASC,beheer_type_id ASC)
;

CREATE INDEX IXFK_zoek_gebied_agrarisch3 ON imna.zoek_gebied_toegestane_beheer_typen_agrarisch (zoek_gebied_agrarisch_id ASC,agrarisch_natuur_type_id ASC)
;

ALTER TABLE imna.zoek_gebied_toegestane_beheer_typen_landschap ADD CONSTRAINT PK_zoek_gebied_toegestane_beheer_typen_landschap
	PRIMARY KEY (zoek_gebied_landschap_id,beheer_type_id)
;

CREATE INDEX IXFK_dmn_beheer_type_landschap3 ON imna.zoek_gebied_toegestane_beheer_typen_landschap (beheer_type_id ASC)
;

CREATE INDEX IXFK_zoek_gebied_landschap2 ON imna.zoek_gebied_toegestane_beheer_typen_landschap (zoek_gebied_landschap_id ASC)
;

ALTER TABLE imna.zoek_gebied_toegestane_beheer_typen_water ADD CONSTRAINT PK_zoek_gebied_toegestane_beheer_typen_water
	PRIMARY KEY (zoek_gebied_water_id,water_natuur_type_id,beheer_type_id)
;

CREATE INDEX IXFK_lnk_table_beheer_typen2 ON imna.zoek_gebied_toegestane_beheer_typen_water (water_natuur_type_id ASC,beheer_type_id ASC)
;

CREATE INDEX IXFK_zoek_gebied_water3 ON imna.zoek_gebied_toegestane_beheer_typen_water (zoek_gebied_water_id ASC,water_natuur_type_id ASC)
;

ALTER TABLE imna.zoek_gebied_water ADD CONSTRAINT PK_zoek_gebied_water
	PRIMARY KEY (id)
;

ALTER TABLE imna.zoek_gebied_water ADD CONSTRAINT UN_zk_gbd_water_identificatie UNIQUE (identificatie,begin_geldigheid,provincie_id)
;

ALTER TABLE imna.zoek_gebied_water ADD CONSTRAINT UN_zk_gbd_water_watertype UNIQUE (id,water_natuur_type_id)
;

CREATE INDEX IXFK_dmn_natuur_type_water1 ON imna.zoek_gebied_water (water_natuur_type_id ASC)
;

CREATE INDEX IXFK_dmn_provincie_code7 ON imna.zoek_gebied_water (provincie_id ASC)
;

CREATE INDEX IXFK_dmn_status_plan7 ON imna.zoek_gebied_water (status_id ASC)
;

CREATE INDEX IXFK_natuur_beheer_plan7 ON imna.zoek_gebied_water (nbp_id ASC)
;

/* Create Foreign Key Constraints */

ALTER TABLE imna.ambitie_grootschaligenatuur ADD CONSTRAINT FK_beheer_gebied_ambitie1
	FOREIGN KEY (ambitie_gebied_id) REFERENCES imna.beheer_gebied_ambitie (id) ON DELETE No Action ON UPDATE No Action
;

ALTER TABLE imna.ambitie_grootschaligenatuur ADD CONSTRAINT FK_dmn_beheer_type_grootschaligenatuur1
	FOREIGN KEY (beheer_type_id) REFERENCES masterdata.dmn_beheer_type_grootschaligenatuur (id) ON DELETE No Action ON UPDATE No Action
;

ALTER TABLE imna.ambitie_indicatieve_verhouding_beheer_typen_gr ADD CONSTRAINT FK_ambitie_grootschaligenatuur1
	FOREIGN KEY (ambitie_gebied_id) REFERENCES imna.ambitie_grootschaligenatuur (ambitie_gebied_id) ON DELETE No Action ON UPDATE No Action
;

ALTER TABLE imna.ambitie_indicatieve_verhouding_beheer_typen_gr ADD CONSTRAINT FK_dmn_beheer_type_natuur_ambitie2
	FOREIGN KEY (beheer_type_id) REFERENCES masterdata.dmn_beheer_type_natuur_ambitie (id) ON DELETE No Action ON UPDATE No Action
;

ALTER TABLE imna.ambitie_indicatieve_verhouding_beheer_typen_vr ADD CONSTRAINT FK_ambitie_omtevormennatuur1
	FOREIGN KEY (ambitie_gebied_id) REFERENCES imna.ambitie_omtevormennatuur (ambitie_gebied_id) ON DELETE No Action ON UPDATE No Action
;

ALTER TABLE imna.ambitie_indicatieve_verhouding_beheer_typen_vr ADD CONSTRAINT FK_dmn_beheer_type_natuur_ambitie3
	FOREIGN KEY (beheer_type_id) REFERENCES masterdata.dmn_beheer_type_natuur_ambitie (id) ON DELETE No Action ON UPDATE No Action
;

ALTER TABLE imna.ambitie_landschap ADD CONSTRAINT FK_beheer_gebied_ambitie2
	FOREIGN KEY (ambitie_gebied_id) REFERENCES imna.beheer_gebied_ambitie (id) ON DELETE No Action ON UPDATE No Action
;

ALTER TABLE imna.ambitie_landschap ADD CONSTRAINT FK_dmn_beheer_type_landschap1
	FOREIGN KEY (beheer_type_id) REFERENCES masterdata.dmn_beheer_type_landschap (id) ON DELETE No Action ON UPDATE No Action
;

ALTER TABLE imna.ambitie_natuur ADD CONSTRAINT FK_beheer_gebied_ambitie3
	FOREIGN KEY (ambitie_gebied_id) REFERENCES imna.beheer_gebied_ambitie (id) ON DELETE No Action ON UPDATE No Action
;

ALTER TABLE imna.ambitie_natuur ADD CONSTRAINT FK_dmn_beheer_type_natuur_ambitie1
	FOREIGN KEY (beheer_type_id) REFERENCES masterdata.dmn_beheer_type_natuur_ambitie (id) ON DELETE No Action ON UPDATE No Action
;

ALTER TABLE imna.ambitie_omtevormennatuur ADD CONSTRAINT FK_beheer_gebied_ambitie4
	FOREIGN KEY (ambitie_gebied_id) REFERENCES imna.beheer_gebied_ambitie (id) ON DELETE No Action ON UPDATE No Action
;

ALTER TABLE imna.ambitie_omtevormennatuur ADD CONSTRAINT FK_dmn_beheer_type_omtevormennatuur_ambitie1
	FOREIGN KEY (beheer_type_id) REFERENCES masterdata.dmn_beheer_type_omtevormennatuur_ambitie (id) ON DELETE No Action ON UPDATE No Action
;

ALTER TABLE imna.ambitie_toegestane_beheer_pakketten_landschap ADD CONSTRAINT FK_ambitie_landschap1
	FOREIGN KEY (ambitie_gebied_id,beheer_type_id) REFERENCES imna.ambitie_landschap (ambitie_gebied_id,beheer_type_id) ON DELETE No Action ON UPDATE No Action
;

ALTER TABLE imna.ambitie_toegestane_beheer_pakketten_landschap ADD CONSTRAINT FK_lnk_table_beheerpakket3
	FOREIGN KEY (beheer_type_id,beheer_pakket_id) REFERENCES masterdata.lnk_table_beheerpakket (beheer_type_id,beheer_pakket_id) ON DELETE No Action ON UPDATE No Action
;

ALTER TABLE imna.ambitie_water ADD CONSTRAINT FK_beheer_gebied_ambitie5
	FOREIGN KEY (ambitie_gebied_id) REFERENCES imna.beheer_gebied_ambitie (id) ON DELETE No Action ON UPDATE No Action
;

ALTER TABLE imna.ambitie_water ADD CONSTRAINT FK_dmn_beheer_type_water1
	FOREIGN KEY (beheer_type_id) REFERENCES masterdata.dmn_beheer_type_water (id) ON DELETE No Action ON UPDATE No Action
;

ALTER TABLE imna.beheer_agrarisch ADD CONSTRAINT FK_beheer_gebied1
	FOREIGN KEY (beheer_gebied_id) REFERENCES imna.beheer_gebied (id) ON DELETE No Action ON UPDATE No Action
;

ALTER TABLE imna.beheer_agrarisch ADD CONSTRAINT FK_dmn_beheer_type_agrarisch1
	FOREIGN KEY (beheer_type_id) REFERENCES masterdata.dmn_beheer_type_agrarisch (id) ON DELETE No Action ON UPDATE No Action
;

ALTER TABLE imna.beheer_gebied ADD CONSTRAINT FK_dmn_beheergebied_type1
	FOREIGN KEY (gebied_type_id) REFERENCES masterdata.dmn_beheergebied_type (id) ON DELETE No Action ON UPDATE No Action
;

ALTER TABLE imna.beheer_gebied ADD CONSTRAINT FK_dmn_provincie_code1
	FOREIGN KEY (provincie_id) REFERENCES masterdata.dmn_provincie_code (id) ON DELETE No Action ON UPDATE No Action
;

ALTER TABLE imna.beheer_gebied ADD CONSTRAINT FK_dmn_status_plan1
	FOREIGN KEY (status_id) REFERENCES masterdata.dmn_status_plan (id) ON DELETE No Action ON UPDATE No Action
;

ALTER TABLE imna.beheer_gebied ADD CONSTRAINT FK_natuur_beheer_plan1
	FOREIGN KEY (nbp_id) REFERENCES imna.natuur_beheer_plan (id) ON DELETE No Action ON UPDATE No Action
;

ALTER TABLE imna.beheer_gebied_ambitie ADD CONSTRAINT FK_dmn_ambitiegebied_type1
	FOREIGN KEY (gebied_type_id) REFERENCES masterdata.dmn_ambitiegebied_type (id) ON DELETE No Action ON UPDATE No Action
;

ALTER TABLE imna.beheer_gebied_ambitie ADD CONSTRAINT FK_dmn_provincie_code2
	FOREIGN KEY (provincie_id) REFERENCES masterdata.dmn_provincie_code (id) ON DELETE No Action ON UPDATE No Action
;

ALTER TABLE imna.beheer_gebied_ambitie ADD CONSTRAINT FK_dmn_status_ehs1
	FOREIGN KEY (status_ehs_id) REFERENCES masterdata.dmn_status_ehs (id) ON DELETE No Action ON UPDATE No Action
;

ALTER TABLE imna.beheer_gebied_ambitie ADD CONSTRAINT FK_dmn_status_plan2
	FOREIGN KEY (status_id) REFERENCES masterdata.dmn_status_plan (id) ON DELETE No Action ON UPDATE No Action
;

ALTER TABLE imna.beheer_gebied_ambitie ADD CONSTRAINT FK_natuur_beheer_plan2
	FOREIGN KEY (nbp_id) REFERENCES imna.natuur_beheer_plan (id) ON DELETE No Action ON UPDATE No Action
;

ALTER TABLE imna.beheer_gebied_to_ambities ADD CONSTRAINT FK_beheer_gebied_ambitie6
	FOREIGN KEY (ambitie_gebied_id) REFERENCES imna.beheer_gebied_ambitie (id) ON DELETE No Action ON UPDATE No Action
;

ALTER TABLE imna.beheer_gebied_to_ambities ADD CONSTRAINT FK_beheer_gebied2
	FOREIGN KEY (beheer_gebied_id) REFERENCES imna.beheer_gebied (id) ON DELETE No Action ON UPDATE No Action
;

ALTER TABLE imna.beheer_grootschaligenatuur ADD CONSTRAINT FK_dmn_beheer_type_grootschaligenatuur2
	FOREIGN KEY (beheer_type_id) REFERENCES masterdata.dmn_beheer_type_grootschaligenatuur (id) ON DELETE No Action ON UPDATE No Action
;

ALTER TABLE imna.beheer_grootschaligenatuur ADD CONSTRAINT FK_dmn_openstellings_bijdrage_type1
	FOREIGN KEY (openstellings_bijdrage_type_id) REFERENCES masterdata.dmn_openstellings_bijdrage_type (id) ON DELETE No Action ON UPDATE No Action
;

ALTER TABLE imna.beheer_grootschaligenatuur ADD CONSTRAINT FK_natuur_beheer_gebied1
	FOREIGN KEY (beheer_gebied_id) REFERENCES imna.beheer_gebied (id) ON DELETE No Action ON UPDATE No Action
;

ALTER TABLE imna.beheer_indicatieve_verhouding_beheer_typen ADD CONSTRAINT FK_beheer_grootschaligenatuur1
	FOREIGN KEY (beheer_gebied_id) REFERENCES imna.beheer_grootschaligenatuur (beheer_gebied_id) ON DELETE No Action ON UPDATE No Action
;

ALTER TABLE imna.beheer_indicatieve_verhouding_beheer_typen ADD CONSTRAINT FK_dmn_beheer_type_natuur1
	FOREIGN KEY (beheer_type_id) REFERENCES masterdata.dmn_beheer_type_natuur (id) ON DELETE No Action ON UPDATE No Action
;

ALTER TABLE imna.beheer_landschap ADD CONSTRAINT FK_beheer_gebied3
	FOREIGN KEY (beheer_gebied_id) REFERENCES imna.beheer_gebied (id) ON DELETE No Action ON UPDATE No Action
;

ALTER TABLE imna.beheer_landschap ADD CONSTRAINT FK_dmn_beheer_type_landschap2
	FOREIGN KEY (beheer_type_id) REFERENCES masterdata.dmn_beheer_type_landschap (id) ON DELETE No Action ON UPDATE No Action
;

ALTER TABLE imna.beheer_natuur ADD CONSTRAINT FK_beheer_gebied5
	FOREIGN KEY (beheer_gebied_id) REFERENCES imna.beheer_gebied (id) ON DELETE No Action ON UPDATE No Action
;

ALTER TABLE imna.beheer_natuur ADD CONSTRAINT FK_dmn_beheer_type_natuur2
	FOREIGN KEY (beheer_type_id) REFERENCES masterdata.dmn_beheer_type_natuur (id) ON DELETE No Action ON UPDATE No Action
;

ALTER TABLE imna.beheer_natuur ADD CONSTRAINT FK_dmn_openstellings_bijdrage_type2
	FOREIGN KEY (openstellings_bijdrage_type_id) REFERENCES masterdata.dmn_openstellings_bijdrage_type (id) ON DELETE No Action ON UPDATE No Action
;

ALTER TABLE imna.beheer_niet_subsidiabele_beheer_pakketten_agrarisch ADD CONSTRAINT FK_beheer_agrarisch1
	FOREIGN KEY (beheer_gebied_id,beheer_type_id) REFERENCES imna.beheer_agrarisch (beheer_gebied_id,beheer_type_id) ON DELETE No Action ON UPDATE No Action
;

ALTER TABLE imna.beheer_niet_subsidiabele_beheer_pakketten_agrarisch ADD CONSTRAINT FK_lnk_table_beheerpakket4
	FOREIGN KEY (beheer_type_id,beheer_pakket_id) REFERENCES masterdata.lnk_table_beheerpakket (beheer_type_id,beheer_pakket_id) ON DELETE No Action ON UPDATE No Action
;

ALTER TABLE imna.beheer_niet_subsidiabele_beheer_pakketten_landschap ADD CONSTRAINT FK_beheer_landschap1
	FOREIGN KEY (beheer_gebied_id,beheer_type_id) REFERENCES imna.beheer_landschap (beheer_gebied_id,beheer_type_id) ON DELETE No Action ON UPDATE No Action
;

ALTER TABLE imna.beheer_niet_subsidiabele_beheer_pakketten_landschap ADD CONSTRAINT FK_lnk_table_beheerpakket5
	FOREIGN KEY (beheer_type_id,beheer_pakket_id) REFERENCES masterdata.lnk_table_beheerpakket (beheer_type_id,beheer_pakket_id) ON DELETE No Action ON UPDATE No Action
;

ALTER TABLE imna.beheer_toegestane_beheer_pakketten_agrarisch ADD CONSTRAINT FK_beheer_agrarisch2
	FOREIGN KEY (beheer_gebied_id,beheer_type_id) REFERENCES imna.beheer_agrarisch (beheer_gebied_id,beheer_type_id) ON DELETE No Action ON UPDATE No Action
;

ALTER TABLE imna.beheer_toegestane_beheer_pakketten_agrarisch ADD CONSTRAINT FK_lnk_table_beheerpakket6
	FOREIGN KEY (beheer_type_id,beheer_pakket_id) REFERENCES masterdata.lnk_table_beheerpakket (beheer_type_id,beheer_pakket_id) ON DELETE No Action ON UPDATE No Action
;

ALTER TABLE imna.beheer_toegestane_beheer_pakketten_landschap ADD CONSTRAINT FK_beheer_landschap2
	FOREIGN KEY (beheer_gebied_id,beheer_type_id) REFERENCES imna.beheer_landschap (beheer_gebied_id,beheer_type_id) ON DELETE No Action ON UPDATE No Action
;

ALTER TABLE imna.beheer_toegestane_beheer_pakketten_landschap ADD CONSTRAINT FK_lnk_table_beheerpakket7
	FOREIGN KEY (beheer_type_id,beheer_pakket_id) REFERENCES masterdata.lnk_table_beheerpakket (beheer_type_id,beheer_pakket_id) ON DELETE No Action ON UPDATE No Action
;

ALTER TABLE imna.beheer_water ADD CONSTRAINT FK_beheer_gebied4
	FOREIGN KEY (beheer_gebied_id) REFERENCES imna.beheer_gebied (id) ON DELETE No Action ON UPDATE No Action
;

ALTER TABLE imna.beheer_water ADD CONSTRAINT FK_dmn_beheer_type_water2
	FOREIGN KEY (beheer_type_id) REFERENCES masterdata.dmn_beheer_type_water (id) ON DELETE No Action ON UPDATE No Action
;

ALTER TABLE imna.bijzonder_gebied ADD CONSTRAINT FK_dmn_bijzonder_gebied_code1
	FOREIGN KEY (gebieds_code_id) REFERENCES masterdata.dmn_bijzonder_gebied_code (id) ON DELETE No Action ON UPDATE No Action
;

ALTER TABLE imna.bijzonder_gebied ADD CONSTRAINT FK_dmn_provincie_code3
	FOREIGN KEY (provincie_id) REFERENCES masterdata.dmn_provincie_code (id) ON DELETE No Action ON UPDATE No Action
;

ALTER TABLE imna.bijzonder_gebied ADD CONSTRAINT FK_dmn_status_plan3
	FOREIGN KEY (status_id) REFERENCES masterdata.dmn_status_plan (id) ON DELETE No Action ON UPDATE No Action
;

ALTER TABLE imna.bijzonder_gebied ADD CONSTRAINT FK_natuur_beheer_plan3
	FOREIGN KEY (nbp_id) REFERENCES imna.natuur_beheer_plan (id) ON DELETE No Action ON UPDATE No Action
;

ALTER TABLE imna.deel_gebied ADD CONSTRAINT FK_dmn_provincie_code4
	FOREIGN KEY (provincie_id) REFERENCES masterdata.dmn_provincie_code (id) ON DELETE No Action ON UPDATE No Action
;

ALTER TABLE imna.deel_gebied ADD CONSTRAINT FK_dmn_status_plan4
	FOREIGN KEY (status_id) REFERENCES masterdata.dmn_status_plan (id) ON DELETE No Action ON UPDATE No Action
;

ALTER TABLE imna.deel_gebied ADD CONSTRAINT FK_natuur_beheer_plan4
	FOREIGN KEY (nbp_id) REFERENCES imna.natuur_beheer_plan (id) ON DELETE No Action ON UPDATE No Action
;

ALTER TABLE imna.natuur_beheer_plan ADD CONSTRAINT FK_dmn_provincie_code_eigenaar1
	FOREIGN KEY (plan_eigenaar_id) REFERENCES masterdata.dmn_provincie_code (id) ON DELETE No Action ON UPDATE No Action
;

ALTER TABLE imna.natuur_beheer_plan ADD CONSTRAINT FK_dmn_provincie_code_prov1
	FOREIGN KEY (provincie_id) REFERENCES masterdata.dmn_provincie_code (id) ON DELETE No Action ON UPDATE No Action
;

ALTER TABLE imna.natuur_beheer_plan ADD CONSTRAINT FK_dmn_status_plan_ambitie1
	FOREIGN KEY (beheer_gebied_ambitie_status_id) REFERENCES masterdata.dmn_status_plan (id) ON DELETE No Action ON UPDATE No Action
;

ALTER TABLE imna.natuur_beheer_plan ADD CONSTRAINT FK_dmn_status_plan_beheer_gebied1
	FOREIGN KEY (beheer_gebied_status_id) REFERENCES masterdata.dmn_status_plan (id) ON DELETE No Action ON UPDATE No Action
;

ALTER TABLE imna.natuur_beheer_plan ADD CONSTRAINT FK_dmn_status_plan_bijzonder1
	FOREIGN KEY (bijzonder_gebied_status_id) REFERENCES masterdata.dmn_status_plan (id) ON DELETE No Action ON UPDATE No Action
;

ALTER TABLE imna.natuur_beheer_plan ADD CONSTRAINT FK_dmn_status_plan_deel1
	FOREIGN KEY (deel_gebied_status_id) REFERENCES masterdata.dmn_status_plan (id) ON DELETE No Action ON UPDATE No Action
;

ALTER TABLE imna.natuur_beheer_plan ADD CONSTRAINT FK_dmn_status_plan_plan1
	FOREIGN KEY (status_id) REFERENCES masterdata.dmn_status_plan (id) ON DELETE No Action ON UPDATE No Action
;

ALTER TABLE imna.natuur_beheer_plan ADD CONSTRAINT FK_dmn_status_plan_z_agr1
	FOREIGN KEY (zoek_gebied_agrarisch_status_id) REFERENCES masterdata.dmn_status_plan (id) ON DELETE No Action ON UPDATE No Action
;

ALTER TABLE imna.natuur_beheer_plan ADD CONSTRAINT FK_dmn_status_plan_z_land1
	FOREIGN KEY (zoek_gebied_landschap_status_id) REFERENCES masterdata.dmn_status_plan (id) ON DELETE No Action ON UPDATE No Action
;

ALTER TABLE imna.natuur_beheer_plan ADD CONSTRAINT FK_dmn_status_plan_z_water1
	FOREIGN KEY (zoek_gebied_water_status_id) REFERENCES masterdata.dmn_status_plan (id) ON DELETE No Action ON UPDATE No Action
;

ALTER TABLE imna.zoek_gebied_agrarisch ADD CONSTRAINT FK_dmn_natuur_type_agrarisch1
	FOREIGN KEY (agrarisch_natuur_type_id) REFERENCES masterdata.dmn_natuur_type_agrarisch (id) ON DELETE No Action ON UPDATE No Action
;

ALTER TABLE imna.zoek_gebied_agrarisch ADD CONSTRAINT FK_dmn_provincie_code5
	FOREIGN KEY (provincie_id) REFERENCES masterdata.dmn_provincie_code (id) ON DELETE No Action ON UPDATE No Action
;

ALTER TABLE imna.zoek_gebied_agrarisch ADD CONSTRAINT FK_dmn_status_plan5
	FOREIGN KEY (status_id) REFERENCES masterdata.dmn_status_plan (id) ON DELETE No Action ON UPDATE No Action
;

ALTER TABLE imna.zoek_gebied_agrarisch ADD CONSTRAINT FK_natuur_beheer_plan5
	FOREIGN KEY (nbp_id) REFERENCES imna.natuur_beheer_plan (id) ON DELETE No Action ON UPDATE No Action
;

ALTER TABLE imna.zoek_gebied_landschap ADD CONSTRAINT FK_dmn_provincie_code6
	FOREIGN KEY (provincie_id) REFERENCES masterdata.dmn_provincie_code (id) ON DELETE No Action ON UPDATE No Action
;

ALTER TABLE imna.zoek_gebied_landschap ADD CONSTRAINT FK_dmn_status_plan6
	FOREIGN KEY (status_id) REFERENCES masterdata.dmn_status_plan (id) ON DELETE No Action ON UPDATE No Action
;

ALTER TABLE imna.zoek_gebied_landschap ADD CONSTRAINT FK_natuur_beheer_plan6
	FOREIGN KEY (nbp_id) REFERENCES imna.natuur_beheer_plan (id) ON DELETE No Action ON UPDATE No Action
;

ALTER TABLE imna.zoek_gebied_niet_subsidiabele_beheer_pakketten_landschap ADD CONSTRAINT FK_beheer_pakket_landschap1
	FOREIGN KEY (beheer_pakket_id) REFERENCES masterdata.dmn_beheer_pakket_landschap (id) ON DELETE No Action ON UPDATE No Action
;

ALTER TABLE imna.zoek_gebied_niet_subsidiabele_beheer_pakketten_landschap ADD CONSTRAINT FK_zoek_gebied_landschap1
	FOREIGN KEY (zoek_gebied_landschap_id) REFERENCES imna.zoek_gebied_landschap (id) ON DELETE No Action ON UPDATE No Action
;

ALTER TABLE imna.zoek_gebied_toegestane_beheer_functies_agrarisch ADD CONSTRAINT FK_lnk_table_beheer_functies1
	FOREIGN KEY (agrarisch_natuur_type_id,beheer_functie_id) REFERENCES masterdata.lnk_table_beheer_functies (natuur_type_id,beheer_functie_id) ON DELETE No Action ON UPDATE No Action
;

ALTER TABLE imna.zoek_gebied_toegestane_beheer_functies_agrarisch ADD CONSTRAINT FK_zoek_gebied_agrarisch2
	FOREIGN KEY (zoek_gebied_agrarisch_id,agrarisch_natuur_type_id) REFERENCES imna.zoek_gebied_agrarisch (id,agrarisch_natuur_type_id) ON DELETE No Action ON UPDATE No Action
;

ALTER TABLE imna.zoek_gebied_toegestane_beheer_functies_water ADD CONSTRAINT FK_lnk_table_beheer_functies2
	FOREIGN KEY (water_natuur_type_id,beheer_functie_id) REFERENCES masterdata.lnk_table_beheer_functies (natuur_type_id,beheer_functie_id) ON DELETE No Action ON UPDATE No Action
;

ALTER TABLE imna.zoek_gebied_toegestane_beheer_functies_water ADD CONSTRAINT FK_zoek_gebied_water2
	FOREIGN KEY (zoek_gebied_water_id,water_natuur_type_id) REFERENCES imna.zoek_gebied_water (id,water_natuur_type_id) ON DELETE No Action ON UPDATE No Action
;

ALTER TABLE imna.zoek_gebied_toegestane_beheer_typen_agrarisch ADD CONSTRAINT FK_lnk_table_beheer_typen1
	FOREIGN KEY (agrarisch_natuur_type_id,beheer_type_id) REFERENCES masterdata.lnk_table_beheer_typen (natuur_type_id,beheer_type_id) ON DELETE No Action ON UPDATE No Action
;

ALTER TABLE imna.zoek_gebied_toegestane_beheer_typen_agrarisch ADD CONSTRAINT FK_zoek_gebied_agrarisch3
	FOREIGN KEY (zoek_gebied_agrarisch_id,agrarisch_natuur_type_id) REFERENCES imna.zoek_gebied_agrarisch (id,agrarisch_natuur_type_id) ON DELETE No Action ON UPDATE No Action
;

ALTER TABLE imna.zoek_gebied_toegestane_beheer_typen_landschap ADD CONSTRAINT FK_dmn_beheer_type_landschap3
	FOREIGN KEY (beheer_type_id) REFERENCES masterdata.dmn_beheer_type_landschap (id) ON DELETE No Action ON UPDATE No Action
;

ALTER TABLE imna.zoek_gebied_toegestane_beheer_typen_landschap ADD CONSTRAINT FK_zoek_gebied_landschap2
	FOREIGN KEY (zoek_gebied_landschap_id) REFERENCES imna.zoek_gebied_landschap (id) ON DELETE No Action ON UPDATE No Action
;

ALTER TABLE imna.zoek_gebied_toegestane_beheer_typen_water ADD CONSTRAINT FK_lnk_table_beheer_typen2
	FOREIGN KEY (water_natuur_type_id,beheer_type_id) REFERENCES masterdata.lnk_table_beheer_typen (natuur_type_id,beheer_type_id) ON DELETE No Action ON UPDATE No Action
;

ALTER TABLE imna.zoek_gebied_toegestane_beheer_typen_water ADD CONSTRAINT FK_zoek_gebied_water3
	FOREIGN KEY (zoek_gebied_water_id,water_natuur_type_id) REFERENCES imna.zoek_gebied_water (id,water_natuur_type_id) ON DELETE No Action ON UPDATE No Action
;

ALTER TABLE imna.zoek_gebied_water ADD CONSTRAINT FK_dmn_natuur_type_water1
	FOREIGN KEY (water_natuur_type_id) REFERENCES masterdata.dmn_natuur_type_water (id) ON DELETE No Action ON UPDATE No Action
;

ALTER TABLE imna.zoek_gebied_water ADD CONSTRAINT FK_dmn_provincie_code7
	FOREIGN KEY (provincie_id) REFERENCES masterdata.dmn_provincie_code (id) ON DELETE No Action ON UPDATE No Action
;

ALTER TABLE imna.zoek_gebied_water ADD CONSTRAINT FK_dmn_status_plan7
	FOREIGN KEY (status_id) REFERENCES masterdata.dmn_status_plan (id) ON DELETE No Action ON UPDATE No Action
;

ALTER TABLE imna.zoek_gebied_water ADD CONSTRAINT FK_natuur_beheer_plan7
	FOREIGN KEY (nbp_id) REFERENCES imna.natuur_beheer_plan (id) ON DELETE No Action ON UPDATE No Action
;

/* Create Table Comments, Sequences for Autonumber Columns */

COMMENT ON TABLE imna.ambitie_grootschaligenatuur
	IS 'Detail information of a Ambition Area of type G / Large Nature'
;

COMMENT ON COLUMN imna.ambitie_grootschaligenatuur.ambitie_gebied_id
	IS 'ID linking to  the internal id of  the ambition area'
;

COMMENT ON COLUMN imna.ambitie_grootschaligenatuur.beheer_type_id
	IS 'Domain Id linking to the specific maintenance type of the large nature ambition area'
;

COMMENT ON COLUMN imna.ambitie_grootschaligenatuur.subsidiabel
	IS 'Specifies if the area can be subsidized'
;

COMMENT ON TABLE imna.ambitie_indicatieve_verhouding_beheer_typen_gr
	IS 'Specifies the maintenance types relevant for a large nature ambition area and what for percentage of this type applies to the area. If multiple types apply for one area (denoted by ambitie_gebied_id) the total percentage should amount to 100%.'
;

COMMENT ON COLUMN imna.ambitie_indicatieve_verhouding_beheer_typen_gr.ambitie_gebied_id
	IS 'ID linking to the large nature ambition area'
;

COMMENT ON COLUMN imna.ambitie_indicatieve_verhouding_beheer_typen_gr.beheer_type_id
	IS 'Domain Id linking to the specific maintenance type of a nature ambition area'
;

COMMENT ON COLUMN imna.ambitie_indicatieve_verhouding_beheer_typen_gr.percentage
	IS 'the percentage of the ambition area this maintenance type is relevant for'
;

COMMENT ON TABLE imna.ambitie_indicatieve_verhouding_beheer_typen_vr
	IS 'Specifies the maintenance types relevant for a to transform nature ambition area and what for percentage of this type applies to the area. If multiple types apply for one area (denoted by ambitie_gebied_id) the total percentage should amount to 100%.'
;

COMMENT ON COLUMN imna.ambitie_indicatieve_verhouding_beheer_typen_vr.ambitie_gebied_id
	IS 'ID linking to the to transform nature ambition area'
;

COMMENT ON COLUMN imna.ambitie_indicatieve_verhouding_beheer_typen_vr.beheer_type_id
	IS 'Domain Id linking to the specific maintenance type of a nature ambition area'
;

COMMENT ON COLUMN imna.ambitie_indicatieve_verhouding_beheer_typen_vr.percentage
	IS 'the percentage of the ambition area this maintenance type is relevant for'
;

COMMENT ON TABLE imna.ambitie_landschap
	IS 'Detail information of a Ambition Area of type L / Landscape'
;

COMMENT ON COLUMN imna.ambitie_landschap.ambitie_gebied_id
	IS 'ID linking to  the internal id of  the ambition area'
;

COMMENT ON COLUMN imna.ambitie_landschap.beheer_type_id
	IS 'Domain Id linking to the specific maintenance type of the landscape ambition area'
;

COMMENT ON COLUMN imna.ambitie_landschap.subsidiabel
	IS 'Specifies if the area can be subsidized'
;

COMMENT ON TABLE imna.ambitie_natuur
	IS 'Detail information of a Ambition Area of type N / Nature'
;

COMMENT ON COLUMN imna.ambitie_natuur.ambitie_gebied_id
	IS 'ID linking to  the internal id of  the ambition area'
;

COMMENT ON COLUMN imna.ambitie_natuur.beheer_type_id
	IS 'Domain Id linking to the specific maintenance type of the nature ambition area'
;

COMMENT ON COLUMN imna.ambitie_natuur.subsidiabel
	IS 'Specifies if the area can be subsidized'
;

COMMENT ON TABLE imna.ambitie_omtevormennatuur
	IS 'Detail information of a Ambition Area of type V / to transform nature'
;

COMMENT ON COLUMN imna.ambitie_omtevormennatuur.ambitie_gebied_id
	IS 'ID linking to  the internal id of  the ambition area'
;

COMMENT ON COLUMN imna.ambitie_omtevormennatuur.beheer_type_id
	IS 'Domain Id linking to the specific maintenance type of the to transform ambition area'
;

COMMENT ON COLUMN imna.ambitie_omtevormennatuur.subsidiabel
	IS 'Specifies if the area can be subsidized'
;

COMMENT ON TABLE imna.ambitie_toegestane_beheer_pakketten_landschap
	IS 'Specifies what maintenance packages are allowed for the landscape ambition area Allowed packages are specific to the maintenance type of the landscape ambition area'
;

COMMENT ON COLUMN imna.ambitie_toegestane_beheer_pakketten_landschap.ambitie_gebied_id
	IS 'ID linking to landscape ambition area'
;

COMMENT ON COLUMN imna.ambitie_toegestane_beheer_pakketten_landschap.beheer_type_id
	IS 'Maintenance type inherited from  the landscape ambition area. Together with maintenance packages refers to the link table that specifies the allowed maintenance packages for the maintenance type'
;

COMMENT ON COLUMN imna.ambitie_toegestane_beheer_pakketten_landschap.beheer_pakket_id
	IS 'Maintenance package for the landscape ambition area. Together with maintenance type refers to the link table that specifies the allowed maintenance packages for the maintenance type.'
;

COMMENT ON TABLE imna.ambitie_water
	IS 'Detail information of a Ambition Area of type W / Water'
;

COMMENT ON COLUMN imna.ambitie_water.ambitie_gebied_id
	IS 'ID linking to  the internal id of  the ambition area'
;

COMMENT ON COLUMN imna.ambitie_water.beheer_type_id
	IS 'Domain Id linking to the specific maintenance type of the water ambition area'
;

COMMENT ON COLUMN imna.ambitie_water.subsidiabel
	IS 'Specifies if the area can be subsidized'
;

COMMENT ON TABLE imna.beheer_agrarisch
	IS 'Detail information of a Maintenance Area of type A / Agricultural'
;

COMMENT ON COLUMN imna.beheer_agrarisch.beheer_gebied_id
	IS 'ID linking to  the internal id of  the maintenance area'
;

COMMENT ON COLUMN imna.beheer_agrarisch.beheer_type_id
	IS 'Domain Id linking to the specific maintenance type of the landscape area'
;

COMMENT ON COLUMN imna.beheer_agrarisch.subsidiabel
	IS 'Specifies if the area can be subsidized'
;

COMMENT ON TABLE imna.beheer_gebied
	IS 'Maintenance area. Aggregation of all maintenance areas in a plan. Detailed specification of the area is stored in its detailed tables. Attribute gebied_type_id specifies what detail table to use for this maintenance area.'
;

COMMENT ON COLUMN imna.beheer_gebied.id
	IS 'Internal ID of the maintenance area'
;

COMMENT ON COLUMN imna.beheer_gebied.identificatie
	IS 'External ID of the maintenance area'
;

COMMENT ON COLUMN imna.beheer_gebied.begin_geldigheid
	IS 'Start of the validity for this version of the maintenance area'
;

COMMENT ON COLUMN imna.beheer_gebied.eind_geldigheid
	IS 'End of the validity for this version of the maintenance area'
;

COMMENT ON COLUMN imna.beheer_gebied.begin_tijd
	IS 'Start of the validity for this version of the maintenance area identified by the idenficatie and provinceId'
;

COMMENT ON COLUMN imna.beheer_gebied.eind_tijd
	IS 'End of the validity for this version of the maintenance area identified by the idenficatie and provinceId'
;

COMMENT ON COLUMN imna.beheer_gebied.nbp_id
	IS 'Id linking to the Nature Maintenance Plan used to submit this version of the Maintenance area'
;

COMMENT ON COLUMN imna.beheer_gebied.status_id
	IS 'Domain Id linking to the status of the maintenance area'
;

COMMENT ON COLUMN imna.beheer_gebied.provincie_id
	IS 'Domain id linking to the province who is responsible for the maintenance area'
;

COMMENT ON COLUMN imna.beheer_gebied.gebied_type_id
	IS 'Domain id linking to the main type of the maintenance area. This will denote what detail table is attached to this maintenance area.'
;

COMMENT ON COLUMN imna.beheer_gebied.geom
	IS 'Geometry single polygon in EPSG:28992 of the maintenance area'
;

COMMENT ON TABLE imna.beheer_gebied_ambitie
	IS 'Ambition of maintenance area. Aggregation of all ambition areas in a plan. Detailed specification of the area is stored in its detailed tables. Attribute gebied_type_id specifies what detail table to use for this maintenance area.'
;

COMMENT ON COLUMN imna.beheer_gebied_ambitie.id
	IS 'Internal ID of the ambition area'
;

COMMENT ON COLUMN imna.beheer_gebied_ambitie.identificatie
	IS 'External ID of the ambition area'
;

COMMENT ON COLUMN imna.beheer_gebied_ambitie.begin_geldigheid
	IS 'Start of the validity for this version of the ambition area'
;

COMMENT ON COLUMN imna.beheer_gebied_ambitie.eind_geldigheid
	IS 'End of the validity for this version of the ambition area'
;

COMMENT ON COLUMN imna.beheer_gebied_ambitie.begin_tijd
	IS 'Start of the validity for this version of the ambition area identified by the idenficatie and provinceId'
;

COMMENT ON COLUMN imna.beheer_gebied_ambitie.eind_tijd
	IS 'End of the validity for this version of the ambition area identified by the idenficatie and provinceId'
;

COMMENT ON COLUMN imna.beheer_gebied_ambitie.nbp_id
	IS 'Id linking to the Nature Maintenance Plan used to submit this version of the ambition area'
;

COMMENT ON COLUMN imna.beheer_gebied_ambitie.status_id
	IS 'Domain Id linking to the status of the ambition area.'
;

COMMENT ON COLUMN imna.beheer_gebied_ambitie.provincie_id
	IS 'Domain id linking to the province who is responsible for the ambition area'
;

COMMENT ON COLUMN imna.beheer_gebied_ambitie.gebied_type_id
	IS 'Domain id linking to the main type of the ambition area. This will denote what detail table is attached to this ambition area.'
;

COMMENT ON COLUMN imna.beheer_gebied_ambitie.status_ehs_id
	IS 'Domain Id linking to the EHS status of the ambition area. EHS (Ecologische hoofd structuur) stands for main ecological structure.'
;

COMMENT ON COLUMN imna.beheer_gebied_ambitie.geom
	IS 'Geometry single polygon in EPSG:28992 of the ambition area'
;

COMMENT ON TABLE imna.beheer_gebied_to_ambities
	IS 'Specifies maintenance areas that relate to a ambition area. They relate because their geometries overlap.'
;

COMMENT ON COLUMN imna.beheer_gebied_to_ambities.beheer_gebied_id
	IS 'ID linking to the maintenance area'
;

COMMENT ON COLUMN imna.beheer_gebied_to_ambities.ambitie_gebied_id
	IS 'ID linking to the ambition area'
;

COMMENT ON TABLE imna.beheer_grootschaligenatuur
	IS 'Detail information of the maintenance area of type G / or large nature.  Large Nature areas are nature areas that have not yet been split in detail. Therefore multiple maintenance types can apply to the area.'
;

COMMENT ON COLUMN imna.beheer_grootschaligenatuur.beheer_gebied_id
	IS 'ID linking to  the internal id of  the maintenance area'
;

COMMENT ON COLUMN imna.beheer_grootschaligenatuur.beheer_type_id
	IS 'Domain Id linking to the main specific maintenance type of the large nature area'
;

COMMENT ON COLUMN imna.beheer_grootschaligenatuur.subsidiabel
	IS 'Specifies if the area can be subsidized'
;

COMMENT ON COLUMN imna.beheer_grootschaligenatuur.openstellings_bijdrage_type_id
	IS 'Domain Id linking to the type of allowance that can be received to have the area opened to the public'
;

COMMENT ON TABLE imna.beheer_indicatieve_verhouding_beheer_typen
	IS 'Specifies the maintenance types relevant for a large nature area and what for percentage of this type applies to the area. If multiple types apply for one area (denoted by beheer_gebied_id) the total percentage should amount to 100%.'
;

COMMENT ON COLUMN imna.beheer_indicatieve_verhouding_beheer_typen.beheer_gebied_id
	IS 'ID linking to the large nature area'
;

COMMENT ON COLUMN imna.beheer_indicatieve_verhouding_beheer_typen.beheer_type_id
	IS 'Domain Id linking to the specific maintenance type of a nature area'
;

COMMENT ON COLUMN imna.beheer_indicatieve_verhouding_beheer_typen.percentage
	IS 'the percentage of the maintenance area this maintenance type is relevant for.'
;

COMMENT ON TABLE imna.beheer_landschap
	IS 'Detail information of a Maintenance Area of type L / Landscape'
;

COMMENT ON COLUMN imna.beheer_landschap.beheer_gebied_id
	IS 'ID linking to  the internal id of  the maintenance area'
;

COMMENT ON COLUMN imna.beheer_landschap.beheer_type_id
	IS 'Domain Id linking to the specific maintenance type of the landscape area'
;

COMMENT ON COLUMN imna.beheer_landschap.subsidiabel
	IS 'Specifies if the area can be subsidized'
;

COMMENT ON TABLE imna.beheer_natuur
	IS 'Detail information of a Maintenance Area of type N / Nature'
;

COMMENT ON COLUMN imna.beheer_natuur.beheer_gebied_id
	IS 'ID linking to  the internal id of  the maintenance area'
;

COMMENT ON COLUMN imna.beheer_natuur.beheer_type_id
	IS 'Domain Id linking to the specific maintenance type of the nature area'
;

COMMENT ON COLUMN imna.beheer_natuur.subsidiabel
	IS 'Specifies if the area can be subsidized'
;

COMMENT ON COLUMN imna.beheer_natuur.openstellings_bijdrage_type_id
	IS 'Domain Id linking to the type of allowance that can be received to have the area opened to the public'
;

COMMENT ON TABLE imna.beheer_niet_subsidiabele_beheer_pakketten_agrarisch
	IS 'Specifies what maintenance packages cannot be subsidized for the agricultural area Allowed packages are specific to the maintenance type of the agricultural area.'
;

COMMENT ON COLUMN imna.beheer_niet_subsidiabele_beheer_pakketten_agrarisch.beheer_type_id
	IS 'Maintenance type inherited from  the agricultural area. Together with maintenance packages refers to the link table that specifies the allowed maintenance packages for the maintenance type.'
;

COMMENT ON COLUMN imna.beheer_niet_subsidiabele_beheer_pakketten_agrarisch.beheer_pakket_id
	IS 'Maintenance package for the agricultural area. Together with maintenance type refers to the link table that specifies the allowed maintenance packages for the maintenance type.'
;

COMMENT ON TABLE imna.beheer_niet_subsidiabele_beheer_pakketten_landschap
	IS 'Specifies what maintenance packages cannot be subsidized for the landscape area Allowed packages are specific to the maintenance type of the landscape area.'
;

COMMENT ON COLUMN imna.beheer_niet_subsidiabele_beheer_pakketten_landschap.beheer_gebied_id
	IS 'ID linking to landscape area'
;

COMMENT ON COLUMN imna.beheer_niet_subsidiabele_beheer_pakketten_landschap.beheer_type_id
	IS 'Maintenance type inherited from  the landscape area. Together with maintenance packages refers to the link table that specifies the allowed maintenance packages for the maintenance type'
;

COMMENT ON COLUMN imna.beheer_niet_subsidiabele_beheer_pakketten_landschap.beheer_pakket_id
	IS 'Maintenance package for the landscape area. Together with maintenance type refers to the link table that specifies the allowed maintenance packages for the maintenance type.'
;

COMMENT ON TABLE imna.beheer_toegestane_beheer_pakketten_agrarisch
	IS 'Specifies what maintenance packages are allowed for the agricultural area Allowed packages are specific to the maintenance type of the agricultural area.'
;

COMMENT ON COLUMN imna.beheer_toegestane_beheer_pakketten_agrarisch.beheer_gebied_id
	IS 'ID linking to agricultural area'
;

COMMENT ON COLUMN imna.beheer_toegestane_beheer_pakketten_agrarisch.beheer_type_id
	IS 'Maintenance type inherited from  the agricultural area. Together with maintenance packages refers to the link table that specifies the allowed maintenance packages for the maintenance type.'
;

COMMENT ON COLUMN imna.beheer_toegestane_beheer_pakketten_agrarisch.beheer_pakket_id
	IS 'Maintenance package for the agricultural area. Together with maintenance type refers to the link table that specifies the allowed maintenance packages for the maintenance type.'
;

COMMENT ON TABLE imna.beheer_toegestane_beheer_pakketten_landschap
	IS 'Specifies what maintenance packages are allowed for the landscape area Allowed packages are specific to the maintenance type of the landscape area'
;

COMMENT ON COLUMN imna.beheer_toegestane_beheer_pakketten_landschap.beheer_gebied_id
	IS 'ID linking to landscape area'
;

COMMENT ON COLUMN imna.beheer_toegestane_beheer_pakketten_landschap.beheer_type_id
	IS 'Maintenance type inherited from  the landscape area. Together with maintenance packages refers to the link table that specifies the allowed maintenance packages for the maintenance type'
;

COMMENT ON COLUMN imna.beheer_toegestane_beheer_pakketten_landschap.beheer_pakket_id
	IS 'Maintenance package for the landscape area. Together with maintenance type refers to the link table that specifies the allowed maintenance packages for the maintenance type.'
;

COMMENT ON TABLE imna.beheer_water
	IS 'Detail information of a Maintenance Area of type W / Water'
;

COMMENT ON COLUMN imna.beheer_water.beheer_gebied_id
	IS 'ID linking to  the internal id of  the maintenance area'
;

COMMENT ON COLUMN imna.beheer_water.beheer_type_id
	IS 'Domain Id linking to the specific maintenance type of the water area'
;

COMMENT ON COLUMN imna.beheer_water.subsidiabel
	IS 'Specifies if the area can be subsidized'
;

COMMENT ON TABLE imna.bijzonder_gebied
	IS 'Special area. Special areas are areas that can will be subsidized in a different way, dependant on the policy of the province.'
;

COMMENT ON COLUMN imna.bijzonder_gebied.id
	IS 'Internal ID of the special area'
;

COMMENT ON COLUMN imna.bijzonder_gebied.identificatie
	IS 'External ID of the special area'
;

COMMENT ON COLUMN imna.bijzonder_gebied.begin_geldigheid
	IS 'Start of the validity for this version of the special area'
;

COMMENT ON COLUMN imna.bijzonder_gebied.eind_geldigheid
	IS 'End of the validity for this version of the special area'
;

COMMENT ON COLUMN imna.bijzonder_gebied.begin_tijd
	IS 'Start of the validity for this version of the special area identified by the idenficatie and provinceId'
;

COMMENT ON COLUMN imna.bijzonder_gebied.eind_tijd
	IS 'End of the validity for this version of the special area identified by the idenficatie and provinceId'
;

COMMENT ON COLUMN imna.bijzonder_gebied.nbp_id
	IS 'Id linking to the Nature Maintenance Plan use to submit this version of the special area'
;

COMMENT ON COLUMN imna.bijzonder_gebied.status_id
	IS 'Domain Id linking to the status of the special area.'
;

COMMENT ON COLUMN imna.bijzonder_gebied.provincie_id
	IS 'Domain id linking to the province who is responsible for the special area'
;

COMMENT ON COLUMN imna.bijzonder_gebied.geom
	IS 'Geometry single polygon in EPSG:28992 of the special area'
;

COMMENT ON COLUMN imna.bijzonder_gebied.gebieds_code_id
	IS 'Domain id linking to the code of the special area'
;

COMMENT ON COLUMN imna.bijzonder_gebied.gebieds_naam
	IS 'name of the special area'
;

COMMENT ON TABLE imna.deel_gebied
	IS 'Sub area. Sub areas are areas that share a common description of how maintenance is done on this area'
;

COMMENT ON COLUMN imna.deel_gebied.id
	IS 'Internal ID of the sub area'
;

COMMENT ON COLUMN imna.deel_gebied.identificatie
	IS 'External ID of the sub area'
;

COMMENT ON COLUMN imna.deel_gebied.begin_geldigheid
	IS 'Start of the validity for this version of the sub area'
;

COMMENT ON COLUMN imna.deel_gebied.eind_geldigheid
	IS 'End of the validity for this version of the sub area'
;

COMMENT ON COLUMN imna.deel_gebied.begin_tijd
	IS 'Start of the validity for this version of the sub area identified by the idenficatie and provinceId'
;

COMMENT ON COLUMN imna.deel_gebied.eind_tijd
	IS 'End of the validity for this version of the sub area identified by the idenficatie and provinceId'
;

COMMENT ON COLUMN imna.deel_gebied.nbp_id
	IS 'Id linking to the Nature Maintenance Plan use to submit this version of the sub area'
;

COMMENT ON COLUMN imna.deel_gebied.status_id
	IS 'Domain Id linking to the status of the sub area'
;

COMMENT ON COLUMN imna.deel_gebied.provincie_id
	IS 'Domain id linking to the province who is responsible for the sub area'
;

COMMENT ON COLUMN imna.deel_gebied.geom
	IS 'Geometry single polygon in EPSG:28992 of the sub area'
;

COMMENT ON COLUMN imna.deel_gebied.gebieds_naam
	IS 'name of the sub area'
;

COMMENT ON COLUMN imna.deel_gebied.beschrijving
	IS 'description of the maintenance done for this area'
;

COMMENT ON TABLE imna.natuur_beheer_plan
	IS 'Meta data for each individual submission of a Maintenance Nature Plan.'
;

COMMENT ON COLUMN imna.natuur_beheer_plan.id
	IS 'Internal ID of the plan'
;

COMMENT ON COLUMN imna.natuur_beheer_plan.identificatie
	IS 'External ID of the plan'
;

COMMENT ON COLUMN imna.natuur_beheer_plan.begin_geldigheid
	IS 'Start of the validity for this version of the plan'
;

COMMENT ON COLUMN imna.natuur_beheer_plan.eind_geldigheid
	IS 'End of the validity for this version of the plan'
;

COMMENT ON COLUMN imna.natuur_beheer_plan.status_id
	IS 'Domain Id linking to the status of the plan. '
;

COMMENT ON COLUMN imna.natuur_beheer_plan.provincie_id
	IS 'Domain id linking to the province who submitted the plan'
;

COMMENT ON COLUMN imna.natuur_beheer_plan.datum_vaststelling
	IS 'Date when the plan was specified by the province'
;

COMMENT ON COLUMN imna.natuur_beheer_plan.plan_naam
	IS 'Name of the plan'
;

COMMENT ON COLUMN imna.natuur_beheer_plan.plan_eigenaar_id
	IS 'Domain Id linking to the owner of the plan.'
;

COMMENT ON COLUMN imna.natuur_beheer_plan.plan_verwijzing
	IS 'Description of the area this plan applies to. Normally this is the province border'
;

COMMENT ON COLUMN imna.natuur_beheer_plan.subsidie_jaar
	IS 'Year the plan applies to.'
;

COMMENT ON COLUMN imna.natuur_beheer_plan.beheer_gebied_status_id
	IS 'Domain Id linking to the status of maintenance area layer of the plan'
;

COMMENT ON COLUMN imna.natuur_beheer_plan.beheer_gebied_ambitie_status_id
	IS 'Domain Id linking to the status of maintenance ambition area layer of the plan'
;

COMMENT ON COLUMN imna.natuur_beheer_plan.bijzonder_gebied_status_id
	IS 'Domain Id linking to the status of special area layer of the plan'
;

COMMENT ON COLUMN imna.natuur_beheer_plan.deel_gebied_status_id
	IS 'Domain Id linking to the status of subarea layer of the plan'
;

COMMENT ON COLUMN imna.natuur_beheer_plan.zoek_gebied_landschap_status_id
	IS 'Domain Id linking to the status of landscape search area layer of the plan'
;

COMMENT ON COLUMN imna.natuur_beheer_plan.zoek_gebied_agrarisch_status_id
	IS 'Domain Id linking to the status of agricultural search area layer of the plan'
;

COMMENT ON COLUMN imna.natuur_beheer_plan.zoek_gebied_water_status_id
	IS 'Domain Id linking to the status of water search area layer of the plan'
;

COMMENT ON COLUMN imna.natuur_beheer_plan.document_link
	IS 'FileName of the main document that has the detailed description of the plan. Will be used in the viewers to facilitate linking to this document in Drupal'
;

COMMENT ON TABLE imna.zoek_gebied_agrarisch
	IS 'Agricultural search area. In this area collectives can request subsidies to maintain the agricultural nature '
;

COMMENT ON COLUMN imna.zoek_gebied_agrarisch.id
	IS 'Internal ID of the agricultural search area'
;

COMMENT ON COLUMN imna.zoek_gebied_agrarisch.identificatie
	IS 'External ID of the agricultural search area'
;

COMMENT ON COLUMN imna.zoek_gebied_agrarisch.begin_geldigheid
	IS 'Start of the validity for this version of the agricultural search area'
;

COMMENT ON COLUMN imna.zoek_gebied_agrarisch.eind_geldigheid
	IS 'End of the validity for this version of the agricultural search area'
;

COMMENT ON COLUMN imna.zoek_gebied_agrarisch.begin_tijd
	IS 'Start of the validity for this version of the agricultural search area identified by the idenficatie and provinceId'
;

COMMENT ON COLUMN imna.zoek_gebied_agrarisch.eind_tijd
	IS 'End of the validity for this version of the agricultural search area identified by the idenficatie and provinceId'
;

COMMENT ON COLUMN imna.zoek_gebied_agrarisch.nbp_id
	IS 'Id linking to the Nature Maintenance Plan use to submit this version of the agricultural search area'
;

COMMENT ON COLUMN imna.zoek_gebied_agrarisch.status_id
	IS 'Domain Id linking to the status of the agricultural search area'
;

COMMENT ON COLUMN imna.zoek_gebied_agrarisch.provincie_id
	IS ' Domain id linking to the province who is responsible for the agricultural search area'
;

COMMENT ON COLUMN imna.zoek_gebied_agrarisch.geom
	IS 'Geometry single polygon in EPSG:28992 of the agricultural search area'
;

COMMENT ON COLUMN imna.zoek_gebied_agrarisch.agrarisch_natuur_type_id
	IS 'Domain id linking to the agricultural nature type of the agricultural search area'
;

COMMENT ON COLUMN imna.zoek_gebied_agrarisch.naam
	IS 'name of the agricultural search area'
;

COMMENT ON TABLE imna.zoek_gebied_landschap
	IS 'Landscape search area. In this area collectives can request subsidies to maintain the landscape nature '
;

COMMENT ON COLUMN imna.zoek_gebied_landschap.id
	IS 'Internal ID of the landscape search area'
;

COMMENT ON COLUMN imna.zoek_gebied_landschap.identificatie
	IS 'External ID of the landscape search area'
;

COMMENT ON COLUMN imna.zoek_gebied_landschap.begin_geldigheid
	IS 'Start of the validity for this version of the landscape search area'
;

COMMENT ON COLUMN imna.zoek_gebied_landschap.eind_geldigheid
	IS 'End of the validity for this version of the landscape search area'
;

COMMENT ON COLUMN imna.zoek_gebied_landschap.begin_tijd
	IS 'Start of the validity for this version of the landscape search area identified by the idenficatie and provinceId'
;

COMMENT ON COLUMN imna.zoek_gebied_landschap.eind_tijd
	IS 'End of the validity for this version of the landscape search area identified by the idenficatie and provinceId'
;

COMMENT ON COLUMN imna.zoek_gebied_landschap.nbp_id
	IS 'Id linking to the Nature Maintenance Plan use to submit this version of the landscape search area'
;

COMMENT ON COLUMN imna.zoek_gebied_landschap.status_id
	IS 'Domain Id linking to the status of the landscape search area'
;

COMMENT ON COLUMN imna.zoek_gebied_landschap.provincie_id
	IS 'Domain id linking to the province who is responsible for the landscape search area'
;

COMMENT ON COLUMN imna.zoek_gebied_landschap.geom
	IS 'Geometry single polygon in EPSG:28992 of the landscape search area'
;

COMMENT ON COLUMN imna.zoek_gebied_landschap.naam
	IS 'name of the landscape search area'
;

COMMENT ON TABLE imna.zoek_gebied_niet_subsidiabele_beheer_pakketten_landschap
	IS 'Specifies what maintenance packages will not be subsidized for the landscape search area'
;

COMMENT ON COLUMN imna.zoek_gebied_niet_subsidiabele_beheer_pakketten_landschap.zoek_gebied_landschap_id
	IS 'ID linking to the landscape search area'
;

COMMENT ON COLUMN imna.zoek_gebied_niet_subsidiabele_beheer_pakketten_landschap.beheer_pakket_id
	IS 'Domain Id linking to the specific maintenance package of a nature area'
;

COMMENT ON TABLE imna.zoek_gebied_toegestane_beheer_functies_agrarisch
	IS 'Specifies what maintenance functions are allowed for the agricultural search area Allowed functions are specific to the nature type of the agricultural search area.'
;

COMMENT ON COLUMN imna.zoek_gebied_toegestane_beheer_functies_agrarisch.zoek_gebied_agrarisch_id
	IS 'ID linking to the agricultural search area'
;

COMMENT ON COLUMN imna.zoek_gebied_toegestane_beheer_functies_agrarisch.agrarisch_natuur_type_id
	IS 'Nature type inherited from  the agricultural search area. Together with maintenance function refers to the link table that specifies the allowed maintenance functions for the nature type'
;

COMMENT ON COLUMN imna.zoek_gebied_toegestane_beheer_functies_agrarisch.beheer_functie_id
	IS 'Maintenance function for the agricultural search area. Together with nature type refers to the link table that specifies the allowed maintenance function for the nature type .'
;

COMMENT ON TABLE imna.zoek_gebied_toegestane_beheer_functies_water
	IS 'Specifies what maintenance functions are allowed for the water search area Allowed functions are specific to the nature type of the water search area.'
;

COMMENT ON COLUMN imna.zoek_gebied_toegestane_beheer_functies_water.zoek_gebied_water_id
	IS 'ID linking to the water search area'
;

COMMENT ON COLUMN imna.zoek_gebied_toegestane_beheer_functies_water.water_natuur_type_id
	IS 'Nature type inherited from  the water search area. Together with maintenance function refers to the link table that specifies the allowed maintenance functions for the nature type'
;

COMMENT ON COLUMN imna.zoek_gebied_toegestane_beheer_functies_water.beheer_functie_id
	IS 'Maintenance function for the water search area. Together with nature type refers to the link table that specifies the allowed maintenance function for the nature type .'
;

COMMENT ON TABLE imna.zoek_gebied_toegestane_beheer_typen_agrarisch
	IS 'Specifies what maintenance types are allowed for the agricultural search area Allowed types are specific to the nature type of the agricultural search area.'
;

COMMENT ON COLUMN imna.zoek_gebied_toegestane_beheer_typen_agrarisch.zoek_gebied_agrarisch_id
	IS 'ID linking to the agricultural search area'
;

COMMENT ON COLUMN imna.zoek_gebied_toegestane_beheer_typen_agrarisch.agrarisch_natuur_type_id
	IS 'Nature type inherited from  the agricultural search area. Together with maintenance type refers to the link table that specifies the allowed maintenance types for the nature type'
;

COMMENT ON COLUMN imna.zoek_gebied_toegestane_beheer_typen_agrarisch.beheer_type_id
	IS 'Maintenance type for the agricultural search area. Together with nature type refers to the link table that specifies the allowed maintenance type for the nature type'
;

COMMENT ON TABLE imna.zoek_gebied_toegestane_beheer_typen_landschap
	IS 'Specifies what maintenance types are allowed for the landscape search area'
;

COMMENT ON COLUMN imna.zoek_gebied_toegestane_beheer_typen_landschap.zoek_gebied_landschap_id
	IS 'ID linking to the landscape search area'
;

COMMENT ON COLUMN imna.zoek_gebied_toegestane_beheer_typen_landschap.beheer_type_id
	IS 'Domain Id linking to the specific maintenance type of a landscape area'
;

COMMENT ON TABLE imna.zoek_gebied_toegestane_beheer_typen_water
	IS 'Specifies what maintenance types are allowed for the water search area Allowed types are specific to the nature type of the water search area.'
;

COMMENT ON COLUMN imna.zoek_gebied_toegestane_beheer_typen_water.zoek_gebied_water_id
	IS 'ID linking to the water search area'
;

COMMENT ON COLUMN imna.zoek_gebied_toegestane_beheer_typen_water.water_natuur_type_id
	IS 'Nature type inherited from  the water search area. Together with maintenance type refers to the link table that specifies the allowed maintenance types for the nature type'
;

COMMENT ON COLUMN imna.zoek_gebied_water.id
	IS 'Internal ID of the water search area'
;

COMMENT ON COLUMN imna.zoek_gebied_water.identificatie
	IS 'External ID of the water search area'
;

COMMENT ON COLUMN imna.zoek_gebied_water.begin_geldigheid
	IS 'Start of the validity for this version of the water search area'
;

COMMENT ON COLUMN imna.zoek_gebied_water.eind_geldigheid
	IS 'End of the validity for this version of the water search area'
;

COMMENT ON COLUMN imna.zoek_gebied_water.begin_tijd
	IS 'Start of the validity for this version of the water search area identified by the idenficatie and provinceId'
;

COMMENT ON COLUMN imna.zoek_gebied_water.eind_tijd
	IS 'End of the validity for this version of the water search area identified by the idenficatie and provinceId'
;

COMMENT ON COLUMN imna.zoek_gebied_water.nbp_id
	IS 'Id linking to the Nature Maintenance Plan use to submit this version of the water search area'
;

COMMENT ON COLUMN imna.zoek_gebied_water.status_id
	IS 'Domain Id linking to the status of the water search area'
;

COMMENT ON COLUMN imna.zoek_gebied_water.provincie_id
	IS 'Domain id linking to the province who is responsible for the water search area'
;

COMMENT ON COLUMN imna.zoek_gebied_water.geom
	IS 'Geometry single polygon in EPSG:28992 of the water search area'
;

COMMENT ON COLUMN imna.zoek_gebied_water.water_natuur_type_id
	IS 'Domain id linking to the water nature type of the water search area'
;

COMMENT ON COLUMN imna.zoek_gebied_water.naam
	IS 'name of the water search area'
;

GRANT SELECT ON ALL TABLES IN SCHEMA imna TO anlb_sqlpad;