/* ---------------------------------------------------- */
/*  Generated by Enterprise Architect Version 12.1 		*/
/*  Created On : 23-Mar-2021 09:57:03 				*/
/*  DBMS       : PostgreSQL 						*/
/* ---------------------------------------------------- */

/* Drop Views */

DROP VIEW IF EXISTS imna.v_rvo_gebied_inrichting CASCADE
;

DROP VIEW IF EXISTS imna.v_rvo_gebied_natuur CASCADE
;

DROP VIEW IF EXISTS imna.v_rvo_gebied_verwerving CASCADE
;

DROP VIEW IF EXISTS imna.v_rvo_natuur_netwerk_nederland CASCADE
;

DROP VIEW IF EXISTS imna.v_rvo_resterende_inrichtings_ambitie CASCADE
;

DROP VIEW IF EXISTS imna.v_rvo_voortgangs_rapportage CASCADE
;

/* Create Views */

CREATE OR REPLACE VIEW imna.v_rvo_gebied_inrichting AS 
 SELECT ( SELECT btrim((dmn_provincie_code.code)::text) AS btrim
           FROM masterdata.dmn_provincie_code
          WHERE (dmn_provincie_code.id = g.bron_houder_id)) AS provincie,
    p.rapportage_jaar,
    btrim((g.identificatie)::text) AS identificatie,
    g.begin_geldigheid,
    NULL::text AS eind_geldigheid,
    g.begin_tijd,
    g.eind_tijd,
    g.geom
   FROM (imna.vm_prov_year_gebied_inrichting p
     JOIN imna.gebied_inrichting g ON ((g.id = p.gebied_inrichting_id)));
;

CREATE OR REPLACE VIEW imna.v_rvo_gebied_natuur AS 
 SELECT ( SELECT btrim((dmn_provincie_code.code)::text) AS btrim
           FROM masterdata.dmn_provincie_code
          WHERE (dmn_provincie_code.id = g.bron_houder_id)) AS provincie,
    p.rapportage_jaar,
    btrim((g.identificatie)::text) AS identificatie,
    g.begin_geldigheid,
    NULL::text AS eind_geldigheid,
    g.begin_tijd,
    g.eind_tijd,
    ( SELECT btrim((dmn_status_natuur.code)::text) AS btrim
           FROM masterdata.dmn_status_natuur
          WHERE (dmn_status_natuur.id = g.status_natuur_id)) AS status_natuur,
    g.geom
   FROM (imna.vm_prov_year_gebied_natuur p
     JOIN imna.gebied_natuur g ON ((g.id = p.gebied_natuur_id)));
;

CREATE OR REPLACE VIEW imna.v_rvo_gebied_verwerving AS 
 SELECT ( SELECT btrim((dmn_provincie_code.code)::text) AS btrim
           FROM masterdata.dmn_provincie_code
          WHERE (dmn_provincie_code.id = g.bron_houder_id)) AS provincie,
    p.rapportage_jaar,
    btrim((g.identificatie)::text) AS identificatie,
    g.begin_geldigheid,
    NULL::text AS eind_geldigheid,
    g.begin_tijd,
    g.eind_tijd,
    g.geom
   FROM (imna.vm_prov_year_gebied_verwerving p
     JOIN imna.gebied_verwerving g ON ((g.id = p.gebied_verwerving_id)));
;

CREATE OR REPLACE VIEW imna.v_rvo_natuur_netwerk_nederland AS 
 SELECT ( SELECT btrim((dmn_provincie_code.code)::text) AS btrim
           FROM masterdata.dmn_provincie_code
          WHERE (dmn_provincie_code.id = g.bron_houder_id)) AS provincie,
    p.rapportage_jaar,
    btrim((g.identificatie)::text) AS identificatie,
    g.begin_geldigheid,
    NULL::text AS eind_geldigheid,
    g.begin_tijd,
    g.eind_tijd,
    g.geom
   FROM (imna.vm_prov_year_natuur_netwerk_nederland p
     JOIN imna.natuur_netwerk_nederland g ON ((g.id = p.natuur_netwerk_nederland_id)));
;

CREATE OR REPLACE VIEW imna.v_rvo_resterende_inrichtings_ambitie AS 
 SELECT ( SELECT btrim((dmn_provincie_code.code)::text) AS btrim
           FROM masterdata.dmn_provincie_code
          WHERE (dmn_provincie_code.id = g.bron_houder_id)) AS provincie,
    p.rapportage_jaar,
    btrim((g.identificatie)::text) AS identificatie,
    g.begin_geldigheid,
    NULL::text AS eind_geldigheid,
    g.resterende_inrichtings_ambitie
   FROM (imna.vm_prov_year_resterende_inrichtings_ambitie p
     JOIN imna.resterende_inrichtings_ambitie g ON ((g.id = p.resterende_inrichtings_ambitie_id)));
;

CREATE OR REPLACE VIEW imna.v_rvo_voortgangs_rapportage AS 
 SELECT ( SELECT btrim((dmn_provincie_code.code)::text) AS btrim
           FROM masterdata.dmn_provincie_code
          WHERE (dmn_provincie_code.id = g.bron_houder_id)) AS bron_houder,
    p.rapportage_jaar,
    btrim((g.identificatie)::text) AS identificatie,
    g.begin_geldigheid,
    NULL::text AS eind_geldigheid,
    btrim(g.opmerkingen) AS opmerkingen
   FROM (imna.vm_prov_year_voortgangs_rapportage p
     JOIN imna.voortgangs_rapportage g ON ((g.id = p.report_id)));
;
