/* ---------------------------------------------------- */
/*  Generated by Enterprise Architect Version 12.1 		*/
/*  Created On : 02-Jun-2020 16:27:17 				*/
/*  DBMS       : PostgreSQL 						*/
/* ---------------------------------------------------- */

/* Drop Tables */

DROP TABLE IF EXISTS imna.beschikking CASCADE
;

DROP TABLE IF EXISTS imna.beschikking_beheer_type_niet_snl CASCADE
;

DROP TABLE IF EXISTS imna.beschikking_beheer_type_snl CASCADE
;

DROP TABLE IF EXISTS imna.beschikking_rapportage CASCADE
;

/* Create Tables */

CREATE TABLE imna.beschikking
(
	id bigint NOT NULL   DEFAULT NEXTVAL(('imna_seq'::text)::regclass),    -- Internal ID of the agreement
	identificatie char(100) NOT NULL,    -- External ID of the agreement
	begin_geldigheid timestamp NOT NULL,    -- Start of the validity for this version of the agreement
	eind_geldigheid timestamp NULL,    -- End of the validity for this version of the agreement
	provincie_id bigint NOT NULL,    -- Domain id linking to the province who is responsible for the agreement
	beschikking_rapportage_id bigint NOT NULL,    -- Id linking to the agreement upload used to submit this version of the agreement
	begin_tijd timestamp NOT NULL,    -- Start of the validity for this version of the agreement identified by the idenficatie and provinceId
	eind_tijd timestamp NOT NULL,    -- End of the validity for this version of the agreement identified by the idenficatie and provinceId
	contract_nummer char(20) NOT NULL,    -- contract number of the agreement
	datum_beschikking timestamp NOT NULL,    -- Date the agreement was signed
	status_aanvraag_subsidie_id bigint NOT NULL,    -- Domain id linking to the status of the agreement
	type_regeling_id bigint NOT NULL,    -- Domain id linking to the type of regulation of the agreement 
	geom geometry NOT NULL    -- Geometry single polygon in EPSG:28992 of the agreement
)
;

CREATE TABLE imna.beschikking_beheer_type_niet_snl
(
	beschikking_id bigint NOT NULL,    -- ID linking to  the internal id of  the agreement
	type_regeling_id bigint NOT NULL,    -- Domain id linking to the type of regulation of the agreement 
	beheer_type_id bigint NULL    -- Domain id linking to the type of maintenance 
)
;

CREATE TABLE imna.beschikking_beheer_type_snl
(
	beschikking_id bigint NOT NULL,    -- ID linking to  the internal id of  the agreement
	type_regeling_id bigint NOT NULL,    -- Domain id linking to the type of regulation of the agreement 
	beheer_type_id bigint NOT NULL    -- Domain id linking to the type of maintenance 
)
;

CREATE TABLE imna.beschikking_rapportage
(
	id bigint NOT NULL   DEFAULT NEXTVAL(('imna_seq'::text)::regclass),    -- Internal ID of the agreement upload
	identificatie char(100) NOT NULL,    -- External ID of the agreement upload
	begin_geldigheid timestamp NOT NULL,    -- Start of the validity for this version of the agreement upload
	eind_geldigheid timestamp NULL,    -- End of the validity for this version of the agreement upload
	provincie_id bigint NOT NULL,    -- Domain id linking to the province who is responsible for the agreement upload
	beheer_jaar smallint NOT NULL    -- year of the agreement upload
)
;

/* Create Primary Keys, Indexes, Uniques, Checks */

ALTER TABLE imna.beschikking ADD CONSTRAINT PK_beschikking
	PRIMARY KEY (id)
;

ALTER TABLE imna.beschikking ADD CONSTRAINT UN_beschikking_indentificatie UNIQUE (provincie_id,identificatie,begin_geldigheid)
;

CREATE INDEX IXFK_beschikking_beschikking_jaar ON imna.beschikking (beschikking_rapportage_id ASC)
;

CREATE INDEX IXFK_dmn_provincie_code_17 ON imna.beschikking (provincie_id ASC)
;

CREATE INDEX IXFK_dmn_status_aanvraag_subsidie_1 ON imna.beschikking (status_aanvraag_subsidie_id ASC)
;

CREATE INDEX IXFK_dmn_type_regeling_1 ON imna.beschikking (type_regeling_id ASC)
;

ALTER TABLE imna.beschikking_beheer_type_niet_snl ADD CONSTRAINT PK_beschikking_beheertype_niet_snl
	PRIMARY KEY (beschikking_id)
;

CREATE INDEX IXFK_beschikking_2 ON imna.beschikking_beheer_type_niet_snl (beschikking_id ASC)
;

CREATE INDEX IXFK_dmn_beheer_type_5 ON imna.beschikking_beheer_type_niet_snl (beheer_type_id ASC)
;

CREATE INDEX IXFK_dmn_beheer_type_niet_snl_1 ON imna.beschikking_beheer_type_niet_snl (type_regeling_id ASC)
;

ALTER TABLE imna.beschikking_beheer_type_snl ADD CONSTRAINT PK_beschikking_beheertype_snl
	PRIMARY KEY (beschikking_id)
;

CREATE INDEX IXFK_beschikking_1 ON imna.beschikking_beheer_type_snl (beschikking_id ASC)
;

CREATE INDEX IXFK_lnk_table_beheer_type_regeling_1 ON imna.beschikking_beheer_type_snl (type_regeling_id ASC,beheer_type_id ASC)
;

ALTER TABLE imna.beschikking_rapportage ADD CONSTRAINT PK_beschikking_rapportage
	PRIMARY KEY (id)
;

ALTER TABLE imna.beschikking_rapportage ADD CONSTRAINT UN_beschikking_rapportage UNIQUE (provincie_id,identificatie,begin_geldigheid)
;

CREATE INDEX IXFK_dmn_provincie_code_16 ON imna.beschikking_rapportage (provincie_id ASC)
;

/* Create Foreign Key Constraints */

ALTER TABLE imna.beschikking ADD CONSTRAINT FK_beschikking_beschikking_jaar
	FOREIGN KEY (beschikking_rapportage_id) REFERENCES imna.beschikking_rapportage (id) ON DELETE No Action ON UPDATE No Action
;

ALTER TABLE imna.beschikking ADD CONSTRAINT FK_dmn_provincie_code_17
	FOREIGN KEY (provincie_id) REFERENCES masterdata.dmn_provincie_code (id) ON DELETE No Action ON UPDATE No Action
;

ALTER TABLE imna.beschikking ADD CONSTRAINT FK_dmn_status_aanvraag_subsidie_1
	FOREIGN KEY (status_aanvraag_subsidie_id) REFERENCES masterdata.dmn_status_aanvraag_subsidie (id) ON DELETE No Action ON UPDATE No Action
;

ALTER TABLE imna.beschikking ADD CONSTRAINT FK_dmn_type_regeling_1
	FOREIGN KEY (type_regeling_id) REFERENCES masterdata.dmn_type_regeling (id) ON DELETE No Action ON UPDATE No Action
;

ALTER TABLE imna.beschikking_beheer_type_niet_snl ADD CONSTRAINT FK_beschikking_2
	FOREIGN KEY (beschikking_id) REFERENCES imna.beschikking (id) ON DELETE No Action ON UPDATE No Action
;

ALTER TABLE imna.beschikking_beheer_type_niet_snl ADD CONSTRAINT FK_dmn_beheer_type_beschikking_niet_snl_01
	FOREIGN KEY (beheer_type_id) REFERENCES masterdata.dmn_beheer_type_beschikking_niet_snl (id) ON DELETE No Action ON UPDATE No Action
;

ALTER TABLE imna.beschikking_beheer_type_niet_snl ADD CONSTRAINT FK_dmn_beheer_type_niet_snl_1
	FOREIGN KEY (type_regeling_id) REFERENCES masterdata.dmn_type_regeling_niet_snl (id) ON DELETE No Action ON UPDATE No Action
;

ALTER TABLE imna.beschikking_beheer_type_snl ADD CONSTRAINT FK_beschikking_1
	FOREIGN KEY (beschikking_id) REFERENCES imna.beschikking (id) ON DELETE No Action ON UPDATE No Action
;

ALTER TABLE imna.beschikking_beheer_type_snl ADD CONSTRAINT FK_lnk_table_beheer_type_regeling_1
	FOREIGN KEY (type_regeling_id,beheer_type_id) REFERENCES masterdata.lnk_table_beheer_type_regeling (type_regeling_id,beheer_type_id) ON DELETE No Action ON UPDATE No Action
;

ALTER TABLE imna.beschikking_rapportage ADD CONSTRAINT FK_dmn_provincie_code_16
	FOREIGN KEY (provincie_id) REFERENCES masterdata.dmn_provincie_code (id) ON DELETE No Action ON UPDATE No Action
;

/* Create Table Comments, Sequences for Autonumber Columns */

COMMENT ON TABLE imna.beschikking
	IS 'Agreement between a province and a collective to provide nature maintenance for a certain area'
;

COMMENT ON COLUMN imna.beschikking.id
	IS 'Internal ID of the agreement'
;

COMMENT ON COLUMN imna.beschikking.identificatie
	IS 'External ID of the agreement'
;

COMMENT ON COLUMN imna.beschikking.begin_geldigheid
	IS 'Start of the validity for this version of the agreement'
;

COMMENT ON COLUMN imna.beschikking.eind_geldigheid
	IS 'End of the validity for this version of the agreement'
;

COMMENT ON COLUMN imna.beschikking.provincie_id
	IS 'Domain id linking to the province who is responsible for the agreement'
;

COMMENT ON COLUMN imna.beschikking.beschikking_rapportage_id
	IS 'Id linking to the agreement upload used to submit this version of the agreement'
;

COMMENT ON COLUMN imna.beschikking.begin_tijd
	IS 'Start of the validity for this version of the agreement identified by the idenficatie and provinceId'
;

COMMENT ON COLUMN imna.beschikking.eind_tijd
	IS 'End of the validity for this version of the agreement identified by the idenficatie and provinceId'
;

COMMENT ON COLUMN imna.beschikking.contract_nummer
	IS 'contract number of the agreement'
;

COMMENT ON COLUMN imna.beschikking.datum_beschikking
	IS 'Date the agreement was signed'
;

COMMENT ON COLUMN imna.beschikking.status_aanvraag_subsidie_id
	IS 'Domain id linking to the status of the agreement'
;

COMMENT ON COLUMN imna.beschikking.type_regeling_id
	IS 'Domain id linking to the type of regulation of the agreement '
;

COMMENT ON COLUMN imna.beschikking.geom
	IS 'Geometry single polygon in EPSG:28992 of the agreement'
;

COMMENT ON TABLE imna.beschikking_beheer_type_niet_snl
	IS 'Detail information of a agreement for regarding the maintenance type for the following type_regeling: 5	TRPN 6	GroenBlauwe Diensten 7	Regeling Experimenten'
;

COMMENT ON COLUMN imna.beschikking_beheer_type_niet_snl.beschikking_id
	IS 'ID linking to  the internal id of  the agreement'
;

COMMENT ON COLUMN imna.beschikking_beheer_type_niet_snl.type_regeling_id
	IS 'Domain id linking to the type of regulation of the agreement '
;

COMMENT ON COLUMN imna.beschikking_beheer_type_niet_snl.beheer_type_id
	IS 'Domain id linking to the type of maintenance '
;

COMMENT ON TABLE imna.beschikking_beheer_type_snl
	IS 'Detail information of a agreement for regarding the maintenance type for the following type_regeling: 1	SVNL-N 2016 2	SNL-N 3	SNL-A 4	SKNL 8	ANLb'
;

COMMENT ON COLUMN imna.beschikking_beheer_type_snl.beschikking_id
	IS 'ID linking to  the internal id of  the agreement'
;

COMMENT ON COLUMN imna.beschikking_beheer_type_snl.type_regeling_id
	IS 'Domain id linking to the type of regulation of the agreement '
;

COMMENT ON COLUMN imna.beschikking_beheer_type_snl.beheer_type_id
	IS 'Domain id linking to the type of maintenance '
;

COMMENT ON TABLE imna.beschikking_rapportage
	IS 'Meta data for an provincial upload of agreements (beschikkingen)'
;

COMMENT ON COLUMN imna.beschikking_rapportage.id
	IS 'Internal ID of the agreement upload'
;

COMMENT ON COLUMN imna.beschikking_rapportage.identificatie
	IS 'External ID of the agreement upload'
;

COMMENT ON COLUMN imna.beschikking_rapportage.begin_geldigheid
	IS 'Start of the validity for this version of the agreement upload'
;

COMMENT ON COLUMN imna.beschikking_rapportage.eind_geldigheid
	IS 'End of the validity for this version of the agreement upload'
;

COMMENT ON COLUMN imna.beschikking_rapportage.provincie_id
	IS 'Domain id linking to the province who is responsible for the agreement upload'
;

COMMENT ON COLUMN imna.beschikking_rapportage.beheer_jaar
	IS 'year of the agreement upload'
;
