/* ---------------------------------------------------- */
/*  Generated by Enterprise Architect Version 12.1 		*/
/*  Created On : 07-Feb-2022 14:49:52 				*/
/*  DBMS       : PostgreSQL 						*/
/* ---------------------------------------------------- */


ALTER TABLE imna.beschikking 
	ADD CONSTRAINT FK_beschikking_lnk_table_provincie_type_regeling
	FOREIGN KEY (provincie_id,type_regeling_id) REFERENCES masterdata.lnk_table_provincie_type_regeling (provincie_id,type_regeling_id) ON DELETE No Action ON UPDATE No Action
;

CREATE INDEX IXFK_beschikking_lnk_table_provincie_type_regeling ON imna.beschikking (provincie_id ASC,type_regeling_id ASC)
;
