variables:
  IMNa_PATH: D:\GitLab-Deployments\IMNa

include:
  - project: 'Generic/GenericCICDScripts'
    file: 'geoserver-scripts.yml' 
  - local: '/FME/workspaces/.gitlab-ci-IMNa_HAB_Publish.yml'
  - local: '/FME/workspaces/.gitlab-ci-IMNa_VEG_Submission.yml'
  - local: '/FME/workspaces/.gitlab-ci-IMNa_RNN_TaxaPerBeheertype_Submission.yml'
  - local: '/FME/workspaces/.gitlab-ci-IMNa_RNN_GPKG_Submission.yml'
  - local: '/FME/workspaces/.gitlab-ci-IMNa_VEG_Publish.yml'
  - local: '/FME/workspaces/.gitlab-ci-IMNa_SYNB_Submission.yml'
  - local: '/FME/workspaces/.gitlab-ci-IMNa_VEG_Unpublish.yml'
  - local: '/FME/workspaces/.gitlab-ci-IMNa_Generic_CustomTransformers.yml'
  - local: '/FME/workspaces/.gitlab-ci-IMNa_HAB_T0_Submission.yml'
  - local: '/FME/workspaces/.gitlab-ci-IMNa_HAB_Tx_Submission.yml'
  - local: '/FME/workspaces/.gitlab-ci-IMNa_HAB_Download.yml'
  - local: '/FME/workspaces/.gitlab-ci-IMNa_NDFF_Species_Submission.yml'
  - local: '/FME/workspaces/.gitlab-ci-IMNa_N2000_Submission.yml'
  - local: '/FME/workspaces/.gitlab-ci-IMNa_NBP_Submission.yml'
  - local: '/FME/workspaces/.gitlab-ci-IMNa_NBP_Validation.yml'
  - local: '/FME/workspaces/.gitlab-ci-IMNa_VRN_Validation.yml'
  - local: '/FME/workspaces/.gitlab-ci-IMNa_VRN_Submission.yml'
  - local: '/FME/workspaces/.gitlab-ci-IMNa_VRN_UpdateDatamart.yml'
  - local: '/FME/workspaces/.gitlab-ci-IMNa_NBP_UpdateDatamart.yml'
  - local: '/FME/workspaces/.gitlab-ci-IMNa_NBP_CreateRVOFile.yml'
  - local: '/FME/workspaces/.gitlab-ci-IMNa_VRN_CreateRVOFile.yml'
  - local: '/FME/workspaces/.gitlab-ci-IMNa_DSO_Workitems_Submission.yml'
  - local: '/FME/workspaces/.gitlab-ci-IMNa_BES_Validation.yml'
  - local: '/FME/workspaces/.gitlab-ci-IMNa_BES_Submission.yml'
  - local: '/FME/workspaces/.gitlab-ci-IMNa_BES_CreateRVOFile.yml'
  - local: '/FME/workspaces/.gitlab-ci-IMNa_BESI_Export_Submission.yml'
  - local: '/FME/workspaces/.gitlab-ci-IMNa_BESI_Import_Submission.yml'
  - local: '/FME/workspaces/.gitlab-ci-IMNa_IKN_WFS_Submission.yml'
  - local: '/FME/workspaces/.gitlab-ci-IMNa_IKN_WFS_Validation.yml'
  - local: '/FME/workspaces/.gitlab-ci-IMNa_IKN_N2K_Submission.yml'
  - local: '/FME/workspaces/.gitlab-ci-IMNa_IKN_FGDB_Submission.yml'  
  - local: '/FME/workspaces/.gitlab-ci-IMNa_IKN_FGDB_Validation.yml'      
  - local: '/FME/workspaces/.gitlab-ci-IMNa_HAB_Complete.yml'
  - local: '/FME/workspaces/.gitlab-ci-IMNa_IKN_End_Koppelvlak.yml'
  - local: '/FME/workspaces/.gitlab-ci-IMNa_SOVON.yml'
  - local: '/DB scripts/ANLB/.gitlab-ci-SNL.yml'
  - local: '/DB scripts/ANLB/.gitlab-ci-NDVH.yml'
  - local: '/DB scripts/ANLB/.gitlab-ci-RNN.yml'
  - local: '/DB scripts/ANLB/.gitlab-ci-Besi.yml'
  - local: '/DB scripts/IKN/.gitlab-ci-IKN.yml'
  - local: '/Geoweb/Sites/.gitlab-ci-NDVH_Prof.yml'
  - local: '/Geoweb/Sites/.gitlab-ci-SNL.yml'
  - local: '/GeoServer/Workspaces/.gitlab-ci-SNL_UPLOAD.yml'
  - local: '/GeoServer/Workspaces/.gitlab-ci-IMNa_NDVH.yml'
  - local: '/Geoweb/Sites/.gitlab-ci-BeSI_beheer.yml'
  - local: '/Geoweb/Sites/.gitlab-ci-BeSI_Rapport.yml'
  - local: '/Geoweb/Sites/.gitlab-ci-IKN_Pub.yml'
  - local: '/Geoweb/Sites/.gitlab-ci-ikn_pub_catalog.yml'
  - local: '/Geoweb/Sites/.gitlab-ci-SNL_historie.yml'
  - local: '/GeoServer/Workspaces/.gitlab-ci-IMNa_NBP.yml'
  - local: '/ArcGIS-Portal/.gitlab-ci-besi_public.yml'
  - local: '/DotNET/DSO-API/.gitlab-ci-besi-dso-api.yml'
  - local: '/DotNET/SecureFileAPI/.gitlab-ci-securefile-api.yml'
  - local: '/GeoServer/Workspaces/.gitlab-ci-IMNa_BES.yml'
  - local: '/GeoServer/Workspaces/.gitlab-ci-IMNa_VRN.yml'
  - local: '/GeoServer/Workspaces/.gitlab-ci-IMNa_BES_CURRENT.yml'
  - local: '/GeoServer/Workspaces/.gitlab-ci-IMNa_NBP_CURRENT.yml'
  - local: '/GeoServer/Workspaces/.gitlab-ci-IMNa_VRN_CURRENT.yml'
  - local: '/GeoServer/Workspaces/.gitlab-ci-SNL_CBP.yml'
  - local: '/GeoServer/Workspaces/.gitlab-ci-SNL_NBP.yml'
  - local: '/GeoServer/Workspaces/.gitlab-ci-IKN_UPLOAD.yml'
  - local: '/GeoServer/Workspaces/.gitlab-ci-IMNa_IKN.yml'
  - local: '/GeoServer/Workspaces/.gitlab-ci-IMNa_BESI.yml'
  - local: '/ArcGIS-Portal/.gitlab-ci-content_migration_test.yml'
  - local: '/ArcGIS-Portal/.gitlab-ci-ndvh-services.yml'
  - local: '/ArcGIS-Portal/.gitlab-ci-snl-services.yml'
  - local: '/ArcGIS-Portal/.gitlab-ci-ikn-services.yml'
  - local: '/ArcGIS-Portal/.gitlab-ci-rk-services.yml'
  - local: '/ArcGIS-Portal/.gitlab-ci-rnn-services.yml'
  - local: '/ArcGIS-Portal/.gitlab-ci-wmp-services.yml'
  - local: '/ArcGIS-Portal/.gitlab-ci-test-viewer.yml'
  - local: '/ArcGIS-Portal/.gitlab-ci-snl_catalog.yml'
  - local: '/ArcGIS-Portal/.gitlab-ci-ikn_catalog.yml'
  - local: '/ArcGIS-Portal/.gitlab-ci-generic.yml'
  - local: '/ArcGIS-Portal/.gitlab-ci-ikn.yml'
  - local: '/ArcGIS-Portal/.gitlab-ci-ndvh.yml'
  - local: '/ArcGIS-Portal/.gitlab-ci-snl.yml'
  - local: '/ArcGIS-Portal/.gitlab-ci-upload-portal-generic.yml'
  - local: '/ArcGIS-Portal/.gitlab-ci-upload-portal-besi.yml'
  - local: '/ArcGIS-Portal/.gitlab-ci-upload-portal-ndvh-habitat.yml'
  - local: '/ArcGIS-Portal/.gitlab-ci-upload-portal-ndvh-vegetation.yml'
  - local: '/ArcGIS-Portal/.gitlab-ci-upload-portal-snl-bes.yml'
  - local: '/ArcGIS-Portal/.gitlab-ci-upload-portal-snl-nbp.yml'
  - local: '/ArcGIS-Portal/.gitlab-ci-upload-portal-snl-vrn.yml'
  - local: '/ArcGIS-Portal/.gitlab-ci-upload-portal-ikn.yml'
  - local: '/ArcGIS-Portal/.gitlab-ci-upload-portal-rnn.yml'
  







