/* ---------------------------------------------------- */
/*  Generated by Enterprise Architect Version 12.1 		*/
/*  Created On : 19-Feb-2024 12:43:08 				*/
/*  DBMS       : PostgreSQL 						*/
/* ---------------------------------------------------- */


/* Create Tables */

CREATE TABLE IF NOT EXISTS ndff.ndff_waarnemingen
(
	id bigint NOT NULL   DEFAULT NEXTVAL(('ndff.ndff_sec'::text)::regclass),
	taxa_id bigint NOT NULL,
	species_group_id bigint NOT NULL,
	begin_geldigheid timestamp NOT NULL,
	eind_geldigheid timestamp NULL,
	geom geometry(point) NOT NULL    -- geometry of the waarneming, which will be indexed
)
;

ALTER TABLE ndff.ndff_waarnemingen
    OWNER to anlb;

CREATE TABLE IF NOT EXISTS ndff.rode_lijst_categorie
(
	id bigint NOT NULL   DEFAULT NEXTVAL(('ndff.ndff_sec'::text)::regclass),
	identity varchar(255) NOT NULL,
	naam varchar(50) NULL,
	description text NULL,
	index_value varchar(255) NULL,
	begin_geldigheid timestamp NOT NULL,
	eind_geldigheid timestamp NULL
)
;

ALTER TABLE ndff.rode_lijst_categorie
    OWNER to anlb;

CREATE TABLE IF NOT EXISTS ndff.rode_lijst_soort
(
	taxa_id bigint NOT NULL,
	rode_lijst_categorie_id bigint NOT NULL,
	begin_geldigheid timestamp NOT NULL,
	eind_geldigheid timestamp NULL
)
;

ALTER TABLE ndff.rode_lijst_soort
    OWNER to anlb;


/* Create Primary Keys, Indexes, Uniques, Checks */


SELECT pg_temp.create_constraint_if_not_exists ('ndff','ndff_waarnemingen','PK_ndff_waarnemingen',
'ALTER TABLE ndff.ndff_waarnemingen ADD CONSTRAINT PK_ndff_waarnemingen
	PRIMARY KEY (id)
;');

CREATE INDEX IF NOT EXISTS IXFK_ndff_waarnemingen_species_group ON ndff.ndff_waarnemingen (species_group_id ASC);

CREATE INDEX IF NOT EXISTS IXFK_ndff_waarnemingen_taxa ON ndff.ndff_waarnemingen (taxa_id ASC);

SELECT pg_temp.create_constraint_if_not_exists ('ndff','rode_lijst_categorie','PK_rode_lijst_categorie',
'ALTER TABLE ndff.rode_lijst_categorie ADD CONSTRAINT PK_rode_lijst_categorie
	PRIMARY KEY (id)
;');

SELECT pg_temp.create_constraint_if_not_exists ('ndff','rode_lijst_categorie','UN_rode_lijst_categorie_identificatie',
'ALTER TABLE ndff.rode_lijst_categorie ADD CONSTRAINT UN_rode_lijst_categorie_identificatie UNIQUE (identity)
;');

SELECT pg_temp.create_constraint_if_not_exists ('ndff','rode_lijst_soort','PK_rode_lijst_soort',
'ALTER TABLE ndff.rode_lijst_soort ADD CONSTRAINT PK_rode_lijst_soort
	PRIMARY KEY (taxa_id,rode_lijst_categorie_id,begin_geldigheid)
;');

CREATE INDEX IF NOT EXISTS IXFK_rode_lijst_soort_rode_lijst_categorie ON ndff.rode_lijst_soort (rode_lijst_categorie_id ASC);

CREATE INDEX IF NOT EXISTS IXFK_rode_lijst_soort_taxa ON ndff.rode_lijst_soort (taxa_id ASC);



/* Create Foreign Key Constraints */

SELECT pg_temp.create_constraint_if_not_exists ('ndff','ndff_waarnemingen','FK_ndff_waarnemingen_species_group',
'ALTER TABLE ndff.ndff_waarnemingen ADD CONSTRAINT FK_ndff_waarnemingen_species_group
	FOREIGN KEY (species_group_id) REFERENCES ndff.species_group (id) ON DELETE No Action ON UPDATE No Action
;');

SELECT pg_temp.create_constraint_if_not_exists ('ndff','ndff_waarnemingen','FK_ndff_waarnemingen_taxa',
'ALTER TABLE ndff.ndff_waarnemingen ADD CONSTRAINT FK_ndff_waarnemingen_taxa
	FOREIGN KEY (taxa_id) REFERENCES ndff.taxa (id) ON DELETE No Action ON UPDATE No Action
;');

SELECT pg_temp.create_constraint_if_not_exists ('ndff','rode_lijst_soort','FK_rode_lijst_soort_rode_lijst_categorie',
'ALTER TABLE ndff.rode_lijst_soort ADD CONSTRAINT FK_rode_lijst_soort_rode_lijst_categorie
	FOREIGN KEY (rode_lijst_categorie_id) REFERENCES ndff.rode_lijst_categorie (id) ON DELETE No Action ON UPDATE No Action
;');

SELECT pg_temp.create_constraint_if_not_exists ('ndff','rode_lijst_soort','FK_rode_lijst_soort_taxa',
'ALTER TABLE ndff.rode_lijst_soort ADD CONSTRAINT FK_rode_lijst_soort_taxa
	FOREIGN KEY (taxa_id) REFERENCES ndff.taxa (id) ON DELETE No Action ON UPDATE No Action
;');


/* Create Table Comments, Sequences for Autonumber Columns */


COMMENT ON COLUMN ndff.ndff_waarnemingen.geom
	IS 'geometry of the waarneming, which will be indexed'
;

/* Added with the correct name in file imna-17929-added-index-on-geom-on-observations-table.sql
CREATE INDEX IF NOT EXISTS "IDX_basis_grid_geom"
    ON ndff.ndff_waarnemingen USING gist
    (geom);
*/

GRANT SELECT ON ALL TABLES IN SCHEMA ndff TO anlb_sqlpad;