




-- Rename tables
ALTER TABLE besi.besi_species_group_kans_versie_staging RENAME TO besi_species_group_kans_versie;
ALTER TABLE besi.besi_species_group_kansen_huidig_staging RENAME TO besi_species_group_kansen_huidig;
ALTER TABLE besi.taxa_kans_versie_staging RENAME TO taxa_kans_versie;
ALTER TABLE besi.taxa_kansen_huidig_staging RENAME TO taxa_kansen_huidig;

ALTER TABLE geoweb.besi_geotiff_staging RENAME TO besi_geotiff;
ALTER TABLE geoweb.besi_geotiff_files_staging RENAME TO besi_geotiff_files;
ALTER TABLE geoweb.besi_species_group_geotiff_staging RENAME TO besi_species_group_geotiff;
ALTER TABLE geoweb.besi_species_group_geotiff_files_staging RENAME TO besi_species_group_geotiff_files;

-- Rename constraints and indexes
ALTER TABLE besi.besi_species_group_kans_versie RENAME CONSTRAINT pk_besi_species_group_kans_versie_staging TO pk_besi_species_group_kans_versie;
ALTER TABLE besi.besi_species_group_kans_versie RENAME CONSTRAINT fk_besi_species_group_kans_versie_staging_besi_species_group TO fk_besi_species_group_kans_versie_besi_species_group;
ALTER INDEX besi.ixfk_besi_species_group_kans_versie_staging_besi_species_group RENAME TO ixfk_besi_species_group_kans_versie_besi_species_group;



ALTER TABLE besi.besi_species_group_kansen_huidig RENAME CONSTRAINT pk_besi_species_group_kansen_huidig_staging TO pk_besi_species_group_kansen_huidig;
ALTER TABLE besi.besi_species_group_kansen_huidig RENAME CONSTRAINT fk_besi_species_group_kansen_huidig_staging_basis_grid TO fk_besi_species_group_kansen_huidig_basis_grid;
ALTER TABLE besi.besi_species_group_kansen_huidig RENAME CONSTRAINT fk_besi_species_group_kansen_huidig_staging_besi_species_group TO fk_besi_species_group_kansen_huidig_besi_species_group;



ALTER TABLE besi.taxa_kans_versie RENAME CONSTRAINT pk_taxa_kans_versie_staging TO pk_taxa_kans_versie;
ALTER TABLE besi.taxa_kans_versie RENAME CONSTRAINT fk_taxa_kans_versie_taxa_staging TO fk_taxa_kans_versie_taxa;
ALTER INDEX besi.ixfk_taxa_kans_versie_staging_taxa RENAME TO ixfk_taxa_kans_versie_taxa;



ALTER TABLE besi.taxa_kansen_huidig RENAME CONSTRAINT pk_taxa_kansen_huidig_staging TO pk_taxa_kansen_huidig;
ALTER TABLE besi.taxa_kansen_huidig RENAME CONSTRAINT fk_taxa_kansen_huidig_staging_basis_grid TO fk_taxa_kansen_huidig_basis_grid;
ALTER TABLE besi.taxa_kansen_huidig RENAME CONSTRAINT fk_taxa_kansen_huidig_staging_taxa TO fk_taxa_kansen_huidig_taxa;




-- Rename staging constraints and indexes to correct name
ALTER TABLE geoweb.besi_geotiff RENAME CONSTRAINT pk_besi_geotiff_staging TO pk_besi_geotiff;
ALTER TABLE geoweb.besi_geotiff RENAME CONSTRAINT fk_besi_geotiff_staging_taxa_kans_versie TO fk_besi_geotiff_taxa_kans_versie;
ALTER INDEX geoweb.ixfk_besi_geotiff_staging_taxa_kans_versie RENAME TO ixfk_besi_geotiff_taxa_kans_versie;

ALTER TABLE geoweb.besi_geotiff_files RENAME CONSTRAINT pk_besi_geotiff_files_staging TO pk_besi_geotiff_files;
ALTER TABLE geoweb.besi_geotiff_files RENAME CONSTRAINT fk_besi_geotiff_files_staging_besi_geotiff TO fk_besi_geotiff_files_besi_geotiff;

ALTER TABLE geoweb.besi_species_group_geotiff RENAME CONSTRAINT pk_besi_species_group_geotiff_staging TO pk_besi_species_group_geotiff;
ALTER TABLE geoweb.besi_species_group_geotiff RENAME CONSTRAINT fk_besi_species_group_geotiff_staging_besi_species_group_kans_v TO fk_besi_species_group_geotiff_besi_species_group_kans_versie;
ALTER INDEX geoweb.ixfk_besi_species_group_geotiff_staging_besi_species_group RENAME TO ixfk_besi_species_group_geotiff_besi_species_group;

ALTER TABLE geoweb.besi_species_group_geotiff_files RENAME CONSTRAINT pk_besi_species_group_geotiff_files_staging TO pk_besi_species_group_geotiff_files;
ALTER TABLE geoweb.besi_species_group_geotiff_files RENAME CONSTRAINT fk_besi_species_group_geotiff_files_staging_besi_species_group_ TO fk_besi_species_group_geotiff_files_besi_species_group_geotiff;