
-- Rename tables
ALTER TABLE besi.besi_species_group_kans_versie RENAME TO besi_species_group_kans_versie_old;
ALTER TABLE besi.besi_species_group_kansen_huidig RENAME TO besi_species_group_kansen_huidig_old;
ALTER TABLE besi.taxa_kans_versie RENAME TO taxa_kans_versie_old;
ALTER TABLE besi.taxa_kansen_huidig RENAME TO taxa_kansen_huidig_old;

ALTER TABLE geoweb.besi_geotiff RENAME TO besi_geotiff_old;
ALTER TABLE geoweb.besi_geotiff_files RENAME TO besi_geotiff_files_old;
ALTER TABLE geoweb.besi_species_group_geotiff RENAME TO besi_species_group_geotiff_old;
ALTER TABLE geoweb.besi_species_group_geotiff_files RENAME TO besi_species_group_geotiff_files_old;

-- Rename constraints and indexes
ALTER TABLE besi.besi_species_group_kans_versie_old RENAME CONSTRAINT pk_besi_species_group_kans_versie TO pk_besi_species_group_kans_versie_old;
ALTER TABLE besi.besi_species_group_kans_versie_old RENAME CONSTRAINT fk_besi_species_group_kans_versie_besi_species_group TO fk_besi_species_group_kans_versie_old_besi_species_group;
ALTER INDEX besi.ixfk_besi_species_group_kans_versie_besi_species_group RENAME TO ixfk_besi_species_group_kans_versie_old_besi_species_group;


ALTER TABLE besi.besi_species_group_kansen_huidig_old RENAME CONSTRAINT pk_besi_species_group_kansen_huidig TO pk_besi_species_group_kansen_huidig_old;
ALTER TABLE besi.besi_species_group_kansen_huidig_old RENAME CONSTRAINT fk_besi_species_group_kansen_huidig_basis_grid TO fk_besi_species_group_kansen_huidig_old_basis_grid;
ALTER TABLE besi.besi_species_group_kansen_huidig_old RENAME CONSTRAINT fk_besi_species_group_kansen_huidig_besi_species_group TO fk_besi_species_group_kansen_huidig_old_besi_species_group;


ALTER TABLE besi.taxa_kans_versie_old RENAME CONSTRAINT pk_taxa_kans_versie TO pk_taxa_kans_versie_old;
ALTER TABLE besi.taxa_kans_versie_old RENAME CONSTRAINT fk_taxa_kans_versie_taxa TO fk_taxa_kans_versie_old_taxa;
ALTER INDEX besi.ixfk_taxa_kans_versie_taxa RENAME TO ixfk_taxa_kans_versie_old_taxa;


ALTER TABLE besi.taxa_kansen_huidig_old RENAME CONSTRAINT pk_taxa_kansen_huidig TO pk_taxa_kansen_huidig_old;
ALTER TABLE besi.taxa_kansen_huidig_old RENAME CONSTRAINT fk_taxa_kansen_huidig_basis_grid TO fk_taxa_kansen_huidig_old_basis_grid;
ALTER TABLE besi.taxa_kansen_huidig_old RENAME CONSTRAINT fk_taxa_kansen_huidig_taxa TO fk_taxa_kansen_huidig_old_taxa;




ALTER TABLE geoweb.besi_geotiff_old RENAME CONSTRAINT pk_besi_geotiff TO pk_besi_geotiff_old;
ALTER TABLE geoweb.besi_geotiff_old RENAME CONSTRAINT fk_besi_geotiff_taxa_kans_versie TO fk_besi_geotiff_old_taxa_kans_versie;
ALTER INDEX geoweb.ixfk_besi_geotiff_taxa_kans_versie RENAME TO ixfk_besi_geotiff_old_taxa_kans_versie;

ALTER TABLE geoweb.besi_geotiff_files_old RENAME CONSTRAINT pk_besi_geotiff_files TO pk_besi_geotiff_files_old;
ALTER TABLE geoweb.besi_geotiff_files_old RENAME CONSTRAINT FK_besi_geotiff_files_besi_geotiff TO FK_besi_geotiff_files_old_besi_geotiff;


ALTER TABLE geoweb.besi_species_group_geotiff_old RENAME CONSTRAINT PK_besi_species_group_geotiff TO PK_besi_species_group_geotiff_old;
ALTER TABLE geoweb.besi_species_group_geotiff_old RENAME CONSTRAINT FK_besi_species_group_geotiff_besi_species_group_kans_versie TO FK_besi_species_group_geotiff_old_besi_species_group_kans_versi;
ALTER INDEX geoweb.ixfk_besi_species_group_geotiff_besi_species_group RENAME TO ixfk_besi_species_group_old_geotiff_besi_species_group;


ALTER TABLE geoweb.besi_species_group_geotiff_files_old RENAME CONSTRAINT PK_besi_species_group_geotiff_files TO PK_besi_species_group_geotiff_files_old;
ALTER TABLE geoweb.besi_species_group_geotiff_files_old RENAME CONSTRAINT fk_besi_species_group_geotiff_files_besi_species_group_geotiff TO fk_besi_species_group_geotiff_old_files_besi_species_group_geot;

