/* ---------------------------------------------------- */
/*  Generated by Enterprise Architect Version 12.1 		*/
/*  Created On : 17-Mar-2020 10:50:08 				*/
/*  DBMS       : PostgreSQL 						*/
/* ---------------------------------------------------- */

/* Drop Tables */

DROP TABLE IF EXISTS etl.etl_run_geometries_staging CASCADE
;

/* Create Tables */

CREATE TABLE etl.etl_run_geometries_staging
(
	etl_id bigint NOT NULL,
	layer char(100) NOT NULL,
	identificatie char(100) NOT NULL,
	geom geometry NOT NULL
)
;

/* Create Primary Keys, Indexes, Uniques, Checks */

ALTER TABLE etl.etl_run_geometries_staging ADD CONSTRAINT PK_etl_run_geometries_staging
	PRIMARY KEY (etl_id,layer,identificatie)
;

CREATE INDEX IXFK_etl_run_geometries_staging_etl_run ON etl.etl_run_geometries_staging (etl_id ASC)
;

/* Create Foreign Key Constraints */

ALTER TABLE etl.etl_run_geometries_staging ADD CONSTRAINT FK_etl_run_geometries_staging_etl_run
	FOREIGN KEY (etl_id) REFERENCES etl.etl_run (id) ON DELETE No Action ON UPDATE No Action
;

ALTER TABLE etl.etl_run_geometries_staging
    OWNER to anlb;
	
GRANT SELECT ON ALL TABLES IN SCHEMA etl TO anlb_sqlpad;	