/* ---------------------------------------------------- */
/*  Generated by Enterprise Architect Version 12.1 		*/
/*  Created On : 11-Mar-2022 4:23:38 PM 				*/
/*  DBMS       : PostgreSQL 						*/
/* ---------------------------------------------------- */

/* Drop Tables */

DROP TABLE IF EXISTS geoweb.snl_vrn_upload CASCADE
;

DROP TABLE IF EXISTS geoweb.snl_vrn_upload_files CASCADE
;

/* Create Tables */

CREATE TABLE geoweb.snl_vrn_upload
(
	id bigint NOT NULL,
	voortgangs_rapportage_id bigint NULL,
	provincie_id bigint NOT NULL,
	voortgangs_rapportage_jaar integer NOT NULL,
	upload_date timestamp NOT NULL,
	user_id varchar(50) NOT NULL,
	contains_errors boolean NOT NULL,
	type_run varchar(40) NOT NULL,
	status varchar(50) NOT NULL
)
;

CREATE TABLE geoweb.snl_vrn_upload_files
(
	snl_vrn_upload_id bigint NOT NULL,
	sequence bigint NOT NULL,
	file_name varchar(1024) NOT NULL,
	file_type varchar(50) NOT NULL
)
;

/* Create Primary Keys, Indexes, Uniques, Checks */

ALTER TABLE geoweb.snl_vrn_upload ADD CONSTRAINT PK_snl_vrn_upload
	PRIMARY KEY (id)
;

CREATE INDEX IXFK_snl_vrn_upload_dmn_provincie_code ON geoweb.snl_vrn_upload (provincie_id ASC)
;

CREATE INDEX IXFK_snl_vrn_upload_voortgangs_rapportage ON geoweb.snl_vrn_upload (voortgangs_rapportage_id ASC)
;

ALTER TABLE geoweb.snl_vrn_upload_files ADD CONSTRAINT PK_snl_vrn_upload_files
	PRIMARY KEY (sequence,snl_vrn_upload_id)
;

CREATE INDEX IXFK_snl_vrn_upload_files_snl_vrn_upload ON geoweb.snl_vrn_upload_files (snl_vrn_upload_id ASC)
;

/* Create Foreign Key Constraints */

ALTER TABLE geoweb.snl_vrn_upload ADD CONSTRAINT FK_snl_vrn_upload_dmn_provincie_code
	FOREIGN KEY (provincie_id) REFERENCES masterdata.dmn_provincie_code (id) ON DELETE No Action ON UPDATE No Action
;

ALTER TABLE geoweb.snl_vrn_upload ADD CONSTRAINT FK_snl_vrn_upload_voortgangs_rapportage
	FOREIGN KEY (voortgangs_rapportage_id) REFERENCES imna.voortgangs_rapportage (id) ON DELETE No Action ON UPDATE No Action
;

ALTER TABLE geoweb.snl_vrn_upload_files ADD CONSTRAINT FK_snl_vrn_upload_files_snl_vrn_upload
	FOREIGN KEY (snl_vrn_upload_id) REFERENCES geoweb.snl_vrn_upload (id) ON DELETE No Action ON UPDATE No Action
;
