/* ---------------------------------------------------- */
/*  Generated by Enterprise Architect Version 12.1 		*/
/*  Created On : 09-Nov-2021 08:44:47 				*/
/*  DBMS       : PostgreSQL 						*/
/* ---------------------------------------------------- */

ALTER TABLE imna.informatie_kaart_natuur DROP CONSTRAINT UN_natuur_indentificatie 
;
ALTER TABLE imna.informatie_kaart_natuur ADD CONSTRAINT UN_natuur_indentificatie UNIQUE (identificatie,begin_geldigheid,bron_houder_id,beleid_naam_id)
;



