/* ---------------------------------------------------- */
/*  Generated by Enterprise Architect Version 12.1 		*/
/*  Created On : 24-Oct-2023 16:28:00 				*/
/*  DBMS       : PostgreSQL 						*/
/* ---------------------------------------------------- */


/* Create Tables */

CREATE TABLE IF NOT EXISTS imna.beschikking
(
	id bigint NOT NULL   DEFAULT NEXTVAL(('imna_seq'::text)::regclass),    -- Internal ID of the agreement
	identificatie char(100) NOT NULL,    -- External ID of the agreement
	begin_geldigheid timestamp NOT NULL,    -- Start of the validity for this version of the agreement
	eind_geldigheid timestamp NULL,    -- End of the validity for this version of the agreement
	provincie_id bigint NOT NULL,    -- Domain id linking to the province who is responsible for the agreement
	beschikking_rapportage_id bigint NOT NULL,    -- Id linking to the agreement upload used to submit this version of the agreement
	begin_tijd timestamp NOT NULL,    -- Start of the validity for this version of the agreement identified by the idenficatie and provinceId
	eind_tijd timestamp NOT NULL,    -- End of the validity for this version of the agreement identified by the idenficatie and provinceId
	contract_nummer char(20) NOT NULL,    -- contract number of the agreement
	datum_beschikking timestamp NOT NULL,    -- Date the agreement was signed
	status_aanvraag_subsidie_id bigint NOT NULL,    -- Domain id linking to the status of the agreement
	type_regeling_id bigint NOT NULL,    -- Domain id linking to the type of regulation of the agreement 
	geom geometry NOT NULL    -- Geometry single polygon in EPSG:28992 of the agreement
)
;

ALTER TABLE imna.beschikking
    OWNER to anlb;

CREATE TABLE IF NOT EXISTS imna.beschikking_beheer_type_niet_snl
(
	beschikking_id bigint NOT NULL,    -- ID linking to  the internal id of  the agreement
	type_regeling_id bigint NOT NULL,    -- Domain id linking to the type of regulation of the agreement 
	beheer_type_id bigint NULL    -- Domain id linking to the type of maintenance 
)
;

ALTER TABLE imna.beschikking_beheer_type_niet_snl
    OWNER to anlb;

CREATE TABLE IF NOT EXISTS imna.beschikking_beheer_type_snl
(
	beschikking_id bigint NOT NULL,    -- ID linking to  the internal id of  the agreement
	type_regeling_id bigint NOT NULL,    -- Domain id linking to the type of regulation of the agreement 
	beheer_type_id bigint NOT NULL    -- Domain id linking to the type of maintenance 
)
;

ALTER TABLE imna.beschikking_beheer_type_snl
    OWNER to anlb;

CREATE TABLE IF NOT EXISTS imna.beschikking_rapportage
(
	id bigint NOT NULL   DEFAULT NEXTVAL(('imna_seq'::text)::regclass),    -- Internal ID of the agreement upload
	identificatie char(100) NOT NULL,    -- External ID of the agreement upload
	begin_geldigheid timestamp NOT NULL,    -- Start of the validity for this version of the agreement upload
	eind_geldigheid timestamp NULL,    -- End of the validity for this version of the agreement upload
	provincie_id bigint NOT NULL,    -- Domain id linking to the province who is responsible for the agreement upload
	beheer_jaar smallint NOT NULL    -- year of the agreement upload
)
;

ALTER TABLE imna.beschikking_rapportage
    OWNER to anlb;

/* Create Primary Keys, Indexes, Uniques, Checks */

SELECT pg_temp.create_constraint_if_not_exists ('imna','beschikking','PK_beschikking',
'ALTER TABLE imna.beschikking ADD CONSTRAINT PK_beschikking
	PRIMARY KEY (id)
;');

SELECT pg_temp.create_constraint_if_not_exists ('imna','beschikking','UN_beschikking_indentificatie',
'ALTER TABLE imna.beschikking ADD CONSTRAINT UN_beschikking_indentificatie UNIQUE (provincie_id,identificatie,begin_geldigheid)
;');

CREATE INDEX IF NOT EXISTS IXFK_beschikking_beschikking_jaar ON imna.beschikking (beschikking_rapportage_id ASC)
;

CREATE INDEX IF NOT EXISTS IXFK_beschikking_lnk_table_provincie_type_regeling ON imna.beschikking (provincie_id ASC,type_regeling_id ASC)
;

CREATE INDEX IF NOT EXISTS IXFK_dmn_provincie_code_17 ON imna.beschikking (provincie_id ASC)
;

CREATE INDEX IF NOT EXISTS IXFK_dmn_status_aanvraag_subsidie_1 ON imna.beschikking (status_aanvraag_subsidie_id ASC)
;

CREATE INDEX IF NOT EXISTS IXFK_dmn_type_regeling_1 ON imna.beschikking (type_regeling_id ASC)
;

SELECT pg_temp.create_constraint_if_not_exists ('imna','beschikking_beheer_type_niet_snl','PK_beschikking_beheertype_niet_snl',
'ALTER TABLE imna.beschikking_beheer_type_niet_snl ADD CONSTRAINT PK_beschikking_beheertype_niet_snl
	PRIMARY KEY (beschikking_id)
;');

CREATE INDEX IF NOT EXISTS IXFK_beschikking_2 ON imna.beschikking_beheer_type_niet_snl (beschikking_id ASC)
;

CREATE INDEX IF NOT EXISTS IXFK_dmn_beheer_type_5 ON imna.beschikking_beheer_type_niet_snl (beheer_type_id ASC)
;

CREATE INDEX IF NOT EXISTS IXFK_dmn_beheer_type_niet_snl_1 ON imna.beschikking_beheer_type_niet_snl (type_regeling_id ASC)
;

SELECT pg_temp.create_constraint_if_not_exists ('imna','beschikking_beheer_type_snl','PK_beschikking_beheertype_snl',
'ALTER TABLE imna.beschikking_beheer_type_snl ADD CONSTRAINT PK_beschikking_beheertype_snl
	PRIMARY KEY (beschikking_id)
;');

CREATE INDEX IF NOT EXISTS IXFK_beschikking_1 ON imna.beschikking_beheer_type_snl (beschikking_id ASC)
;

CREATE INDEX IF NOT EXISTS IXFK_lnk_table_beheer_type_regeling_1 ON imna.beschikking_beheer_type_snl (type_regeling_id ASC,beheer_type_id ASC)
;

SELECT pg_temp.create_constraint_if_not_exists ('imna','beschikking_rapportage','PK_beschikking_rapportage',
'ALTER TABLE imna.beschikking_rapportage ADD CONSTRAINT PK_beschikking_rapportage
	PRIMARY KEY (id)
;');

SELECT pg_temp.create_constraint_if_not_exists ('imna','beschikking_rapportage','UN_beschikking_rapportage',
'ALTER TABLE imna.beschikking_rapportage ADD CONSTRAINT UN_beschikking_rapportage UNIQUE (provincie_id,identificatie,begin_geldigheid)
;');

CREATE INDEX IF NOT EXISTS IXFK_dmn_provincie_code_16 ON imna.beschikking_rapportage (provincie_id ASC)
;

/* Create Foreign Key Constraints */

SELECT pg_temp.create_constraint_if_not_exists ('imna','beschikking','FK_beschikking_beschikking_jaar',
'ALTER TABLE imna.beschikking ADD CONSTRAINT FK_beschikking_beschikking_jaar
	FOREIGN KEY (beschikking_rapportage_id) REFERENCES imna.beschikking_rapportage (id) ON DELETE No Action ON UPDATE No Action
;');

SELECT pg_temp.create_constraint_if_not_exists ('imna','beschikking','FK_beschikking_lnk_table_provincie_type_regeling',
'ALTER TABLE imna.beschikking ADD CONSTRAINT FK_beschikking_lnk_table_provincie_type_regeling
	FOREIGN KEY (provincie_id,type_regeling_id) REFERENCES masterdata.lnk_table_provincie_type_regeling (provincie_id,type_regeling_id) ON DELETE No Action ON UPDATE No Action
;');

SELECT pg_temp.create_constraint_if_not_exists ('imna','beschikking','FK_beschikking_lnk_table_provincie_type_regeling',
'ALTER TABLE imna.beschikking ADD CONSTRAINT FK_beschikking_lnk_table_provincie_type_regeling
	FOREIGN KEY (provincie_id,type_regeling_id) REFERENCES masterdata.lnk_table_provincie_type_regeling (provincie_id,type_regeling_id) ON DELETE No Action ON UPDATE No Action
;');

SELECT pg_temp.create_constraint_if_not_exists ('imna','beschikking','FK_dmn_provincie_code_17',
'ALTER TABLE imna.beschikking ADD CONSTRAINT FK_dmn_provincie_code_17
	FOREIGN KEY (provincie_id) REFERENCES masterdata.dmn_provincie_code (id) ON DELETE No Action ON UPDATE No Action
;');

SELECT pg_temp.create_constraint_if_not_exists ('imna','beschikking','FK_dmn_status_aanvraag_subsidie_1',
'ALTER TABLE imna.beschikking ADD CONSTRAINT FK_dmn_status_aanvraag_subsidie_1
	FOREIGN KEY (status_aanvraag_subsidie_id) REFERENCES masterdata.dmn_status_aanvraag_subsidie (id) ON DELETE No Action ON UPDATE No Action
;');

SELECT pg_temp.create_constraint_if_not_exists ('imna','beschikking','FK_dmn_type_regeling_1',
'ALTER TABLE imna.beschikking ADD CONSTRAINT FK_dmn_type_regeling_1
	FOREIGN KEY (type_regeling_id) REFERENCES masterdata.dmn_type_regeling (id) ON DELETE No Action ON UPDATE No Action
;');

SELECT pg_temp.create_constraint_if_not_exists ('imna','beschikking_beheer_type_niet_snl','FK_beschikking_2',
'ALTER TABLE imna.beschikking_beheer_type_niet_snl ADD CONSTRAINT FK_beschikking_2
	FOREIGN KEY (beschikking_id) REFERENCES imna.beschikking (id) ON DELETE No Action ON UPDATE No Action
;');

SELECT pg_temp.create_constraint_if_not_exists ('imna','beschikking_beheer_type_niet_snl','FK_dmn_beheer_type_beschikking_niet_snl_01',
'ALTER TABLE imna.beschikking_beheer_type_niet_snl ADD CONSTRAINT FK_dmn_beheer_type_beschikking_niet_snl_01
	FOREIGN KEY (beheer_type_id) REFERENCES masterdata.dmn_beheer_type_beschikking_niet_snl (id) ON DELETE No Action ON UPDATE No Action
;');

SELECT pg_temp.create_constraint_if_not_exists ('imna','beschikking_beheer_type_niet_snl','FK_dmn_beheer_type_niet_snl_1',
'ALTER TABLE imna.beschikking_beheer_type_niet_snl ADD CONSTRAINT FK_dmn_beheer_type_niet_snl_1
	FOREIGN KEY (type_regeling_id) REFERENCES masterdata.dmn_type_regeling_niet_snl (id) ON DELETE No Action ON UPDATE No Action
;');

SELECT pg_temp.create_constraint_if_not_exists ('imna','beschikking_beheer_type_snl','FK_beschikking_1',
'ALTER TABLE imna.beschikking_beheer_type_snl ADD CONSTRAINT FK_beschikking_1
	FOREIGN KEY (beschikking_id) REFERENCES imna.beschikking (id) ON DELETE No Action ON UPDATE No Action
;');

SELECT pg_temp.create_constraint_if_not_exists ('imna','beschikking_beheer_type_snl','FK_lnk_table_beheer_type_regeling_1',
'ALTER TABLE imna.beschikking_beheer_type_snl ADD CONSTRAINT FK_lnk_table_beheer_type_regeling_1
	FOREIGN KEY (type_regeling_id,beheer_type_id) REFERENCES masterdata.lnk_table_beheer_type_regeling (type_regeling_id,beheer_type_id) ON DELETE No Action ON UPDATE No Action
;');

SELECT pg_temp.create_constraint_if_not_exists ('imna','beschikking_rapportage','FK_dmn_provincie_code_16',
'ALTER TABLE imna.beschikking_rapportage ADD CONSTRAINT FK_dmn_provincie_code_16
	FOREIGN KEY (provincie_id) REFERENCES masterdata.dmn_provincie_code (id) ON DELETE No Action ON UPDATE No Action
;');

/* Create Table Comments, Sequences for Autonumber Columns */

COMMENT ON TABLE imna.beschikking
	IS 'Agreement between a province and a collective to provide nature maintenance for a certain area'
;

COMMENT ON COLUMN imna.beschikking.id
	IS 'Internal ID of the agreement'
;

COMMENT ON COLUMN imna.beschikking.identificatie
	IS 'External ID of the agreement'
;

COMMENT ON COLUMN imna.beschikking.begin_geldigheid
	IS 'Start of the validity for this version of the agreement'
;

COMMENT ON COLUMN imna.beschikking.eind_geldigheid
	IS 'End of the validity for this version of the agreement'
;

COMMENT ON COLUMN imna.beschikking.provincie_id
	IS 'Domain id linking to the province who is responsible for the agreement'
;

COMMENT ON COLUMN imna.beschikking.beschikking_rapportage_id
	IS 'Id linking to the agreement upload used to submit this version of the agreement'
;

COMMENT ON COLUMN imna.beschikking.begin_tijd
	IS 'Start of the validity for this version of the agreement identified by the idenficatie and provinceId'
;

COMMENT ON COLUMN imna.beschikking.eind_tijd
	IS 'End of the validity for this version of the agreement identified by the idenficatie and provinceId'
;

COMMENT ON COLUMN imna.beschikking.contract_nummer
	IS 'contract number of the agreement'
;

COMMENT ON COLUMN imna.beschikking.datum_beschikking
	IS 'Date the agreement was signed'
;

COMMENT ON COLUMN imna.beschikking.status_aanvraag_subsidie_id
	IS 'Domain id linking to the status of the agreement'
;

COMMENT ON COLUMN imna.beschikking.type_regeling_id
	IS 'Domain id linking to the type of regulation of the agreement '
;

COMMENT ON COLUMN imna.beschikking.geom
	IS 'Geometry single polygon in EPSG:28992 of the agreement'
;

COMMENT ON TABLE imna.beschikking_beheer_type_niet_snl
	IS 'Detail information of a agreement for regarding the maintenance type for the following type_regeling: 5	TRPN 6	GroenBlauwe Diensten 7	Regeling Experimenten'
;

COMMENT ON COLUMN imna.beschikking_beheer_type_niet_snl.beschikking_id
	IS 'ID linking to  the internal id of  the agreement'
;

COMMENT ON COLUMN imna.beschikking_beheer_type_niet_snl.type_regeling_id
	IS 'Domain id linking to the type of regulation of the agreement '
;

COMMENT ON COLUMN imna.beschikking_beheer_type_niet_snl.beheer_type_id
	IS 'Domain id linking to the type of maintenance '
;

COMMENT ON TABLE imna.beschikking_beheer_type_snl
	IS 'Detail information of a agreement for regarding the maintenance type for the following type_regeling: 1	SVNL-N 2016 2	SNL-N 3	SNL-A 4	SKNL 8	ANLb'
;

COMMENT ON COLUMN imna.beschikking_beheer_type_snl.beschikking_id
	IS 'ID linking to  the internal id of  the agreement'
;

COMMENT ON COLUMN imna.beschikking_beheer_type_snl.type_regeling_id
	IS 'Domain id linking to the type of regulation of the agreement '
;

COMMENT ON COLUMN imna.beschikking_beheer_type_snl.beheer_type_id
	IS 'Domain id linking to the type of maintenance '
;

COMMENT ON TABLE imna.beschikking_rapportage
	IS 'Meta data for an provincial upload of agreements (beschikkingen)'
;

COMMENT ON COLUMN imna.beschikking_rapportage.id
	IS 'Internal ID of the agreement upload'
;

COMMENT ON COLUMN imna.beschikking_rapportage.identificatie
	IS 'External ID of the agreement upload'
;

COMMENT ON COLUMN imna.beschikking_rapportage.begin_geldigheid
	IS 'Start of the validity for this version of the agreement upload'
;

COMMENT ON COLUMN imna.beschikking_rapportage.eind_geldigheid
	IS 'End of the validity for this version of the agreement upload'
;

COMMENT ON COLUMN imna.beschikking_rapportage.provincie_id
	IS 'Domain id linking to the province who is responsible for the agreement upload'
;

COMMENT ON COLUMN imna.beschikking_rapportage.beheer_jaar
	IS 'year of the agreement upload'
;


/* Create Views */

CREATE OR REPLACE VIEW imna.bes_reports AS 
 SELECT r.id,
    r.begin_geldigheid,
    r.eind_geldigheid,
    r.provincie_id,
    r.beheer_jaar
   FROM imna.beschikking_rapportage r
  WHERE (NOT (EXISTS ( SELECT 1
           FROM imna.beschikking_rapportage r_prev
          WHERE ((r.provincie_id = r_prev.provincie_id) AND (r.provincie_id = r_prev.provincie_id) AND (r.begin_geldigheid < r_prev.begin_geldigheid)))));
;

ALTER TABLE imna.bes_reports
    OWNER TO anlb;

CREATE OR REPLACE VIEW imna.vm_prov_year_beschikking AS 
 SELECT r.beheer_jaar,
    r.provincie_id,
    g.id AS beschikking_id,
    r.id AS report_id
   FROM imna.beschikking g,
    imna.bes_reports r
  WHERE ((g.provincie_id = r.provincie_id) AND (g.begin_geldigheid <= r.begin_geldigheid) AND (NOT (EXISTS ( SELECT 1
           FROM imna.beschikking g_prev
          WHERE ((g.identificatie = g_prev.identificatie) AND (g.provincie_id = g_prev.provincie_id) AND (r.begin_geldigheid >= g_prev.begin_geldigheid) AND (g.begin_geldigheid < g_prev.begin_geldigheid))))) AND ((g.eind_geldigheid IS NULL) OR (g.eind_geldigheid >= r.eind_geldigheid)));
;

ALTER TABLE imna.vm_prov_year_beschikking
    OWNER TO anlb;

CREATE OR REPLACE VIEW imna.vm_prov_year_beschikking_rapportage AS 
 SELECT r.beheer_jaar,
    r.provincie_id,
    g.id AS report_id
   FROM imna.beschikking_rapportage g,
    imna.bes_reports r
  WHERE ((g.provincie_id = r.provincie_id) AND (g.begin_geldigheid <= r.begin_geldigheid) AND (NOT (EXISTS ( SELECT 1
           FROM imna.beschikking_rapportage g_prev
          WHERE ((g.identificatie = g_prev.identificatie) AND (g.provincie_id = g_prev.provincie_id) AND (r.begin_geldigheid >= g_prev.begin_geldigheid) AND (g.begin_geldigheid < g_prev.begin_geldigheid))))) AND ((g.eind_geldigheid IS NULL) OR (g.eind_geldigheid >= r.eind_geldigheid)));
;

ALTER TABLE imna.vm_prov_year_beschikking_rapportage
    OWNER TO anlb;

CREATE OR REPLACE VIEW imna.v_gs_beschikking AS 
 SELECT ( SELECT btrim((dmn_provincie_code.code)::text) AS btrim
           FROM masterdata.dmn_provincie_code
          WHERE (dmn_provincie_code.id = g.provincie_id)) AS provincie,
    ( SELECT btrim((dmn_provincie_code.description)::text) AS btrim
           FROM masterdata.dmn_provincie_code
          WHERE (dmn_provincie_code.id = g.provincie_id)) AS provincie_desc,
    p.beheer_jaar,
    btrim((g.identificatie)::text) AS identificatie,
    g.begin_geldigheid,
    NULL::text AS eind_geldigheid,
    g.begin_tijd,
    g.eind_tijd,
    g.contract_nummer,
    g.datum_beschikking,
    ( SELECT btrim((dmn_status_aanvraag_subsidie.code)::text) AS btrim
           FROM masterdata.dmn_status_aanvraag_subsidie
          WHERE (dmn_status_aanvraag_subsidie.id = g.status_aanvraag_subsidie_id)) AS status_aanvraag_subsidie,
    ( SELECT btrim((dmn_status_aanvraag_subsidie.description)::text) AS btrim
           FROM masterdata.dmn_status_aanvraag_subsidie
          WHERE (dmn_status_aanvraag_subsidie.id = g.status_aanvraag_subsidie_id)) AS status_aanvraag_subsidie_desc,
    ( SELECT btrim((dmn_type_regeling.code)::text) AS btrim
           FROM masterdata.dmn_type_regeling
          WHERE (dmn_type_regeling.id = g.type_regeling_id)) AS type_regeling,
    ( SELECT btrim((dmn_type_regeling.description)::text) AS btrim
           FROM masterdata.dmn_type_regeling
          WHERE (dmn_type_regeling.id = g.type_regeling_id)) AS type_regeling_desc,
        CASE
            WHEN (EXISTS ( SELECT 1
               FROM masterdata.dmn_type_regeling_snl
              WHERE (dmn_type_regeling_snl.id = g.type_regeling_id))) THEN ( SELECT btrim((dmn_beheer_type.code)::text) AS btrim
               FROM masterdata.dmn_beheer_type
              WHERE (dmn_beheer_type.id = snl.beheer_type_id))
            WHEN (EXISTS ( SELECT 1
               FROM masterdata.dmn_type_regeling_niet_snl
              WHERE (dmn_type_regeling_niet_snl.id = g.type_regeling_id))) THEN ( SELECT btrim((dmn_beheer_type.code)::text) AS btrim
               FROM masterdata.dmn_beheer_type
              WHERE (dmn_beheer_type.id = nietsnl.beheer_type_id))
            ELSE NULL::text
        END AS beheer_type,
        CASE
            WHEN (EXISTS ( SELECT 1
               FROM masterdata.dmn_type_regeling_snl
              WHERE (dmn_type_regeling_snl.id = g.type_regeling_id))) THEN ( SELECT btrim((dmn_beheer_type.description)::text) AS btrim
               FROM masterdata.dmn_beheer_type
              WHERE (dmn_beheer_type.id = snl.beheer_type_id))
            WHEN (EXISTS ( SELECT 1
               FROM masterdata.dmn_type_regeling_niet_snl
              WHERE (dmn_type_regeling_niet_snl.id = g.type_regeling_id))) THEN ( SELECT btrim((dmn_beheer_type.description)::text) AS btrim
               FROM masterdata.dmn_beheer_type
              WHERE (dmn_beheer_type.id = nietsnl.beheer_type_id))
            ELSE NULL::text
        END AS beheer_type_desc,
    g.geom
   FROM (((imna.vm_prov_year_beschikking p
     JOIN imna.beschikking g ON ((g.id = p.beschikking_id)))
     LEFT JOIN imna.beschikking_beheer_type_snl snl ON ((snl.beschikking_id = p.beschikking_id)))
     LEFT JOIN imna.beschikking_beheer_type_niet_snl nietsnl ON ((nietsnl.beschikking_id = p.beschikking_id)));
;

ALTER TABLE imna.v_gs_beschikking
    OWNER TO anlb;

CREATE OR REPLACE VIEW imna.v_gs_beschikking_rapportage AS 
 SELECT ( SELECT btrim((dmn_provincie_code.code)::text) AS btrim
           FROM masterdata.dmn_provincie_code
          WHERE (dmn_provincie_code.id = g.provincie_id)) AS provincie,
    ( SELECT btrim((dmn_provincie_code.description)::text) AS btrim
           FROM masterdata.dmn_provincie_code
          WHERE (dmn_provincie_code.id = g.provincie_id)) AS provincie_desc,
    p.beheer_jaar,
    btrim((g.identificatie)::text) AS identificatie,
    g.begin_geldigheid,
    NULL::text AS eind_geldigheid
   FROM (imna.vm_prov_year_beschikking_rapportage p
     JOIN imna.beschikking_rapportage g ON ((g.id = p.report_id)));
;

ALTER TABLE imna.v_gs_beschikking_rapportage
    OWNER TO anlb;

CREATE OR REPLACE VIEW imna.v_rvo_beschikking AS 
 SELECT ( SELECT btrim((dmn_provincie_code.code)::text) AS btrim
           FROM masterdata.dmn_provincie_code
          WHERE (dmn_provincie_code.id = g.provincie_id)) AS provincie,
    p.beheer_jaar,
    btrim((g.identificatie)::text) AS identificatie,
    g.begin_geldigheid,
    NULL::text AS eind_geldigheid,
    g.begin_tijd,
    g.eind_tijd,
    g.contract_nummer,
    g.datum_beschikking,
    ( SELECT btrim((dmn_status_aanvraag_subsidie.code)::text) AS btrim
           FROM masterdata.dmn_status_aanvraag_subsidie
          WHERE (dmn_status_aanvraag_subsidie.id = g.status_aanvraag_subsidie_id)) AS status_aanvraag_subsidie,
    ( SELECT btrim((dmn_type_regeling.code)::text) AS btrim
           FROM masterdata.dmn_type_regeling
          WHERE (dmn_type_regeling.id = g.type_regeling_id)) AS type_regeling,
        CASE
            WHEN (EXISTS ( SELECT 1
               FROM masterdata.dmn_type_regeling_snl
              WHERE (dmn_type_regeling_snl.id = g.type_regeling_id))) THEN ( SELECT btrim((dmn_beheer_type.code)::text) AS btrim
               FROM masterdata.dmn_beheer_type
              WHERE (dmn_beheer_type.id = snl.beheer_type_id))
            WHEN (EXISTS ( SELECT 1
               FROM masterdata.dmn_type_regeling_niet_snl
              WHERE (dmn_type_regeling_niet_snl.id = g.type_regeling_id))) THEN ( SELECT btrim((dmn_beheer_type.code)::text) AS btrim
               FROM masterdata.dmn_beheer_type
              WHERE (dmn_beheer_type.id = nietsnl.beheer_type_id))
            ELSE NULL::text
        END AS beheer_type,
    g.geom
   FROM (((imna.vm_prov_year_beschikking p
     JOIN imna.beschikking g ON ((g.id = p.beschikking_id)))
     LEFT JOIN imna.beschikking_beheer_type_snl snl ON ((snl.beschikking_id = p.beschikking_id)))
     LEFT JOIN imna.beschikking_beheer_type_niet_snl nietsnl ON ((nietsnl.beschikking_id = p.beschikking_id)));
;

ALTER TABLE imna.v_rvo_beschikking
    OWNER TO anlb;

CREATE OR REPLACE VIEW imna.v_rvo_beschikking_rapportage AS 
 SELECT ( SELECT btrim((dmn_provincie_code.code)::text) AS btrim
           FROM masterdata.dmn_provincie_code
          WHERE (dmn_provincie_code.id = g.provincie_id)) AS provincie,
    p.beheer_jaar,
    btrim((g.identificatie)::text) AS identificatie,
    g.begin_geldigheid,
    NULL::text AS eind_geldigheid
   FROM (imna.vm_prov_year_beschikking_rapportage p
     JOIN imna.beschikking_rapportage g ON ((g.id = p.report_id)));
;

ALTER TABLE imna.v_rvo_beschikking_rapportage
    OWNER TO anlb;


GRANT SELECT ON ALL TABLES IN SCHEMA imna TO anlb_sqlpad;