/* ---------------------------------------------------- */
/*  Generated by Enterprise Architect Version 12.1 		*/
/*  Created On : 24-Oct-2023 16:28:11 				*/
/*  DBMS       : PostgreSQL 						*/
/* ---------------------------------------------------- */


/* Create Tables */

CREATE TABLE IF NOT EXISTS imna.gebied_inrichting
(
	id bigint NOT NULL   DEFAULT NEXTVAL(('imna_seq'::text)::regclass),    -- Internal ID of the reported setup area
	identificatie char(100) NOT NULL,    -- External ID  of the reported setup area
	begin_geldigheid timestamp NOT NULL,    -- Start of the validity for this version  of the reported setup area
	eind_geldigheid timestamp NULL,    -- End of the validity for this version of the reported setup area
	begin_tijd timestamp NOT NULL,    -- Start of the validity for this version  of the reported setup area identified by the idenficatie and bron_houder_id
	eind_tijd timestamp NULL,    -- End of the validity for this version of the reported setup area identified by the idenficatie and bron_houder_id
	vrn_id bigint NOT NULL,    -- Id linking to the VoortgangsRapportage used to submit this version  of the reported setup area
	bron_houder_id bigint NOT NULL,    -- Domain Id linking to the province responsible for the reported setup area
	type_beheerder_id bigint NULL,    -- Domain id linking to the type of maintainer responsible for the contract on the reported setup area
	relatie_nummer integer NULL,
	contract_nummer integer NULL,    -- contractnumber from the beschikking / agreement
	geom geometry NOT NULL    -- Geometry single polygon in EPSG:28992  of the reported setup area
)
;

ALTER TABLE imna.gebied_inrichting
    OWNER to anlb;

CREATE TABLE IF NOT EXISTS imna.gebied_natuur
(
	id bigint NOT NULL   DEFAULT NEXTVAL(('imna_seq'::text)::regclass),    -- Internal ID of the reported nature area
	identificatie char(100) NOT NULL,    -- External ID of the reported nature area
	begin_geldigheid timestamp NOT NULL,    -- Start of the validity for this version  of the reported nature area
	eind_geldigheid timestamp NULL,    -- End of the validity for this version of  of the reported nature area
	begin_tijd timestamp NOT NULL,    -- Start of the validity for this version  of the reported nature area identified by the idenficatie and bron_houder_id
	eind_tijd timestamp NULL,    -- End of the validity for this version  of the reported nature area identified by the idenficatie and bron_houder_id
	vrn_id bigint NOT NULL,    -- Id linking to the VoortgangsRapportage used to submit this version  of the reported nature area
	status_natuur_id bigint NOT NULL,    -- Domain id linking to the status for the reported nature area
	bron_houder_id bigint NOT NULL,    -- Domain Id linking to the province responsible for the reported nature area
	type_beheerder_id bigint NULL,    -- Domain id linking to the type of maintainer responsible for the contract on the reported nature area
	eenheid_nummer char(100) NULL,
	beheer_pakket_id bigint NULL,    -- Domain Id linking to the maintenance package choosen to deliver maintenance on this Nature Area
	relatie_nummer integer NULL,
	contract_nummer integer NULL,    -- contractnumber from the beschikking / agreement
	geom geometry NOT NULL    -- Geometry single polygon in EPSG:28992  of the reported nature area
)
;

ALTER TABLE imna.gebied_natuur
    OWNER to anlb;

CREATE TABLE IF NOT EXISTS imna.gebied_verwerving
(
	id bigint NOT NULL   DEFAULT NEXTVAL(('imna_seq'::text)::regclass),    -- Internal ID of the reported acquisition area
	identificatie char(100) NOT NULL,    -- External ID of the reported acquisition area
	begin_geldigheid timestamp NOT NULL,    -- Start of the validity for this version of the reported acquisition area
	eind_geldigheid timestamp NULL,    -- End of the validity for this version of the reported acquisition area
	begin_tijd timestamp NOT NULL,    -- Start of the validity for this version  of the reported acquisition area identified by the idenficatie and bron_houder_id
	eind_tijd timestamp NULL,    -- End of the validity for this version of the reported acquisition area identified by the idenficatie and bron_houder_id
	vrn_id bigint NOT NULL,    -- Id linking to the VoortgangsRapportage used to submit this version of the reported acquisition area
	bron_houder_id bigint NOT NULL,    -- Domain Id linking to the province responsible for the reported acquisition area
	type_eigenaar_id bigint NULL,    -- Domain id linking to the type of owner responsible for the contract on the reported acquisition area
	relatie_nummer integer NULL,
	contract_nummer integer NULL,    -- contractnumber from the beschikking / agreement
	geom geometry NOT NULL    -- Geometry single polygon in EPSG:28992 of the reported acquisition area
)
;

ALTER TABLE imna.gebied_verwerving
    OWNER to anlb;

CREATE TABLE IF NOT EXISTS imna.natuur_netwerk_nederland
(
	id bigint NOT NULL   DEFAULT NEXTVAL(('imna_seq'::text)::regclass),    -- Internal ID of the nature network area
	identificatie char(100) NOT NULL,    -- External ID of the nature network area
	begin_geldigheid timestamp NOT NULL,    -- Start of the validity for this version of the nature network area
	eind_geldigheid timestamp NULL,    -- End of the validity for this version of the nature network area
	begin_tijd timestamp NOT NULL,    -- Start of the validity for this version of the nature network area identified by the idenficatie and bron_houder_id
	eind_tijd timestamp NULL,    -- End of the validity for this version of the nature network area identified by the idenficatie and bron_houder_id
	vrn_id bigint NOT NULL,    -- Id linking to the VoortgangsRapportage used to submit this version of the nature network area
	bron_houder_id bigint NOT NULL,    -- Domain Id linking to the province responsible for the nature network area
	geom geometry NOT NULL    -- Geometry single polygon in EPSG:28992 of the nature network area
)
;

ALTER TABLE imna.natuur_netwerk_nederland
    OWNER to anlb;

CREATE TABLE IF NOT EXISTS imna.resterende_inrichtings_ambitie
(
	id bigint NOT NULL   DEFAULT NEXTVAL(('imna_seq'::text)::regclass),    -- Internal ID of the additional reporting
	identificatie char(100) NOT NULL,    -- External ID of the additional reporting
	begin_geldigheid timestamp NOT NULL,    -- Start of the validity for this version of the additional reporting
	eind_geldigheid timestamp NULL,    -- End of the validity for this version of the additional reporting
	vrn_id bigint NOT NULL,    -- Id linking to the VoortgangsRapportage used to submit this version of the additional reporting
	bron_houder_id bigint NOT NULL,    -- Domain Id linking to the province responsible for the additional reporting
	resterende_inrichtings_ambitie integer NOT NULL
)
;

ALTER TABLE imna.resterende_inrichtings_ambitie
    OWNER to anlb;

CREATE TABLE IF NOT EXISTS imna.voortgangs_rapportage
(
	id bigint NOT NULL   DEFAULT NEXTVAL(('imna_seq'::text)::regclass),    -- Internal ID of the progress report
	identificatie char(100) NOT NULL,    -- External ID of the progress report
	begin_geldigheid timestamp NOT NULL,    -- Start of the validity for this version of the progress report
	eind_geldigheid timestamp NULL,    -- End of the validity for this version of the progress report
	bron_houder_id bigint NOT NULL,    -- Domain Id linking to the province responsible for  the progress report
	rapportage_jaar smallint NOT NULL,    -- year the progress report applies to
	opmerkingen text NULL    -- possible remarks on the progress report
)
;

ALTER TABLE imna.voortgangs_rapportage
    OWNER to anlb;

/* Create Primary Keys, Indexes, Uniques, Checks */

SELECT pg_temp.create_constraint_if_not_exists ('imna','gebied_inrichting','PK_gebied_inrichting',
'ALTER TABLE imna.gebied_inrichting ADD CONSTRAINT PK_gebied_inrichting
	PRIMARY KEY (id)
;');

SELECT pg_temp.create_constraint_if_not_exists ('imna','gebied_inrichting','UN_gebied_inrichting_identificatie',
'ALTER TABLE imna.gebied_inrichting ADD CONSTRAINT UN_gebied_inrichting_identificatie UNIQUE (identificatie,begin_geldigheid,bron_houder_id)
;');

CREATE INDEX IF NOT EXISTS IXFK_dmn_provincie_code_12 ON imna.gebied_inrichting (bron_houder_id ASC)
;

CREATE INDEX IF NOT EXISTS IXFK_dmn_type_beheerder_en_eigenaar_02 ON imna.gebied_inrichting (type_beheerder_id ASC)
;

CREATE INDEX IF NOT EXISTS IXFK_voortgangs_rapportage_02 ON imna.gebied_inrichting (vrn_id ASC)
;

SELECT pg_temp.create_constraint_if_not_exists ('imna','gebied_natuur','PK_gebied_natuur',
'ALTER TABLE imna.gebied_natuur ADD CONSTRAINT PK_gebied_natuur
	PRIMARY KEY (id)
;');

SELECT pg_temp.create_constraint_if_not_exists ('imna','gebied_natuur','UN_gebied_natuur_identificatie',
'ALTER TABLE imna.gebied_natuur ADD CONSTRAINT UN_gebied_natuur_identificatie UNIQUE (identificatie,begin_geldigheid,bron_houder_id)
;');

CREATE INDEX IF NOT EXISTS IXFK_dmn_beheer_pakket_10 ON imna.gebied_natuur (beheer_pakket_id ASC)
;

CREATE INDEX IF NOT EXISTS IXFK_dmn_provincie_code_11 ON imna.gebied_natuur (bron_houder_id ASC)
;

CREATE INDEX IF NOT EXISTS IXFK_dmn_status_natuur ON imna.gebied_natuur (status_natuur_id ASC)
;

CREATE INDEX IF NOT EXISTS IXFK_dmn_type_beheerder_en_eigenaar_01 ON imna.gebied_natuur (type_beheerder_id ASC)
;

CREATE INDEX IF NOT EXISTS IXFK_voortgangs_rapportage_01 ON imna.gebied_natuur (vrn_id ASC)
;

SELECT pg_temp.create_constraint_if_not_exists ('imna','gebied_verwerving','PK_gebied_verwerving',
'ALTER TABLE imna.gebied_verwerving ADD CONSTRAINT PK_gebied_verwerving
	PRIMARY KEY (id)
;');

SELECT pg_temp.create_constraint_if_not_exists ('imna','gebied_verwerving','UN_gebied_verwerving_identificatie',
'ALTER TABLE imna.gebied_verwerving ADD CONSTRAINT UN_gebied_verwerving_identificatie UNIQUE (identificatie,begin_geldigheid,bron_houder_id)
;');

CREATE INDEX IF NOT EXISTS IXFK_dmn_provincie_code_13 ON imna.gebied_verwerving (bron_houder_id ASC)
;

CREATE INDEX IF NOT EXISTS IXFK_dmn_type_beheerder_en_eigenaar_03 ON imna.gebied_verwerving (type_eigenaar_id ASC)
;

CREATE INDEX IF NOT EXISTS IXFK_voortgangs_rapportage_03 ON imna.gebied_verwerving (vrn_id ASC)
;

SELECT pg_temp.create_constraint_if_not_exists ('imna','natuur_netwerk_nederland','PK_natuur_netwerk_nederland',
'ALTER TABLE imna.natuur_netwerk_nederland ADD CONSTRAINT PK_natuur_netwerk_nederland
	PRIMARY KEY (id)
;');

SELECT pg_temp.create_constraint_if_not_exists ('imna','natuur_netwerk_nederland','UN_NNN_identificatie',
'ALTER TABLE imna.natuur_netwerk_nederland ADD CONSTRAINT UN_NNN_identificatie UNIQUE (identificatie,begin_geldigheid,bron_houder_id)
;');

CREATE INDEX IF NOT EXISTS IXFK_dmn_provincie_code_14 ON imna.natuur_netwerk_nederland (bron_houder_id ASC)
;

CREATE INDEX IF NOT EXISTS IXFK_voortgangs_rapportage_04 ON imna.natuur_netwerk_nederland (vrn_id ASC)
;

SELECT pg_temp.create_constraint_if_not_exists ('imna','resterende_inrichtings_ambitie','PK_resterende_inrichtings_ambitie',
'ALTER TABLE imna.resterende_inrichtings_ambitie ADD CONSTRAINT PK_resterende_inrichtings_ambitie
	PRIMARY KEY (id)
;');

SELECT pg_temp.create_constraint_if_not_exists ('imna','resterende_inrichtings_ambitie','UN_resterende_ambitie_identificatie',
'ALTER TABLE imna.resterende_inrichtings_ambitie ADD CONSTRAINT UN_resterende_ambitie_identificatie UNIQUE (identificatie,begin_geldigheid,bron_houder_id)
;');

CREATE INDEX IF NOT EXISTS IXFK_dmn_provincie_code_15 ON imna.resterende_inrichtings_ambitie (bron_houder_id ASC)
;

CREATE INDEX IF NOT EXISTS IXFK_voortgangs_rapportage_05 ON imna.resterende_inrichtings_ambitie (vrn_id ASC)
;

SELECT pg_temp.create_constraint_if_not_exists ('imna','voortgangs_rapportage','PK_voortgangs_rapportage',
'ALTER TABLE imna.voortgangs_rapportage ADD CONSTRAINT PK_voortgangs_rapportage
	PRIMARY KEY (id)
;');

SELECT pg_temp.create_constraint_if_not_exists ('imna','voortgangs_rapportage','UN_voortgangs_rapportage_identificatie',
'ALTER TABLE imna.voortgangs_rapportage ADD CONSTRAINT UN_voortgangs_rapportage_identificatie UNIQUE (identificatie,begin_geldigheid,bron_houder_id)
;');

CREATE INDEX IF NOT EXISTS IXFK_dmn_provincie_code_10 ON imna.voortgangs_rapportage (bron_houder_id ASC)
;

/* Create Foreign Key Constraints */

SELECT pg_temp.create_constraint_if_not_exists ('imna','gebied_inrichting','FK_dmn_provincie_code_12',
'ALTER TABLE imna.gebied_inrichting ADD CONSTRAINT FK_dmn_provincie_code_12
	FOREIGN KEY (bron_houder_id) REFERENCES masterdata.dmn_provincie_code (id) ON DELETE No Action ON UPDATE No Action
;');

SELECT pg_temp.create_constraint_if_not_exists ('imna','gebied_inrichting','FK_dmn_type_beheerder_en_eigenaar_02',
'ALTER TABLE imna.gebied_inrichting ADD CONSTRAINT FK_dmn_type_beheerder_en_eigenaar_02
	FOREIGN KEY (type_beheerder_id) REFERENCES masterdata.dmn_type_beheerder_en_eigenaar (id) ON DELETE No Action ON UPDATE No Action
;');

SELECT pg_temp.create_constraint_if_not_exists ('imna','gebied_inrichting','FK_voortgangs_rapportage_02',
'ALTER TABLE imna.gebied_inrichting ADD CONSTRAINT FK_voortgangs_rapportage_02
	FOREIGN KEY (vrn_id) REFERENCES imna.voortgangs_rapportage (id) ON DELETE No Action ON UPDATE No Action
;');

SELECT pg_temp.create_constraint_if_not_exists ('imna','gebied_natuur','FK_dmn_beheer_pakket_10',
'ALTER TABLE imna.gebied_natuur ADD CONSTRAINT FK_dmn_beheer_pakket_10
	FOREIGN KEY (beheer_pakket_id) REFERENCES masterdata.dmn_beheer_pakket (id) ON DELETE No Action ON UPDATE No Action
;');

SELECT pg_temp.create_constraint_if_not_exists ('imna','gebied_natuur','FK_dmn_provincie_code_11',
'ALTER TABLE imna.gebied_natuur ADD CONSTRAINT FK_dmn_provincie_code_11
	FOREIGN KEY (bron_houder_id) REFERENCES masterdata.dmn_provincie_code (id) ON DELETE No Action ON UPDATE No Action
;');

SELECT pg_temp.create_constraint_if_not_exists ('imna','gebied_natuur','FK_dmn_status_natuur',
'ALTER TABLE imna.gebied_natuur ADD CONSTRAINT FK_dmn_status_natuur
	FOREIGN KEY (status_natuur_id) REFERENCES masterdata.dmn_status_natuur (id) ON DELETE No Action ON UPDATE No Action
;');

SELECT pg_temp.create_constraint_if_not_exists ('imna','gebied_natuur','FK_dmn_type_beheerder_en_eigenaar_01',
'ALTER TABLE imna.gebied_natuur ADD CONSTRAINT FK_dmn_type_beheerder_en_eigenaar_01
	FOREIGN KEY (type_beheerder_id) REFERENCES masterdata.dmn_type_beheerder_en_eigenaar (id) ON DELETE No Action ON UPDATE No Action
;');

SELECT pg_temp.create_constraint_if_not_exists ('imna','gebied_natuur','FK_voortgangs_rapportage_01',
'ALTER TABLE imna.gebied_natuur ADD CONSTRAINT FK_voortgangs_rapportage_01
	FOREIGN KEY (vrn_id) REFERENCES imna.voortgangs_rapportage (id) ON DELETE No Action ON UPDATE No Action
;');

SELECT pg_temp.create_constraint_if_not_exists ('imna','gebied_verwerving','FK_dmn_provincie_code_13',
'ALTER TABLE imna.gebied_verwerving ADD CONSTRAINT FK_dmn_provincie_code_13
	FOREIGN KEY (bron_houder_id) REFERENCES masterdata.dmn_provincie_code (id) ON DELETE No Action ON UPDATE No Action
;');

SELECT pg_temp.create_constraint_if_not_exists ('imna','gebied_verwerving','FK_dmn_type_beheerder_en_eigenaar_03',
'ALTER TABLE imna.gebied_verwerving ADD CONSTRAINT FK_dmn_type_beheerder_en_eigenaar_03
	FOREIGN KEY (type_eigenaar_id) REFERENCES masterdata.dmn_type_beheerder_en_eigenaar (id) ON DELETE No Action ON UPDATE No Action
;');

SELECT pg_temp.create_constraint_if_not_exists ('imna','gebied_verwerving','FK_voortgangs_rapportage_03',
'ALTER TABLE imna.gebied_verwerving ADD CONSTRAINT FK_voortgangs_rapportage_03
	FOREIGN KEY (vrn_id) REFERENCES imna.voortgangs_rapportage (id) ON DELETE No Action ON UPDATE No Action
;');

SELECT pg_temp.create_constraint_if_not_exists ('imna','natuur_netwerk_nederland','FK_dmn_provincie_code_14',
'ALTER TABLE imna.natuur_netwerk_nederland ADD CONSTRAINT FK_dmn_provincie_code_14
	FOREIGN KEY (bron_houder_id) REFERENCES masterdata.dmn_provincie_code (id) ON DELETE No Action ON UPDATE No Action
;');

SELECT pg_temp.create_constraint_if_not_exists ('imna','natuur_netwerk_nederland','FK_voortgangs_rapportage_04',
'ALTER TABLE imna.natuur_netwerk_nederland ADD CONSTRAINT FK_voortgangs_rapportage_04
	FOREIGN KEY (vrn_id) REFERENCES imna.voortgangs_rapportage (id) ON DELETE No Action ON UPDATE No Action
;');

SELECT pg_temp.create_constraint_if_not_exists ('imna','resterende_inrichtings_ambitie','FK_dmn_provincie_code_15',
'ALTER TABLE imna.resterende_inrichtings_ambitie ADD CONSTRAINT FK_dmn_provincie_code_15
	FOREIGN KEY (bron_houder_id) REFERENCES masterdata.dmn_provincie_code (id) ON DELETE No Action ON UPDATE No Action
;');

SELECT pg_temp.create_constraint_if_not_exists ('imna','resterende_inrichtings_ambitie','FK_voortgangs_rapportage_05',
'ALTER TABLE imna.resterende_inrichtings_ambitie ADD CONSTRAINT FK_voortgangs_rapportage_05
	FOREIGN KEY (vrn_id) REFERENCES imna.voortgangs_rapportage (id) ON DELETE No Action ON UPDATE No Action
;');

SELECT pg_temp.create_constraint_if_not_exists ('imna','voortgangs_rapportage','FK_dmn_provincie_code_10',
'ALTER TABLE imna.voortgangs_rapportage ADD CONSTRAINT FK_dmn_provincie_code_10
	FOREIGN KEY (bron_houder_id) REFERENCES masterdata.dmn_provincie_code (id) ON DELETE No Action ON UPDATE No Action
;');



/* Create Table Comments, Sequences for Autonumber Columns */

COMMENT ON TABLE imna.gebied_inrichting
	IS 'Areas that have been setup for nature maintenance that are not yet in maintenance.'
;

COMMENT ON COLUMN imna.gebied_inrichting.id
	IS 'Internal ID of the reported setup area'
;

COMMENT ON COLUMN imna.gebied_inrichting.identificatie
	IS 'External ID  of the reported setup area'
;

COMMENT ON COLUMN imna.gebied_inrichting.begin_geldigheid
	IS 'Start of the validity for this version  of the reported setup area'
;

COMMENT ON COLUMN imna.gebied_inrichting.eind_geldigheid
	IS 'End of the validity for this version of the reported setup area'
;

COMMENT ON COLUMN imna.gebied_inrichting.begin_tijd
	IS 'Start of the validity for this version  of the reported setup area identified by the idenficatie and bron_houder_id'
;

COMMENT ON COLUMN imna.gebied_inrichting.eind_tijd
	IS 'End of the validity for this version of the reported setup area identified by the idenficatie and bron_houder_id'
;

COMMENT ON COLUMN imna.gebied_inrichting.vrn_id
	IS 'Id linking to the VoortgangsRapportage used to submit this version  of the reported setup area'
;

COMMENT ON COLUMN imna.gebied_inrichting.bron_houder_id
	IS 'Domain Id linking to the province responsible for the reported setup area'
;

COMMENT ON COLUMN imna.gebied_inrichting.type_beheerder_id
	IS 'Domain id linking to the type of maintainer responsible for the contract on the reported setup area'
;

COMMENT ON COLUMN imna.gebied_inrichting.contract_nummer
	IS 'contractnumber from the beschikking / agreement'
;

COMMENT ON COLUMN imna.gebied_inrichting.geom
	IS 'Geometry single polygon in EPSG:28992  of the reported setup area'
;


COMMENT ON TABLE imna.gebied_natuur
	IS 'Nature areas in maintenance being reported on'
;

COMMENT ON COLUMN imna.gebied_natuur.id
	IS 'Internal ID of the reported nature area'
;

COMMENT ON COLUMN imna.gebied_natuur.identificatie
	IS 'External ID of the reported nature area'
;

COMMENT ON COLUMN imna.gebied_natuur.begin_geldigheid
	IS 'Start of the validity for this version  of the reported nature area'
;

COMMENT ON COLUMN imna.gebied_natuur.eind_geldigheid
	IS 'End of the validity for this version of  of the reported nature area'
;

COMMENT ON COLUMN imna.gebied_natuur.begin_tijd
	IS 'Start of the validity for this version  of the reported nature area identified by the idenficatie and bron_houder_id'
;

COMMENT ON COLUMN imna.gebied_natuur.eind_tijd
	IS 'End of the validity for this version  of the reported nature area identified by the idenficatie and bron_houder_id'
;

COMMENT ON COLUMN imna.gebied_natuur.vrn_id
	IS 'Id linking to the VoortgangsRapportage used to submit this version  of the reported nature area'
;

COMMENT ON COLUMN imna.gebied_natuur.status_natuur_id
	IS 'Domain id linking to the status for the reported nature area'
;

COMMENT ON COLUMN imna.gebied_natuur.bron_houder_id
	IS 'Domain Id linking to the province responsible for the reported nature area'
;

COMMENT ON COLUMN imna.gebied_natuur.type_beheerder_id
	IS 'Domain id linking to the type of maintainer responsible for the contract on the reported nature area'
;

COMMENT ON COLUMN imna.gebied_natuur.beheer_pakket_id
	IS 'Domain Id linking to the maintenance package choosen to deliver maintenance on this Nature Area'
;

COMMENT ON COLUMN imna.gebied_natuur.contract_nummer
	IS 'contractnumber from the beschikking / agreement'
;

COMMENT ON COLUMN imna.gebied_natuur.geom
	IS 'Geometry single polygon in EPSG:28992  of the reported nature area'
;


COMMENT ON TABLE imna.gebied_verwerving
	IS 'Areas that are being purchased by the province so that they can be setup for maintenance'
;

COMMENT ON COLUMN imna.gebied_verwerving.id
	IS 'Internal ID of the reported acquisition area'
;

COMMENT ON COLUMN imna.gebied_verwerving.identificatie
	IS 'External ID of the reported acquisition area'
;

COMMENT ON COLUMN imna.gebied_verwerving.begin_geldigheid
	IS 'Start of the validity for this version of the reported acquisition area'
;

COMMENT ON COLUMN imna.gebied_verwerving.eind_geldigheid
	IS 'End of the validity for this version of the reported acquisition area'
;

COMMENT ON COLUMN imna.gebied_verwerving.begin_tijd
	IS 'Start of the validity for this version  of the reported acquisition area identified by the idenficatie and bron_houder_id'
;

COMMENT ON COLUMN imna.gebied_verwerving.eind_tijd
	IS 'End of the validity for this version of the reported acquisition area identified by the idenficatie and bron_houder_id'
;

COMMENT ON COLUMN imna.gebied_verwerving.vrn_id
	IS 'Id linking to the VoortgangsRapportage used to submit this version of the reported acquisition area'
;

COMMENT ON COLUMN imna.gebied_verwerving.bron_houder_id
	IS 'Domain Id linking to the province responsible for the reported acquisition area'
;

COMMENT ON COLUMN imna.gebied_verwerving.type_eigenaar_id
	IS 'Domain id linking to the type of owner responsible for the contract on the reported acquisition area'
;

COMMENT ON COLUMN imna.gebied_verwerving.contract_nummer
	IS 'contractnumber from the beschikking / agreement'
;

COMMENT ON COLUMN imna.gebied_verwerving.geom
	IS 'Geometry single polygon in EPSG:28992 of the reported acquisition area'
;

COMMENT ON TABLE imna.natuur_netwerk_nederland
	IS 'The part of the provincial part of the National Nature Network that has been approved by the provincial senate'
;

COMMENT ON COLUMN imna.natuur_netwerk_nederland.id
	IS 'Internal ID of the nature network area'
;

COMMENT ON COLUMN imna.natuur_netwerk_nederland.identificatie
	IS 'External ID of the nature network area'
;

COMMENT ON COLUMN imna.natuur_netwerk_nederland.begin_geldigheid
	IS 'Start of the validity for this version of the nature network area'
;

COMMENT ON COLUMN imna.natuur_netwerk_nederland.eind_geldigheid
	IS 'End of the validity for this version of the nature network area'
;

COMMENT ON COLUMN imna.natuur_netwerk_nederland.begin_tijd
	IS 'Start of the validity for this version of the nature network area identified by the idenficatie and bron_houder_id'
;

COMMENT ON COLUMN imna.natuur_netwerk_nederland.eind_tijd
	IS 'End of the validity for this version of the nature network area identified by the idenficatie and bron_houder_id'
;

COMMENT ON COLUMN imna.natuur_netwerk_nederland.vrn_id
	IS 'Id linking to the VoortgangsRapportage used to submit this version of the nature network area'
;

COMMENT ON COLUMN imna.natuur_netwerk_nederland.bron_houder_id
	IS 'Domain Id linking to the province responsible for the nature network area'
;

COMMENT ON COLUMN imna.natuur_netwerk_nederland.geom
	IS 'Geometry single polygon in EPSG:28992 of the nature network area'
;

COMMENT ON TABLE imna.resterende_inrichtings_ambitie
	IS 'Additional numbers being reported on for the progress report  not captured in the other layers.'
;

COMMENT ON COLUMN imna.resterende_inrichtings_ambitie.id
	IS 'Internal ID of the additional reporting'
;

COMMENT ON COLUMN imna.resterende_inrichtings_ambitie.identificatie
	IS 'External ID of the additional reporting'
;

COMMENT ON COLUMN imna.resterende_inrichtings_ambitie.begin_geldigheid
	IS 'Start of the validity for this version of the additional reporting'
;

COMMENT ON COLUMN imna.resterende_inrichtings_ambitie.eind_geldigheid
	IS 'End of the validity for this version of the additional reporting'
;

COMMENT ON COLUMN imna.resterende_inrichtings_ambitie.vrn_id
	IS 'Id linking to the VoortgangsRapportage used to submit this version of the additional reporting'
;

COMMENT ON COLUMN imna.resterende_inrichtings_ambitie.bron_houder_id
	IS 'Domain Id linking to the province responsible for the additional reporting'
;

COMMENT ON TABLE imna.voortgangs_rapportage
	IS 'Meta data for each individual submission of a progress report '
;

COMMENT ON COLUMN imna.voortgangs_rapportage.id
	IS 'Internal ID of the progress report'
;

COMMENT ON COLUMN imna.voortgangs_rapportage.identificatie
	IS 'External ID of the progress report'
;

COMMENT ON COLUMN imna.voortgangs_rapportage.begin_geldigheid
	IS 'Start of the validity for this version of the progress report'
;

COMMENT ON COLUMN imna.voortgangs_rapportage.eind_geldigheid
	IS 'End of the validity for this version of the progress report'
;

COMMENT ON COLUMN imna.voortgangs_rapportage.bron_houder_id
	IS 'Domain Id linking to the province responsible for  the progress report'
;

COMMENT ON COLUMN imna.voortgangs_rapportage.rapportage_jaar
	IS 'year the progress report applies to'
;

COMMENT ON COLUMN imna.voortgangs_rapportage.opmerkingen
	IS 'possible remarks on the progress report'
;


/* Create Views */



CREATE OR REPLACE VIEW imna.vm_reports AS 
 SELECT r.id,
    r.begin_geldigheid,
    r.eind_geldigheid,
    r.bron_houder_id,
    r.rapportage_jaar
   FROM imna.voortgangs_rapportage r
  WHERE (NOT (EXISTS ( SELECT 1
           FROM imna.voortgangs_rapportage r_prev
          WHERE ((r.bron_houder_id = r_prev.bron_houder_id) AND (r.rapportage_jaar = r_prev.rapportage_jaar) AND (r.begin_geldigheid < r_prev.begin_geldigheid)))));
;

ALTER TABLE imna.vm_reports
    OWNER to anlb;
	
CREATE OR REPLACE VIEW imna.vm_prov_year_gebied_inrichting AS 
 SELECT r.rapportage_jaar,
    r.bron_houder_id,
    g.id AS gebied_inrichting_id,
    r.id AS report_id
   FROM imna.gebied_inrichting g,
    imna.vm_reports r
  WHERE ((g.bron_houder_id = r.bron_houder_id) AND (g.begin_geldigheid <= r.begin_geldigheid) AND (NOT (EXISTS ( SELECT 1
           FROM imna.gebied_inrichting g_prev
          WHERE ((g.identificatie = g_prev.identificatie) AND (g.bron_houder_id = g_prev.bron_houder_id) AND (r.begin_geldigheid >= g_prev.begin_geldigheid) AND (g.begin_geldigheid < g_prev.begin_geldigheid))))) AND ((g.eind_geldigheid IS NULL) OR (g.eind_geldigheid >= r.eind_geldigheid)));
;

ALTER TABLE imna.vm_prov_year_gebied_inrichting
    OWNER to anlb;

CREATE OR REPLACE VIEW imna.vm_prov_year_voortgangs_rapportage AS 
 SELECT r.rapportage_jaar,
    r.bron_houder_id,
    g.id AS report_id
   FROM imna.voortgangs_rapportage g,
    imna.vm_reports r
  WHERE ((g.bron_houder_id = r.bron_houder_id) AND (g.begin_geldigheid <= r.begin_geldigheid) AND (NOT (EXISTS ( SELECT 1
           FROM imna.voortgangs_rapportage g_prev
          WHERE ((g.identificatie = g_prev.identificatie) AND (g.bron_houder_id = g_prev.bron_houder_id) AND (r.begin_geldigheid >= g_prev.begin_geldigheid) AND (g.begin_geldigheid < g_prev.begin_geldigheid))))) AND ((g.eind_geldigheid IS NULL) OR (g.eind_geldigheid >= r.eind_geldigheid)));
;

ALTER TABLE imna.vm_prov_year_voortgangs_rapportage
    OWNER to anlb;

CREATE OR REPLACE VIEW imna.vm_prov_year_gebied_natuur AS 
 SELECT r.rapportage_jaar,
    r.bron_houder_id,
    g.id AS gebied_natuur_id,
    r.id AS report_id
   FROM imna.gebied_natuur g,
    imna.vm_reports r
  WHERE ((g.bron_houder_id = r.bron_houder_id) AND (g.begin_geldigheid <= r.begin_geldigheid) AND (NOT (EXISTS ( SELECT 1
           FROM imna.gebied_natuur g_prev
          WHERE ((g.identificatie = g_prev.identificatie) AND (g.bron_houder_id = g_prev.bron_houder_id) AND (r.begin_geldigheid >= g_prev.begin_geldigheid) AND (g.begin_geldigheid < g_prev.begin_geldigheid))))) AND ((g.eind_geldigheid IS NULL) OR (g.eind_geldigheid >= r.eind_geldigheid)));
;

ALTER TABLE imna.vm_prov_year_gebied_natuur
    OWNER to anlb;

CREATE OR REPLACE VIEW imna.vm_prov_year_gebied_verwerving AS 
 SELECT r.rapportage_jaar,
    r.bron_houder_id,
    g.id AS gebied_verwerving_id,
    r.id AS report_id
   FROM imna.gebied_verwerving g,
    imna.vm_reports r
  WHERE ((g.bron_houder_id = r.bron_houder_id) AND (g.begin_geldigheid <= r.begin_geldigheid) AND (NOT (EXISTS ( SELECT 1
           FROM imna.gebied_verwerving g_prev
          WHERE ((g.identificatie = g_prev.identificatie) AND (g.bron_houder_id = g_prev.bron_houder_id) AND (r.begin_geldigheid >= g_prev.begin_geldigheid) AND (g.begin_geldigheid < g_prev.begin_geldigheid))))) AND ((g.eind_geldigheid IS NULL) OR (g.eind_geldigheid >= r.eind_geldigheid)));
;

ALTER TABLE imna.vm_prov_year_gebied_verwerving
    OWNER to anlb;
	
CREATE OR REPLACE VIEW imna.vm_prov_year_natuur_netwerk_nederland AS 
 SELECT r.rapportage_jaar,
    r.bron_houder_id,
    g.id AS natuur_netwerk_nederland_id,
    r.id AS report_id
   FROM imna.natuur_netwerk_nederland g,
    imna.vm_reports r
  WHERE ((g.bron_houder_id = r.bron_houder_id) AND (g.begin_geldigheid <= r.begin_geldigheid) AND (NOT (EXISTS ( SELECT 1
           FROM imna.natuur_netwerk_nederland g_prev
          WHERE ((g.identificatie = g_prev.identificatie) AND (g.bron_houder_id = g_prev.bron_houder_id) AND (r.begin_geldigheid >= g_prev.begin_geldigheid) AND (g.begin_geldigheid < g_prev.begin_geldigheid))))) AND ((g.eind_geldigheid IS NULL) OR (g.eind_geldigheid >= r.eind_geldigheid)));
;

ALTER TABLE imna.vm_prov_year_natuur_netwerk_nederland
    OWNER to anlb;

CREATE OR REPLACE VIEW imna.vm_prov_year_resterende_inrichtings_ambitie AS 
 SELECT r.rapportage_jaar,
    r.bron_houder_id,
    g.id AS resterende_inrichtings_ambitie_id,
    r.id AS report_id
   FROM imna.resterende_inrichtings_ambitie g,
    imna.vm_reports r
  WHERE ((g.bron_houder_id = r.bron_houder_id) AND (g.begin_geldigheid <= r.begin_geldigheid) AND (NOT (EXISTS ( SELECT 1
           FROM imna.resterende_inrichtings_ambitie g_prev
          WHERE ((g.identificatie = g_prev.identificatie) AND (g.bron_houder_id = g_prev.bron_houder_id) AND (r.begin_geldigheid >= g_prev.begin_geldigheid) AND (g.begin_geldigheid < g_prev.begin_geldigheid))))) AND ((g.eind_geldigheid IS NULL) OR (g.eind_geldigheid >= r.eind_geldigheid)));
;

ALTER TABLE imna.vm_prov_year_resterende_inrichtings_ambitie
    OWNER to anlb;


CREATE OR REPLACE VIEW imna.v_gs_gebied_inrichting AS 
 SELECT ( SELECT btrim((dmn_provincie_code.code)::text) AS btrim
           FROM masterdata.dmn_provincie_code
          WHERE (dmn_provincie_code.id = g.bron_houder_id)) AS bron_houder,
    ( SELECT btrim((dmn_provincie_code.description)::text) AS btrim
           FROM masterdata.dmn_provincie_code
          WHERE (dmn_provincie_code.id = g.bron_houder_id)) AS bron_houder_desc,
    p.rapportage_jaar,
    btrim((g.identificatie)::text) AS identificatie,
    g.begin_geldigheid,
    NULL::text AS eind_geldigheid,
    g.begin_tijd,
    g.eind_tijd,
    ( SELECT btrim((dmn_type_beheerder_en_eigenaar.code)::text) AS btrim
           FROM masterdata.dmn_type_beheerder_en_eigenaar
          WHERE (dmn_type_beheerder_en_eigenaar.id = g.type_beheerder_id)) AS type_beheerder,
    ( SELECT btrim((dmn_type_beheerder_en_eigenaar.description)::text) AS btrim
           FROM masterdata.dmn_type_beheerder_en_eigenaar
          WHERE (dmn_type_beheerder_en_eigenaar.id = g.type_beheerder_id)) AS type_beheerder_desc,
    g.contract_nummer,
    g.relatie_nummer,
    g.geom
   FROM (imna.vm_prov_year_gebied_inrichting p
     JOIN imna.gebied_inrichting g ON ((g.id = p.gebied_inrichting_id)));
;

ALTER TABLE imna.v_gs_gebied_inrichting
    OWNER to anlb;

CREATE OR REPLACE VIEW imna.v_gs_gebied_natuur AS 
 SELECT ( SELECT btrim((dmn_provincie_code.code)::text) AS btrim
           FROM masterdata.dmn_provincie_code
          WHERE (dmn_provincie_code.id = g.bron_houder_id)) AS bron_houder,
    ( SELECT btrim((dmn_provincie_code.description)::text) AS btrim
           FROM masterdata.dmn_provincie_code
          WHERE (dmn_provincie_code.id = g.bron_houder_id)) AS bron_houder_desc,
    p.rapportage_jaar,
    btrim((g.identificatie)::text) AS identificatie,
    g.begin_geldigheid,
    NULL::text AS eind_geldigheid,
    g.begin_tijd,
    g.eind_tijd,
    ( SELECT btrim((dmn_status_natuur.code)::text) AS btrim
           FROM masterdata.dmn_status_natuur
          WHERE (dmn_status_natuur.id = g.status_natuur_id)) AS status_natuur,
    ( SELECT btrim((dmn_status_natuur.description)::text) AS btrim
           FROM masterdata.dmn_status_natuur
          WHERE (dmn_status_natuur.id = g.status_natuur_id)) AS status_natuur_desc,
    ( SELECT btrim((dmn_type_beheerder_en_eigenaar.code)::text) AS btrim
           FROM masterdata.dmn_type_beheerder_en_eigenaar
          WHERE (dmn_type_beheerder_en_eigenaar.id = g.type_beheerder_id)) AS type_beheerder,
    ( SELECT btrim((dmn_type_beheerder_en_eigenaar.description)::text) AS btrim
           FROM masterdata.dmn_type_beheerder_en_eigenaar
          WHERE (dmn_type_beheerder_en_eigenaar.id = g.type_beheerder_id)) AS type_beheerder_desc,
    btrim((g.eenheid_nummer)::text) AS eenheid_nummer,
    ( SELECT btrim((dmn_beheer_pakket.code)::text) AS btrim
           FROM masterdata.dmn_beheer_pakket
          WHERE (dmn_beheer_pakket.id = g.beheer_pakket_id)) AS beheer_pakket,
    ( SELECT btrim((dmn_beheer_pakket.description)::text) AS btrim
           FROM masterdata.dmn_beheer_pakket
          WHERE (dmn_beheer_pakket.id = g.beheer_pakket_id)) AS beheer_pakket_desc,
    g.contract_nummer,
    g.relatie_nummer,
    g.geom
   FROM (imna.vm_prov_year_gebied_natuur p
     JOIN imna.gebied_natuur g ON ((g.id = p.gebied_natuur_id)));
;

ALTER TABLE imna.v_gs_gebied_natuur
    OWNER to anlb;

CREATE OR REPLACE VIEW imna.v_gs_gebied_verwerving AS 
 SELECT ( SELECT btrim((dmn_provincie_code.code)::text) AS btrim
           FROM masterdata.dmn_provincie_code
          WHERE (dmn_provincie_code.id = g.bron_houder_id)) AS bron_houder,
    ( SELECT btrim((dmn_provincie_code.description)::text) AS btrim
           FROM masterdata.dmn_provincie_code
          WHERE (dmn_provincie_code.id = g.bron_houder_id)) AS bron_houder_desc,
    p.rapportage_jaar,
    btrim((g.identificatie)::text) AS identificatie,
    g.begin_geldigheid,
    NULL::text AS eind_geldigheid,
    g.begin_tijd,
    g.eind_tijd,
    ( SELECT btrim((dmn_type_beheerder_en_eigenaar.code)::text) AS btrim
           FROM masterdata.dmn_type_beheerder_en_eigenaar
          WHERE (dmn_type_beheerder_en_eigenaar.id = g.type_eigenaar_id)) AS type_eigenaar,
    ( SELECT btrim((dmn_type_beheerder_en_eigenaar.description)::text) AS btrim
           FROM masterdata.dmn_type_beheerder_en_eigenaar
          WHERE (dmn_type_beheerder_en_eigenaar.id = g.type_eigenaar_id)) AS type_eigenaar_desc,
    g.contract_nummer,
    g.relatie_nummer,
    g.geom
   FROM (imna.vm_prov_year_gebied_verwerving p
     JOIN imna.gebied_verwerving g ON ((g.id = p.gebied_verwerving_id)));
;

ALTER TABLE imna.v_gs_gebied_verwerving
    OWNER to anlb;

CREATE OR REPLACE VIEW imna.v_gs_natuur_netwerk_nederland AS 
 SELECT ( SELECT btrim((dmn_provincie_code.code)::text) AS btrim
           FROM masterdata.dmn_provincie_code
          WHERE (dmn_provincie_code.id = g.bron_houder_id)) AS bron_houder,
    ( SELECT btrim((dmn_provincie_code.description)::text) AS btrim
           FROM masterdata.dmn_provincie_code
          WHERE (dmn_provincie_code.id = g.bron_houder_id)) AS bron_houder_desc,
    p.rapportage_jaar,
    btrim((g.identificatie)::text) AS identificatie,
    g.begin_geldigheid,
    NULL::text AS eind_geldigheid,
    g.begin_tijd,
    g.eind_tijd,
    g.geom
   FROM (imna.vm_prov_year_natuur_netwerk_nederland p
     JOIN imna.natuur_netwerk_nederland g ON ((g.id = p.natuur_netwerk_nederland_id)));
;

ALTER TABLE imna.v_gs_natuur_netwerk_nederland
    OWNER to anlb;

CREATE OR REPLACE VIEW imna.v_gs_resterende_inrichtings_ambitie AS 
 SELECT ( SELECT btrim((dmn_provincie_code.code)::text) AS btrim
           FROM masterdata.dmn_provincie_code
          WHERE (dmn_provincie_code.id = g.bron_houder_id)) AS bron_houder,
    ( SELECT btrim((dmn_provincie_code.description)::text) AS btrim
           FROM masterdata.dmn_provincie_code
          WHERE (dmn_provincie_code.id = g.bron_houder_id)) AS bron_houder_desc,
    p.rapportage_jaar,
    btrim((g.identificatie)::text) AS identificatie,
    g.begin_geldigheid,
    NULL::text AS eind_geldigheid,
    g.resterende_inrichtings_ambitie
   FROM (imna.vm_prov_year_resterende_inrichtings_ambitie p
     JOIN imna.resterende_inrichtings_ambitie g ON ((g.id = p.resterende_inrichtings_ambitie_id)));
;

ALTER TABLE imna.v_gs_resterende_inrichtings_ambitie
    OWNER to anlb;

CREATE OR REPLACE VIEW imna.v_gs_voortgangs_rapportage AS 
 SELECT ( SELECT btrim((dmn_provincie_code.code)::text) AS btrim
           FROM masterdata.dmn_provincie_code
          WHERE (dmn_provincie_code.id = g.bron_houder_id)) AS bron_houder,
    ( SELECT btrim((dmn_provincie_code.description)::text) AS btrim
           FROM masterdata.dmn_provincie_code
          WHERE (dmn_provincie_code.id = g.bron_houder_id)) AS bron_houder_desc,
    p.rapportage_jaar,
    btrim((g.identificatie)::text) AS identificatie,
    g.begin_geldigheid,
    NULL::text AS eind_geldigheid,
    btrim(g.opmerkingen) AS opmerkingen
   FROM (imna.vm_prov_year_voortgangs_rapportage p
     JOIN imna.voortgangs_rapportage g ON ((g.id = p.report_id)));
;

ALTER TABLE imna.v_gs_voortgangs_rapportage
    OWNER to anlb;
	
CREATE OR REPLACE VIEW imna.v_rvo_gebied_inrichting AS 
 SELECT ( SELECT btrim((dmn_provincie_code.code)::text) AS btrim
           FROM masterdata.dmn_provincie_code
          WHERE (dmn_provincie_code.id = g.bron_houder_id)) AS provincie,
    p.rapportage_jaar,
    btrim((g.identificatie)::text) AS identificatie,
    g.begin_geldigheid,
    NULL::text AS eind_geldigheid,
    g.begin_tijd,
    g.eind_tijd,
    g.geom
   FROM (imna.vm_prov_year_gebied_inrichting p
     JOIN imna.gebied_inrichting g ON ((g.id = p.gebied_inrichting_id)));
;

ALTER TABLE imna.v_rvo_gebied_inrichting
    OWNER to anlb;

CREATE OR REPLACE VIEW imna.v_rvo_gebied_natuur AS 
 SELECT ( SELECT btrim((dmn_provincie_code.code)::text) AS btrim
           FROM masterdata.dmn_provincie_code
          WHERE (dmn_provincie_code.id = g.bron_houder_id)) AS provincie,
    p.rapportage_jaar,
    btrim((g.identificatie)::text) AS identificatie,
    g.begin_geldigheid,
    NULL::text AS eind_geldigheid,
    g.begin_tijd,
    g.eind_tijd,
    ( SELECT btrim((dmn_status_natuur.code)::text) AS btrim
           FROM masterdata.dmn_status_natuur
          WHERE (dmn_status_natuur.id = g.status_natuur_id)) AS status_natuur,
    g.geom
   FROM (imna.vm_prov_year_gebied_natuur p
     JOIN imna.gebied_natuur g ON ((g.id = p.gebied_natuur_id)));
;

ALTER TABLE imna.v_rvo_gebied_natuur
    OWNER to anlb;

CREATE OR REPLACE VIEW imna.v_rvo_gebied_verwerving AS 
 SELECT ( SELECT btrim((dmn_provincie_code.code)::text) AS btrim
           FROM masterdata.dmn_provincie_code
          WHERE (dmn_provincie_code.id = g.bron_houder_id)) AS provincie,
    p.rapportage_jaar,
    btrim((g.identificatie)::text) AS identificatie,
    g.begin_geldigheid,
    NULL::text AS eind_geldigheid,
    g.begin_tijd,
    g.eind_tijd,
    g.geom
   FROM (imna.vm_prov_year_gebied_verwerving p
     JOIN imna.gebied_verwerving g ON ((g.id = p.gebied_verwerving_id)));
;

ALTER TABLE imna.v_rvo_gebied_verwerving
    OWNER to anlb;
	
CREATE OR REPLACE VIEW imna.v_rvo_natuur_netwerk_nederland AS 
 SELECT ( SELECT btrim((dmn_provincie_code.code)::text) AS btrim
           FROM masterdata.dmn_provincie_code
          WHERE (dmn_provincie_code.id = g.bron_houder_id)) AS provincie,
    p.rapportage_jaar,
    btrim((g.identificatie)::text) AS identificatie,
    g.begin_geldigheid,
    NULL::text AS eind_geldigheid,
    g.begin_tijd,
    g.eind_tijd,
    g.geom
   FROM (imna.vm_prov_year_natuur_netwerk_nederland p
     JOIN imna.natuur_netwerk_nederland g ON ((g.id = p.natuur_netwerk_nederland_id)));
;

ALTER TABLE imna.v_rvo_natuur_netwerk_nederland
    OWNER to anlb;

CREATE OR REPLACE VIEW imna.v_rvo_resterende_inrichtings_ambitie AS 
 SELECT ( SELECT btrim((dmn_provincie_code.code)::text) AS btrim
           FROM masterdata.dmn_provincie_code
          WHERE (dmn_provincie_code.id = g.bron_houder_id)) AS provincie,
    p.rapportage_jaar,
    btrim((g.identificatie)::text) AS identificatie,
    g.begin_geldigheid,
    NULL::text AS eind_geldigheid,
    g.resterende_inrichtings_ambitie
   FROM (imna.vm_prov_year_resterende_inrichtings_ambitie p
     JOIN imna.resterende_inrichtings_ambitie g ON ((g.id = p.resterende_inrichtings_ambitie_id)));
;

ALTER TABLE imna.v_rvo_resterende_inrichtings_ambitie
    OWNER to anlb;

CREATE OR REPLACE VIEW imna.v_rvo_voortgangs_rapportage AS 
 SELECT ( SELECT btrim((dmn_provincie_code.code)::text) AS btrim
           FROM masterdata.dmn_provincie_code
          WHERE (dmn_provincie_code.id = g.bron_houder_id)) AS bron_houder,
    p.rapportage_jaar,
    btrim((g.identificatie)::text) AS identificatie,
    g.begin_geldigheid,
    NULL::text AS eind_geldigheid,
    btrim(g.opmerkingen) AS opmerkingen
   FROM (imna.vm_prov_year_voortgangs_rapportage p
     JOIN imna.voortgangs_rapportage g ON ((g.id = p.report_id)));
;

ALTER TABLE imna.v_rvo_voortgangs_rapportage
    OWNER to anlb;






GRANT SELECT ON ALL TABLES IN SCHEMA imna TO anlb_sqlpad;
