\echo "Starting deployment of rnn"

/* ---------------------------------------------------- */
/*  Generated by Enterprise Architect Version 12.1 		*/
/*  Created On : 19-Feb-2024 14:29:03 				*/
/*  DBMS       : PostgreSQL 						*/
/* ---------------------------------------------------- */

/* Create Schema */
CREATE SCHEMA IF NOT EXISTS rnn
    AUTHORIZATION anlb;

GRANT ALL ON SCHEMA rnn TO anlb;

GRANT USAGE ON SCHEMA rnn TO anlb_sqlpad;

/* Create Sequences */

CREATE SEQUENCE IF NOT EXISTS rnn.rnn_seq
    INCREMENT 1
    START 1
    MINVALUE 1
    MAXVALUE 9223372036854775807
    CACHE 1;

ALTER SEQUENCE rnn.rnn_seq
    OWNER TO anlb
;

/* Create Tables */
CREATE TABLE IF NOT EXISTS rnn.soort_per_beheer_type
(
	soort_id bigint NOT NULL,
	beheer_type_id bigint NOT NULL,
	begin_geldigheid timestamp NOT NULL,
	end_geldigheid timestamp NULL,
	rnn_soort_groep_voor_telling bigint NULL
);

ALTER TABLE rnn.soort_per_beheer_type
    OWNER to anlb;


CREATE TABLE IF NOT EXISTS rnn.grid_100_by_100
(
	id bigint NOT NULL,
	geom geometry(polygon) NOT NULL
)
;

ALTER TABLE rnn.grid_100_by_100
    OWNER to anlb;

CREATE TABLE IF NOT EXISTS rnn.beoordelings_gebied
(
	id bigint NOT NULL   DEFAULT NEXTVAL(('rnn.rnn_seq'::text)::regclass),
	gebiedsnaam varchar(255) NOT NULL,    -- name of the beoordelings gebied
	identificatie varchar(255) NOT NULL,    -- identification for this table, which contains the name and bronhouder_id
	beschrijving varchar(1000) NULL,
	bronhouder_id bigint NOT NULL,
	object_begin_tijd timestamp NOT NULL,
	object_eind_tijd timestamp NULL,
	geom geometry NOT NULL
)
;

ALTER TABLE rnn.beoordelings_gebied
    OWNER to anlb;

CREATE TABLE IF NOT EXISTS rnn.indicator_beheer_type
(
	id bigint NOT NULL   DEFAULT NEXTVAL(('rnn.rnn_seq'::text)::regclass),
	beheer_type_id bigint NOT NULL,
	indicator_type_id bigint NOT NULL,
	wegingsfactor integer NULL,
	begin_geldigheid timestamp NOT NULL,
	eind_geldigheid timestamp NULL
)
;

ALTER TABLE rnn.indicator_beheer_type
    OWNER to anlb;

CREATE TABLE IF NOT EXISTS rnn.kwalificerende_kenmerk
(
	id bigint NOT NULL   DEFAULT NEXTVAL(('rnn.rnn_seq'::text)::regclass),
	indicator_beheer_type_id bigint NOT NULL,
	domain_kwalificerende_kenmerk_id bigint NOT NULL,
	begin_geldigheid timestamp NOT NULL,
	eind_geldigheid timestamp NULL
)
;

ALTER TABLE rnn.kwalificerende_kenmerk
    OWNER to anlb;

CREATE TABLE IF NOT EXISTS rnn.maatlat
(
	id bigint NOT NULL   DEFAULT NEXTVAL(('rnn.rnn_seq'::text)::regclass),
	kwalificerende_kenmerk_id bigint NOT NULL,
	waarde_min NUMERIC(10,2) NOT NULL,
	waarde_max NUMERIC(10,2) NOT NULL,
	kwaliteits_bepaling bigint NOT NULL
)
;


ALTER TABLE rnn.maatlat
    OWNER to anlb;

CREATE TABLE IF NOT EXISTS rnn.rode_lijst_configuratie
(
	id bigint NOT NULL   DEFAULT NEXTVAL(('rnn.rnn_seq'::text)::regclass),
	kwalificerende_kenmerk_id bigint NOT NULL,
	aantal_extra_kwalificerende_soorten integer NOT NULL
)
;

ALTER TABLE rnn.rode_lijst_configuratie
    OWNER to anlb;

CREATE TABLE IF NOT EXISTS rnn.rode_lijst_configuratie_rode_lijst_categorie
(
	rode_lijst_configuratie_id bigint NOT NULL,
	rode_lijst_categorie_id bigint NOT NULL
)
;

ALTER TABLE rnn.rode_lijst_configuratie_rode_lijst_categorie
    OWNER to anlb;

CREATE TABLE IF NOT EXISTS rnn.rode_lijst_configuratie_soort_groep
(
	rode_lijst_configuratie_id bigint NOT NULL,
	soort_groep_id bigint NOT NULL
)
;

ALTER TABLE rnn.rode_lijst_configuratie_soort_groep
    OWNER to anlb;

CREATE TABLE IF NOT EXISTS rnn.rnn_soort_groep
(
	soort_groep_id bigint NOT NULL
)
;

ALTER TABLE rnn.rnn_soort_groep
    OWNER to anlb;
	
/* Create Primary Keys, Indexes, Uniques, Checks */

SELECT pg_temp.create_constraint_if_not_exists ('rnn','soort_per_beheer_type','PK_taxa_per_beheer_type',
'ALTER TABLE rnn.soort_per_beheer_type ADD CONSTRAINT PK_taxa_per_beheer_type
	PRIMARY KEY (soort_id,beheer_type_id,begin_geldigheid)
;');


CREATE INDEX IF NOT EXISTS IXFK_soort_per_beheer_type_dmn_beheer_type ON rnn.soort_per_beheer_type (beheer_type_id ASC);

CREATE INDEX IF NOT EXISTS IXFK_soort_per_beheer_type_soort ON rnn.soort_per_beheer_type (soort_id ASC)
;

CREATE INDEX IF NOT EXISTS IXFK_soort_per_beheer_type_dmn_rnn_soort_groep_voor_telling ON rnn.soort_per_beheer_type (rnn_soort_groep_voor_telling ASC);

SELECT pg_temp.create_constraint_if_not_exists ('rnn','grid_100_by_100','PK_grid_100_by_100',
'ALTER TABLE rnn.grid_100_by_100 ADD CONSTRAINT PK_grid_100_by_100
	PRIMARY KEY (id)
;');

SELECT pg_temp.create_constraint_if_not_exists ('rnn','beoordelings_gebied','PK_beoordelings_gebied',
'ALTER TABLE rnn.beoordelings_gebied ADD CONSTRAINT PK_beoordelings_gebied
	PRIMARY KEY (id)
;');

SELECT pg_temp.create_constraint_if_not_exists ('rnn','beoordelings_gebied','UN_beoordelings_gebied_identificatie',
'ALTER TABLE rnn.beoordelings_gebied ADD CONSTRAINT UN_beoordelings_gebied_identificatie UNIQUE (identificatie)
;');

SELECT pg_temp.create_constraint_if_not_exists ('rnn','beoordelings_gebied','UN_beoordelings_gebied_naam_brondhouder',
'ALTER TABLE rnn.beoordelings_gebied ADD CONSTRAINT UN_beoordelings_gebied_naam_brondhouder UNIQUE (gebiedsnaam,bronhouder_id)
;');

CREATE INDEX IF NOT EXISTS IXFK_beoordelings_gebied_dmn_bronhouder_code ON rnn.beoordelings_gebied (bronhouder_id ASC)
;

SELECT pg_temp.create_constraint_if_not_exists ('rnn','indicator_beheer_type','PK_indicator_beheer_type',
'ALTER TABLE rnn.indicator_beheer_type ADD CONSTRAINT PK_indicator_beheer_type
	PRIMARY KEY (id)
;');

SELECT pg_temp.create_constraint_if_not_exists ('rnn','indicator_beheer_type','UN_indicator_beheer_type_identity',
'ALTER TABLE rnn.indicator_beheer_type ADD CONSTRAINT UN_indicator_beheer_type_identity UNIQUE (beheer_type_id,indicator_type_id,begin_geldigheid)
;');


CREATE INDEX IF NOT EXISTS IXFK_indicator_beheer_type_dmn_beheer_type ON rnn.indicator_beheer_type (beheer_type_id ASC);

CREATE INDEX IF NOT EXISTS IXFK_indicator_beheer_type_dmn_indicator_type ON rnn.indicator_beheer_type (indicator_type_id ASC)
;

SELECT pg_temp.create_constraint_if_not_exists ('rnn','kwalificerende_kenmerk','PK_kwalificerende_kenmerk',
'ALTER TABLE rnn.kwalificerende_kenmerk ADD CONSTRAINT PK_kwalificerende_kenmerk
	PRIMARY KEY (id)
;');

SELECT pg_temp.create_constraint_if_not_exists ('rnn','kwalificerende_kenmerk','UN_kwalificerende_kenmerk_indentity',
'ALTER TABLE rnn.kwalificerende_kenmerk ADD CONSTRAINT UN_kwalificerende_kenmerk_indentity UNIQUE (domain_kwalificerende_kenmerk_id,indicator_beheer_type_id,begin_geldigheid)
;');


CREATE INDEX IF NOT EXISTS IXFK_kwalificerende_kenmerk_dmn_kwalificerende_kenmerk ON rnn.kwalificerende_kenmerk (domain_kwalificerende_kenmerk_id ASC)
;

CREATE INDEX IF NOT EXISTS IXFK_kwalificerende_kenmerk_indicator_beheer_type ON rnn.kwalificerende_kenmerk (indicator_beheer_type_id ASC)
;

SELECT pg_temp.create_constraint_if_not_exists ('rnn','maatlat','PK_maatlat',
'ALTER TABLE rnn.maatlat ADD CONSTRAINT PK_maatlat
	PRIMARY KEY (id)
;');

CREATE INDEX IF NOT EXISTS IXFK_maatlat_dmn_kwaliteits_bepaling ON rnn.maatlat (kwaliteits_bepaling ASC)
;

CREATE INDEX IF NOT EXISTS IXFK_maatlat_kwalificerende_kenmerk ON rnn.maatlat (kwalificerende_kenmerk_id ASC)
;

SELECT pg_temp.create_constraint_if_not_exists ('rnn','rode_lijst_configuratie','PK_rode_lijst_configuratie',
'ALTER TABLE rnn.rode_lijst_configuratie ADD CONSTRAINT PK_rode_lijst_configuratie
	PRIMARY KEY (id)
;');

SELECT pg_temp.create_constraint_if_not_exists ('rnn','rode_lijst_configuratie','UN_rode_lijst_configuratie_identificatie',
'ALTER TABLE rnn.rode_lijst_configuratie ADD CONSTRAINT UN_rode_lijst_configuratie_identificatie UNIQUE (kwalificerende_kenmerk_id)
;');

CREATE INDEX IF NOT EXISTS IXFK_rode_lijst_configuratie_kwalificerende_kenmerk ON rnn.rode_lijst_configuratie (kwalificerende_kenmerk_id ASC)
;

SELECT pg_temp.create_constraint_if_not_exists ('rnn','rode_lijst_configuratie_rode_lijst_categorie','PK_rode_lijst_conf_rode_lijst_cat',
'ALTER TABLE rnn.rode_lijst_configuratie_rode_lijst_categorie ADD CONSTRAINT PK_rode_lijst_conf_rode_lijst_cat
	PRIMARY KEY (rode_lijst_configuratie_id,rode_lijst_categorie_id)
;');


CREATE INDEX IF NOT EXISTS IXFK_rode_lijst_conf_rode_lijst_cat_rode_lijst_cat ON rnn.rode_lijst_configuratie_rode_lijst_categorie (rode_lijst_categorie_id ASC)
;

CREATE INDEX IF NOT EXISTS IXFK_rode_lijst_conf_rode_lijst_cat_rode_lijst_conf ON rnn.rode_lijst_configuratie_rode_lijst_categorie (rode_lijst_configuratie_id ASC)
;

SELECT pg_temp.create_constraint_if_not_exists ('rnn','rode_lijst_configuratie_soort_groep','PK_rode_lijst_conf_soort_groep',
'ALTER TABLE rnn.rode_lijst_configuratie_soort_groep ADD CONSTRAINT PK_rode_lijst_conf_soort_groep
	PRIMARY KEY (rode_lijst_configuratie_id,soort_groep_id)
;');


CREATE INDEX IF NOT EXISTS IXFK_rode_lijst_conf_soort_groep_soort_groep ON rnn.rode_lijst_configuratie_soort_groep (rode_lijst_configuratie_id ASC)
;

CREATE INDEX IF NOT EXISTS IXFK_rode_lijst_conf_soort_groep_rode_lijst_conf ON rnn.rode_lijst_configuratie_soort_groep (soort_groep_id ASC)
;

SELECT pg_temp.create_constraint_if_not_exists ('rnn','rnn_soort_groep','PK_rnn_soort_groep',
'ALTER TABLE rnn.rnn_soort_groep ADD CONSTRAINT PK_rnn_soort_groep
	PRIMARY KEY (soort_groep_id)
;');


CREATE INDEX IF NOT EXISTS IXFK_rnn_soort_groep_species_group ON rnn.rnn_soort_groep (soort_groep_id ASC)
;


-- Create Foreign Key Constraints

SELECT pg_temp.create_constraint_if_not_exists ('rnn','soort_per_beheer_type','fk_soort_per_beheer_type_dmn_rnn_soort_groep_voor_telling',
'ALTER TABLE rnn.soort_per_beheer_type ADD CONSTRAINT fk_soort_per_beheer_type_dmn_rnn_soort_groep_voor_telling
	FOREIGN KEY (beheer_type_id) REFERENCES masterdata.dmn_beheer_type (id) ON DELETE No Action ON UPDATE No Action
;');



SELECT pg_temp.create_constraint_if_not_exists ('rnn','soort_per_beheer_type','FK_soort_per_beheer_type_soort',
'ALTER TABLE rnn.soort_per_beheer_type ADD CONSTRAINT FK_soort_per_beheer_type_soort
	FOREIGN KEY (soort_id) REFERENCES ndff.taxa (id) ON DELETE No Action ON UPDATE No Action
;');

SELECT pg_temp.create_constraint_if_not_exists ('rnn','soort_per_beheer_type','fk_taxa_per_beheer_type_dmn_rnn_soort_groep_voor_telling',
'ALTER TABLE rnn.soort_per_beheer_type ADD CONSTRAINT fk_taxa_per_beheer_type_dmn_rnn_soort_groep_voor_telling
	FOREIGN KEY (rnn_soort_groep_voor_telling) REFERENCES masterdata.dmn_rnn_soort_groep_voor_telling (id) ON DELETE No Action ON UPDATE No Action
;');

SELECT pg_temp.create_constraint_if_not_exists ('rnn','beoordelings_gebied','FK_beoordelings_gebied_dmn_bronhouder_rnn',
'ALTER TABLE rnn.beoordelings_gebied ADD CONSTRAINT FK_beoordelings_gebied_dmn_bronhouder_rnn
	FOREIGN KEY (bronhouder_id) REFERENCES masterdata.dmn_bronhouder_rnn (id) ON DELETE No Action ON UPDATE No Action
;');

SELECT pg_temp.create_constraint_if_not_exists ('rnn','indicator_beheer_type','FK_indicator_beheer_type_dmn_beheer_type',
'ALTER TABLE rnn.indicator_beheer_type ADD CONSTRAINT FK_indicator_beheer_type_dmn_beheer_type
	FOREIGN KEY (beheer_type_id) REFERENCES masterdata.dmn_beheer_type (id) ON DELETE No Action ON UPDATE No Action
;');



SELECT pg_temp.create_constraint_if_not_exists ('rnn','indicator_beheer_type','FK_indicator_beheer_type_dmn_indicator_type',
'ALTER TABLE rnn.indicator_beheer_type ADD CONSTRAINT FK_indicator_beheer_type_dmn_indicator_type
	FOREIGN KEY (indicator_type_id) REFERENCES masterdata.dmn_indicator_type (id) ON DELETE No Action ON UPDATE No Action
;');

SELECT pg_temp.create_constraint_if_not_exists ('rnn','kwalificerende_kenmerk','FK_kwalificerende_kenmerk_dmn_kwalificerende_kenmerk',
'ALTER TABLE rnn.kwalificerende_kenmerk ADD CONSTRAINT FK_kwalificerende_kenmerk_dmn_kwalificerende_kenmerk
	FOREIGN KEY (domain_kwalificerende_kenmerk_id) REFERENCES masterdata.dmn_kwalificerende_kenmerk (id) ON DELETE No Action ON UPDATE No Action
;');

SELECT pg_temp.create_constraint_if_not_exists ('rnn','kwalificerende_kenmerk','FK_kwalificerende_kenmerk_indicator_beheer_type',
'ALTER TABLE rnn.kwalificerende_kenmerk ADD CONSTRAINT FK_kwalificerende_kenmerk_indicator_beheer_type
	FOREIGN KEY (indicator_beheer_type_id) REFERENCES rnn.indicator_beheer_type (id) ON DELETE No Action ON UPDATE No Action
;');

SELECT pg_temp.create_constraint_if_not_exists ('rnn','maatlat','FK_maatlat_dmn_kwaliteits_bepaling',
'ALTER TABLE rnn.maatlat ADD CONSTRAINT FK_maatlat_dmn_kwaliteits_bepaling
	FOREIGN KEY (kwaliteits_bepaling) REFERENCES masterdata.dmn_kwaliteits_bepaling (id) ON DELETE No Action ON UPDATE No Action
;');

SELECT pg_temp.create_constraint_if_not_exists ('rnn','maatlat','FK_maatlat_kwalificerende_kenmerk',
'ALTER TABLE rnn.maatlat ADD CONSTRAINT FK_maatlat_kwalificerende_kenmerk
	FOREIGN KEY (kwalificerende_kenmerk_id) REFERENCES rnn.kwalificerende_kenmerk (id) ON DELETE No Action ON UPDATE No Action
;');

SELECT pg_temp.create_constraint_if_not_exists ('rnn','rode_lijst_configuratie','FK_rode_lijst_configuratie_kwalificerende_kenmerk',
'ALTER TABLE rnn.rode_lijst_configuratie ADD CONSTRAINT FK_rode_lijst_configuratie_kwalificerende_kenmerk
	FOREIGN KEY (kwalificerende_kenmerk_id) REFERENCES rnn.kwalificerende_kenmerk (id) ON DELETE No Action ON UPDATE No Action
;');

SELECT pg_temp.create_constraint_if_not_exists ('rnn','rode_lijst_configuratie_rode_lijst_categorie','FK_rode_lijst_conf_rode_lijst_cat_rode_lijst_cat',
'ALTER TABLE rnn.rode_lijst_configuratie_rode_lijst_categorie ADD CONSTRAINT FK_rode_lijst_conf_rode_lijst_cat_rode_lijst_cat
	FOREIGN KEY (rode_lijst_categorie_id) REFERENCES ndff.rode_lijst_categorie (id) ON DELETE No Action ON UPDATE No Action
;');

SELECT pg_temp.create_constraint_if_not_exists ('rnn','rode_lijst_configuratie_rode_lijst_categorie','FK_rode_lijst_conf_rode_lijst_cat_rode_lijst_conf',
'ALTER TABLE rnn.rode_lijst_configuratie_rode_lijst_categorie ADD CONSTRAINT FK_rode_lijst_conf_rode_lijst_cat_rode_lijst_conf
	FOREIGN KEY (rode_lijst_configuratie_id) REFERENCES rnn.rode_lijst_configuratie (id) ON DELETE No Action ON UPDATE No Action
;');


SELECT pg_temp.create_constraint_if_not_exists ('rnn','rode_lijst_configuratie_soort_groep','FK_rode_lijst_conf_soort_groep_rode_lijst_conf',
'ALTER TABLE rnn.rode_lijst_configuratie_soort_groep ADD CONSTRAINT FK_rode_lijst_conf_soort_groep_rode_lijst_conf
	FOREIGN KEY (rode_lijst_configuratie_id) REFERENCES rnn.rode_lijst_configuratie (id) ON DELETE No Action ON UPDATE No Action
;');

SELECT pg_temp.create_constraint_if_not_exists ('rnn','rode_lijst_configuratie_soort_groep','FK_rode_lijst_conf_soort_groep_soort_groep',
'ALTER TABLE rnn.rode_lijst_configuratie_soort_groep ADD CONSTRAINT FK_rode_lijst_conf_soort_groep_soort_groep
	FOREIGN KEY (soort_groep_id) REFERENCES ndff.species_group (id) ON DELETE No Action ON UPDATE No Action
;');

SELECT pg_temp.create_constraint_if_not_exists ('rnn','rnn_soort_groep','FK_rnn_soort_groep_species_group',
'ALTER TABLE rnn.rnn_soort_groep ADD CONSTRAINT FK_rnn_soort_groep_species_group
	FOREIGN KEY (soort_groep_id) REFERENCES ndff.species_group (id) ON DELETE No Action ON UPDATE No Action
;');


/* Create Table Comments, Sequences for Autonumber Columns */

COMMENT ON TABLE rnn.beoordelings_gebied
	IS 'The official beoordelings gebieden which where provided from the province are stored in this table.  Users can also add their own assessment areas to a file.'
;

COMMENT ON COLUMN rnn.beoordelings_gebied.id
	IS 'Internal id of the official assessment area.'
;

COMMENT ON COLUMN rnn.beoordelings_gebied.identificatie
	IS 'identification for this table, which contains the name and province id'
;

COMMENT ON COLUMN rnn.beoordelings_gebied.gebiedsnaam
	IS 'name of the beoordelings gebied'
;

COMMENT ON COLUMN rnn.beoordelings_gebied.beschrijving
	IS 'The coherent enumeration of characteristics of the object'
;

COMMENT ON COLUMN rnn.beoordelings_gebied.object_begin_tijd
	IS 'The time at which the object came into existence in reality'
;

COMMENT ON COLUMN rnn.beoordelings_gebied.object_eind_tijd
	IS 'The point in time at which the object is no longer valid in reality.'
;

COMMENT ON COLUMN rnn.beoordelings_gebied.geom
	IS 'The two-dimensional geometric representation of the plane formed by the contours of the object.'
;

COMMENT ON TABLE rnn.indicator_beheer_type
	IS 'Geeft weer welke indicatoren op een beheertype van toepassing zijn.'
;

COMMENT ON COLUMN rnn.indicator_beheer_type.beheer_type_id
	IS 'Indicates which indicators apply to a management type.'
;

COMMENT ON COLUMN rnn.indicator_beheer_type.wegingsfactor
	IS 'Weighting factor for a management type for an indicator'
;

COMMENT ON TABLE rnn.kwalificerende_kenmerk
	IS 'Kwalificerende kenmerk that apply to an indicator and to a management type.'
;

COMMENT ON TABLE rnn.maatlat
	IS 'The maatlatten are used for each management type and qualifying characteristic. The score for each management type is determined based on the maatlat.'
;

COMMENT ON COLUMN rnn.maatlat.kwalificerende_kenmerk_id
	IS 'Reference to kwalificerende kenmerk'
;

COMMENT ON COLUMN rnn.maatlat.waarde_min
	IS 'Minimum value that a calculation must fall within in order to be considered a kwaliteits bepaling'
;

COMMENT ON COLUMN rnn.maatlat.waarde_max
	IS 'Maximum value a calculation must fall within in order to be considered a kwaliteits bepaling.'
;

COMMENT ON COLUMN rnn.maatlat.kwaliteits_bepaling
	IS 'Reference to kwaliteits bepaling'
;

COMMENT ON TABLE rnn.rnn_soort_groep
	IS 'This table is used to provide the correct specie groups in the table dossier_beheer_type_soorten. A specie can have multiple species groups, but for RNN we only want to know the species groups that are also stated in this table. If it is not stated, the user sees null.'
;

COMMENT ON TABLE rnn.rode_lijst_configuratie
	IS 'This class describes the configuratie for the Kwalificerende Kenmerk ''Rode Lijst''. With this informatie the value of the Kwalificerende Kenmerk ''Rode lijst'' can be calculated. This value will be used when calculating the value of the kwalificerende kenmerk ''kwalificerende Soorten''.'''
;

COMMENT ON COLUMN rnn.rode_lijst_configuratie.kwalificerende_kenmerk_id
	IS 'Reference to kwalificerende kenmerk.'
;

COMMENT ON COLUMN rnn.rode_lijst_configuratie.aantal_extra_kwalificerende_soorten
	IS 'A number that indicates the maximum number of Red List species that can be added to the qualifying species.'
;

COMMENT ON TABLE rnn.rode_lijst_configuratie_rode_lijst_categorie
	IS 'Describes which red list categories are important for a red list configuration.'
;

COMMENT ON TABLE rnn.rode_lijst_configuratie_soort_groep
	IS 'Describes which type of groups are important for a red list configuration.'
;

COMMENT ON TABLE rnn.soort_per_beheer_type
	IS 'Configuration table that indicates which species are important for a management type.'
;

COMMENT ON COLUMN rnn.soort_per_beheer_type.rnn_soort_groep_voor_telling
	IS 'Indicates the species group to which a species belongs. These are different species groups than the NDFF.SpeciesGroups. These are used to calculate how many species groups have been observed.'
;


COMMENT ON COLUMN rnn.indicator_beheer_type.wegingsfactor
	IS 'Weighting factor for a management type for an indicator'
;

CREATE INDEX IF NOT EXISTS "IDX_grid_100_by_100_geom"
    ON rnn.grid_100_by_100 USING gist
    (geom);

GRANT SELECT ON ALL TABLES IN SCHEMA rnn TO anlb_sqlpad;