/* ---------------------------------------------------- */
/*  Generated by Enterprise Architect Version 12.1 		*/
/*  Created On : 26-Oct-2021 12:50:27 				*/
/*  DBMS       : PostgreSQL 						*/
/* ---------------------------------------------------- */

CREATE SCHEMA masterdata
    AUTHORIZATION ikn;

GRANT ALL ON SCHEMA masterdata TO ikn;

GRANT USAGE ON SCHEMA masterdata TO ikn_readonly;


/* Drop Views */

DROP VIEW IF EXISTS all_domains CASCADE
;

DROP VIEW IF EXISTS all_domain_features CASCADE
;

/* Drop Tables */

DROP TABLE IF EXISTS masterdata.beleid_naam_type CASCADE
;

DROP TABLE IF EXISTS masterdata.bron_specificatie CASCADE
;

DROP TABLE IF EXISTS masterdata.bron_specificatie_wfs CASCADE
;

DROP TABLE IF EXISTS masterdata.dmn_beleid_naam CASCADE
;

DROP TABLE IF EXISTS masterdata.dmn_beleid_type CASCADE
;

DROP TABLE IF EXISTS masterdata.dmn_bron_type CASCADE
;

DROP TABLE IF EXISTS masterdata.dmn_bronhouder CASCADE
;

DROP TABLE IF EXISTS masterdata.dmn_classificatie CASCADE
;

DROP TABLE IF EXISTS masterdata.domain_feature CASCADE
;

DROP TABLE IF EXISTS masterdata.feature_layer CASCADE
;

DROP TABLE IF EXISTS masterdata.layer_metadata CASCADE
;

DROP TABLE IF EXISTS masterdata.lnk_table_classificatie_1 CASCADE
;

DROP TABLE IF EXISTS masterdata.lnk_table_classificatie_2 CASCADE
;

DROP TABLE IF EXISTS masterdata.lnk_table_classificatie_3 CASCADE
;

DROP TABLE IF EXISTS masterdata.mandatory_attributes CASCADE
;

DROP TABLE IF EXISTS masterdata.parameters CASCADE
;

DROP TABLE IF EXISTS masterdata.provinces CASCADE
;

DROP TABLE IF EXISTS masterdata.specific_attribute_types CASCADE
;

DROP TABLE IF EXISTS masterdata.translations CASCADE
;

/* Drop Sequences */

DROP SEQUENCE  IF EXISTS  masterdata_seq  CASCADE
;

/* Create Sequences */

CREATE SEQUENCE masterdata.masterdata_seq
    INCREMENT 1
    START 1
    MINVALUE 1
    MAXVALUE 9223372036854775807
    CACHE 1;

ALTER SEQUENCE masterdata.masterdata_seq
    OWNER TO ikn
;

/* Create Tables */

CREATE TABLE masterdata.beleid_naam_type
(
	beleid_naam_id bigint NOT NULL,    -- De aanduiding van het natuurbeleid in de informatiekaart natuur
	beleid_type_id bigint NOT NULL    -- De indeling in type natuurbeleid volgens de typering uit de codelijst beleidType
)
;

CREATE TABLE masterdata.bron_specificatie
(
	beleid_naam_id bigint NOT NULL,    -- De aanduiding van het natuurbeleid in de informatiekaart natuur
	bronhouder_id bigint NOT NULL,    -- De overheidsorganisatie die het beleid heeft opgesteld
	bron_type_id bigint NOT NULL,    -- Source can be  	- WFS 	- FGDB 	- Other
	valid_from timestamp NOT NULL,
	valid_to timestamp NULL
)
;

CREATE TABLE masterdata.bron_specificatie_wfs
(
	beleid_naam_id bigint NOT NULL,    -- De aanduiding van het natuurbeleid in de informatiekaart natuur
	bronhouder_id bigint NOT NULL,    -- De overheidsorganisatie die het beleid heeft opgesteld
	metadata_url varchar(1024) NOT NULL,    -- The URL to the xml containing the metadata of this dataset as specified in v2.1.0 of the Dutch profile on the ISO 19115.
	wfs_end_point varchar(255) NOT NULL,    -- Link to the WFS endpoint where the source data can be harvested.
	feature_type varchar(255) NOT NULL,    -- The featuere type of the dataset in the WFS endpoint where the source data can be harvested.
	laatste_revisie timestamp NOT NULL,    -- Latest revision of the dataset that was processed into IKN
	changed_by_user boolean NOT NULL   DEFAULT false    -- Indicates if the user manually changed the WFS specification.
)
;

CREATE TABLE masterdata.dmn_beleid_naam
(
	id bigint NOT NULL   DEFAULT NEXTVAL(('masterdata.masterdata_seq'::text)::regclass),
	code char(20) NOT NULL,
	description char(100) NULL,
	valid_from timestamp NOT NULL,
	valid_to timestamp NULL
)
;

CREATE TABLE masterdata.dmn_beleid_type
(
	id bigint NOT NULL   DEFAULT NEXTVAL(('masterdata.masterdata_seq'::text)::regclass),
	code char(20) NOT NULL,
	description char(100) NULL,
	valid_from timestamp NOT NULL,
	valid_to timestamp NULL
)
;

CREATE TABLE masterdata.dmn_bron_type
(
	id bigint NOT NULL   DEFAULT NEXTVAL(('masterdata.masterdata_seq'::text)::regclass),
	code char(20) NOT NULL,
	description char(100) NULL,
	valid_from timestamp NOT NULL,
	valid_to timestamp NULL
)
;

CREATE TABLE masterdata.dmn_bronhouder
(
	id bigint NOT NULL   DEFAULT NEXTVAL(('masterdata.masterdata_seq'::text)::regclass),
	code char(20) NOT NULL,
	description char(100) NULL,
	valid_from timestamp NOT NULL,
	valid_to timestamp NULL
)
;

CREATE TABLE masterdata.dmn_classificatie
(
	id bigint NOT NULL   DEFAULT NEXTVAL(('masterdata.masterdata_seq'::text)::regclass),
	code char(20) NOT NULL,
	description char(100) NULL,
	valid_from timestamp NOT NULL,
	valid_to timestamp NULL
)
;

CREATE TABLE masterdata.domain_feature
(
	domain char(100) NOT NULL,
	feature char(100) NOT NULL,
	attribute char(100) NOT NULL
)
;

CREATE TABLE masterdata.feature_layer
(
	feature char(100) NOT NULL,
	layer char(100) NOT NULL,
	geo_validation boolean NOT NULL,
	self_overlap_validation boolean NOT NULL,
	multipart_validation boolean NOT NULL,
	date_range_validation boolean NOT NULL,
	identificatie_validation boolean NOT NULL
)
;

CREATE TABLE masterdata.layer_metadata
(
	layer varchar(100) NOT NULL,
	metadata_id uuid NOT NULL,
	metadata_file varchar(1024) NOT NULL,
	domain_id bigint NULL
)
;

CREATE TABLE masterdata.lnk_table_classificatie_1
(
	beleid_naam_id bigint NOT NULL,
	classificatie_1_id bigint NOT NULL,
	valid_from timestamp NOT NULL,
	valid_to timestamp NULL
)
;

CREATE TABLE masterdata.lnk_table_classificatie_2
(
	beleid_naam_id bigint NOT NULL,
	classificatie_2_id bigint NOT NULL,
	valid_from timestamp NOT NULL,
	valid_to timestamp NULL
)
;

CREATE TABLE masterdata.lnk_table_classificatie_3
(
	beleid_naam_id bigint NOT NULL,
	classificatie_3_id bigint NOT NULL,
	valid_from timestamp NOT NULL,
	valid_to timestamp NULL
)
;

CREATE TABLE masterdata.mandatory_attributes
(
	feature char(100) NOT NULL,
	attribute char(100) NOT NULL
)
;

CREATE TABLE masterdata.parameters
(
	name varchar(50) NOT NULL,
	value varchar(1024) NOT NULL
)
;

CREATE TABLE masterdata.provinces
(
	code char(2) NOT NULL,
	drupal_role char(50) NOT NULL,
	program char(10) NOT NULL,
	name char(50) NOT NULL
)
;

CREATE TABLE masterdata.specific_attribute_types
(
	feature varchar(100) NOT NULL,
	attribute varchar(100) NOT NULL,
	type varchar(20) NOT NULL,
	length bigint NULL
)
;

CREATE TABLE masterdata.translations
(
	nl varchar(255) NOT NULL,
	en varchar(255) NOT NULL
)
;

/* Create Primary Keys, Indexes, Uniques, Checks */

ALTER TABLE masterdata.beleid_naam_type ADD CONSTRAINT PK_beleid_naam_type
	PRIMARY KEY (beleid_naam_id)
;

CREATE INDEX IXFK_beleid_naam_type_dmn_beleid_naam ON masterdata.beleid_naam_type (beleid_naam_id ASC)
;

CREATE INDEX IXFK_beleid_naam_type_dmn_beleid_type ON masterdata.beleid_naam_type (beleid_type_id ASC)
;

ALTER TABLE masterdata.bron_specificatie ADD CONSTRAINT PK_bron_specificatie
	PRIMARY KEY (beleid_naam_id,bronhouder_id)
;

CREATE INDEX IXFK_bron_specificatie_dmn_beleid_naam ON masterdata.bron_specificatie (beleid_naam_id ASC)
;

CREATE INDEX IXFK_bron_specificatie_dmn_bron_type ON masterdata.bron_specificatie (bron_type_id ASC)
;

CREATE INDEX IXFK_bron_specificatie_dmn_bronhouder ON masterdata.bron_specificatie (bronhouder_id ASC)
;

ALTER TABLE masterdata.bron_specificatie_wfs ADD CONSTRAINT PK_bron_specificatie_wfs
	PRIMARY KEY (beleid_naam_id,bronhouder_id)
;

CREATE INDEX IXFK_bron_specificatie_wfs_bron_specificatie ON masterdata.bron_specificatie_wfs (beleid_naam_id ASC,bronhouder_id ASC)
;

ALTER TABLE masterdata.dmn_beleid_naam ADD CONSTRAINT PK_dmn_beleid_naam
	PRIMARY KEY (id)
;

ALTER TABLE masterdata.dmn_beleid_naam ADD CONSTRAINT un_code_beleid_naam UNIQUE (code)
;

ALTER TABLE masterdata.dmn_beleid_type ADD CONSTRAINT PK_dmn_beleid_type
	PRIMARY KEY (id)
;

ALTER TABLE masterdata.dmn_beleid_type ADD CONSTRAINT un_code_beleid_type UNIQUE (code)
;

ALTER TABLE masterdata.dmn_bron_type ADD CONSTRAINT PK_dmn_bron_type
	PRIMARY KEY (id)
;

ALTER TABLE masterdata.dmn_bron_type ADD CONSTRAINT un_code_bron_type UNIQUE (code)
;

ALTER TABLE masterdata.dmn_bronhouder ADD CONSTRAINT PK_dmn_bronhouder
	PRIMARY KEY (id)
;

ALTER TABLE masterdata.dmn_bronhouder ADD CONSTRAINT un_code_bronhouder UNIQUE (code)
;

ALTER TABLE masterdata.dmn_classificatie ADD CONSTRAINT PK_dmn_classificatie
	PRIMARY KEY (id)
;

ALTER TABLE masterdata.dmn_classificatie ADD CONSTRAINT un_code_classificatie UNIQUE (code)
;

ALTER TABLE masterdata.feature_layer ADD CONSTRAINT PK_feature_layer
	PRIMARY KEY (feature,layer)
;

ALTER TABLE masterdata.layer_metadata ADD CONSTRAINT PK_layer_metadata
	PRIMARY KEY (layer)
;

ALTER TABLE masterdata.lnk_table_classificatie_1 ADD CONSTRAINT PK_lnk_table_classificatie_1
	PRIMARY KEY (beleid_naam_id,classificatie_1_id)
;

CREATE INDEX IXFK_lnk_table_classificatie_1_dmn_beleid_naam ON masterdata.lnk_table_classificatie_1 (beleid_naam_id ASC)
;

CREATE INDEX IXFK_lnk_table_classificatie_1_dmn_classificatie ON masterdata.lnk_table_classificatie_1 (classificatie_1_id ASC)
;

ALTER TABLE masterdata.lnk_table_classificatie_2 ADD CONSTRAINT PK_lnk_table_classificatie_2
	PRIMARY KEY (beleid_naam_id,classificatie_2_id)
;

CREATE INDEX IXFK_lnk_table_classificatie_2_dmn_beleid_naam ON masterdata.lnk_table_classificatie_2 (beleid_naam_id ASC)
;

CREATE INDEX IXFK_lnk_table_classificatie_2_dmn_classificatie ON masterdata.lnk_table_classificatie_2 (classificatie_2_id ASC)
;

ALTER TABLE masterdata.lnk_table_classificatie_3 ADD CONSTRAINT PK_lnk_table_classificatie_3
	PRIMARY KEY (beleid_naam_id,classificatie_3_id)
;

CREATE INDEX IXFK_lnk_table_classificatie_3_dmn_beleid_naam ON masterdata.lnk_table_classificatie_3 (beleid_naam_id ASC)
;

CREATE INDEX IXFK_lnk_table_classificatie_3_dmn_classificatie ON masterdata.lnk_table_classificatie_3 (classificatie_3_id ASC)
;

ALTER TABLE masterdata.mandatory_attributes ADD CONSTRAINT PK_mandatory_attributes
	PRIMARY KEY (feature,attribute)
;

ALTER TABLE masterdata.parameters ADD CONSTRAINT PK_parameters
	PRIMARY KEY (name)
;

ALTER TABLE masterdata.provinces ADD CONSTRAINT PK_provinces
	PRIMARY KEY (code,drupal_role)
;

ALTER TABLE masterdata.specific_attribute_types ADD CONSTRAINT PK_specific_attribute_types
	PRIMARY KEY (feature,attribute)
;

ALTER TABLE masterdata.translations ADD CONSTRAINT PK_translations
	PRIMARY KEY (nl)
;

/* Create Foreign Key Constraints */

ALTER TABLE masterdata.beleid_naam_type ADD CONSTRAINT FK_beleid_naam_type_dmn_beleid_naam
	FOREIGN KEY (beleid_naam_id) REFERENCES masterdata.dmn_beleid_naam (id) ON DELETE No Action ON UPDATE No Action
;

ALTER TABLE masterdata.beleid_naam_type ADD CONSTRAINT FK_beleid_naam_type_dmn_beleid_type
	FOREIGN KEY (beleid_type_id) REFERENCES masterdata.dmn_beleid_type (id) ON DELETE No Action ON UPDATE No Action
;

ALTER TABLE masterdata.bron_specificatie ADD CONSTRAINT FK_bron_specificatie_dmn_beleid_naam
	FOREIGN KEY (beleid_naam_id) REFERENCES masterdata.dmn_beleid_naam (id) ON DELETE No Action ON UPDATE No Action
;

ALTER TABLE masterdata.bron_specificatie ADD CONSTRAINT FK_bron_specificatie_dmn_bron_type
	FOREIGN KEY (bron_type_id) REFERENCES masterdata.dmn_bron_type (id) ON DELETE No Action ON UPDATE No Action
;

ALTER TABLE masterdata.bron_specificatie ADD CONSTRAINT FK_bron_specificatie_dmn_bronhouder
	FOREIGN KEY (bronhouder_id) REFERENCES masterdata.dmn_bronhouder (id) ON DELETE No Action ON UPDATE No Action
;

ALTER TABLE masterdata.bron_specificatie_wfs ADD CONSTRAINT FK_bron_specificatie_wfs_bron_specificatie
	FOREIGN KEY (beleid_naam_id,bronhouder_id) REFERENCES masterdata.bron_specificatie (beleid_naam_id,bronhouder_id) ON DELETE No Action ON UPDATE No Action
;

ALTER TABLE masterdata.lnk_table_classificatie_1 ADD CONSTRAINT FK_lnk_table_classificatie_1_dmn_beleid_naam
	FOREIGN KEY (beleid_naam_id) REFERENCES masterdata.dmn_beleid_naam (id) ON DELETE No Action ON UPDATE No Action
;

ALTER TABLE masterdata.lnk_table_classificatie_1 ADD CONSTRAINT FK_lnk_table_classificatie_1_dmn_classificatie
	FOREIGN KEY (classificatie_1_id) REFERENCES masterdata.dmn_classificatie (id) ON DELETE No Action ON UPDATE No Action
;

ALTER TABLE masterdata.lnk_table_classificatie_2 ADD CONSTRAINT FK_lnk_table_classificatie_2_dmn_beleid_naam
	FOREIGN KEY (beleid_naam_id) REFERENCES masterdata.dmn_beleid_naam (id) ON DELETE No Action ON UPDATE No Action
;

ALTER TABLE masterdata.lnk_table_classificatie_2 ADD CONSTRAINT FK_lnk_table_classificatie_2_dmn_classificatie
	FOREIGN KEY (classificatie_2_id) REFERENCES masterdata.dmn_classificatie (id) ON DELETE No Action ON UPDATE No Action
;

ALTER TABLE masterdata.lnk_table_classificatie_3 ADD CONSTRAINT FK_lnk_table_classificatie_3_dmn_beleid_naam
	FOREIGN KEY (beleid_naam_id) REFERENCES masterdata.dmn_beleid_naam (id) ON DELETE No Action ON UPDATE No Action
;

ALTER TABLE masterdata.lnk_table_classificatie_3 ADD CONSTRAINT FK_lnk_table_classificatie_3_dmn_classificatie
	FOREIGN KEY (classificatie_3_id) REFERENCES masterdata.dmn_classificatie (id) ON DELETE No Action ON UPDATE No Action
;

/* Create Table Comments, Sequences for Autonumber Columns */

COMMENT ON TABLE masterdata.beleid_naam_type
	IS 'Masterdata table specifying the beleidType that is linked to the beleidNaam'
;

COMMENT ON COLUMN masterdata.beleid_naam_type.beleid_naam_id
	IS 'De aanduiding van het natuurbeleid in de informatiekaart natuur'
;

COMMENT ON COLUMN masterdata.beleid_naam_type.beleid_type_id
	IS 'De indeling in type natuurbeleid volgens de typering uit de codelijst beleidType'
;

COMMENT ON TABLE masterdata.bron_specificatie
	IS 'Masterdata table specifying the source per  	1. bronhouder 	2. beleidNaam   Source can be  	- WFS 	- FGDB 	- Other'
;

COMMENT ON COLUMN masterdata.bron_specificatie.beleid_naam_id
	IS 'De aanduiding van het natuurbeleid in de informatiekaart natuur'
;

COMMENT ON COLUMN masterdata.bron_specificatie.bronhouder_id
	IS 'De overheidsorganisatie die het beleid heeft opgesteld'
;

COMMENT ON COLUMN masterdata.bron_specificatie.bron_type_id
	IS 'Source can be  	- WFS 	- FGDB 	- Other'
;

COMMENT ON TABLE masterdata.bron_specificatie_wfs
	IS 'Masterdata table specifying the WFS source per  	1. bronhouder 	2. beleidNaam'
;

COMMENT ON COLUMN masterdata.bron_specificatie_wfs.beleid_naam_id
	IS 'De aanduiding van het natuurbeleid in de informatiekaart natuur'
;

COMMENT ON COLUMN masterdata.bron_specificatie_wfs.bronhouder_id
	IS 'De overheidsorganisatie die het beleid heeft opgesteld'
;

COMMENT ON COLUMN masterdata.bron_specificatie_wfs.metadata_url
	IS 'The URL to the xml containing the metadata of this dataset as specified in v2.1.0 of the Dutch profile on the ISO 19115.'
;

COMMENT ON COLUMN masterdata.bron_specificatie_wfs.wfs_end_point
	IS 'Link to the WFS endpoint where the source data can be harvested.'
;

COMMENT ON COLUMN masterdata.bron_specificatie_wfs.feature_type
	IS 'The featuere type of the dataset in the WFS endpoint where the source data can be harvested.'
;

COMMENT ON COLUMN masterdata.bron_specificatie_wfs.laatste_revisie
	IS 'Latest revision of the dataset that was processed into IKN'
;

COMMENT ON COLUMN masterdata.bron_specificatie_wfs.changed_by_user
	IS 'Indicates if the user manually changed the WFS specification.'
;

COMMENT ON TABLE masterdata.dmn_beleid_naam
	IS 'Domain specifying the regulation that applies to the nature area'
;

COMMENT ON TABLE masterdata.dmn_beleid_type
	IS 'Domain specifying the type of regulation (so an aggregate of the regulation e.g. beleid) of the nature area'
;

COMMENT ON TABLE masterdata.dmn_bron_type
	IS 'Domain specifying the source of the data. Possible values can be:  	1. WFS 	2. FGDB 	3. Other'
;

COMMENT ON TABLE masterdata.dmn_bronhouder
	IS 'Domain specifying the unique organisations responslible for a certain set of the data in IKN'
;

COMMENT ON TABLE masterdata.dmn_classificatie
	IS 'Domain specifying a sub classification of the nature area that can be used in the symology of map layer for the nature area'
;

/* Create Views */

-- View: masterdata.all_domains

--DROP VIEW masterdata.all_domains;

CREATE OR REPLACE VIEW masterdata.all_domains AS
    SELECT
        id,
        code,
        description,
		valid_from,
		valid_to,
        'dmn_beleid_naam' AS dmn
    FROM
        masterdata.dmn_beleid_naam
    UNION
    SELECT
        id,
        code,
        description,
		valid_from,
		valid_to,
        'dmn_bronhouder' AS dmn
    FROM
        masterdata.dmn_bronhouder
    UNION
    SELECT
        id,
        code,
        description,
		valid_from,
		valid_to,
        'dmn_classificatie' AS dmn
    FROM
        masterdata.dmn_classificatie
    UNION
    SELECT
        id,
        code,
        description,
		valid_from,
		valid_to,
        'dmn_beleid_type' AS dmn
    FROM
        masterdata.dmn_beleid_type
    UNION
    SELECT
        id,
        code,
        description,
		valid_from,
		valid_to,
        'dmn_bron_type' AS dmn
    FROM
        masterdata.dmn_bron_type		
		;

ALTER TABLE masterdata.all_domains
  OWNER TO ikn;
GRANT SELECT ON TABLE masterdata.all_domains TO ikn_readonly
;

-- View: masterdata.all_domain_features

-- DROP VIEW masterdata.all_domain_features;

CREATE OR REPLACE VIEW masterdata.all_domain_features AS 
 SELECT all_domains.id,
    all_domains.code,
    all_domains.description,
    all_domains.valid_from,
    all_domains.valid_to,
    all_domains.dmn,
    domain_feature.domain,
    domain_feature.feature,
    domain_feature.attribute
   FROM masterdata.all_domains
     JOIN masterdata.domain_feature ON all_domains.dmn = domain_feature.domain;

ALTER TABLE masterdata.all_domain_features
  OWNER TO ikn;
GRANT SELECT ON TABLE masterdata.all_domain_features TO ikn_readonly
;

GRANT SELECT ON ALL TABLES IN SCHEMA masterdata TO ikn_readonly;
