stages:
  - build

build-new_dev-n2000_submission:
  stage: build

  cache: null

  script:
    - echo "BEGIN - Deploying the code for dev..."
    - if (Test-Path $IMNa_PATH\FME) { Remove-Item $IMNa_PATH\FME -Force -Recurse }
    - cp -R FME $IMNa_PATH\FME
    - Invoke-Command -ScriptBlock { D:\GitLab-Deployments\IMNa\FME\scripts\IMNa_N2000_Submission.ps1 D:\GitLab-Deployments\IMNa\FME\properties\dev.properties $FME_TOKEN_NEW_DEV}
    - echo "END - Deployment complete."

  environment:
    name: development

  rules:
    - if: $CI_COMMIT_BRANCH == $CI_DEFAULT_BRANCH
      changes:
        - FME/projects/IMNa_N2000_Submission.fsproject
        - FME/properties/IMNa_N2000_Submission_Dev.xml
        - FME/scripts/IMNa_N2000_Submission.ps1
        - FME/xslts/IMNa_N2000_Submission.xslt
        - FME/workspaces/IMNa_N2000/*
        - FME/workspaces/.gitlab-ci-IMNa_N2000_Submission.yml
      when: manual

build-new_test-n2000_submission:
  stage: build

  cache: null

  script:
    - echo "BEGIN - Deploying the code for test..."
    - if (Test-Path $IMNa_PATH\FME) { Remove-Item $IMNa_PATH\FME -Force -Recurse }
    - cp -R FME $IMNa_PATH\FME
    - Invoke-Command -ScriptBlock { D:\GitLab-Deployments\IMNa\FME\scripts\IMNa_N2000_Submission.ps1 D:\GitLab-Deployments\IMNa\FME\properties\test.properties $FME_TOKEN_NEW_TEST}
    - echo "END - Deployment complete."

  environment:
    name: test

  rules:
    - if: $CI_COMMIT_BRANCH == $CI_DEFAULT_BRANCH
      changes:
        - FME/projects/IMNa_N2000_Submission.fsproject
        - FME/properties/IMNa_N2000_Submission_Test.xml
        - FME/scripts/IMNa_N2000_Submission.ps1
        - FME/xslts/IMNa_N2000_Submission.xslt
        - FME/workspaces/IMNa_N2000/*
        - FME/workspaces/.gitlab-ci-IMNa_N2000_Submission.yml
      when: manual

# This is for Acceptance environment
build-new_acc-n2000_submission:
  stage: build

  cache: null

  script:
    - echo "BEGIN - Deploying the code for acc..."
    - if (Test-Path $IMNa_PATH\FME) { Remove-Item $IMNa_PATH\FME -Force -Recurse }
    - cp -R FME $IMNa_PATH\FME
    - Invoke-Command -ScriptBlock { D:\GitLab-Deployments\IMNa\FME\scripts\IMNa_N2000_Submission.ps1 D:\GitLab-Deployments\IMNa\FME\properties\acc.properties $FME_TOKEN_NEW_ACC}
    - echo "END - Deployment complete."

  environment:
    name: acceptance

  rules:
    - if: '$CI_COMMIT_TAG =~ /^v\d+.\d+.\d+-NDVH$/'
      when: manual

# This is for Production environment
build-new_prod-n2000_submission:
  stage: build

  cache: null

  script:
    - echo "BEGIN - Deploying the code for prod..."
    - if (Test-Path $IMNa_PATH\FME) { Remove-Item $IMNa_PATH\FME -Force -Recurse }
    - cp -R FME $IMNa_PATH\FME
    - Invoke-Command -ScriptBlock { D:\GitLab-Deployments\IMNa\FME\scripts\IMNa_N2000_Submission.ps1 D:\GitLab-Deployments\IMNa\FME\properties\prod.properties $FME_TOKEN_NEW_PROD}
    - echo "END - Deployment complete."

  environment:
    name: production

  rules:
    - if: '$CI_COMMIT_TAG =~ /^v\d+.\d+.\d+-NDVH$/'
      when: manual