/* ---------------------------------------------------- */
/*  Generated by Enterprise Architect Version 12.1 		*/
/*  Created On : 17-Feb-2022 12:42:55 				*/
/*  DBMS       : PostgreSQL 						*/
/* ---------------------------------------------------- */

/* Create Views */

-- View: geoserver.snl_nbp_upload

-- DROP VIEW geoserver.snl_nbp_upload;

CREATE OR REPLACE VIEW geoserver.snl_nbp_upload AS
 SELECT snl_nbp_upload.id,
        snl_nbp_upload.natuur_beheer_plan_id,
        ( SELECT dmn_provincie_code.code
            FROM masterdata.dmn_provincie_code
           WHERE dmn_provincie_code.id = snl_nbp_upload.provincie_id) AS provincie_code,
        ( SELECT dmn_provincie_code.description
            FROM masterdata.dmn_provincie_code
            WHERE dmn_provincie_code.id = snl_nbp_upload.provincie_id) AS provincie_desc,
        ( SELECT dmn_status_plan.code
            FROM masterdata.dmn_status_plan
           WHERE dmn_status_plan.id = snl_nbp_upload.plan_status_id) AS plan_status_code,
        ( SELECT dmn_status_plan.description
            FROM masterdata.dmn_status_plan
            WHERE dmn_status_plan.id = snl_nbp_upload.plan_status_id) AS plan_status_desc,			
		snl_nbp_upload.plan_subsidie_jaar,
        snl_nbp_upload.upload_date,
        snl_nbp_upload.user_id,
		snl_nbp_upload.type_run,
        snl_nbp_upload.status,
	    NULL::geometry AS geom
   FROM geoweb.snl_nbp_upload;

ALTER TABLE geoserver.snl_nbp_upload
    OWNER TO anlb;

GRANT SELECT ON TABLE geoserver.snl_nbp_upload TO snl_readonly;
GRANT SELECT ON TABLE geoserver.snl_nbp_upload TO anlb_sqlpad;


;

-- View: geoserver.snl_nbp_upload_files

-- DROP VIEW geoserver.snl_nbp_upload_files;

CREATE OR REPLACE VIEW geoserver.snl_nbp_upload_files AS
 SELECT snl_nbp_upload.id,
        snl_nbp_upload.natuur_beheer_plan_id,
        ( SELECT dmn_provincie_code.code
            FROM masterdata.dmn_provincie_code
           WHERE dmn_provincie_code.id = snl_nbp_upload.provincie_id) AS provincie_code,
        ( SELECT dmn_provincie_code.description
            FROM masterdata.dmn_provincie_code
           WHERE dmn_provincie_code.id = snl_nbp_upload.provincie_id) AS provincie_desc,	  
        snl_nbp_upload.upload_date,
        snl_nbp_upload.user_id,
        snl_nbp_upload_files.file_name,
		snl_nbp_upload_files.file_type,
        ((((( SELECT parameters.value
                FROM masterdata.parameters
               WHERE parameters.name::text = 'GeoWebNBPGetFileURL'::text))::text) || snl_nbp_upload.id) || '/'::text) || snl_nbp_upload_files.file_name::text AS file_url,
	     NULL::geometry AS geom
    FROM geoweb.snl_nbp_upload
    JOIN geoweb.snl_nbp_upload_files ON snl_nbp_upload.id = snl_nbp_upload_files.snl_nbp_upload_id;

ALTER TABLE geoserver.snl_nbp_upload_files
    OWNER TO anlb;

GRANT SELECT ON TABLE geoserver.snl_nbp_upload_files TO snl_readonly;
GRANT SELECT ON TABLE geoserver.snl_nbp_upload_files TO anlb_sqlpad;
;
