/* ---------------------------------------------------- */
/*  Generated by Enterprise Architect Version 12.1 		*/
/*  Created On : 11-Mar-2022 4:25:49 PM 				*/
/*  DBMS       : PostgreSQL 						*/
/* ---------------------------------------------------- */

/* Drop Views */

DROP VIEW IF EXISTS geoserver.snl_vrn_upload CASCADE
;

DROP VIEW IF EXISTS geoserver.snl_vrn_upload_files CASCADE
;

/* Create Views */

-- View: geoserver.snl_vrn_upload

-- DROP VIEW geoserver.snl_vrn_upload;

CREATE OR REPLACE VIEW geoserver.snl_vrn_upload AS
 SELECT snl_vrn_upload.id,
        snl_vrn_upload.voortgangs_rapportage_id,
        ( SELECT dmn_provincie_code.code
            FROM masterdata.dmn_provincie_code
           WHERE dmn_provincie_code.id = snl_vrn_upload.provincie_id) AS provincie_code,
        ( SELECT dmn_provincie_code.description
            FROM masterdata.dmn_provincie_code
            WHERE dmn_provincie_code.id = snl_vrn_upload.provincie_id) AS provincie_desc,		
		snl_vrn_upload.voortgangs_rapportage_jaar,
        snl_vrn_upload.upload_date,
        snl_vrn_upload.user_id,
		snl_vrn_upload.type_run,
        snl_vrn_upload.status,
	    NULL::geometry AS geom
   FROM geoweb.snl_vrn_upload;

ALTER TABLE geoserver.snl_vrn_upload
    OWNER TO anlb;

GRANT SELECT ON TABLE geoserver.snl_vrn_upload TO snl_readonly;
GRANT SELECT ON TABLE geoserver.snl_vrn_upload TO anlb_sqlpad;

;

-- View: geoserver.snl_vrn_upload_files

-- DROP VIEW geoserver.snl_vrn_upload_files;

CREATE OR REPLACE VIEW geoserver.snl_vrn_upload_files AS
 SELECT snl_vrn_upload.id,
        snl_vrn_upload.voortgangs_rapportage_id,
        ( SELECT dmn_provincie_code.code
            FROM masterdata.dmn_provincie_code
           WHERE dmn_provincie_code.id = snl_vrn_upload.provincie_id) AS provincie_code,
        ( SELECT dmn_provincie_code.description
            FROM masterdata.dmn_provincie_code
           WHERE dmn_provincie_code.id = snl_vrn_upload.provincie_id) AS provincie_desc,	  
        snl_vrn_upload.upload_date,
        snl_vrn_upload.user_id,
        snl_vrn_upload_files.file_name,
		snl_vrn_upload_files.file_type,
        ((((( SELECT parameters.value
                FROM masterdata.parameters
               WHERE parameters.name::text = 'GeoWebVRNGetFileURL'::text))::text) || snl_vrn_upload.id) || '/'::text) || snl_vrn_upload_files.file_name::text AS file_url,
	     NULL::geometry AS geom
    FROM geoweb.snl_vrn_upload
    JOIN geoweb.snl_vrn_upload_files ON snl_vrn_upload.id = snl_vrn_upload_files.snl_vrn_upload_id;

ALTER TABLE geoserver.snl_vrn_upload_files
    OWNER TO anlb;

GRANT SELECT ON TABLE geoserver.snl_vrn_upload_files TO snl_readonly;
GRANT SELECT ON TABLE geoserver.snl_vrn_upload_files TO anlb_sqlpad;
;
