/* ---------------------------------------------------- */
/*  Generated by Enterprise Architect Version 12.1 		*/
/*  Created On : 22-Feb-2022 10:21:30 AM 				*/
/*  DBMS       : PostgreSQL 						*/
/* ---------------------------------------------------- */

/* Drop Views */

DROP VIEW IF EXISTS geoserver.snl_bes_upload CASCADE
;

DROP VIEW IF EXISTS geoserver.snl_bes_upload_files CASCADE
;

/* Create Views */

-- View: geoserver.snl_bes_upload

-- DROP VIEW geoserver.snl_bes_upload;

CREATE OR REPLACE VIEW geoserver.snl_bes_upload AS
 SELECT snl_bes_upload.id,
        snl_bes_upload.beschikking_rapportage_id,
        ( SELECT dmn_provincie_code.code
            FROM masterdata.dmn_provincie_code
           WHERE dmn_provincie_code.id = snl_bes_upload.provincie_id) AS provincie_code,
        ( SELECT dmn_provincie_code.description
            FROM masterdata.dmn_provincie_code
            WHERE dmn_provincie_code.id = snl_bes_upload.provincie_id) AS provincie_desc,		
		snl_bes_upload.beschikking_beheer_jaar,
        snl_bes_upload.upload_date,
        snl_bes_upload.user_id,
		snl_bes_upload.type_run,
        snl_bes_upload.status,
	    NULL::geometry AS geom
   FROM geoweb.snl_bes_upload;

ALTER TABLE geoserver.snl_bes_upload
    OWNER TO anlb;

GRANT SELECT ON TABLE geoserver.snl_bes_upload TO snl_readonly;
GRANT SELECT ON TABLE geoserver.snl_bes_upload TO anlb_sqlpad;


;

-- View: geoserver.snl_bes_upload_files

-- DROP VIEW geoserver.snl_bes_upload_files;

CREATE OR REPLACE VIEW geoserver.snl_bes_upload_files AS
 SELECT snl_bes_upload.id,
        snl_bes_upload.beschikking_rapportage_id,
        ( SELECT dmn_provincie_code.code
            FROM masterdata.dmn_provincie_code
           WHERE dmn_provincie_code.id = snl_bes_upload.provincie_id) AS provincie_code,
        ( SELECT dmn_provincie_code.description
            FROM masterdata.dmn_provincie_code
           WHERE dmn_provincie_code.id = snl_bes_upload.provincie_id) AS provincie_desc,	  
        snl_bes_upload.upload_date,
        snl_bes_upload.user_id,
        snl_bes_upload_files.file_name,
		snl_bes_upload_files.file_type,
        ((((( SELECT parameters.value
                FROM masterdata.parameters
               WHERE parameters.name::text = 'GeoWebBESGetFileURL'::text))::text) || snl_bes_upload.id) || '/'::text) || snl_bes_upload_files.file_name::text AS file_url,
	     NULL::geometry AS geom
    FROM geoweb.snl_bes_upload
    JOIN geoweb.snl_bes_upload_files ON snl_bes_upload.id = snl_bes_upload_files.snl_bes_upload_id;

ALTER TABLE geoserver.snl_bes_upload_files
    OWNER TO anlb;

GRANT SELECT ON TABLE geoserver.snl_bes_upload_files TO snl_readonly;
GRANT SELECT ON TABLE geoserver.snl_bes_upload_files TO anlb_sqlpad;
;
