/* ---------------------------------------------------- */
/*  Generated by Enterprise Architect Version 12.1 		*/
/*  Created On : 22-Jan-2021 12:12:05 				*/
/*  DBMS       : PostgreSQL 						*/
/* ---------------------------------------------------- */

/* Drop VIEW */

DROP VIEW geoserver.imna_bes_beschikking;
DROP VIEW geoserver.imna_bes_beschikking_rapportage;

DROP VIEW geoserver.imna_nbp_viewer_beheer_gebied;
DROP VIEW geoserver.imna_nbp_viewer_beheer_gebied_ambitie;
DROP VIEW geoserver.imna_nbp_viewer_bijzonder_gebied;
DROP VIEW geoserver.imna_nbp_viewer_deel_gebied;
DROP VIEW geoserver.imna_nbp_viewer_natuur_beheer_plan;
DROP VIEW geoserver.imna_nbp_viewer_zoek_gebied_agrarisch;
DROP VIEW geoserver.imna_nbp_viewer_zoek_gebied_landschap;
DROP VIEW geoserver.imna_nbp_viewer_zoek_gebied_water;

DROP VIEW geoserver.imna_vrn_gebied_inrichting;
DROP VIEW geoserver.imna_vrn_gebied_natuur;
DROP VIEW geoserver.imna_vrn_gebied_verwerving;
DROP VIEW geoserver.imna_vrn_natuur_netwerk_nederland;
DROP VIEW geoserver.imna_vrn_resterende_inrichtings_ambitie;
DROP VIEW geoserver.imna_vrn_voortgangs_rapportage;

/* Create Tables */

CREATE TABLE geoserver.imna_bes_beschikking
(
	provincie varchar(20) NOT NULL,
	provincie_desc varchar(100) NULL,
	beheer_jaar integer NOT NULL,
	identificatie varchar(50) NOT NULL,
	begin_geldigheid timestamp NOT NULL,
	eind_geldigheid varchar(50) NULL,
	begin_tijd timestamp NULL,
	eind_tijd timestamp NULL,
	contract_nummer varchar(50) NULL,
	datum_beschikking timestamp NULL,
	status_aanvraag_subsidie varchar(20) NULL,
	status_aanvraag_subsidie_desc varchar(100) NULL,
	type_regeling varchar(20) NULL,
	type_regeling_desc varchar(100) NULL,
	beheer_type varchar(20) NULL,
	beheer_type_desc varchar(100) NULL,
	geom geometry(Geometry,28992)
)
;

CREATE TABLE geoserver.imna_bes_beschikking_rapportage
(
	provincie varchar(20) NOT NULL,
	provincie_desc varchar(100) NULL,
	beheer_jaar integer NOT NULL,
	identificatie varchar(50) NOT NULL,
	begin_geldigheid timestamp NOT NULL,
	eind_geldigheid varchar(50) NULL
)
;

CREATE TABLE geoserver.imna_nbp_viewer_beheer_gebied
(
	provincie varchar(20) NOT NULL,
	provincie_desc varchar(100) NULL,
	subsidie_jaar integer NOT NULL,
	status varchar(20) NOT NULL,
	status_desc varchar(100) NULL,
	identificatie varchar(100) NOT NULL,
	begin_geldigheid timestamp NOT NULL,
	eind_geldigheid timestamp NULL,
	begin_tijd timestamp NULL,
	eind_tijd timestamp NULL,
	beheer_type varchar(20) NULL,
	beheer_type_desc varchar(100) NULL,
	subsidiabel varchar(3) NULL,
	openstellings_bijdrage_type varchar(20) NULL,
	openstellings_bijdrage_type_desc varchar(100) NULL,
	indicatieve_verhouding_beheer_type text NULL,
	toegestane_beheer_paketten text NULL,
	niet_subsidiabele_beheer_paketten text NULL,
	document_link text NULL,
	geom geometry(Geometry,28992)
)
;

CREATE TABLE geoserver.imna_nbp_viewer_beheer_gebied_ambitie
(
	provincie varchar(20) NOT NULL,
	provincie_desc varchar(100) NULL,
	subsidie_jaar integer NOT NULL,
	status varchar(20) NOT NULL,
	status_desc varchar(100) NULL,
	identificatie varchar(100) NOT NULL,
	begin_geldigheid timestamp NOT NULL,
	eind_geldigheid timestamp NULL,
	begin_tijd timestamp NULL,
	eind_tijd timestamp NULL,
	status_ehs varchar(20) NULL,
	status_ehs_desc varchar(100) NULL,
	beheer_type varchar(20) NULL,
	beheer_type_desc varchar(100) NULL,
	subsidiabel varchar(3) NULL,
	indicatieve_verhouding_beheer_typen text NULL,
	toegestane_beheer_paketten text NULL,
	document_link text NULL,
	geom geometry(Geometry,28992)
)
;

CREATE TABLE geoserver.imna_nbp_viewer_bijzonder_gebied
(
	provincie varchar(20) NOT NULL,
	provincie_desc varchar(100) NULL,
	subsidie_jaar integer NOT NULL,
	status varchar(20) NOT NULL,
	status_desc varchar(100) NULL,
	identificatie varchar(100) NOT NULL,
	begin_geldigheid timestamp NOT NULL,
	eind_geldigheid timestamp NULL,
	begin_tijd timestamp NULL,
	eind_tijd timestamp NULL,
	gebieds_code varchar(20) NULL,
	gebieds_code_desc varchar(100) NULL,
	gebieds_naam varchar(100) NULL,
	document_link text NULL,
	geom geometry(Geometry,28992)
)
;

CREATE TABLE geoserver.imna_nbp_viewer_deel_gebied
(
	provincie varchar(20) NOT NULL,
	provincie_desc varchar(100) NULL,
	subsidie_jaar integer NOT NULL,
	status varchar(20) NOT NULL,
	status_desc varchar(100) NULL,
	identificatie varchar(100) NOT NULL,
	begin_geldigheid timestamp NOT NULL,
	eind_geldigheid timestamp NULL,
	begin_tijd timestamp NULL,
	eind_tijd timestamp NULL,
	gebieds_naam varchar(100) NULL,
	beschrijving text NULL,
	document_link text NULL,
	geom geometry(Geometry,28992)
)
;

CREATE TABLE geoserver.imna_nbp_viewer_natuur_beheer_plan
(
	provincie varchar(20) NOT NULL,
	provincie_desc varchar(100) NULL,
	subsidie_jaar integer NOT NULL,
	status varchar(20) NOT NULL,
	status_desc varchar(100) NULL,
	identificatie varchar(100) NOT NULL,
	begin_geldigheid timestamp NOT NULL,
	eind_geldigheid timestamp NULL,
	datum_vaststelling timestamp NULL,
	plan_eigenaar varchar(20) NULL,
	plan_eigenaar_desc varchar(100) NULL,
	plan_verwijzing text NULL,
	beheer_gebied_status varchar(20) NULL,
	beheer_gebied_status_desc varchar(100) NULL,
	beheer_gebied_ambitie_status varchar(20) NULL,
	beheer_gebied_ambitie_status_desc varchar(100) NULL,
	bijzonder_gebied_status varchar(20) NULL,
	bijzonder_gebied_status_desc varchar(100) NULL,
	deel_gebied_status varchar(20) NULL,
	deel_gebied_status_desc varchar(100) NULL,
	zoek_gebied_landschap_status varchar(20) NULL,
	zoek_gebied_landschap_status_desc varchar(100) NULL,
	zoek_gebied_agrarisch_status varchar(20) NULL,
	zoek_gebied_agrarisch_status_desc varchar(100) NULL,
	zoek_gebied_water_status varchar(20) NULL,
	zoek_gebied_water_status_desc varchar(100) NULL,
	document_link text NULL
)
;

CREATE TABLE geoserver.imna_nbp_viewer_zoek_gebied_agrarisch
(
	provincie varchar(20) NOT NULL,
	provincie_desc varchar(100) NULL,
	subsidie_jaar integer NOT NULL,
	status varchar(20) NOT NULL,
	status_desc varchar(100) NULL,
	identificatie varchar(100) NOT NULL,
	begin_geldigheid timestamp NOT NULL,
	eind_geldigheid timestamp NULL,
	begin_tijd timestamp NULL,
	eind_tijd timestamp NULL,
	agrarisch_natuur_type varchar(20) NULL,
	agrarisch_natuur_type_desc varchar(100) NULL,
	naam varchar(100) NULL,
	deel_gebied_naam varchar(100) NULL,
	toegestane_beheer_functies text NULL,
	toegestane_beheer_typen text NULL,
	document_link text NULL,
	geom geometry(Geometry,28992)
)
;

CREATE TABLE geoserver.imna_nbp_viewer_zoek_gebied_landschap
(
	provincie varchar(20) NOT NULL,
	provincie_desc varchar(100) NULL,
	subsidie_jaar integer NOT NULL,
	status varchar(20) NOT NULL,
	status_desc varchar(100) NULL,
	identificatie varchar(100) NOT NULL,
	begin_geldigheid timestamp NOT NULL,
	eind_geldigheid timestamp NULL,
	begin_tijd timestamp NULL,
	eind_tijd timestamp NULL,
	geom geometry(Geometry,28992),
	toegestane_beheer_typen text NULL,
	niet_subsidiabele_beheer_pakketten text NULL,
	document_link text NULL,
	naam varchar(100) NULL
)
;

CREATE TABLE geoserver.imna_nbp_viewer_zoek_gebied_water
(
	provincie varchar(20) NOT NULL,
	provincie_desc varchar(100) NULL,
	subsidie_jaar integer NOT NULL,
	status varchar(20) NOT NULL,
	status_desc varchar(100) NULL,
	identificatie varchar(100) NOT NULL,
	begin_geldigheid timestamp NOT NULL,
	eind_geldigheid timestamp NULL,
	begin_tijd timestamp NULL,
	eind_tijd timestamp NULL,
	water_natuur_type varchar(20) NULL,
	water_natuur_type_desc varchar(100) NULL,
	naam varchar(100) NULL,
	deel_gebied_naam varchar(100) NULL,
	toegestane_beheer_functies text NULL,
	toegestane_beheer_typen text NULL,
	document_link text NULL,
	geom geometry(Geometry,28992)
)
;

CREATE TABLE geoserver.imna_vrn_gebied_inrichting
(
	bron_houder varchar(20) NOT NULL,
	bron_houder_desc varchar(100) NULL,
	rapportage_jaar integer NOT NULL,
	identificatie varchar(100) NOT NULL,
	begin_geldigheid timestamp NOT NULL,
	eind_geldigheid timestamp NULL,
	begin_tijd timestamp NULL,
	eind_tijd timestamp NULL,
	type_beheerder varchar(20) NULL,
	type_beheerder_desc varchar(100) NULL,
	contract_nummer integer NULL,
	relatie_nummer integer NULL,
	geom geometry(Geometry,28992)
)
;

CREATE TABLE geoserver.imna_vrn_gebied_natuur
(
	bron_houder varchar(20) NOT NULL,
	bron_houder_desc varchar(100) NULL,
	rapportage_jaar integer NOT NULL,
	identificatie varchar(100) NOT NULL,
	begin_geldigheid timestamp NOT NULL,
	eind_geldigheid timestamp NULL,
	begin_tijd timestamp NULL,
	eind_tijd timestamp NULL,
	status_natuur varchar(20) NULL,
	status_natuur_desc varchar(100) NULL,
	type_beheerder varchar(20) NULL,
	type_beheerder_desc varchar(100) NULL,
	eenheid_nummer varchar(100) NULL,
	beheer_pakket varchar(20) NULL,
	beheer_pakket_desc varchar(100) NULL,
	contract_nummer integer NULL,
	relatie_nummer integer NULL,
	geom geometry(Geometry,28992)
)
;

CREATE TABLE geoserver.imna_vrn_gebied_verwerving
(
	bron_houder varchar(20) NOT NULL,
	bron_houder_desc varchar(100) NULL,
	rapportage_jaar integer NOT NULL,
	identificatie varchar(100) NOT NULL,
	begin_geldigheid timestamp NOT NULL,
	eind_geldigheid timestamp NULL,
	begin_tijd timestamp NULL,
	eind_tijd timestamp NULL,
	type_eigenaar varchar(20) NULL,
	type_eigenaar_desc varchar(100) NULL,
	contract_nummer integer NULL,
	relatie_nummer integer NULL,
	geom geometry(Geometry,28992)
)
;

CREATE TABLE geoserver.imna_vrn_natuur_netwerk_nederland
(
	bron_houder varchar(20) NOT NULL,
	bron_houder_desc varchar(100) NULL,
	rapportage_jaar integer NOT NULL,
	identificatie varchar(100) NOT NULL,
	begin_geldigheid timestamp NOT NULL,
	eind_geldigheid timestamp NULL,
	begin_tijd timestamp NULL,
	eind_tijd timestamp NULL,
	geom geometry(Geometry,28992)
)
;

CREATE TABLE geoserver.imna_vrn_resterende_inrichtings_ambitie
(
	bron_houder varchar(20) NOT NULL,
	bron_houder_desc varchar(100) NULL,
	rapportage_jaar integer NOT NULL,
	identificatie varchar(100) NOT NULL,
	begin_geldigheid timestamp NOT NULL,
	eind_geldigheid timestamp NULL,
	resterende_inrichtings_ambitie integer NOT NULL
)
;

CREATE TABLE geoserver.imna_vrn_voortgangs_rapportage
(
	bron_houder varchar(20) NOT NULL,
	bron_houder_desc varchar(100) NULL,
	rapportage_jaar integer NOT NULL,
	identificatie varchar(100) NOT NULL,
	begin_geldigheid timestamp NULL,
	eind_geldigheid timestamp NULL,
	opmerkingen text NULL,
	geom geometry(Geometry,28992)
)
;

/* Create Primary Keys, Indexes, Uniques, Checks */

ALTER TABLE geoserver.imna_bes_beschikking ADD CONSTRAINT PK_imna_bes_beschikking
	PRIMARY KEY (provincie,beheer_jaar,identificatie,begin_geldigheid)
;

CREATE INDEX INDX_imna_bes_beschikking_jaar ON geoserver.imna_bes_beschikking (beheer_jaar ASC)
;

CREATE INDEX INDX_imna_bes_beschikking_geom ON geoserver.imna_bes_beschikking (geom ASC)
;

ALTER TABLE geoserver.imna_bes_beschikking_rapportage ADD CONSTRAINT PK_imna_bes_beschikking_rapportage
	PRIMARY KEY (provincie,beheer_jaar,identificatie,begin_geldigheid)
;

CREATE INDEX INDX_imna_bes_rapportage_jaar ON geoserver.imna_bes_beschikking_rapportage (beheer_jaar ASC)
;

ALTER TABLE geoserver.imna_nbp_viewer_beheer_gebied ADD CONSTRAINT PK_imna_nbp_viewer_beheer_gebied
	PRIMARY KEY (provincie,identificatie,begin_geldigheid,subsidie_jaar,status)
;

CREATE INDEX INDX_vwr_beheer_gebied_subsidiejaar ON geoserver.imna_nbp_viewer_beheer_gebied (subsidie_jaar ASC)
;

CREATE INDEX INDX_vwr_beheer_gebied_status ON geoserver.imna_nbp_viewer_beheer_gebied (status ASC)
;

CREATE INDEX INDX_vwr_beheer_gebied_status_jaar ON geoserver.imna_nbp_viewer_beheer_gebied (status ASC,subsidie_jaar ASC)
;

ALTER TABLE geoserver.imna_nbp_viewer_beheer_gebied_ambitie ADD CONSTRAINT PK_imna_nbp_viewer_beheer_gebied_ambitie
	PRIMARY KEY (provincie,identificatie,begin_geldigheid,subsidie_jaar,status)
;

CREATE INDEX INDX_vwr_beheer_gebied_ambitie_subsidiejaar ON geoserver.imna_nbp_viewer_beheer_gebied_ambitie (subsidie_jaar ASC)
;

CREATE INDEX INDX_vwr_beheer_gebied_ambitie_status ON geoserver.imna_nbp_viewer_beheer_gebied_ambitie (status ASC)
;

CREATE INDEX INDX_vwr_beheer_gebied_ambitie_status_jaar ON geoserver.imna_nbp_viewer_beheer_gebied_ambitie (status ASC,subsidie_jaar ASC)
;

ALTER TABLE geoserver.imna_nbp_viewer_bijzonder_gebied ADD CONSTRAINT PK_imna_nbp_viewer_bijzonder_gebied
	PRIMARY KEY (provincie,subsidie_jaar,status,identificatie,begin_geldigheid)
;

CREATE INDEX INDX_vwr_bijzonder_gebied_subsidiejaar ON geoserver.imna_nbp_viewer_bijzonder_gebied (subsidie_jaar ASC)
;

CREATE INDEX INDX_vwr_bijzonder_gebied_status ON geoserver.imna_nbp_viewer_bijzonder_gebied (status ASC)
;

CREATE INDEX INDX_vwr_bijzonder_gebied_status_jaar ON geoserver.imna_nbp_viewer_bijzonder_gebied (status ASC,subsidie_jaar ASC)
;

ALTER TABLE geoserver.imna_nbp_viewer_deel_gebied ADD CONSTRAINT PK_imna_nbp_viewer_deel_gebied
	PRIMARY KEY (provincie,subsidie_jaar,status,identificatie,begin_geldigheid)
;

CREATE INDEX INDX_vwr_deel_gebied_subsidiejaar ON geoserver.imna_nbp_viewer_deel_gebied (subsidie_jaar ASC)
;

CREATE INDEX INDX_vwr_deel_gebied_status ON geoserver.imna_nbp_viewer_deel_gebied (status ASC)
;

CREATE INDEX INDX_vwr_deel_gebied_status_jaar ON geoserver.imna_nbp_viewer_deel_gebied (status ASC,subsidie_jaar ASC)
;

ALTER TABLE geoserver.imna_nbp_viewer_natuur_beheer_plan ADD CONSTRAINT PK_imna_nbp_viewer_natuur_beheer_plan
	PRIMARY KEY (status,identificatie,begin_geldigheid,provincie,subsidie_jaar)
;

CREATE INDEX INDX_vwr_natuur_beheer_plan_subsidiejaar ON geoserver.imna_nbp_viewer_natuur_beheer_plan (subsidie_jaar ASC)
;

CREATE INDEX INDX_vwr_natuur_beheer_plan_status ON geoserver.imna_nbp_viewer_natuur_beheer_plan (status ASC)
;

CREATE INDEX INDX_vwr_natuur_beheer_plan_status_jaar ON geoserver.imna_nbp_viewer_natuur_beheer_plan (status ASC,subsidie_jaar ASC)
;

ALTER TABLE geoserver.imna_nbp_viewer_zoek_gebied_agrarisch ADD CONSTRAINT PK_imna_nbp_viewer_zoek_gebied_agrarisch
	PRIMARY KEY (provincie,subsidie_jaar,status,identificatie,begin_geldigheid)
;

CREATE INDEX INDX_vwr_zoek_gebied_agrarisch_subsidiejaar ON geoserver.imna_nbp_viewer_zoek_gebied_agrarisch (subsidie_jaar ASC)
;

CREATE INDEX INDX_vwr_zoek_gebied_agrarisch_status ON geoserver.imna_nbp_viewer_zoek_gebied_agrarisch (status ASC)
;

CREATE INDEX INDX_vwr_zoek_gebied_agrarisch_status_jaar ON geoserver.imna_nbp_viewer_zoek_gebied_agrarisch (status ASC,subsidie_jaar ASC)
;

ALTER TABLE geoserver.imna_nbp_viewer_zoek_gebied_landschap ADD CONSTRAINT PK_imna_nbp_viewer_zoek_gebied_landschap
	PRIMARY KEY (provincie,subsidie_jaar,status,identificatie,begin_geldigheid)
;

CREATE INDEX INDX_vwr_zoek_gebied_landschap_subsidiejaar ON geoserver.imna_nbp_viewer_zoek_gebied_landschap (subsidie_jaar ASC)
;

CREATE INDEX INDX_vwr_zoek_gebied_landschap_status ON geoserver.imna_nbp_viewer_zoek_gebied_landschap (status ASC)
;

CREATE INDEX INDX_vwr_zoek_gebied_landschap_status_jaar ON geoserver.imna_nbp_viewer_zoek_gebied_landschap (status ASC,subsidie_jaar ASC)
;

ALTER TABLE geoserver.imna_nbp_viewer_zoek_gebied_water ADD CONSTRAINT PK_imna_nbp_viewer_zoek_gebied_water
	PRIMARY KEY (provincie,subsidie_jaar,status,identificatie,begin_geldigheid)
;

CREATE INDEX INDX_vwr_zoek_gebied_water_subsidiejaar ON geoserver.imna_nbp_viewer_zoek_gebied_water (subsidie_jaar ASC)
;

CREATE INDEX INDX_vwr_zoek_gebied_water_status ON geoserver.imna_nbp_viewer_zoek_gebied_water (status ASC)
;

CREATE INDEX INDX_vwr_zoek_gebied_water_status_jaar ON geoserver.imna_nbp_viewer_zoek_gebied_water (status ASC,subsidie_jaar ASC)
;

ALTER TABLE geoserver.imna_vrn_gebied_inrichting ADD CONSTRAINT PK_imna_vrn_gebied_inrichting
	PRIMARY KEY (bron_houder,rapportage_jaar,identificatie,begin_geldigheid)
;

CREATE INDEX INDX_imna_vrn_inrichting_jaar ON geoserver.imna_vrn_gebied_inrichting (rapportage_jaar ASC)
;

ALTER TABLE geoserver.imna_vrn_gebied_natuur ADD CONSTRAINT PK_imna_vrn_gebied_natuur
	PRIMARY KEY (bron_houder,rapportage_jaar,identificatie,begin_geldigheid)
;

CREATE INDEX INDX_imna_vrn_natuur_jaar ON geoserver.imna_vrn_gebied_natuur (rapportage_jaar ASC)
;

ALTER TABLE geoserver.imna_vrn_gebied_verwerving ADD CONSTRAINT PK_imna_vrn_gebied_verwerving
	PRIMARY KEY (bron_houder,rapportage_jaar,identificatie,begin_geldigheid)
;

CREATE INDEX INDX_iman_vrn_verwerving_jaar ON geoserver.imna_vrn_gebied_verwerving (rapportage_jaar ASC)
;

ALTER TABLE geoserver.imna_vrn_natuur_netwerk_nederland ADD CONSTRAINT PK_imna_vrn_natuur_netwerk_nederland
	PRIMARY KEY (bron_houder,rapportage_jaar,identificatie,begin_geldigheid)
;

CREATE INDEX INDX_imna_vrn_nnn_jaar ON geoserver.imna_vrn_natuur_netwerk_nederland (rapportage_jaar ASC)
;

ALTER TABLE geoserver.imna_vrn_resterende_inrichtings_ambitie ADD CONSTRAINT PK_imna_vrn_resterende_inrichtings_ambitie
	PRIMARY KEY (bron_houder,rapportage_jaar,identificatie,begin_geldigheid)
;

CREATE INDEX INDX_imna_vrn_rest_jaar ON geoserver.imna_vrn_resterende_inrichtings_ambitie (rapportage_jaar ASC)
;

ALTER TABLE geoserver.imna_vrn_voortgangs_rapportage ADD CONSTRAINT PK_imna_vrn_voortgangs_rapportage
	PRIMARY KEY (bron_houder,rapportage_jaar,identificatie)
;

CREATE INDEX INDX_imna_vrn_voortgangs_rapportage_jaar ON geoserver.imna_vrn_voortgangs_rapportage (rapportage_jaar ASC)
;
CREATE INDEX "IMNa_bes_beschikking_geom" ON geoserver."imna_bes_beschikking" USING gist  (geom) TABLESPACE pg_default;
CREATE INDEX "IMNa_nbp_viewer_beheer_gebied_geom" ON geoserver."imna_nbp_viewer_beheer_gebied" USING gist  (geom) TABLESPACE pg_default;
CREATE INDEX "IMNa_nbp_viewer_beheer_gebied_ambitie_geom" ON geoserver."imna_nbp_viewer_beheer_gebied_ambitie" USING gist  (geom) TABLESPACE pg_default;
CREATE INDEX "IMNa_nbp_viewer_bijzonder_gebied_geom" ON geoserver."imna_nbp_viewer_bijzonder_gebied" USING gist  (geom) TABLESPACE pg_default;
CREATE INDEX "IMNa_nbp_viewer_deel_gebied_geom" ON geoserver."imna_nbp_viewer_deel_gebied" USING gist  (geom) TABLESPACE pg_default;
CREATE INDEX "IMNa_nbp_viewer_zoek_gebied_agrarisch_geom" ON geoserver."imna_nbp_viewer_zoek_gebied_agrarisch" USING gist  (geom) TABLESPACE pg_default;
CREATE INDEX "IMNa_nbp_viewer_zoek_gebied_landschap_geom" ON geoserver."imna_nbp_viewer_zoek_gebied_landschap" USING gist  (geom) TABLESPACE pg_default;
CREATE INDEX "IMNa_nbp_viewer_zoek_gebied_water_geom" ON geoserver."imna_nbp_viewer_zoek_gebied_water" USING gist  (geom) TABLESPACE pg_default;
CREATE INDEX "IMNa_vrn_gebied_inrichting_geom" ON geoserver."imna_vrn_gebied_inrichting" USING gist  (geom) TABLESPACE pg_default;
CREATE INDEX "IMNa_vrn_gebied_natuur_geom" ON geoserver."imna_vrn_gebied_natuur" USING gist  (geom) TABLESPACE pg_default;
CREATE INDEX "IMNa_vrn_gebied_verwerving_geom" ON geoserver."imna_vrn_gebied_verwerving" USING gist  (geom) TABLESPACE pg_default;
CREATE INDEX "IMNa_vrn_natuur_netwerk_nederland_geom" ON geoserver."imna_vrn_natuur_netwerk_nederland" USING gist  (geom) TABLESPACE pg_default;

CREATE INDEX "IMNa_vrn_voortgangs_rapportage_geom" ON geoserver."imna_vrn_voortgangs_rapportage" USING gist  (geom) TABLESPACE pg_default;


GRANT SELECT ON TABLE geoserver.imna_bes_beschikking TO anlb_sqlpad;
GRANT SELECT ON TABLE geoserver.imna_bes_beschikking_rapportage TO anlb_sqlpad;
GRANT SELECT ON TABLE geoserver.imna_nbp_viewer_beheer_gebied TO anlb_sqlpad;
GRANT SELECT ON TABLE geoserver.imna_nbp_viewer_beheer_gebied_ambitie TO anlb_sqlpad;
GRANT SELECT ON TABLE geoserver.imna_nbp_viewer_bijzonder_gebied TO anlb_sqlpad;
GRANT SELECT ON TABLE geoserver.imna_nbp_viewer_deel_gebied TO anlb_sqlpad;
GRANT SELECT ON TABLE geoserver.imna_nbp_viewer_natuur_beheer_plan TO anlb_sqlpad;
GRANT SELECT ON TABLE geoserver.imna_nbp_viewer_zoek_gebied_agrarisch TO anlb_sqlpad;
GRANT SELECT ON TABLE geoserver.imna_nbp_viewer_zoek_gebied_landschap TO anlb_sqlpad;
GRANT SELECT ON TABLE geoserver.imna_nbp_viewer_zoek_gebied_water TO anlb_sqlpad;
GRANT SELECT ON TABLE geoserver.imna_vrn_gebied_inrichting TO anlb_sqlpad;
GRANT SELECT ON TABLE geoserver.imna_vrn_gebied_natuur TO anlb_sqlpad;
GRANT SELECT ON TABLE geoserver.imna_vrn_gebied_verwerving TO anlb_sqlpad;
GRANT SELECT ON TABLE geoserver.imna_vrn_natuur_netwerk_nederland TO anlb_sqlpad;
GRANT SELECT ON TABLE geoserver.imna_vrn_resterende_inrichtings_ambitie TO anlb_sqlpad;
GRANT SELECT ON TABLE geoserver.imna_vrn_voortgangs_rapportage TO anlb_sqlpad;

