/* ---------------------------------------------------- */
/*  Generated by Enterprise Architect Version 12.1 		*/
/*  Created On : 10-Feb-2022 17:08:47 				*/
/*  DBMS       : PostgreSQL 						*/
/* ---------------------------------------------------- */

/* Create Tables */
ALTER TABLE geoserver.imna_nbp_viewer_natuur_beheer_plan
	ADD COLUMN zoek_gebied_klimaat_status varchar(20) NULL,
	ADD COLUMN zoek_gebied_klimaat_status_desc varchar(100) NULL
;

ALTER TABLE geoserver.imna_nbp_viewer_beheer_gebied
	ADD COLUMN voorzieningenbijdrage varchar(3) NULL,
	ADD COLUMN toezichtbijdrage varchar(3) NULL,
	ADD COLUMN bijdrage_vaarland varchar(3) NULL,
	ADD COLUMN bijdrage_gescheperde_schaapskuddes varchar(3) NULL,
	ADD COLUMN bijdrage_monitoring varchar(3) NULL
;

ALTER TABLE geoserver.imna_nbp_viewer_zoek_gebied_agrarisch
	ADD COLUMN deel_gebied varchar(20) NULL,
	ADD COLUMN deel_gebied_desc varchar(100) NULL
;

UPDATE geoserver.imna_nbp_viewer_zoek_gebied_agrarisch zga1
   SET deel_gebied_desc = zga2.deel_gebied_naam
  FROM geoserver.imna_nbp_viewer_zoek_gebied_agrarisch zga2
 WHERE zga1.provincie        = zga2.provincie
   AND zga1.subsidie_jaar    = zga2.subsidie_jaar
   AND zga1.status           = zga2.status
   AND zga1.begin_geldigheid = zga2.begin_geldigheid;
	

ALTER TABLE geoserver.imna_nbp_viewer_zoek_gebied_agrarisch
	DROP COLUMN deel_gebied_naam
;

ALTER TABLE geoserver.imna_nbp_viewer_zoek_gebied_water
	ADD COLUMN deel_gebied varchar(20) NULL,
	ADD COLUMN deel_gebied_desc varchar(100) NULL
;

UPDATE geoserver.imna_nbp_viewer_zoek_gebied_water zgw1
   SET deel_gebied_desc = zgw2.deel_gebied_naam
  FROM geoserver.imna_nbp_viewer_zoek_gebied_water zgw2
 WHERE zgw1.provincie        = zgw2.provincie
   AND zgw1.subsidie_jaar    = zgw2.subsidie_jaar
   AND zgw1.status           = zgw2.status
   AND zgw1.begin_geldigheid = zgw2.begin_geldigheid;

ALTER TABLE geoserver.imna_nbp_viewer_zoek_gebied_water
	DROP COLUMN deel_gebied_naam
;

CREATE TABLE geoserver.imna_nbp_viewer_zoek_gebied_klimaat
(
	provincie varchar(20) NOT NULL,
	provincie_desc varchar(100) NULL,
	subsidie_jaar integer NOT NULL,
	status varchar(20) NOT NULL,
	status_desc varchar(100) NULL,
	identificatie varchar(100) NOT NULL,
	begin_geldigheid timestamp NOT NULL,
	eind_geldigheid timestamp NULL,
	begin_tijd timestamp NULL,
	eind_tijd timestamp NULL,
	klimaat_natuur_type varchar(20) NULL,
	klimaat_natuur_type_desc varchar(100) NULL,
	naam varchar(100) NULL,
	deel_gebied varchar(20) NULL,
	deel_gebied_desc varchar(100) NULL,
	toegestane_beheer_functies text NULL,
	toegestane_beheer_typen text NULL,
	document_link text NULL,
	geom geometry NULL
)
;

GRANT ALL ON TABLE geoserver.imna_nbp_viewer_zoek_gebied_klimaat TO anlb;
GRANT SELECT ON TABLE geoserver.imna_nbp_viewer_zoek_gebied_klimaat TO anlb_sqlpad;

/* Create Primary Keys, Indexes, Uniques, Checks */



ALTER TABLE geoserver.imna_nbp_viewer_zoek_gebied_klimaat ADD CONSTRAINT PK_imna_nbp_viewer_zoek_gebied_klimaat
	PRIMARY KEY (provincie,subsidie_jaar,status,identificatie,begin_geldigheid)
;

CREATE INDEX INDX_vwr_zoek_gebied_klimaat_subsidiejaar ON geoserver.imna_nbp_viewer_zoek_gebied_klimaat (subsidie_jaar ASC)
;

CREATE INDEX INDX_vwr_zoek_gebied_klimaat_status ON geoserver.imna_nbp_viewer_zoek_gebied_klimaat (status ASC)
;

CREATE INDEX INDX_vwr_zoek_gebied_klimaat_status_jaar ON geoserver.imna_nbp_viewer_zoek_gebied_klimaat (status ASC,subsidie_jaar ASC)
;
