\echo "GeoServer - creating table gt_pk_metadata"

CREATE TABLE IF NOT EXISTS geoserver.gt_pk_metadata
(
    table_schema character varying(32) COLLATE pg_catalog."default" NOT NULL,
    table_name character varying(64) COLLATE pg_catalog."default" NOT NULL,
    pk_column character varying(64) COLLATE pg_catalog."default" NOT NULL,
    pk_column_idx integer,
    pk_policy character varying(32) COLLATE pg_catalog."default",
    pk_sequence character varying(64) COLLATE pg_catalog."default",
    CONSTRAINT gt_pk_metadata_table_schema_table_name_pk_column_key UNIQUE (table_schema, table_name, pk_column),
    CONSTRAINT gt_pk_metadata_pk_policy_check CHECK (pk_policy::text = ANY (ARRAY['sequence'::character varying::text, 'assigned'::character varying::text, 'autogenerated'::character varying::text]))
);

ALTER TABLE IF EXISTS geoserver.gt_pk_metadata
    OWNER to anlb;

GRANT SELECT ON TABLE geoserver.gt_pk_metadata TO anlb_sqlpad;