/* ---------------------------------------------------- */
/*  Generated by Enterprise Architect Version 12.1 		*/
/*  Created On : 22-Dec-2023 16:18:14 				*/
/*  DBMS       : PostgreSQL 						*/
/* ---------------------------------------------------- */


/* Create Tables */

CREATE TABLE IF NOT EXISTS masterdata.dmn_mammal_type
(
	id bigint NOT NULL   DEFAULT NEXTVAL(('masterdata_seq'::text)::regclass),
	code char(20) NOT NULL,
	description char(100) NULL,
	valid_from timestamp NOT NULL,
	valid_to timestamp NULL
)
;

ALTER TABLE masterdata.dmn_mammal_type
    OWNER to anlb;
	
GRANT SELECT ON TABLE masterdata.dmn_mammal_type TO besi_readonly;

CREATE TABLE IF NOT EXISTS masterdata.dmn_protected_nest
(
	id bigint NOT NULL   DEFAULT NEXTVAL(('masterdata_seq'::text)::regclass),
	code char(20) NOT NULL,
	description char(100) NULL,
	valid_from timestamp NOT NULL,
	valid_to timestamp NULL
)
;

ALTER TABLE masterdata.dmn_protected_nest
    OWNER to anlb;

GRANT SELECT ON TABLE masterdata.dmn_mammal_type TO besi_readonly;

CREATE TABLE IF NOT EXISTS masterdata.dmn_animal_group
(
	id bigint NOT NULL   DEFAULT NEXTVAL(('masterdata_seq'::text)::regclass),
	code char(20) NOT NULL,
	description char(100) NULL,
	valid_from timestamp NOT NULL,
	valid_to timestamp NULL
)
;

ALTER TABLE masterdata.dmn_animal_group
    OWNER to anlb;
	
GRANT SELECT ON TABLE masterdata.dmn_mammal_type TO besi_readonly;
	
/* Create Primary Keys, Indexes, Uniques, Checks */

SELECT pg_temp.create_constraint_if_not_exists ('masterdata','dmn_mammal_type','PK_dmn_mammal_type',
'ALTER TABLE masterdata.dmn_mammal_type ADD CONSTRAINT PK_dmn_mammal_type
	PRIMARY KEY (id)
;');

SELECT pg_temp.create_constraint_if_not_exists ('masterdata','dmn_mammal_type','UN_code_mammal_type',
'ALTER TABLE masterdata.dmn_mammal_type ADD CONSTRAINT UN_code_mammal_type UNIQUE (code)
;');

SELECT pg_temp.create_constraint_if_not_exists ('masterdata','dmn_protected_nest','PK_dmn_protected_nest',
'ALTER TABLE masterdata.dmn_protected_nest ADD CONSTRAINT PK_dmn_protected_nest
	PRIMARY KEY (id)
;');

SELECT pg_temp.create_constraint_if_not_exists ('masterdata','dmn_protected_nest','UN_code_protected_nest',
'ALTER TABLE masterdata.dmn_protected_nest ADD CONSTRAINT UN_code_protected_nest UNIQUE (code)
;');

SELECT pg_temp.create_constraint_if_not_exists ('masterdata','dmn_animal_group','PK_dmn_animal_group',
'ALTER TABLE masterdata.dmn_animal_group ADD CONSTRAINT PK_dmn_animal_group
	PRIMARY KEY (id)
;');

SELECT pg_temp.create_constraint_if_not_exists ('masterdata','dmn_animal_group','UN_animal_group',
'ALTER TABLE masterdata.dmn_animal_group ADD CONSTRAINT UN_animal_group UNIQUE (code)
;');



/* Create Table Comments, Sequences for Autonumber Columns */

COMMENT ON TABLE masterdata.dmn_mammal_type
	IS 'Contains Vleermuizen Eekhoorn Steenmarter Andere marterachtige dan steenmarter Overige zoogdieren'
;

COMMENT ON TABLE masterdata.dmn_protected_nest
	IS 'Contains Broedseizoen Jaarrond Nee'
;

COMMENT ON TABLE masterdata.dmn_animal_group
	IS 'Contains Vogel Zoogdier Andere diersoort dan vogels of zoogdieren Planten'
;


GRANT SELECT ON ALL TABLES IN SCHEMA masterdata TO anlb_sqlpad;