/* ---------------------------------------------------- */
/*  Generated by Enterprise Architect Version 12.1 		*/
/*  Created On : 19-Feb-2024 09:28:44 				*/
/*  DBMS       : PostgreSQL 						*/
/* ---------------------------------------------------- */

/* Create Tables */


CREATE TABLE IF NOT EXISTS masterdata.dmn_indicator_type
(
	id bigint NOT NULL   DEFAULT NEXTVAL(('masterdata.masterdata_sec'::text)::regclass),
	code varchar(20) NOT NULL,
	description varchar(100) NULL,
	valid_from timestamp NOT NULL,
	valid_to timestamp NULL
)
;

ALTER TABLE masterdata.dmn_indicator_type
    OWNER to anlb;

CREATE TABLE IF NOT EXISTS masterdata.dmn_kwalificerende_kenmerk
(
	id bigint NOT NULL   DEFAULT NEXTVAL(('masterdata.masterdata_sec'::text)::regclass),
	code varchar(20) NOT NULL,
	description varchar(100) NULL,
	valid_from timestamp NOT NULL,
	valid_to timestamp NULL
)
;

ALTER TABLE masterdata.dmn_kwalificerende_kenmerk
    OWNER to anlb;

CREATE TABLE IF NOT EXISTS masterdata.dmn_kwaliteits_bepaling
(
	id bigint NOT NULL   DEFAULT NEXTVAL(('masterdata.masterdata_sec'::text)::regclass),
	code varchar(20) NOT NULL,
	description varchar(100) NULL,
	valid_from timestamp NOT NULL,
	valid_to timestamp NULL
)
;

ALTER TABLE masterdata.dmn_kwaliteits_bepaling
    OWNER to anlb;

CREATE TABLE IF NOT EXISTS masterdata.dmn_bronhouder_rnn
(
	id bigint NOT NULL,
	code varchar(20) NOT NULL,
	description varchar(100) NULL,
	valid_from timestamp NOT NULL,
	valid_to timestamp NULL
)
;

ALTER TABLE masterdata.dmn_bronhouder_rnn
    OWNER to anlb;

/* Create Primary Keys, Indexes, Uniques, Checks */

SELECT pg_temp.create_constraint_if_not_exists ('masterdata','dmn_indicator_type','PK_dmn_indicator_type',
'ALTER TABLE masterdata.dmn_indicator_type ADD CONSTRAINT PK_dmn_indicator_type
	PRIMARY KEY (id)
;');

SELECT pg_temp.create_constraint_if_not_exists ('masterdata','dmn_indicator_type','UN_code_indicator_type',
'ALTER TABLE masterdata.dmn_indicator_type ADD CONSTRAINT UN_code_indicator_type UNIQUE (code)
;');


SELECT pg_temp.create_constraint_if_not_exists ('masterdata','dmn_kwalificerende_kenmerk','PK_dmn_kwalificerende_kenmerk',
'ALTER TABLE masterdata.dmn_kwalificerende_kenmerk ADD CONSTRAINT PK_dmn_kwalificerende_kenmerk
	PRIMARY KEY (id)
;');

SELECT pg_temp.create_constraint_if_not_exists ('masterdata','dmn_kwalificerende_kenmerk','UN_code_kwalificerende_kenmerk',
'ALTER TABLE masterdata.dmn_kwalificerende_kenmerk ADD CONSTRAINT UN_code_kwalificerende_kenmerk UNIQUE (code)
;');

SELECT pg_temp.create_constraint_if_not_exists ('masterdata','dmn_kwaliteits_bepaling','PK_dmn_kwaliteits_bepaling',
'ALTER TABLE masterdata.dmn_kwaliteits_bepaling ADD CONSTRAINT PK_dmn_kwaliteits_bepaling
	PRIMARY KEY (id)
;');

SELECT pg_temp.create_constraint_if_not_exists ('masterdata','dmn_kwaliteits_bepaling','UN_code_kwaliteits_bepaling',
'ALTER TABLE masterdata.dmn_kwaliteits_bepaling ADD CONSTRAINT UN_code_kwaliteits_bepaling UNIQUE (code)
;');

SELECT pg_temp.create_constraint_if_not_exists ('masterdata','dmn_bronhouder_rnn','PK_dmn_bronhouder_rnn',
'ALTER TABLE masterdata.dmn_bronhouder_rnn ADD CONSTRAINT PK_dmn_bronhouder_rnn
	PRIMARY KEY (id)
;');

SELECT pg_temp.create_constraint_if_not_exists ('masterdata','dmn_bronhouder_rnn','UN_code_bronhouder_rnn',
'ALTER TABLE masterdata.dmn_bronhouder_rnn ADD CONSTRAINT UN_code_bronhouder_rnn UNIQUE (code)
;');

GRANT SELECT ON ALL TABLES IN SCHEMA masterdata TO anlb_sqlpad;


